### ISSUE TITLE
Make script fails if Registry with Port is used

### ISSUE THREAD

**Issue by MaximilianKindshofer** [getsentry/onpremise#1]
When using a docker repository like described in:

https://docs.docker.com/registry/deploying/
e.g:

> docker run -d -p 5000:5000 --restart=always --name registry \
>   -v `pwd`/certs:/certs \
>   -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
>   -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
>   registry:2

and than using:

`REPOSITORY="registry.example:5000/sentry" make build push`

the makefile exits with

`Makefile:11: *** target pattern contains no '%'.  Stop.`

**Comment by mattrobenolt** [comment]
Oh, that's not great. :( I'll try and get this fixed up today. Thanks for reporting!

**Comment by mfb** [comment]
looks like this is still an issue

**Comment by mattrobenolt** [comment]
Yeah, it definitely is. I haven't had time to address this yet and hasn't been a priority since it's easy to work around just by simply not using the Makefile.

**Comment by serafss2** [comment]
There's a work around for this, you can do:
```
REPOSITORY="registry.example\:5000/sentry"
make build push
```
Just backslash the troublesome characters.

**Comment by BYK** [comment]
This looks like an easy fix for whoever wants to submit a pull request :)

**Comment by BYK** [comment]
We've deprecated and removed the Makefile so closing this issue as it is wontfix.
