### ISSUE TITLE
Mac M1: The CPU your machine is running on does not support the SSE 4.2 instruction set

### ISSUE THREAD

**Issue by lcc807** [getsentry/onpremise#1006]
### Version Information

Version: 21.6.1

 Checking minimum requirements ...
FAIL: The CPU your machine is running on does not support the SSE 4.2 instruction set, which is required for one of the services Sentry uses (Clickhouse). See https://git.io/JvLDt for more info.

mac os 11.4 ; Apple M1

**Comment by BYK** [comment]
@lcc807 as the error message clearly expresses, your CPU is not supported. Not sure what you expect us to do here?

**Comment by BYK** [comment]
You may wanna check #914.

**Comment by lcc807** [comment]
> @ lcc807正如错误消息明确表达的那样，您的CPU不受支持。不确定您希望我们在这里做什么？

Hope to support M1.  For debugging

**Comment by BYK** [comment]
We have a whole project around this owned by our developer productivity team: https://github.com/orgs/getsentry/projects/14#card-62793188

I recommend you follow that project as this is larger than a single issue and won't be addressed here anytime soon. This repo is intended for production use (albeit at low scale).
