### ISSUE TITLE
Some containers keep restarting because of python syntax error

### ISSUE THREAD

**Issue by talalong** [getsentry/onpremise#1008]
### Version Information

Version: *21.6.1*

### Steps to Reproduce
After receiving a huge amount of error messages, Sentry stops working.
### Logs

All of these containers are having the same issue: _web_, _worker_, _subscription-consumer-events_, _subscription-consumer-transactions_

> SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 5, in <module>
    from sentry.runner import main
  File "/data/custom-packages/lib/python3.6/site-packages/sentry/__init__.py", line 12
    except Exception, e:

What you saw along the way, e.g.:

- latest install logs: `ls -1 sentry_install_log-*.txt | tail -1 | xargs cat`
- `docker-compose logs` output

**Comment by BYK** [comment]
You seem to have a syntax error in your config file. Without more logs, it is not possible to say more.

**Comment by talalong** [comment]
@BYK What logs should I show you? 
Using `docker-compose logs web` I could only get this kind of error multiple times.
![grafik](https://user-images.githubusercontent.com/24271207/123637634-89f3b200-d81e-11eb-96a1-a9b0e7ca5c68.png)

**Comment by BYK** [comment]
Is it possible that you have not pulled the images or something? The `except Exception, e:` syntax should not appear in Python 3 which is what we are using for a while. And indeed line 12 in that file is definitely nothing like that: https://github.com/getsentry/sentry/blob/043c5911b91093c6115da17e4528f1d1861798e3/src/sentry/__init__.py#L12

**Comment by talalong** [comment]
We had to reinstall Sentry from scratch, but it gets back to normal now. Thank you.
