### ISSUE TITLE
Kafka won't start after update

### ISSUE THREAD

**Issue by adam1010** [getsentry/onpremise#1009]
### Version Information

Version: Sentry 21.7.0.dev0ee22e17

### Steps to Reproduce

1. I use Docker. I was on a relatively recent version. used the `./install.sh` script to upgrade
2. It won't start up at all anymore.

Is there a way to at least recover so I can login to look at my assigned tickets? (even if I need to rollback?)

### Actual Result

![image](https://user-images.githubusercontent.com/3019544/123710062-f1abfc00-d822-11eb-8e7a-f5cc727b5870.png)

![image](https://user-images.githubusercontent.com/3019544/123710098-fcff2780-d822-11eb-861d-89d8743e96f4.png)

![image](https://user-images.githubusercontent.com/3019544/123710158-16a06f00-d823-11eb-86f0-709e1cbc82d4.png)

What actually happened. Maybe a screenshot/recording?

### Logs

![image](https://user-images.githubusercontent.com/3019544/123710304-60895500-d823-11eb-9324-20b6b603a264.png)
![image](https://user-images.githubusercontent.com/3019544/123710326-6848f980-d823-11eb-925c-7c55bb2e59f5.png)

**Comment by adam1010** [comment]
@BYK I'm available on Sentry Discord if you want me to share my screen or let you look through logs

**Comment by BYK** [comment]
@adam1010 we recently upgraded Kafka and Zookeeper in #1002. This might be related. Can you try reverting those two to `5.5.0` and try that way?

**Comment by djbe** [comment]
I can confirm that reverting those 2 lines in the `docker-compose.yml` (and running `./install.sh`) fixes the issue.

**Comment by BYK** [comment]
Looks like the Kafka upgrade was not smooth. I'll dig into this.

**Comment by adam1010** [comment]
Confirmed, rolling back to `cp-zookeeper:5.5.0` in the two locations in  `docker-compose.yml` then using `./install.sh` got me back up and running.  Thank you!

Not sure if this is helpful, but the first time I ran `./install.sh` I had not done a `git pull` on the repo. If that's an important part of the process, you might consider adding a `git pull` command to the beginning of the `./install.sh` script to force it.

**Comment by BYK** [comment]
@adam1010 if you are on the nightly builds, we expect you to pull the latest version of this repo too. If you are using the tagged CalVer releases, then you already should be using a tagged version of this repo 🙂 

Keeping the issue open as master is still problematic for upgrades I think.
