### ISSUE TITLE
Configure for version 9.0

### ISSUE THREAD

**Issue by HaidarZ** [getsentry/onpremise#101]
[docker-sentry](https://github.com/getsentry/docker-sentry) is now out with version 9.0
Can we support this with **onpremise** having docker-compose for version 9.0.
Is it enough to update _Dockerfile_ to pull from sentry:9.0 ?

**Comment by jackple** [comment]
+1

**Comment by HaidarZ** [comment]
You have to update your database using the given command

**Comment by HaidarZ** [comment]
You have to update the database also given the following command:
`docker-compose run --rm web upgrade`

**Comment by jackple** [comment]
@HaidarZ thanks! It worked!

**Comment by viktorsmari** [comment]
Maybe we should put this in the README? - I came here looking for this info.

**Comment by pataar** [comment]
@viktorsmari It's in the README now :)
