### ISSUE TITLE
Container are not getting up 

### ISSUE THREAD

**Issue by achyuth-111** [getsentry/onpremise#1012]
### Steps to Reproduce

1. foo
2. bar
3. baz

### Expected Result
 the containers are not getting up, they are in restarting status when trying to start it again they are exiting 

![image](https://user-images.githubusercontent.com/75174613/123876396-488c0100-d909-11eb-950f-72678ac6233c.png)

### Actual Result

e.g.:
- latest install logs: `ls -1 sentry_install_log-*.txt | tail -1 | xargs cat`
- `docker-compose logs` output

**Comment by BYK** [comment]
Please follow the template and provide logs and reproduction steps otherwise this issue is not actionable.

**Comment by achyuth-111** [comment]
The sentry was done 7 months back done by my colleague... 
From a Week  sentry is not logging; I've done couple of intentional actions (one of them entering wrong credentials) to test if logging anything. Also changed the filter … saw that last thing logged was a week back...

It is not working only for on-premise image....

**Comment by BYK** [comment]
@achyuth-111 this is not a support forum so you'd have better chances over at [the forum](https://forum.sentry.io), unless this is a bug with the repo.

With the amount of information you have shared it is not possible to help you so I'll be closing the issue. Feel free to come back with more information and we can resume.

You may want to visit our [troubleshooting guide](https://develop.sentry.dev/self-hosted/troubleshooting/) first.
