### ISSUE TITLE
Status: Downloaded newer image for curlimages/curl:latest

### ISSUE THREAD

**Issue by zhouyangit** [getsentry/onpremise#1014]
### Steps to Reproduce

./install.h

...

<img width="663" alt="截屏2021-06-30 下午11 27 45" src="https://user-images.githubusercontent.com/13669516/123989317-5cb02b00-d9fb-11eb-9fef-8323234010ea.png">

### Expected Result

install success

### Actual Result

110e7f874674: Download complete
110e7f874674: Pull complete
Digest: sha256:6e0a786e3e5181df00eaf3a0a1749c18a6bb20b01c9bd192ea72176ce8a1c94b
Status: Downloaded newer image for curlimages/curl:latest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:32 --:--:--     0
An error occurred, caught SIGERR on line 14
Cleaning up...
root@ubuntu2021:/home/onpremise#

**Comment by BYK** [comment]
Sorry this issue is not actionable with the amount of information you've provided.
