### ISSUE TITLE
sentry:test error sending the test event

### ISSUE THREAD

**Issue by tbdavid94** [getsentry/onpremise#1019]
### Problem Statement

I using self-hosted/on-premise instance, after i run php artisan sentry:test
[Sentry] DSN discovered!
[Sentry] Generating test Event
[Sentry] Sending test Event
[Sentry] There was an error sending the test event.
[Sentry] Please check if your DSN is set properly in your config or `.env` as `SENTRY_LARAVEL_DSN`

how can I solve this problem?

**Comment by BYK** [comment]
Duplicate of #1020.
