### ISSUE TITLE
Php artisan sentry:test error 

### ISSUE THREAD

**Issue by tbdavid94** [getsentry/onpremise#1020]
### Version

21.7.0

### Steps to Reproduce

i using php artisan sentry:test

[Sentry] DSN discovered!
[Sentry] Generating test Event
[Sentry] Sending test Event
[Sentry] There was an error sending the test event.
[Sentry] Please check if your DSN is set properly in your config or .env as SENTRY_LARAVEL_DSN

### Expected Result

how can I solve this problem?

### Actual Result

[Sentry] DSN discovered!
[Sentry] Generating test Event
[Sentry] Sending test Event
[Sentry] There was an error sending the test event.
[Sentry] Please check if your DSN is set properly in your config or .env as SENTRY_LARAVEL_DSN

**Comment by BYK** [comment]
Please do not double-post and also respect the issue template.

Closing in favor of: https://forum.sentry.io/t/php-artisan-sentry-test-error/14473

**Comment by tbdavid94** [comment]
> Please do not double-post and also respect the issue template.
> 
> Closing in favor of: https://forum.sentry.io/t/php-artisan-sentry-test-error/14473

thanks @BYK, sorry if i using invaild issue template
