### ISSUE TITLE
Get intenal error from sentry_onpremise_web_1 when download source map from artifacts. And it told me file not found.

### ISSUE THREAD

**Issue by githubmann** [getsentry/onpremise#1022]
### Version

21.5.6

### Steps to Reproduce

using `sentry-cli releases files 0.32.0 upload-sourcemaps ./build/static/js --log-level=debug --ext map --url-prefix '~/new-hardware-market/static/js/' --validate` upload source map.

Get intenal error from sentry_onpremise_web_1 when download source map from artifacts. And it told me file not found.

![image](https://user-images.githubusercontent.com/13065289/124285298-6020ef00-db80-11eb-8a0e-78c6f4bbe997.png)

then i click dowload. it told me that

![image](https://user-images.githubusercontent.com/13065289/124285397-7333bf00-db80-11eb-8a5b-260301980111.png)

i deploy sentry service in the lan, sentry.mim.net(it means i can visit sentry website) . but root url is sentry.mim.com.

### Expected Result

can dowload source map 

### Actual Result

![image](https://user-images.githubusercontent.com/13065289/124285863-f0f7ca80-db80-11eb-85c5-32384b5613b9.png)
![image](https://user-images.githubusercontent.com/13065289/124285397-7333bf00-db80-11eb-8a5b-260301980111.png)

**Comment by githubmann** [comment]
any help i appreciate

**Comment by BYK** [comment]
Hi, can you provide more details about your setup?

Also `21.5.6` is not a version we released, can you double check your Sentry version from the bottom left corner of the UI please?

**Comment by githubmann** [comment]
sorry, it 's 21.5.1.

**Comment by githubmann** [comment]
```yml
diff --git a/cron/Dockerfile b/cron/Dockerfile
index 0e6e76e..a9d7438 100644
--- a/cron/Dockerfile
+++ b/cron/Dockerfile
@@ -1,6 +1,4 @@
 ARG BASE_IMAGE
 FROM ${BASE_IMAGE}
-RUN apt-get update && apt-get install -y --no-install-recommends cron && \
-    rm -r /var/lib/apt/lists/*
 COPY entrypoint.sh /entrypoint.sh
 ENTRYPOINT ["/entrypoint.sh"]
diff --git a/docker-compose.yml b/docker-compose.yml
index 5415f5d..8b3e001 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -74,7 +74,7 @@ services:
     environment:
       POSTGRES_HOST_AUTH_METHOD: "trust"
     volumes:
-      - "sentry-postgres:/var/lib/postgresql/data"
+      - "sentry-postgres-new:/var/lib/postgresql/data"
   zookeeper:
     <<: *restart_policy
     image: "confluentinc/cp-zookeeper:5.5.0"
@@ -274,7 +274,7 @@ services:
 volumes:
   sentry-data:
     external: true
-  sentry-postgres:
+  sentry-postgres-new:
     external: true
   sentry-redis:
     external: true
diff --git a/install.sh b/install.sh
index 171851b..82cb4dc 100755
--- a/install.sh
+++ b/install.sh
@@ -20,7 +20,7 @@ source turn-things-off.sh
 source set-up-zookeeper.sh
 source bootstrap-snuba.sh
 source create-kafka-topics.sh
-source upgrade-postgres.sh
+#source upgrade-postgres.sh
 source set-up-and-migrate-database.sh
 source migrate-file-storage.sh
 source relay-credentials.sh
```

i run `install.sh` and then `COMPOSE_HTTP_TMIEOUT=300 docker-compose up -d`

I comment apt-get, because i can't download from net in the lan. seem it can't cause i unable to download souce map that i uploaded.

**Comment by BYK** [comment]
Hmm, nothing jumps at me tbh. Did you make a change recently?

I'll ping @kamilogorek and @untitaker in case they know anything about this.

**Comment by githubmann** [comment]
jThat's what I listed above, nothing else

**Comment by githubmann** [comment]
help!!! please, I totally have no idea about above error

**Comment by jjbayer** [comment]
The error means that there is an entry for the file in the database, but not on disk. So maybe there's a problem with the `sentry-data` docker volume? @githubmann are there any other files in `/data/files`? You can check with `docker exec sentry_onpremise_web_1 ls /data/files`.
