### ISSUE TITLE
Installation Failed on wal2json step

### ISSUE THREAD

**Issue by georvoud** [getsentry/onpremise#1027]
### Version

21.6.2

### Steps to Reproduce

Run install.sh

### Expected Result

Complete installation

### Actual Result

▶ Downloading and installing wal2json ...
install-wal2json.sh: line 13: WAL2JSON_VERSION: unbound variable

**Comment by BYK** [comment]
It is defined here: https://github.com/getsentry/onpremise/blob/bd8fbf960d403425c1617c14bf8f2eabb8ec50b8/.env#L10

Do you have your `.env` file up-to-date?
