### ISSUE TITLE
Unable to create second organisation [Sentry 9]

### ISSUE THREAD

**Issue by 4imble** [getsentry/onpremise#103]
When I go to the create new organization screen and choose any name (I have tried variations) it will present me with a validation error stating that it is "Unable to save your changes. Please ensure all fields are valid and try again.". 
There is also an error toast that says "There was an error saving your changes."

This will only present itself for about 1 second and then refresh the page.
Nothing is coming up in the internal logs either.

![image](https://user-images.githubusercontent.com/3931126/42019063-f610d540-7aab-11e8-9d4e-4293bc1ac0b6.png)

**Comment by Tommatheussen** [comment]
Got the same problem. When I open up a browser console and retain the logs, I see a 401 response from the API with the following detail message: `Organizations are not allowed to be created by this user.` Executing the command as superuser

**Comment by dcramer** [comment]
Is this a new setup? Have you changed the config for single organization mode?

**Comment by Tommatheussen** [comment]
For me this way a completely clean setup (just starting testing around with it), full docker installation, only secret value was set in the config files

**Comment by dcramer** [comment]
@Tommatheussen and this was trying to create a second organization? Realistically that option shouldn't even be exposed, so it might be a bug.

Was this prompted? Like when you loaded the UI it asked you to create an organization? Or did you click something to do it?

**Comment by dcramer** [comment]
Looks like this isn't correctly checking the SENTRY_SINGLE_ORGANIZATION flag. We'll get it fixed, but ultimately you shouldn't be able to create a second organization.

**Comment by Tommatheussen** [comment]
If I understand correctly, this means we should be able to create second organisation if that entry is set in the config file? Or should it just never be possible to create another organisation?

**Comment by dcramer** [comment]
@Tommatheussen thats correct

**Comment by funkyOne** [comment]
It whould be ood to be able to rename the organization. Currently it fails with "Unable to save change" error.

**Comment by BenoitPoulet** [comment]
@dcramer What is it correct ? 

1. "should it just never be possible to create another organisation?" ?
2. " we should be able to create second organisation if that entry is set in the config file"

thanks

**Comment by raunsbaekdk** [comment]
@BenoitPoulet Setting:

SENTRY_SINGLE_ORGANIZATION=0

does make you able to create an extra organization. Whether it is intentional or not, I am not able to tell you.

**Comment by landsman** [comment]
oh... is possible to change default value of SENTRY_SINGLE_ORGANIZATION to 0 please?

**Comment by dcramer** [comment]
No, we are not changing the default. Multi organization mode is built for use on sentry.io only, not for various installations. You can use it, but you do so without any guarantees. I'm also locking this thread as its a bug tracker, and the comments are unrelated to the original issue.
