### ISSUE TITLE
clickhouse-server fails due to existing status file

### ISSUE THREAD

**Issue by pharindoko** [getsentry/onpremise#1034]
### Version

21.7.0

### Steps to Reproduce

Each time the clickhouse-server will be started it writes a status file in it`s folder.
**Now in my case when I`m recreating a new VM in AWS and attach it to the same external store (AWS EFS) and clickhouse tries to startup it throws an error saying that the server status already exists.**
Due to this it clickhouse won`t startup.

Externally when starting install.sh file you won`t recognize this error. You just get a note that clickhouse on localhost:9000 can`t be connected.

Removing the status file in clickhouse directory fixes the error. clickhouse will start up without issues.

Would be nice having a task in install.sh that ensures the clickhouse status file is deleted to avoid this issue

### Expected Result

1. start install.sh script
2. connection to clickhouse server is successful

### Actual Result

1. Executing install.sh 
2. clickhouse server doesn`t come up correctly.
3. no connection to clickhouse can be established
4. install.sh fails.

**Comment by chadwhitacre** [comment]
> Now in my case when I'm recreating a new VM in AWS and attach it to the same external store (AWS EFS)

@pharindoko Since you have a custom setup, can you solve this with some custom scripting on your side? As I understand it this problem would not generally affect stock `onpremise` deploys, is that right?

**Comment by pharindoko** [comment]
Hey @chadwhitacre , @BYK 

this has nothing to do with the other issue.
It happens when I recreate (for different reasons) the aws ec2 vm (using terraform) and have the same clickhouse folder stored externally. 
(external docker-volume)

It won`t override the status file but throw a nasty error internally in clickhouse, that this file already exists.
And clickhouse doesn`t come up...

I fixed it by removing the file before I start the install.sh

Can you replicate this issue ?

Proposal would be to document this issue (troubleshooting) or add some checks for clickhouse in install.sh

**Comment by BYK** [comment]
@pharindoko since we do not support alterations on this setup, I'm not sure if it makes sense to document this on our own docs. Moreover, this sounds more like an issue with Clickhouse itself rather than how we use it?

**Comment by pharindoko** [comment]
yeah well the tricky thing is that it doesn`t show up as an error in any way when you try to run the installation.
But you`re right - it`s a clickhouse issue - I should forward it to them.
