### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by achyuth-111** [getsentry/onpremise#1037]
### Environment

self-hosted (`onpremise` deployment)

### Steps to Reproduce

I gave the wrong credentials, it should give me the error but it redirecting me to this page [
![image](https://user-images.githubusercontent.com/75174613/125721753-a4eae48f-e5d6-4dc4-8679-0af2af93a6a2.png)
](url)

for the second attempt I gave the right credentials but redirecting to the same page mentioned above

### Expected Result

Welcome page / Main page 

### Actual Result

[
![image](https://user-images.githubusercontent.com/75174613/125720289-2cd1291c-eed1-4d2c-ae33-804b924a7c39.png)
](url)

**Comment by achyuth-111** [comment]
@chadwhitacre
Since I can't login to the sentry I am providing the below  SHA
current version **** (git rev-parse HEAD------->64aec777ceb47a151fefe428df5d351fb434d14d )
What log do you need, can you please specify them?
Is this due to the db is not recognizing me?

**Comment by chadwhitacre** [comment]
> What log

I guess the one for the "server API"? That's what it says is having a problem:

<img width="250" alt="Screen Shot 2021-07-20 at 8 13 27 AM" src="https://user-images.githubusercontent.com/134455/126321848-d06a44d6-b16c-4473-ac97-2b5a83dcd912.png">

One way or another, this appears at this point to be a configuration issue on your side, not a bug on our side. Feel free to use the [forum](https://forum.sentry.io/) or [discord](https://discord.com/invite/Ww9hbqr) to ask the community for help.

**Comment by achyuth-111** [comment]
@chadwhitacre Thank you 
I have created my account in sentry forum but my account is temporarily on hold from almost a week. So can you help me how to proceed further?

**Comment by chadwhitacre** [comment]
You fooled the forum into thinking you were a bot by copying and pasting and entering so fast. :o)

Approved!

**Comment by achyuth-111** [comment]
I don't have any intension to do that any way thank you for the approval.

**Comment by achyuth-111** [comment]
@chadwhitacre Thank you so much for your help.
 Can you explain me what kind of configuration issue it could be ?
