### ISSUE TITLE
Unable to receive issues in Vue Application

### ISSUE THREAD

**Issue by rookie-hhm** [getsentry/onpremise#1046]
### Version

21.8.0.dev0 ebd6723

### Steps to Reproduce

1. clone repo and ./install.sh
2. get a dns and use in project
3. throw some errors, like `throw new Error('erer')`

### Expected Result

Sentry server catch errors and create issues.

### Actual Result

Sentry server cannot catch errors and create issues, but there are nothing.
![image](https://user-images.githubusercontent.com/34794050/128120364-f5503676-babf-4def-906c-e07eefb523b9.png)
project is not active.
![image](https://user-images.githubusercontent.com/34794050/128120241-7375bad5-b2c7-4967-afe1-b97d07342bbb.png)

**Comment by rookie-hhm** [comment]
The docker services are running successfully, not error logs.

**Comment by rookie-hhm** [comment]
When I throw out some errors, I see the sentry request has been sent in chrome's network panel .

**Comment by BYK** [comment]
> I see the sentry request has been sent in chrome's network panel .

We need the logs for these and the logs from the services to be able to diagnose the issue.

**Comment by rookie-hhm** [comment]
> > I see the sentry request has been sent in chrome's network panel .
> 
> We need the logs for these and the logs from the services to be able to diagnose the issue.

Yes, 
`
2021-08-05T02:24:54Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 57.665039062s

2021-08-05T02:25:39Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream

caused by: error sending request for url (http://web:9000/api/0/relays/register/challenge/): error trying to connect: tcp connect error: Connection refused (os error 111)
`

**Comment by BYK** [comment]
Well, there's your error. Your `web` instance doesn't seem to be working?
