### ISSUE TITLE
Unable to create relay/credentials.json in git-bash

### ISSUE THREAD

**Issue by rookie-hhm** [getsentry/onpremise#1047]
### Version

21.8.0.dev0 ebd6723

### Steps to Reproduce

OS: windows server 2016
When I execute install.sh in git-bash

`
Generating Relay credentials...
Creating sentry_onpremise_relay_run ...
Creating sentry_onpremise_relay_run ... done
error: could not open config file (file /work/C:/Users/CurrentUser/AppData/Local/Temp/config.yml)
  caused by: No such file or directory (os error 2)
An error occurred, caught SIGERR on line 319
Cleaning up...
`

I see same issue [#705 ](https://github.com/getsentry/onpremise/issues/705), but I don't konw how to download the relay binary and generated the credentials manually by myself, can you tell me the detailed steps (windows) ?

### Expected Result

create relay/credentials.json successfully

### Actual Result

`Generating Relay credentials... Creating sentry_onpremise_relay_run ... Creating sentry_onpremise_relay_run ... done error: could not open config file (file /work/C:/Users/CurrentUser/AppData/Local/Temp/config.yml) caused by: No such file or directory (os error 2) An error occurred, caught SIGERR on line 319 Cleaning up...`

**Comment by BYK** [comment]
We don't support `git-bash` unfortunately. We don't support it so much that we have a specific line stopping the installation in its tracks:

https://github.com/getsentry/onpremise/blob/39ea4dcec35e9cb73999e8f1686cd39cdb759ca7/install.sh#L3-L6

I'm assuming you removed that line to get the install going and it failed at some other point as expected. So closing this issue as invalid.

**Comment by rookie-hhm** [comment]
Yeah, Thank you!
