### ISSUE TITLE
Can't install on WSL2

### ISSUE THREAD

**Issue by maxisam** [getsentry/onpremise#1055]
### Version

latest

### Steps to Reproduce

I follow the document with the latest docker and I clone repo inside wsl directly.

### Expected Result

work

### Actual Result

I get through most of the steps but failed on

```sh
▶ Generating Relay credentials ...
Creating ../relay/config.yml...
[16243] Failed to execute script docker-compose
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 144, in get_project
  File "compose/config/config.py", line 317, in find
  File "compose/config/config.py", line 353, in get_default_config_files
  File "compose/config/config.py", line 389, in find_candidates_in_parent_dirs
  File "posixpath.py", line 383, in abspath
FileNotFoundError: [Errno 2] No such file or directory
An error occurred, caught SIGERR on line 17
Cleaning up...
```

I check the config in relay. there is no /geoip/GeoLite2-City.mmdb but only GeoLite2-City.mmdb.empty

**Comment by BYK** [comment]
I had the same error just yesterday and realized my `docker-compose` version inside WSL2 was quite old. Could that be the case for you too?

**Comment by maxisam** [comment]
> I had the same error just yesterday and realized my `docker-compose` version inside WSL2 was quite old. Could that be the case for you too?

nope. I am on  version 1.29.2 build 5becea4c

**Comment by BYK** [comment]
>nope. I am on version 1.29.2 build 5becea4c

Could it be a custom version you installed that is not compatible with your Docker Desktop version? Because that's how I fixed the issue:

1. Uninstall from the Linux side
2. Shut down and reopen Docker Desktop and make sure the "WSL2 integration" is applied to my default distro

Oh, I also upgraded all the packages I could upgrade, which might have helped.

**Comment by maxisam** [comment]
No I didn't use a custom version. I update docker from windows this morning to meet the requirement but it doesn't work either

**Comment by BYK** [comment]
@maxisam this is not something we can fix with our code as it clearly works on many other systems. I looked for the error message and there are a bunch of possible reasons and possible solutions: https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue/48957722#48957722

You'll just need to figure out what's off with your system like I did to mine unfortunately.

**Comment by maxisam** [comment]
@BYK I really wish you guys think about k8s setup. I honestly think it is unlikely people will run their own setup instead of using your service, unless you guys charge unreasonable. 

And you guys can sell support package or something else for self-host solution.

**Comment by BYK** [comment]
@maxisam not sure how using k8s is relevant to your issue here but your feedback is noted.

**Comment by maxisam** [comment]
People can use KIND/K3S/MicroK8s.  The whole thing can be 100% repeatable in any environment. I think it will help people to test it locally. You expecting 2 weeks to sell this for a company. It is not possible for some companies. They just don't make decision that fast like people in Silicon Valley.
