### ISSUE TITLE
error opening file: open /sentry/GeoIP.conf

### ISSUE THREAD

**Issue by maxisam** [getsentry/onpremise#1056]
### Version

Sentry 21.8.0.dev 08b6e12c

### Steps to Reproduce

follow the readme and run it on ubuntu 20.04

### Expected Result

it should work

### Actual Result

geoipupdate doesn't work

error loading configuration file /sentry/GeoIP.conf: error opening file: open /sentry/GeoIP.conf: no such file or directory

**Comment by chadwhitacre** [comment]
@maxisam Can I see `ls -l geoip` in your sentry root?

**Comment by maxisam** [comment]
-rw-r--r-- 1 root      root      1055 Aug  5 14:43 GeoLite2-City.mmdb
-rw-rw-r-- 1 xxx      xxx        1055 Aug  5 13:50 GeoLite2-City.mmdb.empty

**Comment by chadwhitacre** [comment]
Hrm ... `ls -l .`?

**Comment by maxisam** [comment]
config.example.yml
config.yml
entrypoint.sh
requirements.example.txt
requirements.txt
sentry.conf.example.py
sentry.conf.py

**Comment by chadwhitacre** [comment]
> in your sentry root?

Sorry, by this I mean your `onpremise` root, the root of your Sentry instance, not the `sentry` directory underneath that root.

> error loading configuration file /sentry/GeoIP.conf: error opening file: open /sentry/GeoIP.conf: no such file or directory

The `/sentry/` in this error message refers to a path inside of the `geoipupdate` docker container, which is [mapped](https://github.com/getsentry/onpremise/blob/d11fb14ceecb92078cf59449a93e1fb02e8b101f/docker-compose.yml#L198-L199) to the `./geoip` directory in your Sentry (i.e. `onpremise`) root. My hunch is that you don't have a file at `./geoip/GeoIP.conf` file on your host system, so therefore you don't have a file at `/sentry/GeoIP.conf` in your `geoipupdate` docker container.

**Comment by maxisam** [comment]
CHANGELOG.md
LICENSE
README.md
_integration-test
certificates
clickhouse
cron
docker-compose.yml
geoip
install
install.sh
nginx
postgres
relay
reset.sh
scripts
sentry
symbolicator
test.sh
zookeeper

No, I don't have GeoIP.Conf anywhere

**Comment by chadwhitacre** [comment]
> No, I don't have GeoIP.Conf anywhere

Well there's your problem, then, isn't it. :)

> follow the readme

Did you really?

> To enable server-side IP address geolocation, sign up for a free MaxMind account, then tell Sentry about your credentials by placing your MaxMind configuration file at `geoip/GeoIP.conf`.

https://develop.sentry.dev/self-hosted/geolocation/

**Comment by maxisam** [comment]
@chadwhitacre Sorry, I assumed all setup to make thing running is inside README.md. And you have a pretty long requirements check script. I guess it would be nice to check if there is a GeoIP.config and throws a warning.

**Comment by chadwhitacre** [comment]
Ah, gotcha. Yeah, in [the README proper we link out](https://github.com/getsentry/onpremise#setup) to the main docs. Good luck! :)
