### ISSUE TITLE
Sentry Gitlab Integrations - only showing 20 repositories

### ISSUE THREAD

**Issue by klemenag** [getsentry/onpremise#1067]
### Version

20.12.1 bade073

### Steps to Reproduce

1. Open Sentry --> Integrations --> Gitlab
2. Add installation and connect with gitlab
3. try adding a repository on the newly added project

### Expected Result

**all** repositories are shown

### Actual Result

On the dropdown menu only 20 repositores are shown

**Comment by chadwhitacre** [comment]
@klemenag You're pretty far out of date there on 20.12.1. Can you repro with the latest version?
