### ISSUE TITLE
ERROR: Invalid interpolation format for "postgres" option in service "services": "pg_isready -U ${POSTGRES_USER:-postgres}"

### ISSUE THREAD

**Issue by Plourt** [getsentry/onpremise#1075]
### Version

21.7.0

### Steps to Reproduce

docker-compose up

### Expected Result

ERROR: Invalid interpolation format for "postgres" option in service "services": "pg_isready -U ${POSTGRES_USER:-postgres}"

### Actual Result

ERROR: Invalid interpolation format for "postgres" option in service "services": "pg_isready -U ${POSTGRES_USER:-postgres}"

**Comment by chadwhitacre** [comment]
Do you have a literal `$` in your `POSTGRES_USER`?

https://stackoverflow.com/questions/49897503/docker-compose-invalid-interpolation-format-for-environment-option-in-service
