### ISSUE TITLE
reset.sh breaking after passing to install.sh during check-minimum-requirements.sh line 3: file not found

### ISSUE THREAD

**Issue by kibble1** [getsentry/onpremise#1079]
### Version

nightly

### Steps to Reproduce

on an existing onpremise setup run ./reset.sh

after the call to install.sh check-minimum-requirements breaks at line 3: with the call to _min_requirements.sh not found.

seems while running in reset.sh and then calling install.sh the working directory changes to onpremise; however if running strictly in install.sh the working directory is onpremise/install

![image](https://user-images.githubusercontent.com/13425185/131177473-70b633cb-4770-4c67-a88f-02cae3e11e8c.png)

### Expected Result

reset.sh and then install.sh should flow correctly

### Actual Result

exits with check-minimum-requirements.sh: line 3: /root/onpremise/_min-requirements.sh: No such file or directory

![image](https://user-images.githubusercontent.com/13425185/131177595-464c92dd-4c7c-495b-88eb-06bd701e894e.png)

**Comment by chadwhitacre** [comment]
Figured I'd better 👍 this issue as I just ran into it myself. 😂 😭
