### ISSUE TITLE
how to limit the memory when upgrade ?

### ISSUE THREAD

**Issue by dishenghk** [getsentry/onpremise#108]
rt..

My machine often crashes when I execute this command.
docker-compose run  --rm web upgrade 
so,how to limit the memory when upgrade ?
thank you

**Comment by dishenghk** [comment]
often stop at
sentry:0407
sentry 0408
...
sentry:0410

**Comment by revolunet** [comment]
this setup has several containers so you need a lot of memory :/

**Comment by BYK** [comment]
https://docs.docker.com/engine/reference/run/#user-memory-constraints
>By default, kernel kills processes in a container if an out-of-memory (OOM) error occurs. To change this behaviour, use the `--oom-kill-disable` option. Only disable the OOM killer on containers where you have also set the `-m/--memory` option. If the `-m` flag is not set, this can result in the host running out of memory and require killing the host’s system processes to free memory.

Closing as this is something to do with Docker itself and we have already documented the minimum memory requirements in the read me lately.

**Comment by dmugtasimov** [comment]
For those who do not have 3Gb RAM, but still want to use Sentry. Add swap file to your VM:

```
#. Add 8G swapfile::

    sudo -i

    # Allocate swap space
    fallocate -l 8G /swapfile
    chmod 600 /swapfile
    mkswap /swapfile

    # Turn on swap file
    swapon /swapfile
    vim /etc/fstab
    # Add the following line
    # /swapfile swap swap defaults 0 0

    # Correcting swappiness
    sysctl vm.swappiness=10
    vim /etc/sysctl.conf
    # Add the following line
    # vm.swappiness=10

    reboot

    # Validate new settings
    swapon --show
    cat /proc/sys/vm/swappiness
```

**Comment by dmugtasimov** [comment]
@BYK Would you add the swap file workaround in official docs as recommendation?

**Comment by BYK** [comment]
I'd rather not as this requirement should go away sometime soon (a few months maybe?) and the new install script actually automatically bails if it cannot use 3GB of RAM in a docker image. That said I do see this being useful.

Maybe just leave it here or post it on [the forum](https://forum.sentry.io/) so when people _really_ need this, they can find _a_ solution? Putting this on the docs would require us to maintain this which I'm not too keen on.
