### ISSUE TITLE
sentry_onpremise_nginx_1 log get 403

### ISSUE THREAD

**Issue by duyuyouci** [getsentry/onpremise#1085]
### Version

21.9.0

### Steps to Reproduce

django：2.2.15
Ubuntu：20.04.3

### Expected Result

The expectation is to get 200

### Actual Result

docker logs -f sentry_onpremise_nginx_1

`
198.19.19.4 - - [02/Sep/2021:17:14:23 +0000] "POST /api/2/envelope/ HTTP/1.1" 403 61 "-" "sentry.python/1.3.1" "-"
198.19.18.153 - - [02/Sep/2021:17:14:23 +0000] "POST /api/2/envelope/ HTTP/1.1" 403 61 "-" "sentry.python/1.3.1" "-"
198.19.18.153 - - [02/Sep/2021:17:14:23 +0000] "POST /api/2/envelope/ HTTP/1.1" 403 61 "-" "sentry.python/1.3.1" "-"
`

I don’t know if this will affect the operation of sentry, and errors can be recorded normally on the web.

**Comment by BYK** [comment]
This is a configuration error on your end. Looks like you are not using our shipped nginx configuration and missing the routing piece towards the relay ingestion service: https://github.com/getsentry/onpremise/blob/b32de84d31dd1cc0b9c9534fae2e95ad86a0cbee/nginx/nginx.conf#L64-L69
