### ISSUE TITLE
Empty reply from server time to time

### ISSUE THREAD

**Issue by zahradehghanpur** [getsentry/onpremise#1087]
### Version

9.12

### Steps to Reproduce

I am getting empty reply from server time to time , for example three times in a row the curl command is ok but the fourth one is giving me empty reply from server

### Expected Result

`curl  --location --request GET 'http://XXXX/api/0/orgthorization: Bearer XX' --header 'TE: gzip' 
{"maxFileSize": 2147483648, "hashAlgorithm": "sha1", "concurrency": 4, "chunkSize": 8388608, "maxRequestSize": 33554432, "url": "https://XXX/api/0/organizations/sentry/chunk-upload/", "chunksPerRequest": 64, "compression": ["gzip"]}`

### Actual Result

```
curl  --location --request GET 'http://XXXX/api/0/orgthorization: Bearer XXXX' --header 'TE: gzip' 
curl: (52) Empty reply from server

```

**Comment by chadwhitacre** [comment]
@zahradehghanpur 9.1.2 is ancient. Can you upgrade?
