### ISSUE TITLE
Failed to create topic events

### ISSUE THREAD

**Issue by realkimmy** [getsentry/onpremise#1092]
### Version

21.8.0

### Steps to Reproduce

[error1.txt](https://github.com/getsentry/onpremise/files/7159858/error1.txt)

### Expected Result

Normal installation

### Actual Result

[error1.txt](https://github.com/getsentry/onpremise/files/7159864/error1.txt)

**Comment by BYK** [comment]
Closing in favor of https://forum.sentry.io/t/failed-to-create-topic-events/15097
