### ISSUE TITLE
Missing Client IP in SDK info

### ISSUE THREAD

**Issue by ankitva** [getsentry/onpremise#1093]
Did you check global, organization and project settings?

_Originally posted by @jaylinski in https://github.com/getsentry/sentry/issues/9172#issuecomment-409161767_

I m facing this issue after sentry upgrade.

**Comment by BYK** [comment]
@ankitva can you please provide more details as that issue is quite old and the details are not clear. Using our issue templates are the best way to express critical details for us to diagnose the issue and help you.

**Comment by ankitva** [comment]
### Version.
21.9.0
### Steps to Reproduce.
1. Install sentry onpremise on linux using docker.
2. Setup nginx to proxy 443 trafic to 9090.
3. Create python project.
4. Project settings -> security and privacy -> turn off data scrubber & Prevent Storing of IP Addresses.
5. Organization settings -> security and privacy -> turn off data scrubber & Prevent Storing of IP Addresses.
6. Create user with superuser privilege.
7. Configure python app with sentry SDK with option "send_default_pii=True"
### Expected Result.
Once new event is captured it should show Client IP under SDK info. if user has superuser privilege. 

![image](https://user-images.githubusercontent.com/91019675/134003568-acc11457-58e2-42c0-958c-9e2d559f39a3.png)
### Actual Result.
Client IP field is missing in SDK info.

![image](https://user-images.githubusercontent.com/91019675/134005017-a8e63d5b-4ba1-47b8-9c39-2bf93d61cf72.png)

**Comment by ankitva** [comment]
@BYK I have added details as per the issue template.

**Comment by chadwhitacre** [comment]
> 
Configure python app with sentry SDK with option "send_default_pii=True"

Hrm ... we had another recent report like this. Was that in the forums? 🤔 ...

**Comment by chadwhitacre** [comment]
[Here it is](https://forum.sentry.io/t/client-ip-section-missing-after-upgrade/14847/14).

**Comment by chadwhitacre** [comment]
Oh lol same OP. 🤡

**Comment by chadwhitacre** [comment]
[From the forum](https://forum.sentry.io/t/client-ip-section-missing-after-upgrade/14847/6?u=chadwhitacre) ...

> I'm getting correct IP in CSP events. But other events like python I m not getting client IP field at all.

Can you try one or two other SDKs? If you are able to see Client IP from Ruby, PHP, Go, etc., then that would be a strong signal that the Python SDK is the problem component here.

Basically we need to figure out which component is dropping the IP address (SDK, Nginx, web app, ... etc.?), and then figure out whether it is a misconfiguration on your end or a bug on our end. :)

**Comment by BYK** [comment]
Pinging @untitaker and @kamilogorek as they are the SMEs here.

**Comment by ankitva** [comment]
sure will check with different SDK.

**Comment by kamilogorek** [comment]
I think https://github.com/getsentry/sentry-python/commit/9de8d4717f4a9846f0df86708307632ae317f20f will fix it. Please try once `1.14.0` is released (should be done Today).

**Comment by ankitva** [comment]
@kamilogorek my issue is not like I am getting wrong IP. but "Client IP" field is missing itself. still i will try new release once it's available.

**Comment by ankitva** [comment]
tried ruby sdk with  "config.send_default_pii = true" option still no luck.

![image](https://user-images.githubusercontent.com/91019675/134191665-02ce6f6b-6df7-4df1-8b44-21f3141abe23.png)

**Comment by chadwhitacre** [comment]
> tried ruby sdk with "config.send_default_pii = true" option. still no luck.

Hmm ... interesting. That suggests that the SDK is not the failing component here. Personally my money is on Nginx. :) Can you take Nginx out of the mix and send traffic directly to the Sentry web app?

**Comment by ankitva** [comment]
Will try sending traffic directly on sentry 9000 port. Do you guys get Client IP field in SDK info on ur sentry setup?

**Comment by BYK** [comment]
>Will try sending traffic directly on sentry 9000 port. 

This will not work as you need `relay` to process the event payload.

Can you increase the level of logging on Nginx and share the event payloads with us?

**Comment by ankitva** [comment]
Hi @BYK this only i can fetch using nginx. let me know if this is helpful. 
[post.log](https://github.com/getsentry/onpremise/files/7279968/post.log)

**Comment by ankitva** [comment]
i also try to setup senty without nginx. Events are captured but no SDK IP.

**Comment by BYK** [comment]
@kamilogorek @st0012, nginx logs have a sample event there, would that help you diagnose?

**Comment by ankitva** [comment]
@st0012 should i try new python SDK and check?

**Comment by ankitva** [comment]
Can we use some other way from which I can get IP of machine from which error is generated? it's very basic and time efficient method to look for issue if application is hosted on multiple machines.  I can see hostname but as we run application in container it show container name instate of host name.

**Comment by untitaker** [comment]
Going to close this as we intentionally removed client IP from events. If there's popular demand we can add it again, but the reasoning at the time, IIRC, was that it is a source of PII with questionable value to the user. If you need a way to distinguish your servers, there's probably better ways to do that anyway by something other than IP: Use a custom tag.

**Comment by ankitva** [comment]
Thanks mark for clarification. will check how to achieve this using tag.
