### ISSUE TITLE
Reset sentry keep dsn

### ISSUE THREAD

**Issue by Herz3h** [getsentry/onpremise#1094]
### Problem Statement

Hello,

I have recently upgraded from sentry 8 into 9.1.2 and I have issues with search, when I type: `site:subdomain.mysite.com` it doesn't suggest this website in search bar, so I can't find it.

This issue appeared after I upgraded sentry. So is there a way to reset sentry data (I guess, I can do a `docker-compose down -v` to remove volumes). Problem is, I would like to keep the DSN and projects, so is there a way to do that ?  I don't mind losing all the reported issues. 

### Solution Brainstorm

Something like export sentry projects.

**Comment by BYK** [comment]
Hi, we have this: https://develop.sentry.dev/self-hosted/backup/#quick-backup

But it has known problems on v9 which is quite old so I cannot guarantee that it would work.

Are you able to upgrade to a more recent version?

**Comment by BYK** [comment]
Closing in favor of #1095.
