### ISSUE TITLE
Sentry no more catch errors. issue not show on my website. 

### ISSUE THREAD

**Issue by MyNameisQiShiQi** [getsentry/onpremise#1099]
### Environment

self-hosted (`onpremise` deployment)

### Version

21.6.3

### Steps to Reproduce

Sentry no more catch errors 5 hours ago.
And I found error something like:
1.  kafka:9092/bootstrap: Connect to ipv4#172.20.0.11:9092 failed: Connection refused (after 1ms in state CONNECT)
2. Caught ConsumerError('KafkaError{code=COORDINATOR_LOAD_IN_PROGRESS,val=14,str="JoinGroup failed: Broker: Coordinator load in progress"}'), shutting down...

### Expected Result

Sentry  catch errors and show on my website

### Actual Result

not show

**Comment by chadwhitacre** [comment]
Can you upgrade? We added some healthchecks since 21.6.3 that might help with the connection timeouts.

**Comment by BYK** [comment]
@MyNameisQiShiQi I'm assuming you followed the steps at https://develop.sentry.dev/self-hosted/troubleshooting/#kafka ?

**Comment by BYK** [comment]
The errors indicate your Kafka service is out of service and this is due to some error spike and a huge processing backlog. Closing as this is not something we can help fix (nothing we can add onto that troubleshooting guide)
