### ISSUE TITLE
 _span_recorder

### ISSUE THREAD

**Issue by rajkumarks7** [getsentry/onpremise#1101]
### Version

 21.10.0.dev0

### Steps to Reproduce

sentry.tasks.send_ping

### Expected Result

sentry.tasks.send_ping

### Actual Result

![Screenshot (16)](https://user-images.githubusercontent.com/64638741/135014595-b72da3c5-2e15-410c-8328-eaaf390497ca.png)

**Comment by BYK** [comment]
Can you share a link to this issue or the stacktrace instead of a screenshot please?

**Comment by rajkumarks7** [comment]
https://sentry.internal.joinworkahub.com/share/issue/a88cd5146bc44feeafaa1624701e6a26/

**Comment by BYK** [comment]
@untitaker any ideas?

**Comment by untitaker** [comment]
pretty sure this is fixed in https://github.com/getsentry/sentry/commit/7c990f98a8aae8792ddf73d6290a4bc4cf354536, I assume this commit didn't make the release?

this is probably a critical bug fwiw

**Comment by rajkumarks7** [comment]
shall i pull the latest code again and try?

**Comment by untitaker** [comment]
if you feel comfortable building your own docker images etc, sure

**Comment by rajkumarks7** [comment]
i just pull the latest code and make docker compose up

**Comment by BYK** [comment]
>if you feel comfortable building your own docker images etc, sure

Yeah, this is not needed as we build images for each commit on master.

@rajkumarks7 would you mind giving this a go?

**Comment by BYK** [comment]
> I assume this commit didn't make the release?

Release was on September 15th so yeah, it did not 🙂 That said I'm 

>this is probably a critical bug fwiw

@untitaker do you know if this is a new bug or an existing bug for a while? Asking to determine whether we should do a patch release before the scheduled 21.10 on October 15th.

**Comment by rajkumarks7** [comment]
what i have do now like master is a head like 21.10 present version is 21.9.0 to get rid of this error

**Comment by BYK** [comment]
You can check out the `master` branch of this repo and then run `./install.sh`

**Comment by rajkumarks7** [comment]
i am on master branch only when i did ./install.sh

**Comment by BYK** [comment]
@rajkumarks7 just run it again and it will fetch the latest version of the image 🙂

**Comment by rajkumarks7** [comment]
ok

**Comment by BYK** [comment]
Just got word from @untitaker that this bug was introduced recently and fixed quickly thereafter. Seems like @rajkumarks7 was just in the wrong place at the wrong time.

**Comment by chadwhitacre** [comment]
Congrats @rajkumarks7, I think? :P
