### ISSUE TITLE
Add support to run sentry upgrade programmatically without having to handle the prompt for the default user

### ISSUE THREAD

**Issue by nbraun-wolf** [getsentry/onpremise#1102]
### Problem Statement

Hi, it is problematic that the first sentry upgrade command requires user input. This makes it hard to fully automate the setup.

### Solution Brainstorm

Allow setting some environment variable or flag for the initial username and password.

**Comment by chadwhitacre** [comment]
Seems reasonable, thanks for the ticket @nbraun-wolf. Putting on the backlog for now, PRs welcome. :)

**Comment by BYK** [comment]
https://github.com/getsentry/onpremise#setup
>During the install, a prompt will ask if you want to create a user account. If you require that the install not be blocked by the prompt, run `./install.sh --no-user-prompt`.

**Comment by chadwhitacre** [comment]
Best feature to add is the one that already exists. 😊
