### ISSUE TITLE
sentry periodically stops processing events but doesn't complain about just anything

### ISSUE THREAD

**Issue by drook** [getsentry/onpremise#1105]
### Version

21.6.3

### Steps to Reproduce

install sentry on premises.

### Expected Result

Sentry is working 24x7x365.

### Actual Result

Sentry periodically stops sending events. Several sentry components can go south: snuba, relay, conluent/kafka, sentry itself. Usually they complain about something (except sentry). When there's no complains, since 10.x it was just possible to flush all the redis keys and the channeling continues. At the moment on 21.6.3 this doesn't always help.

The most critical thing that there's no errors in sentry components like at all (sentry web showing 200, sentry workers/subscribers not showing any logs after start, relay log is silent, snuba spamming normal messages). So there's no way to tell what's wrong.
This behavior isn't changing from 20.8.0 at least.

I totally understand that this issue reported just as it is isn't of any help, but so are the sentry logs.
Clearly something is happening when redis database comprises a lot of keys (from my observations this happens after 2K threshold, with probability of sentry being stuck increasing the more keys it contains), but some component (still don't have any idea which one becomes stuck) could at least complain about being not okay.

**Comment by chadwhitacre** [comment]
> Sentry periodically stops sending events. Several sentry components can go south: snuba, relay, conluent/kafka, sentry itself. 
> I totally understand that this issue reported just as it is isn't of any help, but so are the sentry logs.

Hrm, yeah, we're going to need to really focus to pin down what's going on. Which component went south most recently? Should we start with that one?

First hunch is resource constraints on your side rather than bugs on our side ... but ya never know. :)

**Comment by drook** [comment]
I totally agree that the issue is most probably on my side, but according to logs there's none. I'd be happy if logs would say where does the problem lie.

Let's start on how flushing the redis database can help unstuck the event channeling. This is at least something.
I'm also running with almost the default sentry.conf.py. May be it's out-of-the-box log level just isn't enough ? 
On the other hand, in the sample config I see "DEBUG = False", but setting this to true seems a bit harsh... I suppose I will be overwhelmed by the logs then (considering my instance has an average rps of some hundreds per minute).

**Comment by BYK** [comment]
I think you need to take a look at our docs first:

- For logging: https://develop.sentry.dev/config/#logging
- For Redis/Workers/scaling: https://develop.sentry.dev/self-hosted/troubleshooting/#redis
