### ISSUE TITLE
Could not resolve host: api.github.com

### ISSUE THREAD

**Issue by F3ngdw** [getsentry/onpremise#1136]
### Version

21.7.0

### Steps to Reproduce

Setting up Zookeeper ...
Creating network "sentry_onpremise_default" with the default driver
Creating volume "sentry_onpremise_sentry-secrets" with default driver
Creating volume "sentry_onpremise_sentry-smtp" with default driver
Creating volume "sentry_onpremise_sentry-zookeeper-log" with default driver
Creating volume "sentry_onpremise_sentry-kafka-log" with default driver
Creating volume "sentry_onpremise_sentry-smtp-log" with default driver
Creating volume "sentry_onpremise_sentry-clickhouse-log" with default driver
Creating sentry_onpremise_zookeeper_run ...
Creating sentry_onpremise_zookeeper_run ... done

▶ Downloading and installing wal2json ...
Unable to find image 'curlimages/curl:7.77.0' locally
7.77.0: Pulling from curlimages/curl
339de151aab4: Pulling fs layer
9576f9a419e9: Pulling fs layer
5b67e0e9bce9: Pulling fs layer
7c0640a6c519: Pulling fs layer
1d8f7d50664a: Pulling fs layer
3ce74da83aeb: Pulling fs layer
7094fabf5e16: Pulling fs layer
2f4d0b649c1f: Pulling fs layer
110e7f874674: Pulling fs layer
7c0640a6c519: Waiting
1d8f7d50664a: Waiting
2f4d0b649c1f: Waiting
3ce74da83aeb: Waiting
5b67e0e9bce9: Verifying Checksum
5b67e0e9bce9: Download complete
339de151aab4: Verifying Checksum
339de151aab4: Download complete
9576f9a419e9: Verifying Checksum
9576f9a419e9: Download complete
339de151aab4: Pull complete
9576f9a419e9: Pull complete
5b67e0e9bce9: Pull complete
7c0640a6c519: Verifying Checksum
7c0640a6c519: Download complete
3ce74da83aeb: Download complete
7c0640a6c519: Pull complete
1d8f7d50664a: Verifying Checksum
1d8f7d50664a: Pull complete
3ce74da83aeb: Pull complete
7094fabf5e16: Verifying Checksum
7094fabf5e16: Download complete
2f4d0b649c1f: Verifying Checksum
2f4d0b649c1f: Download complete
110e7f874674: Verifying Checksum
110e7f874674: Download complete
7094fabf5e16: Pull complete
2f4d0b649c1f: Pull complete
110e7f874674: Pull complete
Digest: sha256:6e0a786e3e5181df00eaf3a0a1749c18a6bb20b01c9bd192ea72176ce8a1c94b
Status: Downloaded newer image for curlimages/curl:7.77.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: api.github.com
An error occurred, caught SIGERR on line 18
Cleaning up...

### Expected Result

no

### Actual Result

An error occurred, caught SIGERR on line 18
Cleaning up...

**Comment by aminvakil** [comment]
Most probably this is something related to your system, can you resolve `api.github.com` from your host?
Have you tried changing your system DNS servers?

**Comment by chadwhitacre** [comment]
Thanks for jumping in @aminvakil. :)

@F3ngdw Is this related to https://github.com/getsentry/onpremise/issues/1112#issuecomment-960563655?

**Comment by F3ngdw** [comment]
> Thanks for jumping in @aminvakil. :)
> 
> @F3ngdw Is this related to [#1112 (comment)](https://github.com/getsentry/onpremise/issues/1112#issuecomment-960563655)?

yes! and i replaced the $VERSION=0.0.2 (which is the newest version of wal2json on github) in isntall_wal2json.sh and then this problem was fixed, but later i got  "for snuba-api  Container "c0090556afb0" is unhealthy" (this container is sentry_onprimise_clickhouse_1).

**Comment by chadwhitacre** [comment]
> i replaced the $VERSION=0.0.2 (which is the newest version of wal2json on github) in isntall_wal2json.sh and then this problem was fixed

Seems like a red herring to me. How would pinning the version resolve a network issue?

> later i got "for snuba-api Container "c0090556afb0" is unhealthy" (this container is sentry_onprimise_clickhouse_1).

Seems separate and unrelated. Would need more details to understand if this is due to a bug on our side.

> yes!

In that case let's close this as a duplicate. :)
