### ISSUE TITLE
Unable to log information

### ISSUE THREAD

**Issue by duyuyouci** [getsentry/onpremise#1145]
### Version

21.11.0.dev0

### Steps to Reproduce

1.manually deleted kafka volume and data volume
2.manually created kafka volume and data volume

### Expected Result

Log information normally

### Actual Result

- docker logs -f -n 100 sentry_onpremise_nginx_1
This log shows normal, sentry can receive requests normally

but
![image](https://user-images.githubusercontent.com/39803418/141397398-6a2a85de-7a7e-4733-a4a6-fc161c38cadf.png)

**Comment by chadwhitacre** [comment]
Sorry for my ignorance ... is there a specific reason that you expect Sentry to gracefully hand deleting and recreating the kafka and data volumes? Do we document that somewhere?
