### ISSUE TITLE
Install.sh hangs asking for input

### ISSUE THREAD

**Issue by martmists-gh** [getsentry/onpremise#1146]
### Version

21.10.0

### Steps to Reproduce

1. Extract 21.10.0.zip
2. Run install.sh

### Expected Result

Sentry installs

### Actual Result

Sentry hangs on "Would you like to create a user account now? [Y/n]: " with no way to give input or even ^C, effectively locking me out of my current SSH session.

To get out of this I need to open a second ssh session and kill it with SIGKILL as SIGTERM does not terminate the script.
It also seems to invoke cfmakeraw around this time as the terminal output is offset every newline due to missing carriage returns.

![Screenshot_20211112_032639](https://user-images.githubusercontent.com/16361449/141399206-2a48e239-8a11-456f-bc64-f4aad76d7c30.png)

**Comment by chadwhitacre** [comment]
Thanks for the report @martmists-gh, this is a regression with Docker v2. We're tracking this in #1133.
