### ISSUE TITLE
sentry-kafka and sentry-data fills up the disk

### ISSUE THREAD

**Issue by duyuyouci** [getsentry/onpremise#1147]
### Version

21.11.0.dev0

### Steps to Reproduce

A few days after the service was turned on, the volume of sentry-kafka and sentry-data filled up the disk，
then i delete the volume of sentry-kafka and rebuild sentry-kafka，
Finally restart the service

### Expected Result

i hope it can work

### Actual Result

Sentry cannot record information at this time

i want to know why sentry cannot record information and why sentry-kafka and sentry-data filled up the disk quickly

**Comment by chadwhitacre** [comment]
How many events are you processing?

**Comment by duyuyouci** [comment]
> How many events are you processing?

About 20k，I suspect it is the problem of Kafka,  the message backlog in the message queue

**Comment by aminvakil** [comment]
It's kafka logs that keep getting bigger and bigger (until 20GB), and somehow default log retention does not work.

Even setting it to `.env` did not work for me.

At last adding this to `docker-compose.yml` fixed the issue, now it's about 1.5GB:
```
      KAFKA_LOG_RETENTION_HOURS: "1"
      KAFKA_LOG_RETENTION_BYTES: "53687091200"
      KAFKA_LOG_SEGMENT_BYTES: "134217728"
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: "300000"
      KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: "60000"
      KAFKA_LOG_CLEANER_ENABLE: "true"
      KAFKA_LOG_CLEANUP_POLICY: "delete"
```

**Comment by duyuyouci** [comment]
> It's kafka logs that keep getting bigger and bigger (until 20GB), and somehow default log retention does not work.
> 
> Even setting it to `.env` did not work for me.
> 
> At last adding this to `docker-compose.yml` fixed the issue, now it's about 1.5GB:
> 
> ```
>       KAFKA_LOG_RETENTION_HOURS: "1"
>       KAFKA_LOG_RETENTION_BYTES: "53687091200"
>       KAFKA_LOG_SEGMENT_BYTES: "134217728"
>       KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: "300000"
>       KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: "60000"
>       KAFKA_LOG_CLEANER_ENABLE: "true"
>       KAFKA_LOG_CLEANUP_POLICY: "delete"
> ```

After modifying these configurations, can restart docker take effect?

**Comment by aminvakil** [comment]
As `docker-compose.yml` has been changed, `docker-compose up -d` would recreate changed services (and the ones which are dependent on kafka).

**Comment by duyuyouci** [comment]
> As `docker-compose.yml` has been changed, `docker-compose up -d` would recreate changed services (and the ones which are dependent on kafka).

thx

**Comment by chadwhitacre** [comment]
> At last adding this to docker-compose.yml fixed the issue, now it's about 1.5GB:

@aminvakil Is this a problem everyone will run into? Should update the docs and maybe even the default config?

**Comment by aminvakil** [comment]
> @aminvakil Is this a problem everyone will run into? Should update the docs and maybe even the default config?

I'm not sure about this, but I think kafka by default does not delete logs, and they keep growing, but I'm not 100% confident about this, but if its cleanup policy is `compact` by default, we can add this line to `docker-compose.yml` for sure.
```
      KAFKA_LOG_CLEANUP_POLICY: "delete"
```

**Comment by chadwhitacre** [comment]
> if its cleanup policy is `compact` by default

[Docs say the default is `delete`](https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#topicconfigs_cleanup.policy), so I guess we're good.
