### ISSUE TITLE
Sentry does not show tunneled issues

### ISSUE THREAD

**Issue by FrigoCoder** [getsentry/onpremise#1148]
### Environment

self-hosted (`onpremise` deployment)

### Version

Sentry 21.10.0.dev 079e143d

### Steps to Reproduce

Components are backend, frontend, on-promise Sentry. Sentry is behind a firewall, frontend can not access it, we want to tunnel it through the backend. All kinds of filtering settings are off, both on the user interface, and on the devops side.

Scenario A)
1. Write a backend endpoint that tunnels envelopes to Sentry, /api/{projectId}/envelope/ 
2. Configure a Sentry React client to use DSN that points to the backend
3. Generate a 404 error by trying to access a frontend page

Scenario B)
1. Write a backend endpoint that tunnels envelopes to Sentry, /tunnel/
2. Configure a Sentry React client to use DSN that points to the Sentry, and tunnel that points to the backend
3. Generate a 404 error by trying to access a frontend page

### Expected Result

Sentry sends 200 OK result. Events and corresponding issues appear on the user interface. Events are correct as if they were coming from the frontend.
 ##
### Actual Result

Sentry sends 200 OK result. Events and corresponding issues DO NOT appear on the user interface.

![image](https://user-images.githubusercontent.com/1145680/141777420-42409e90-a617-429b-bfb6-18e325dd8538.png)
[backend log.txt](https://github.com/getsentry/sentry/files/7538418/backend.log.txt)
[sentry.log](https://github.com/getsentry/sentry/files/7538419/sentry.log)
[SentryApplication.java.txt](https://github.com/getsentry/sentry/files/7538523/SentryApplication.java.txt)
[SentryTunnelServerResource.java.txt](https://github.com/getsentry/sentry/files/7538524/SentryTunnelServerResource.java.txt)

**Comment by chadwhitacre** [comment]
Do your logs relate to scenario A or B or both?

> Write a backend endpoint that tunnels envelopes to Sentry

In your testing, does the backend receive the payload from the frontend?

Do you have the Sentry SDK wired into the backend? Are you using it to send events to Sentry? (This might be answered in your file attachments, sorry I didn't check yet).

Can you get an event into Sentry from the backend "normally" i.e., by triggering an error on the backend (vs. reflecting one from the frontend)?

**Comment by FrigoCoder** [comment]
Hi!

The logs contain both scenarios. The envelope endpoint corresponds to the case where we set the backend as DSN, the tunnel endpoint corresponds to when we keep the original DSN but we set the backend as tunnel. (Sorry, both are prefaced with the line TUNNEL because the same class is responsible for handling them.)

The backend does indeed receive the payload from the frontend. Either endpoint works, although we had to implement an additional store endpoint, because sometimes we got data through that. Furthermore the backend successfully sends events to Sentry, the latter returns 200 OK with a json object with the event id in it.

We do have the Sentry Java and Log4j2 wired into the backend. However we are not using them to tunnel these events, I do not even know whether it is possible to tunnel events let alone envelopes (I would appreciate it if you have information on this topic). We are using Restlet to receive and Apache HttpClient to tunnel the requests.

Sentry Java and Log4j2 clients successfully send events from the backend to Sentry. We experience no issue with them whatsoever. Only these tunneling solutions seem to fail, although I have seen an occasional issue slipping through. I have no idea what might be the underlying issue. I do not think it is rate limit, because backend issues arrive consistently.

Br,
Frigo

**Comment by chadwhitacre** [comment]
> Sentry Java and Log4j2 clients successfully send events from the backend to Sentry. We experience no issue with them whatsoever. Only these tunneling solutions seem to fail, although I have seen an occasional issue slipping through.

Okay, so it sounds like you have solid working and non-working cases and you need to whittle down the differences between them to isolate the problem. Can you capture the requests from the backend to Sentry for the two cases and compare them?

**Comment by FrigoCoder** [comment]
I have used Beeceptor to capture direct requests from Sentry clients.
DSN was https://f5509f102cbe4ce595d73c1264f89260@frigo.free.beeceptor.com/console/frigo/4

Backend is straightforward, here are the files:
[body.txt](https://github.com/getsentry/onpremise/files/7549464/body.txt)
[headers.txt](https://github.com/getsentry/onpremise/files/7549465/headers.txt)
[url.txt](https://github.com/getsentry/onpremise/files/7549466/url.txt)

Frontend is more complicated because it sends two requests.
Request 1:
[body.txt](https://github.com/getsentry/onpremise/files/7549478/body.txt)
[header.txt](https://github.com/getsentry/onpremise/files/7549480/header.txt)
[query.txt](https://github.com/getsentry/onpremise/files/7549481/query.txt)
[url.txt](https://github.com/getsentry/onpremise/files/7549482/url.txt)

Request 2:
[body.txt](https://github.com/getsentry/onpremise/files/7549483/body.txt)
[header.txt](https://github.com/getsentry/onpremise/files/7549484/header.txt)
[query.txt](https://github.com/getsentry/onpremise/files/7549485/query.txt)
[url.txt](https://github.com/getsentry/onpremise/files/7549486/url.txt)

I could not try my tunnel with Beeceptor because it does not work with HTTPS addresses.

Both the backend and the frontend works when they talk to Sentry directly.

When I use Postman to send the backend body.txt to our onpremise Sentry, it works completely normally and an event appears.
When I send the frontend request 1 body.txt then it returns a 200 OK empty json and nothing happens.
When I send the frontend request 2 body.txt then it returns a 200 OK json with the event id and nothing happens.

I guess the frontend communicates something within the first request, that works when it talks directly with Sentry, but we somehow fail to tunnel it properly?

I have noticed that the backend uses x-sentry-auth for sending sentry_key and sentry_version, whereas the frontend uses query parameters for this purpose. Can this interfere with things?

**Comment by chadwhitacre** [comment]
> I guess the frontend communicates something within the first request, that works when it talks directly with Sentry, but we somehow fail to tunnel it properly?
> 
> I have noticed that the backend uses x-sentry-auth for sending sentry_key and sentry_version, whereas the frontend uses query parameters for this purpose. Can this interfere with things?

Sounds like you are hot on the trail! :-)

**Comment by FrigoCoder** [comment]
Thank you, managed to solve it. The key was to 1) use X-Sentry-Auth instead of query parameters, because apparently it is more accepted and 2) tunnel the answer perfectly because if I just copy the headers between Apache HttpClient and Restlet then information is lost, and some clients refuse to work properly.

For people seeking a solution to this issue, here is part of the implementation in Restlet:

[SentryTunnelServerResource_Part.java.txt](https://github.com/getsentry/onpremise/files/7564716/SentryTunnelServerResource_Part.java.txt)
[SentryTunnelServiceImpl_Part.java.txt](https://github.com/getsentry/onpremise/files/7564717/SentryTunnelServiceImpl_Part.java.txt)

**Comment by chadwhitacre** [comment]
Sweet! Great work and thanks for posting back, @FrigoCoder. 👍

We good to close here, then?

**Comment by FrigoCoder** [comment]
Yes, thank you very much for your assistance!
