### ISSUE TITLE
Grant triage role to aminvakil

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/onpremise#1152]
@aminvakil I've noticed you getting [more and more involved](https://github.com/getsentry/onpremise/issues?q=is%3Aissue+commenter%3Aaminvakil+) in the project lately, including helping others with setup issues. May I give you the triage role on GitHub? That would allow you to label and close issues as you help others. 🙏

**Comment by aminvakil** [comment]
@chadwhitacre Thanks for the offer.

Yes, I would be pretty happy to help.

**Comment by chadwhitacre** [comment]
Awesome, invite sent! 💃

**Comment by aminvakil** [comment]
Accepted! Thanks again!

**Comment by chadwhitacre** [comment]
Yessssssssssss. 😁 👍
