### ISSUE TITLE
`./install.sh` script not working on osx Big Sur [FIXED]

### ISSUE THREAD

**Issue by Eliorco** [getsentry/onpremise#1153]
### Version

21.11.0

### Steps to Reproduce

Just run `./install.sh` on a fresh new Mac

### Expected Result

self host Senrty will be installed

### Actual Result

`./install/_lib.sh: line 15: realpath: command not found`

In order to fix this issue, run:
`brew install coreutils`

**Comment by chadwhitacre** [comment]
Yeah this is #941. Glad you found the workaround. :)
