### ISSUE TITLE
The SENTRY_MAIL_HOST env variable change isn't documented in the docs

### ISSUE THREAD

**Issue by thibodelanghe** [getsentry/onpremise#1158]
### Version

21.11.0

### Steps to Reproduce

Upgrade from 21.4.0 to 21.11.0

### Expected Result

Working emails

### Actual Result

Emails not working because of the SENTRY_MAIL_HOST not being set to the FQDN of the server. There is a comment in the .env file stating that it has to be declared. Could be handy if this is also noted in the documentation. 

This env variable has been added in this PR https://github.com/getsentry/onpremise/pull/1076

**Comment by chadwhitacre** [comment]
Reasonable request, thanks @thibodelanghe.

**Comment by thibodelanghe** [comment]
I've made a PR https://github.com/getsentry/develop/pull/465

**Comment by chadwhitacre** [comment]
[Deployed](https://develop.sentry.dev/self-hosted/email/), thanks @thibodelanghe! :)
