### ISSUE TITLE
400 Bad request with right system.url-prefix

### ISSUE THREAD

**Issue by erguotou520** [getsentry/onpremise#121]
`system.url-prefix` is right set to `https://sentry.erguotou.me` in web ui. And I tried a example `electron` program like below: 

```js
const { init } = require('@sentry/electron')
const { app, BrowserWindow } = require('electron')

app.once('ready', () => {
  init({
    dsn: 'https://8e1e68fba75442bdad752135c0f63f32@sentry.erguotou.me/2'
  })
  const win = new BrowserWindow()
  throw new Error('test error')
})
```
But got `400 Bad Request` status and `No JSON data was found` in `x-sentry-error` header in sentry send event.

Electron: 2.0.7
Sentry: @sentry/electron@0.8.1

**Comment by BYK** [comment]
This is probably due to the headers being stripped by something in the middle (like nginx). Are you able to provide more details about the request being made from electron?

**Comment by erguotou520** [comment]
Not used now. And I will show you more info if appeared again.
