### ISSUE TITLE
GitHub plugin

### ISSUE THREAD

**Issue by kkalugerov** [getsentry/onpremise#122]
Hello there, can you explain what exactly should put in `requirements.txt` to get `github` plugin while running the `docker-compose` commands :? Where can check some examples of installing plugins for sentry like this way :?

**Comment by msonowal** [comment]
same here

**Comment by slient2010** [comment]
same here

**Comment by martijnpieters** [comment]
Here's an example of adding a plugin to a dockerized Sentry: https://github.com/getsentry/sentry-auth-google/issues/27#issuecomment-397082005

**Comment by riker09** [comment]
I think what @kkalugerov is looking for is this: https://github.com/getsentry/sentry-auth-github/issues/22#issuecomment-408642428

**Comment by BYK** [comment]
These are now baked into the main Sentry package and Docker images so nothing needs to be put into `requirements.txt` file now for GitHub and most anything.
