### ISSUE TITLE
Migration from 8 to 9 and lost data

### ISSUE THREAD

**Issue by alirezaDavid** [getsentry/onpremise#130]
Hello 
We're just upgrade from sentry 8 to 9 with following the instructions in wiki page, after running migrations sentry is up but it looks like all data is lost. Although when i get the size of the data from postgres folder it's not empty and it seems data is there.
The panel is up and running but i can't login using the old username and password. After sentry migration finished the log shows i should run `sentry createuser`.
Is there any way to get my old data or get back to old version (8)?

**Comment by dcramer** [comment]
The data lives wherever your database exists and sentry doesn’t remove user accounts or anything remotely similar on upgrade paths. You’ll need to sort this out yourself as it’s specific to your own setup.
