### ISSUE TITLE
unable to build onpremise > auth pb on docker.io

### ISSUE THREAD

**Issue by BenoitPoulet** [getsentry/onpremise#138]
Hello,

Since the move to alpine for memcache, we can't build it anymore as docker.io need auth :

$ docker-compose run --rm web config generate-secret-key
Pulling memcached (memcached:1.5-alpine)...
Trying to pull repository docker.io/library/memcached ...
ERROR: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup http on 10.64.1.1:53: no such host

$ curl https://registry-1.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"**authentication required**","detail":null}]}

**Comment by mattrobenolt** [comment]
I think this is something wrong on your end. That IP address isn't docker.io's public IP. The second error is fine since there's nothing to curl at that endpoint.

This image is publicly available and there's no reason you couldn't fetch it aside from somethign on your end.

**Comment by BenoitPoulet** [comment]
Ok, nevermind, i switch back to    `image: memcached:1.4` in docker-compose.yml  the buid is going fine.
