### ISSUE TITLE
Sentry-onpremise can't start web-01

### ISSUE THREAD

**Issue by slaffcheff** [getsentry/onpremise#141]
For some reason sentry can't start its web service. I have postgres, memcached, redis and smtp up and running but when I try to start web-01 it shutdowns immediately. 
The output of docker logs --details return the following:
`sentry.runner.importer.ConfigurationError: Exception: Error: REDIS_PORT_6379_TCP_ADDR (or SENTRY_REDIS_HOST) is undefined, did you forget to `--link` a redis container?`

I did the linking as the documentation says, tried to upgrade, rebuild and so on. No result. Any ideas? Do you need more logs or any other info?

**Comment by slaffcheff** [comment]
Yes: SENTRY_REDIS_HOST: redis. redis is in /etc/hosts as well.

I just did  docker-compose stop/down and up -d again. But no joy.

**Comment by solars** [comment]
I've got the same problem following the instructions in the Readme

**Comment by solars** [comment]
@slaffcheff did you find a solution?

**Comment by slaffcheff** [comment]
@solars - yes, switched to python method and it all worked :) I had further issues with Docker method and just got tired of it.

**Comment by RiFi2k** [comment]
I couldn't get this repo working all the way through, but these instructions worked out great for me.
https://mikedombrowski.com/2018/03/self-hosting-sentry-with-docker-and-docker-compose/

**Comment by BYK** [comment]
Closing as this doesn't seem to be an issue with the repo so closing. Feel free to start a thread in our forum if you'd like to leverage the knowledge of the community: https://forum.sentry.io/c/on-premise

**Comment by BYK** [comment]
I closed the issue as it seems like a specific issue

**Comment by BYK** [comment]
Sorry, I closed the issue accidentally. I was able to run Sentry without issues using the latest master of this repo.

@slaffcheff would you like to give it another try as the Python method may not be the best supported option from now on an if there's anything wrong with this one, we'd love to fix it.

**Comment by RiFi2k** [comment]
@BYK I was about to do a sentry install on GCP and noticed this so I'll give this another go using docker and let you know.

**Comment by BYK** [comment]
@RiFi2k since you haven't come back yet, I'm assuming things are alright and closing the issue. Feel free to let us know otherwise and I'll reopen and continue here :)
