### ISSUE TITLE
Environment filter missing on 9.0.0

### ISSUE THREAD

**Issue by AuditeMarlow** [getsentry/onpremise#143]
I've just created a new Sentry project and hooked it up to my Laravel project. I can send test events using `php artisan sentry:test` and it does store the `environment` tag in Sentry. However, when I change my Laravel project's environment to something else, like `testing`, I was expecting Sentry to show the advertised [environment filter](https://docs.sentry.io/enriching-error-data/environments/?platform=javascript) after sending a new test event. Is this not included in the On Premise version?

**Comment by dcramer** [comment]
@AuditeMarlow its in master on github but we haven't tagged a release for a while. If you build from source oyu'll get everything current.
