### ISSUE TITLE
Sentry-OnPremise cannot invited a new user to my orginization

### ISSUE THREAD

**Issue by mnilg** [getsentry/onpremise#144]
When I invited a new user to my orginization，and i can see the user in my orginization.But he cannot visit my orginization and prompt must create new orginization after login.
What's going on here?Do I need the other configurations about sentry?

**Comment by BYK** [comment]
Hi @mnilg - we need a lot more information than this to be able to help you. Can you provide more information like your log outputs, some information regarding your networking and organization setup and any custom configuration you may have?

**Comment by mnilg** [comment]
> Hi @mnilg - we need a lot more information than this to be able to help you. Can you provide more information like your log outputs, some information regarding your networking and organization setup and any custom configuration you may have?

Thank you，I can invite new user to my orginization after I rebuild with onPremise,and i will close the issue.
