### ISSUE TITLE
Version in "./docker-compose.yml" is invalid. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version ("2.0", "2.1", "3.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1

### ISSUE THREAD

**Issue by jinjiaxing** [getsentry/onpremise#145]
Version in "./docker-compose.yml" is invalid. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version ("2.0", "2.1", "3.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1

my docker-compose vsrsion is 1.17

what do i fix it?

**Comment by mattrobenolt** [comment]
I'm guessing you need a newer version of docker-compose, or rewrite the compose file to be compatible for you. It's just intended to be an example, not a final product.

**Comment by 1-pro** [comment]
version: ’2.0’

services: 
  mdb: 
    image: mongo
    ports:
      - ”27017:27017”
    environment:
      MONGO_INITDB_ROOT_USERNAME: ”1234”
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: “mdb”
    networks: 
      -  lexclassnet
    volumes: 
      - /home/kikilove/cantsay:data/db
    depends_on:
      - mydb

  rdb:
    image:
      redis
    ports:
      - “6379:6379”
    networks:
      - lexclassnet
    depends_on:
      - mydb


  mydb:
    image:
      mysql:5.7
    ports:
      - “3306:3306”
    environment:
      MYSQL_ROOT_PASSWORD: “secret”
    networks:
      - lexclassnet


  api:
    build: .
    restart: 
      always
    ports:
      - “3000:3000”
    networks:
      - lexclassnet
    depends_on:
      - mbd
      - rdb
      - mydb


networks:
  lexclassnet:
    driver: bridge

 tried all you said, changed the version but still having same error
ERROR: Version "’2.0’" in "./docker-compose.yml" is invalid.
