### ISSUE TITLE
postgres & memcached keep restarting

### ISSUE THREAD

**Issue by huangjj27** [getsentry/onpremise#149]
Postgres' log, same as https://github.com/sameersbn/docker-postgresql/issues/22#issuecomment-78288058:
```
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
LOG:  could not link file "pg_xlog/xlogtemp.37" to "pg_xlog/000000010000000000000001": Permission denied
FATAL:  could not open file "pg_xlog/000000010000000000000001": No such file or directory
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
creating template1 database in /var/lib/postgresql/data/base/1 ...
```

memcached's log, reference to [here](http://bestandroidtoroot.com/content/memcached-can-t-run-as-root-without-the-switch):
```
can't run as root without the -u switch
```

**Comment by mattrobenolt** [comment]
I’m not sure what the issues are, but they’re unrelated to Sentry and something specific to what you’re doing. I’ve never had these issues for example.

**Comment by huangjj27** [comment]
Sorry I reply late. I finally found out that it’s lack of memory that caused this.
