### ISSUE TITLE
How to recompile static files

### ISSUE THREAD

**Issue by summercn** [getsentry/onpremise#153]
Hi, i'm self hosting an sentry server on my work computer with onpremise.
With the step of README,  the sentry page is available at 127.0.0.1:9000.

Then, i want to enable the filter: filter by error message.
So i used this command to modifiy some files, like projectHeader.jsx.
```shell
docker exec -ti **CONTAINERID** bin/bash
cd /usr/local/lib/python2.7/site-packages/sentry/static/sentry/app/components/projectHeader
vim projectSelector.jsx
```

However NOTHING changed
**so  i wanna know what i can do to make it work**. No doc explained this. 

Another related link is [Command Line Usage](https://docs.sentry.io/server/cli/), i tried:
```shell
root@436929c4191b:/etc/sentry#  sentry devserver
07:17:12 [INFO] sentry.plugins.github: apps-not-configured
07:17:12 system  | webpack started (pid=165)
07:17:12 webpack | /bin/sh: 1: /usr/local/lib/python2.7/site-packages/sentry/node_modules/.bin/webpack: not found
07:17:12 system  | webpack stopped (rc=127)
07:17:12 system  | server started (pid=166)
07:17:12 system  | sending SIGTERM to server (pid 166)
07:17:12 system  | server stopped (rc=-15)
```

I had searched the **webpack.config.js** in the container, 0 result.

**Comment by mattrobenolt** [comment]
If you want to do this, this is the wrong repository, and you would need to build your own image from source based on a fork of Sentry.
