### ISSUE TITLE
SSO enabled Sentry prompting for password for sudo rather than redirect to IDP

### ISSUE THREAD

**Issue by TheMacStack** [getsentry/onpremise#157]
I have an OnPrem sentry instance configured for SAML2 SSO using AzureAD, at times I am prompted to enter my password when navigating admin functionality rather than redirected to IDP login. This seems like odd behavior to me, is Sentry somehow tracking or aware of account credentials even though all authentication should be provided through Azure AD?

Is there anyway to disable this behavior and force all auth/re-auth on time out directly to IDP rather than prompting for and accepting credentials?

**Comment by dcramer** [comment]
you can enable a u2f key and it will not use the password on the account but otherwise no, there’s no way to disable it utilizing it if it exists. If you don’t have a password or u2f key the protection gets disabled.
