### ISSUE TITLE
Can I from 8.14.1  update to 9?

### ISSUE THREAD

**Issue by BingerCoder** [getsentry/onpremise#158]
Now I used 8.14.1  , the lastest version is 9,Can I update from 8.14.1  to 9?
If I can do it ,should I do migrate to update table?what is the command?

**Comment by BingerCoder** [comment]
And

docker-compose run --rm web upgrade

is valid for 8.14.1 to 9?

**Comment by BingerCoder** [comment]
No people answer me ~

I had updated, from 8 to 9, back up date and `docker-compose run --rm web upgrade` , then start docker~

**Comment by dcramer** [comment]
There is an upgrade guide in our documentation. In the future you should reference that.
