### ISSUE TITLE
I want to link the Sentry web link to nginx

### ISSUE THREAD

**Issue by dayhi** [getsentry/onpremise#161]
I use
```
sudo docker run --name nginx -v /data/nginx:/etc/nginx/conf.d --link=onpremise_web_1:sentry -p 80:80 -p 443:443 -d nginx
```
Report an error
```
docker: Error response from daemon: Cannot link to /onpremise_web_1, as it does not belong to the default network.
```
How do I modify the file in order for the onpremise_web_1 container to use the default network. please help me

**Comment by mattrobenolt** [comment]
You’re asking the wrong question. You should run the nginx container within the same network as the sentry containers instead of moving sentry into the default network. Iirc the network we create here is called “sentry”.
