### ISSUE TITLE
Failed to save configuration in "Welcome to Sentry"

### ISSUE THREAD

**Issue by I-Guitar** [getsentry/onpremise#168]
![](http://ww1.sinaimg.cn/large/006V3Yvrgy1g25mxnvc5dj30yi0pzqht.jpg)
When I log in to the sentry, saving the Root Url and Admian Email always fails. Please help me.
build with docker on Centos7

**Comment by ashen9** [comment]
I meet same problem！！！

**Comment by I-Guitar** [comment]
> I meet same problem！！！

Have you solved the problem yet?

**Comment by ashen9** [comment]
> > I meet same problem！！！
> 
> Have you solved the problem yet?

Not yet

**Comment by dcramer** [comment]
https://github.com/getsentry/onpremise/pull/167

**Comment by ashen9** [comment]
> #167
So I need to switch branches  ‘improve config’?

**Comment by I-Guitar** [comment]
> > #167
> > So I need to switch branches  ‘improve config’?
> > when I use improve-config, excute `docker-compose run --rm web upgrade`,
> > **Wrong report** ：
> > `!! Configuration error: `system.secret-key` MUST be set. Use 'sentry config generate-secret-key' to get one.`

me too

**Comment by I-Guitar** [comment]
i solved the issue. see [#12722](https://github.com/getsentry/sentry/issues/12722)

**Comment by ashen9** [comment]
> i solved the issue. see [#12722](https://github.com/getsentry/sentry/issues/12722)

、I still don't know what to do，can you give me some help？

**Comment by I-Guitar** [comment]
> > i solved the issue. see [#12722](https://github.com/getsentry/sentry/issues/12722)
> 
> 、I still don't know what to do，can you give me some help？

* Edit config.yml to add the following conf
```bash
auth.allow-registration: false
beacon.anonymous: true
system.admin-email: "your email"
system.url-prefix: "root url"
```
* Declare the sentry version
```bash
docker exec onpremise_web_1 sentry config set sentry:version-configured '9.1.0'
```
* restart service
