### ISSUE TITLE
upload Vue source map files to sentry do not work

### ISSUE THREAD

**Issue by 15751165579** [getsentry/onpremise#171]
- [x] Review the documentation: https://docs.sentry.io/
- [x] Search for existing issues: https://github.com/getsentry/onpremise/issues
- [x] Use the latest release: https://github.com/getsentry/onpremise/releases

## Package + Version

- [x] `@sentry/browser`
- [ ] `@sentry/node`
- [ ] `raven-js`
- [ ] `raven-node` _(raven for node)_
- [ ] other:

### Version:

```
5.1.0
```

## Description

&emsp;&emsp;project was created by Vue CLI 3, "main.js" file:

```JavaScript
import Vue from 'vue'
import * as Sentry from '@sentry/browser'
import * as Integrations from '@sentry/integrations'
const dsn = 'http://4104209251f24d058f454cb97f4564fc@10.1.1.248:9000/4'
Sentry.init({
  dsn,
  release: '1.0.0',
  integrations: [
    new Integrations.Vue({
      Vue,
      attachProps: true
    })
  ]
})
```

&emsp;&emsp;"vue.config.js" file:

```JavaScript
    new SentryCliPlugin({
        release: '1.0.0',
        include: './dist',
        ignore: ['node_modules', 'vue.config.js'],
        filenameTransform: filename => '~/' + filename
     })
```

![image](https://user-images.githubusercontent.com/17818249/56411244-ba407d00-62b2-11e9-8f78-077bffdeac31.png)

![image](https://user-images.githubusercontent.com/17818249/56411297-e3f9a400-62b2-11e9-933b-011595bd6fa3.png)

**Comment by dcramer** [comment]
This is not an appropriate repo for this ticket. This repository is specifically for the Sentry onpremise helpers.
