### ISSUE TITLE
Unable to save your changes. Please ensure all fields are valid and try again.

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [getsentry/onpremise#172]
Sentry was successfully installed to enable login authorization, but after logging in, the configuration needs to be filled in.
`Unable to save your changes. Please ensure all fields are valid and try again.`
The Root URL is the same as my access address`http://**.**.**.**:9000`,
Admin Email is Admin Email is tencent enterprise Email

**Comment by dcramer** [comment]
This should be resolved in 9.1.1.
