### ISSUE TITLE
Docker with sentry 9.1.1

### ISSUE THREAD

**Issue by cesguerra** [getsentry/onpremise#175]
I am trying to install Sentry 9.1.1 (that fix an important bug) but there is not an updated Docker image in https://hub.docker.com/_/sentry

I dont know if this is the right place to make this request.
Thank you for the help

**Comment by dcramer** [comment]
https://github.com/docker-library/official-images/pull/5772

**Comment by cesguerra** [comment]
but how to install 9.1.1 with onpremise? 
it still installing 9.1.0

**Comment by cesguerra** [comment]
onpremise Dockerfile:
`FROM sentry:9.1-onbuild`
