### ISSUE TITLE
Failure to run on OSX (permission denied)

### ISSUE THREAD

**Issue by buckett** [getsentry/onpremise#18]
When attempting to generate the secret I get an error:
```
$ docker-compose run --rm web config generate-secret-key
Starting onpremise_postgres_1
chown: changing ownership of ‘/var/lib/sentry/files’: Operation not permitted
```

I would guess this is because of the way the data volumes are mounted from the Mac and don't allow the permission change.

**Comment by mattrobenolt** [comment]
As explained here: https://github.com/getsentry/onpremise/pull/19

Please adjust this file to suit your needs. It's not meant to 100% just work as-is without changes on your end for implementation details.
