### ISSUE TITLE
GITHUB_APP_ID not recognized

### ISSUE THREAD

**Issue by jwillmer** [getsentry/onpremise#180]
After upgrade to the latest version the `GITHUB_APP_ID` does not get recognized correctly in the `.env` file.

```
...
raise TypeError('%r: got %r, expected %r' % (key, _type(value), opt.type))
TypeError: 'github-app.id': got <type 'str'>, expected integer
```

This is related to https://github.com/getsentry/onpremise/issues/177 some environment settings are not working anymore.

**Comment by kumy** [comment]
I also got this issue after upgrade, from what I understood, we now have to use GitHub Apps https://github.com/getsentry/sentry-plugins#github but can't figure what to put in the Webhook field while creating the app on GH.

**Comment by jwillmer** [comment]
> I also got this issue after upgrade, from what I understood, we now have to use GitHub Apps https://github.com/getsentry/sentry-plugins#github but can't figure what to put in the Webhook field while creating the app on GH.

The supplied link references exactly the two variables I'm using.

**Comment by jwillmer** [comment]
After [default config fix](https://github.com/getsentry/onpremise/commit/3eb2caf4cb2c7fa4e213039baa96b176e690509f) I get:

.env-file
```
# GitHub
SENTRY_GITHUB_APP_ID=caf1234567890
GITHUB_API_SECRET=123456789ab123456789
```

docker-compose up -d
```
!! Configuration error: InvalidTypeError: 'caf1234567890' is not a valid integer
```

**Comment by jwillmer** [comment]
I switched back to `GITHUB_APP_ID` and now it works.
