### ISSUE TITLE
Unable to access page of sentry

### ISSUE THREAD

**Issue by wupeng1351** [getsentry/onpremise#182]
After the installation is complete,Unable to access page with ip:9000

ERR_CONNECTION_RESET

**Comment by nelsonroliveira** [comment]
Building from 3745dc4fe109e61c6c912a9c15889587e4bcfb39 works even when referencing
`FROM sentry:9.1.1-onbuild`

**Comment by wupeng1351** [comment]
@nelsonroliveira 
Still did not solve the problem

**Comment by wupeng1351** [comment]
Still did not solve the problem




------------------ 原始邮件 ------------------
发件人: "Nelson Oliveira"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 凌晨4:46
收件人: "getsentry/onpremise"<onpremise@noreply.github.com>;
抄送: "金豆豆"<726451064@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [getsentry/onpremise] Unable to access page of sentry (#182)




Building from 3745dc4 works even when referencing
 FROM sentry:9.1.1-onbuild

**Comment by wupeng1351** [comment]
Once again, it's settled.

**Comment by wupeng1351** [comment]
@nelsonroliveira 
The problem has been solved.Thanks
