### ISSUE TITLE
Sentry did not generate DSN

### ISSUE THREAD

**Issue by wupeng1351** [getsentry/onpremise#184]
After I created a new project, sentry did not generate a DSN.It's empty.
![image](https://user-images.githubusercontent.com/48155600/57291736-970b2f80-70f2-11e9-808e-86afd598be5d.png)
![image](https://user-images.githubusercontent.com/48155600/57291798-bd30cf80-70f2-11e9-9b46-ab23b4951325.png)

**Comment by qq790880208** [comment]
same problem,

**Comment by kilkujadek** [comment]
Same here!

**Comment by lwh2015** [comment]
同样，构建完成后，没有显示DSN

**Comment by lwh2015** [comment]
> After I created a new project, sentry did not generate a DSN.It's empty.
> ![image](https://user-images.githubusercontent.com/48155600/57291736-970b2f80-70f2-11e9-808e-86afd598be5d.png)
> ![image](https://user-images.githubusercontent.com/48155600/57291798-bd30cf80-70f2-11e9-9b46-ab23b4951325.png)

Is the request solved?

**Comment by lwh2015** [comment]
在登陆后将默认的localhost：9000改为127.0.0.1:9000，即可

**Comment by wupeng1351** [comment]
是直接用127.0.0.1:9000登陆吗


------------------ 原始邮件 ------------------
发件人: "HWJY"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 下午5:20
收件人: "getsentry/onpremise"<onpremise@noreply.github.com>;
抄送: "金豆豆"<726451064@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [getsentry/onpremise] Sentry did not generate DSN (#184)




在登陆后将默认的localhost：9000改为127.0.0.1:9000，即可

**Comment by wupeng1351** [comment]
> 在登陆后将默认的本地主机：9000改为127.0.0.1:9000，即可

The problem has been solved. Thank you.

**Comment by wupeng1351** [comment]
> 在登陆后将默认的本地主机：9000改为127.0.0.1:9000，即可

The problem was solved in this way.Thank you.

**Comment by qq790880208** [comment]
应该是防火墙或者网络限制之类的原因，就算DSN没有显示，也可以自己合成dsn信息的，组成为http://公钥@ip:port/projectid。

**Comment by wupeng1351** [comment]
> 应该是防火墙或者网络限制之类的原因，就算DSN没有显示，也可以自己合成DSN信息的，组成为[HTTP：//公钥@ip：端口/专案编号。](http://%E5%85%AC%E9%92%A5@ip:port/projectid%E3%80%82)

Ok,The above method can also solve the problem

**Comment by issaTan** [comment]
I have the same issue, It's there any idea how can I fix it?

**Comment by issaTan** [comment]
I fixed this when I set the following code at `config.yml` 
```shell
###################
# System Settings #
###################

# If this file ever becomes compromised, it's important to regenerate your a new key
# Changing this value will result in all current sessions being invalidated.
# A new key can be generated with `$ sentry config generate-secret-key`
# system.secret-key: 'changeme'
system.url-prefix: 'http://my-sentry-host:9000'
```
Than 
```shell
docker-compose build # Build the services again after updating
docker-compose up -d # Recreate the services
```
Hope can help you.
