### ISSUE TITLE
Setting up ssl with nginx

### ISSUE THREAD

**Issue by josh-degraw** [getsentry/onpremise#186]
If there is already good documentation on how to do this, please ignore and just direct me to that.

I have been trying to set up my sentry instance to work with ssl, and all it says in the readme is that options are available, but I don't have much experience with nginx (the rest of our stack is on windows/IIS) and the documentation is very lacking IMO.

I have looked at https://docs.sentry.io/server/nginx/, but it seems to assume nginx has already been set up, I'm having trouble figuring out how to set this up on top of the docker image we're using here.

Is there anywhere that could clearly show how to add ssl to sentry on top of this project?

**Comment by mattrobenolt** [comment]
It's intentionally kinda vague because I don't want to impose security assumptions on you or your company, and you should have some idea of how to handle this from a generic load balancer perspective. It's very common to just use an AWS ELB or similar too, so it's much harder to assume how you'd need to run this. We provide the configuration options needed for Sentry to accept this behavior in a generic way, but you need to provide what works for you here.

**Comment by mattrobenolt** [comment]
It's also worth suggesting, if you're most comfortable with IIS, feel free to use that, there's nothing that'd require using nginx. That's just what we use for ourselves.

**Comment by dyh333** [comment]
do you mean that deploy sentry with ssl should need a proxy like nginx? @mattrobenolt . I am confused on it. thanks

**Comment by mattrobenolt** [comment]
Yes.

**Comment by dyh333** [comment]
hi, @mattrobenolt . I had add nginx with ssl(https: xx:xx:xx:xx:443) to proxy to sentry(http://localhost: 9000). and it seems work. but the project client key dns address still starts with http, like below picture show: 
![image](https://user-images.githubusercontent.com/1221313/65733929-488f1980-e103-11e9-97d3-b10291591ad3.png)
how to change it to https, thanks a lot.

**Comment by mattrobenolt** [comment]
You'd need to configure `system.url-prefix` to also include https.

**Comment by dyh333** [comment]
thanks, like that is ok? @mattrobenolt 
![image](https://user-images.githubusercontent.com/1221313/65737910-99f2d500-e112-11e9-82f2-7a0af2e32f51.png)

**Comment by mattrobenolt** [comment]
If that’s how you’d connect to it from a browser, sure. The :443 shouldn’t be needed since that’s implied with https. But yes.
