### ISSUE TITLE
Deployment completed but can not login

### ISSUE THREAD

**Issue by zjx161027** [getsentry/onpremise#187]
There was no prompt for mailbox and password during deployment, so， unable to obtain information for login。

**Comment by Ricaz** [comment]
Same for me. No prompts during `upgrade`.
After starting the stack with `docker-compose up -d`, the first HTTP request causes the service's logs to throw up:
```
web_1        | 172.29.160.21 - - [21/May/2019:11:39:16 +0000] "GET / HTTP/1.1" 302 466 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
web_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
web_1        |     return self.dispatch(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
web_1        |     return view_func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
web_1        |     return self.handle(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
web_1        |     response = view_func(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
web_1        |     return func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
web_1        |     return super(AuthLoginView, self).handle(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
web_1        |     return super(BaseView, self).dispatch(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
web_1        |     return handler(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
web_1        |     org = Organization.get_default()
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
web_1        |     )[0]
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
web_1        |     return list(qs)[0]
web_1        | IndexError: list index out of range
web_1        | 11:39:16 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
postgres_1   | ERROR:  column sentry_projectkey.data does not exist at character 339
postgres_1   | STATEMENT:  SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added", "sentry_projectkey"."rate_limit_count", "sentry_projectkey"."rate_limit_window", "sentry_projectkey"."data" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = 1  AND "sentry_projectkey"."roles" =  "sentry_projectkey"."roles" | 1) LIMIT 1
```

**Comment by Ricaz** [comment]
**Update:** Oops! I completely neglected the 3GB RAM requirement. I bumped my VM from 2GB RAM to 8GB RAM and I actually got the prompt at the end of `sentry upgrade` - however I had input <CR> a few times so it exited out immediately:
```
Running migrations for sentry:
 - Migrating forwards to 0472_auto__add_field_sentryapp_author.
 > sentry:0001_initial
 > sentry:0002_auto__del_field_groupedmessage_url__chg_field_groupedmessage_view__chg
 > sentry:0003_auto__add_field_message_group__del_field_groupedmessage_server_name
 > sentry:0004_auto__add_filtervalue__add_unique_filtervalue_key_value
...
 > sentry:0469_fix_state
 > sentry:0470_org_saved_search
 > sentry:0471_global_saved_search_types
 > sentry:0472_auto__add_field_sentryapp_author
Created internal Sentry project (slug=internal, id=1)

Would you like to create a user account now? [Y/n]: Email: Email: Y
Error: Enter a valid email address.                                                                                                                                                                                                                                                   sentry %
```
This left Sentry in a broken state. Running `sentry upgrade` after this does not fix it, I had to wipe the postgres volume and remake it.

**Comment by pythonlei** [comment]
I think you can see#191, it will fix your bug

**Comment by BYK** [comment]
@Ricaz, @zjx161027 - do you think we can close this now?

**Comment by biaji** [comment]
Same here, No prompts during upgrade. 

And if I exec createuser in the container,  I got the same error stack @Ricaz have .

I have a 8G rhel7 machine, so maybe it's not releated to the ram?

**Comment by BYK** [comment]
@biaji - It certainly indicates an interrupted migration flow which almost always happens due to the docker instance being killed in the middle, which almost always happens due to OOM killer if you don't see a stack trace.

If you are not running this directly on Linux, that means Docker actually runs in a VM, which is the limiting factor for Docker containers, not the host machine and you should ensure that VM has at least 3 GB of memory allocated. (they are usually set to 2 GB by default)

**Comment by biaji** [comment]
@BYK  Thanks for your quick response. 

I'm a newbie to docker.  When I use "docker stats" , it showed the limit of mem is 8G.  And I run this directly on linux.  

But After I drop all table in postgresql and run "sentry upgrade" directly from container. It goes on without errors.  If I'm not wrong, I run the command by root user.

**Comment by BYK** [comment]
@biaji the container may have died due to another reason during a previous upgrade and then may have ended up in a broken state.

I'm planning to make a few modifications to the commands to add some memory flags to make sure containers are not killed due to oom-killer.

**Comment by karlanke** [comment]
I had a similar issue, where the psql user didn't have permissions to create extensions, so the migrations crashed. It asked to make a user, but I figured I should wait until the whole process finished, so I ctrl-c'd out. After I fixed the permission issue, the migrations finished but the user prompt didn't come up. I managed to use `createuser`, but it also hadn't created the initial project so it crashed out until I put it in multi organization mode. It would be good to have an option to re-run the first-run stuff, or to document that if it goes wrong you have to drop the db and start over.

**Comment by BYK** [comment]
>It would be good to have an option to re-run the first-run stuff, or to document that if it goes wrong you have to drop the db and start over.

Good suggestion, thanks! I'll add some docs regarding this as it is not easy or safe to try rerunning migrations unless you know precisely what you are doing (see https://stackoverflow.com/a/35018583/90297).

**Comment by BYK** [comment]
Gonna close this as now the `./install.sh` script checks for the amount of RAM available to Docker containers. If anyone thinks this solution is not enough, feel free to comment here and we can work together to get something better.
