### ISSUE TITLE
docker-compose of version 1.6.0+ can't  do the job

### ISSUE THREAD

**Issue by biaji** [getsentry/onpremise#191]
In the document it said: 

**Requirements**
Compose 1.6.0+ (optional)

but it can't finish the install process as described in README. 

Maybe the README need an update?

**Comment by BYK** [comment]
I'm using `docker-compose version 1.23.2, build 1110ad01` which works for me. Can you please provide more details?

**Comment by biaji** [comment]
Sure,  I'm using CentOS 7. The docker version is  1.12.6.  So, I have to install docker-compose version 1.12.6 according to the docker engine.

And it complain:

`$ docker-compose build
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version ("2.0", "2.1", "3.0", "3.1", "3.2") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/`

So I remove version key from docker-compose.yml, and still:

`$ docker-compose build
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for x-defaults: 'depends_on'
Unsupported config option for volumes: 'sentry-data'
Unsupported config option for services: 'web'
`

**Comment by BYK** [comment]
@biaji thanks a lot for all the useful information you've provided! You are right, we need to state that the minimum version requirement to be `docker-compose@1.17.0` which is the one introduced support for v3.4 of compose file format and allows these `x-` extension fields.

Update coming.
