### ISSUE TITLE
docker-compose ?

### ISSUE THREAD

**Issue by JeanFred** [getsentry/onpremise#2]
Hello,

I see there is a `docker-compose.yml`. Using docker-compose to run Sentry sounds great ; however it is not mentioned at all in the documentation at https://docs.getsentry.com/on-premise/server/installation/docker/.

Is docker-compose support just experimental, or would you recommend it for new installs?

Thanks!

**Comment by Freundschaft** [comment]
docker-compose up worked for me but before that you need to run
docker-compose run --rm web upgrade in order to create db and user

**Comment by hernandev** [comment]
running it on docker cloud would also be great, running without Dockerfile

**Comment by mattrobenolt** [comment]
It's kinda experimental. I don't fully advocate it since I don't personally know it well enough and last I heard, docker-compose was not intended to be used for production, just small dev environments.

Can it be used now to coordinate large multi machine deployments?

**Comment by hernandev** [comment]
docker cloud, formerly tutum is using it's own sintax but it's 99% compatible with docker-compose, rancher uses docker-compose along with a additional file, so looks like the standard now, anyway, rancher provides a catalog entry for sentry, so it's just one click install, and i'm not using docker-cloud anymore, altough i did got it working on docker-cloud, just adjusting a few things and always keeping the data volumes so when containers are rebuilt data is not lost

**Comment by maguowei** [comment]
add docker-compose usage #5

**Comment by fredvd** [comment]
The sentry 'on premise' documentation is quite confusing at the moment. Running everything under python is deprecated according to the official docs, but the docker documentation is only listing manual steps to individually start and link containers. 

with 'on premise' I understand running something to use it, so some degree of production setup.  the quickest way to production is using the docker-compose.yml, but if it's still experimental it should be clearly marked as such. Also see #9

**Comment by InAnimaTe** [comment]
I'm actually making some changes to the README for this repo and will submit a PR in the next day or two. I'm going to make it clear that this is a somewhat experimental and explain the manual steps needed before a `docker-compose up` will work as expected. We've been running this for a the past few months so it isn't exactly `not production` ready, it just needs a little more explanation (and love ;)

As for the on-prem docs @fredvd is talking about (these), is there any way I can contribute to those @mattrobenolt ?

**Comment by mattrobenolt** [comment]
@InAnimaTe Of course: https://github.com/getsentry/sentry/tree/master/docs/installation/docker :)

**Comment by InAnimaTe** [comment]
Beautiful. I'll have a PR for that too ;)

**Comment by JeanFred** [comment]
I’m closing this: the initial question has been answered, and since then the various docs have been updated too.

As for me I have been running Sentry on-premise using docker-compose for a couple of months and am perfectly happy with it :)

Thanks everyone!
