### ISSUE TITLE
Malformed Config Error

### ISSUE THREAD

**Issue by barrettg** [getsentry/onpremise#20]
I've completed the build steps, generated my key, added it to the docker-composer.yml file and when I 
excute the `docker-compose run --rm web upgrade` command I get the following error:

`File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 96, in bootstrap_options
    raise ConfigurationError('Malformed config.yml file: %s' % six.text_type(e))
sentry.runner.importer.ConfigurationError: Malformed config.yml file: while parsing a block mapping
  in "/etc/sentry/config.yml", line 36, column 1
did not find expected key
  in "/etc/sentry/config.yml", line 55, column 2
`

I've tried leaving the config.yml file included in the repo stock or uncommented and I get the same error each time.

**Comment by mattrobenolt** [comment]
The file that is shipped with this is actually entirely empty, so you definitely are including local modifications and introducing invalid YAML. You might wanna try dumping it here: https://yaml-online-parser.appspot.com/ to see what's wrong.

**Comment by barrettg** [comment]
Thanks for the quick response.  Just out of curiosity, if I leave it empty (all comments), should it work?  I'm getting the error regardless of changing the shipped config file or not.

**Comment by mattrobenolt** [comment]
It should, yeah. Can you do like:

```
$ docker-compose run --rm web cat /etc/sentry/config.yml
```

**Comment by barrettg** [comment]
That helped me debug it.  Seems that docker wasn't including the changes I was making to the config file when I would rebuild the image.  I cleared all the cache, rebuilt, it picked up the changes correct and runs now.  Thanks again.
