### ISSUE TITLE
On-Premise returns 500 after upgrade

### ISSUE THREAD

**Issue by straschek-io** [getsentry/onpremise#200]
### How are you running Sentry?
* [X] On-Premise docker [[259bc29e78b](https://github.com/getsentry/onpremise/commit/259bc29e78b7bdb3173da004458a378e5e3fa8b4)]

## Description
Update was run like specified in https://github.com/getsentry/onpremise#updating-sentry

## Steps to Reproduce
```
docker-compose build --pullto date on patch version
docker-compose run --rm web upgrade
docker-compose up -d
```

Stacktrace when running `docker-compose up`  
```
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
web_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
web_1        |     return self.dispatch(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
web_1        |     return view_func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
web_1        |     return self.handle(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
web_1        |     response = view_func(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
web_1        |     return func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
web_1        |     return super(AuthLoginView, self).handle(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
web_1        |     return super(BaseView, self).dispatch(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
web_1        |     return handler(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
web_1        |     org = Organization.get_default()
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
web_1        |     )[0]
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
web_1        |     return list(qs)[0]
web_1        | IndexError: list index out of range
web_1        | 11:24:27 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
```

**Comment by BYK** [comment]
Can you try running `docker-compose run --rm web upgrade` again and share its output here?

**Comment by iluuu1994** [comment]
I've just installed Sentry on a Kubernetes cluster with the official Helm chart and I get the same issue. It was a fresh install. Can I provide any information that could be helpful to you?

**Comment by BYK** [comment]
@iluuu1994 thanks a lot for the offer that said we do not maintain or support any Helm charts ourselves so https://github.com/helm/charts/tree/master/stable/sentry would be a better place to raise any issues.

**Comment by iluuu1994** [comment]
@BYK But this doesn't seem to be Helm specific, correct? As @straschek-io runs Sentry using `docker-compose` and still got the same error.

**Comment by BYK** [comment]
@iluuu1994 not necessarily. @straschek-io did not respond and I suspect a corrupted initial migration for that case.

Yours seems different and since you are using Helm, it may be due to a difference there from what we support here. Since the 500 error is pretty generic we'd need more details to investigate your issue. That said, the issue happens from the get go, I'd either say it is something related to your configuration or the Helm chart.

**Comment by BYK** [comment]
@straschek-io closing due to lack of response. If you are still having this issue, simply respond here and I'd be happy to reopen the issue and investigate with more details.

**Comment by iluuu1994** [comment]
Thanks @BYK

I've opened an issue here: https://github.com/helm/charts/issues/15296
Let's see if I get a response.
