### ISSUE TITLE
Can't connect to sentry docker container inside different container

### ISSUE THREAD

**Issue by tomreitsma** [getsentry/onpremise#205]
I have a setup as follows:

I have multiple docker-compose files, all connected in the same network. I run the Sentry service and it works perfectly, until I try to connect to it through a different container.

Ping is working just fine, but whenever I try to do a request (as simple as curl sentry_web:9000) I'm getting a **"\<h1\>Bad Request (400)\<\/h1\>"** response.

Full response here:

```bash
bash-4.4# curl -vv sentry_web:9000
* Expire in 0 ms for 6 (transfer 0x55afd0f757a0)
* Expire in 1 ms for 1 (transfer 0x55afd0f757a0)
<snipped for brevity, this is repeated a bunch of times>
* Expire in 0 ms for 1 (transfer 0x55afd0f757a0)
* Expire in 0 ms for 1 (transfer 0x55afd0f757a0)
*   Trying 172.18.0.11...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55afd0f757a0)
* Connected to sentry_web (172.18.0.11) port 9000 (#0)
> GET / HTTP/1.1
> Host: sentry_web:9000
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 400 BAD REQUEST
< Content-Length: 26
< X-XSS-Protection: 1; mode=block
< Content-Language: en-us
< X-Content-Type-Options: nosniff
< Vary: Accept-Language
< X-Frame-Options: deny
< Content-Type: text/html
<
* Connection #0 to host sentry_web left intact
<h1>Bad Request (400)</h1>bash-4.4#
```

The request in the web_1 container only logs as

```web_1        | 172.18.0.3 - - [26/Jun/2019:14:38:40 +0000] "GET / HTTP/1.1" 400 236 "-" "curl/7.64.0"```

I'm assuming somewhere along the way between containers, headers are stripped. Though there is no way that I know of to verify this.

Is there a way to set sentry in debug mode? Do I need to configure something else to make inter-container connectivity possible?

**Comment by BYK** [comment]
Hi @tomreitsma,

This issue doesn't seem to be connected with the repo itself and quite specific to your setup so would you mind creating a new topic at the forums as the community there would be in a better position to help you: https://forum.sentry.io/c/on-premise

We also monitor the forums and try to provide answers to questions we can help with :)
