### ISSUE TITLE
SMTP AUTH extension not supported by server.

### ISSUE THREAD

**Issue by well-monkey** [getsentry/onpremise#206]

**Comment by well-monkey** [comment]
来源地址
root@localhost
主机
smtp:25
用户名
codewellliu@gmail.com
密码
********
使用 TLS?
否
Mailing List Namespace
localhost
测试设置
向您的电子邮件地址发送一封邮件以确认配置正常。

SMTP AUTH extension not supported by server.

**Comment by BYK** [comment]
Hi @well-monkey. Can you provide some more details? Also I'd prefer if you can use English as I don't know Chinese and I don't know how accurate Google Translate can be :)

**Comment by well-monkey** [comment]
i solve the problem by modify port

**Comment by Junran777** [comment]
@well-monkey  which file need modify?

**Comment by Junran777** [comment]
I have the same problem
