### ISSUE TITLE
Retention policy for old/handled events

### ISSUE THREAD

**Issue by almogyehuda** [getsentry/onpremise#208]
Hi,
I'm trying to setup the sentry/onpremise for the first time.

I think I can find it problematic that there's no any retention policy that we can manage through the dashboard / environment variables.

For a scaled, big solutions - or event small solutions with detailed logs, that's going to be a real storage problem.

Am I missing something?

Thanks.

**Comment by BYK** [comment]
Hi @almogyehuda thanks a lot for raising this and you surely are not missing anything. Right now we don't have a built-in retention policy and I agree that we should add one. For sentry.io we are using a cron job that runs `sentry cleanup --days 90` every day AFAIK and I'm thinking about bringing in a similar think to on-premise.

If you have the time, we can work together to get this in faster, if not we'll eventually have it :)

**Comment by almogyehuda** [comment]
> Hi @almogyehuda thanks a lot for raising this and you surely are not missing anything. Right now we don't have a built-in retention policy and I agree that we should add one. For sentry.io we are using a cron job that runs `sentry cleanup --days 90` every day AFAIK and I'm thinking about bringing in a similar think to on-premise.
> 
> If you have the time, we can work together to get this in faster, if not we'll eventually have it :)

Of course, Let's talk on dm

**Comment by BYK** [comment]
@almogyehuda prefer the open discussion here. Do you have a preferred way to run the `cleanup` command periodically in your setup?

**Comment by BYK** [comment]
Closing as this is addressed in #220 now.
