### ISSUE TITLE
SMTP Mail Config not working for tianon/exim4 Container only fro sentry frontend

### ISSUE THREAD

**Issue by SDJeff** [getsentry/onpremise#21]
Hi,

wie configured at the config.yaml our Mailgun Account. At the sentry Frontend the Testmail is ready and sent by this account. But all other mails which are send by the worker queues like invitations or exception notification are sent by our docker host ip and not by the configured smtp config. Anybody know this?

Here the /data/sentry/config.yaml

```
###############
# Mail Server #
###############

 mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
 mail.host: 'smtp.mailgun.org'
 mail.port: 587
 mail.username: 'postmaster@ourdomain.de'
 mail.password: 'secretkey'
 mail.use-tls: true
# The email address to send on behalf of
 mail.from: 'logging@ourdomain.de'
 mail.list-namespace: 'ourdomain.de'

# If you'd like to configure email replies, enable this.
# mail.enable-replies: false

# When email-replies are enabled, this value is used in the Reply-To header
# mail.reply-hostname: ''

# If you're using mailgun for inbound mail, set your API key and configure a
# route to forward to /api/hooks/mailgun/inbound/
# mail.mailgun-api-key: ''
```

All values are ready and checkable at the graphical user interface.

**Comment by dcramer** [comment]
Please see our support options for general questions. Our issue tracker is reserved for actual Sentry issues.

https://sentry.io/support/
