### ISSUE TITLE
Please provide a source image with `from` prior to commit

### ISSUE THREAD

**Issue by Leowuqunqun** [getsentry/onpremise#213]
I pulled the project from the document but failed to execute the script ./install.sh  
ERROR: Service 'web' failed to build: Please provide a source image with `from` prior to commit

**Comment by Leowuqunqun** [comment]
i fix it. 
Dockerfile lacks a reference to the.env.

**Comment by BYK** [comment]
>Dockerfile lacks a reference to the.env.

Can you be a bit more specific? I tested the install script both on my machine and on Travis CI so I'm surprised that this was an issue.

If you can provide a full log of your own commands and their outputs, that may help us solve this for other folks.
