### ISSUE TITLE
-e needed for color codes

### ISSUE THREAD

**Issue by jamincollins** [getsentry/onpremise#214]
https://github.com/getsentry/onpremise/blob/9177155c7906498754057aa76c144c6bfb8ac4ba/Makefile#L8
https://github.com/getsentry/onpremise/blob/9177155c7906498754057aa76c144c6bfb8ac4ba/Makefile#L12
https://github.com/getsentry/onpremise/blob/9177155c7906498754057aa76c144c6bfb8ac4ba/Makefile#L16

`echo` lines need a `-e` to interpret the color code escape sequences:

```
-e     enable interpretation of backslash escapes
```

**Comment by BYK** [comment]
Sounds good, mind creating a PR?
