### ISSUE TITLE
make build error: invalid reference format

### ISSUE THREAD

**Issue by bells** [getsentry/onpremise#216]
-e ==> Building sentry-onpremise:latest
Sending build context to Docker daemon  32.26kB
Step 1/2 : ARG IMAGE
Step 2/2 : FROM ${IMAGE}-onbuild
invalid reference format
make: *** [build] Error 1

**Comment by BYK** [comment]
Can you please provide more details around which version of Docker are you using, whether you are using our install script etc?

**Comment by aliasbody** [comment]
I have exactly the same issue:

> Building sentry-onpremise:latest
> Sending build context to Docker daemon  32.26kB
> Step 1/2 : ARG IMAGE
> Step 2/2 : FROM ${IMAGE}-onbuild
> invalid reference format
> Makefile:8: recipe for target 'build' failed
> make: *** [build] Error 1

With:

- Ubuntu 18.04.2 LTS
- Docker version 18.09.7, build 2d0083d

And following this https://docs.sentry.io/server/installation/docker/

**Comment by BYK** [comment]
@aliasbody sorry for the issue, try again now please! :)

Also, I highly recommend using the `./install.sh` script in the repo which is a new addition (that's why the docs are not updated for it yet)

**Comment by aliasbody** [comment]
@BYK Perfect, everything seems to be working fine, thank you!

**Comment by rangercyh** [comment]
I use the lastest master version, still have the problem
![image](https://user-images.githubusercontent.com/1217541/61758720-78b2f700-adf8-11e9-8d19-84bfb09fa5c4.png)

**Comment by BYK** [comment]
@rangercyh - sorry for the trouble. It should be fully resolved after #223 now.
