### ISSUE TITLE
ERROR: Service 'web' failed to build: invalid reference format

### ISSUE THREAD

**Issue by qiyaozu** [getsentry/onpremise#222]
qiyaozudeMBP:onpremise qiyaozu$ docker-compose run --rm web config generate-secret-key
WARNING: The IMAGE variable is not set. Defaulting to a blank string.
Starting onpremise_memcached_1 ... done
Starting onpremise_redis_1     ... done
Starting onpremise_smtp_1      ... done
Starting onpremise_postgres_1  ... done
Building web
Step 1/2 : ARG IMAGE
Step 2/2 : FROM ${IMAGE}-onbuild
ERROR: Service 'web' failed to build: invalid reference format

**Comment by rangercyh** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/1217541/61758737-8c5e5d80-adf8-11e9-92ba-61ddc601c961.png)

**Comment by liamaharon** [comment]
@qiyaozu do you mind posting how you fixed this?

**Comment by BYK** [comment]
Fixed in #265.
