### ISSUE TITLE
How to set nickname for email

### ISSUE THREAD

**Issue by WizardPro** [getsentry/onpremise#225]
I have tried this in .env:
```php
SENTRY_EMAIL_USER=Sentry<example@example.com>
SENTRY_SERVER_EMAIL=Sentry<example@example.com>
```
but it look's like wrong, when i click the send test email button, i got this:
> 535, 'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256'

So what is the way to set a nickname or it just can't do this?

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
