### ISSUE TITLE
secret key contains special character

### ISSUE THREAD

**Issue by VikramTiwari** [getsentry/onpremise#23]
The secret key generated by the command `docker-compose run --rm web config generate-secret-key` contains special character `$` which needs to be escaped while using with docker [Ref](https://github.com/docker/compose/issues/2507).

The error thrown is:

`ERROR: Invalid interpolation format for "environment" option in service "base": "l=xyhk%r%9$)8ute)6jk#u=fkek!@*1&2jw0w!(qfnq&@s^94i"`

Should remove `$` from the secret key generator's list of characters.

**Comment by mattrobenolt** [comment]
This sounds more like a bug with Docker or docker-compose than Sentry. We're not going to change Sentry code to accommodate this. If it's a problem, you can easily just substitute or do whatever escaping you need on your side.
