### ISSUE TITLE
On-Premise sentry redirects client to vm internal IP

### ISSUE THREAD

**Issue by andreiStoicescu** [getsentry/onpremise#233]
I installed sentry from docker with docker-compose on a vm on my server and i'm trying to expose the application to the internet. 
i am doing the proxy from express.js which is running on another vm.
app.use( vhost('sentry.example.com', proxy('http://192.168.111.150')));
where http://192.168.111.150 is my vm ip
When i try to access sentry.example.com in browser i get redirected to http://192.168.111.150.

Does anyone have any idea how to fix this?

**Comment by BYK** [comment]
Hi there! You need to set your `system.url-prefix` setting to your publicly available URL as described in https://docs.sentry.io/server/config/#general. This information is also asked you during the initial install setup wizard page. Please use [our forums](http://forum.sentry.io/) for questions like these in the future as the issue board is only for the Sentry on-premise code-related issues.
