### ISSUE TITLE
Need sentry an specific network interface?

### ISSUE THREAD

**Issue by raizoor** [getsentry/onpremise#234]
Hi team,

I have installed Sentry on my computer by default, with script .install . Now i verify a new network interface: br-123a5e35681f . 
It's normal? if it's, why need sentry this?

Thanks !!

**Comment by BYK** [comment]
Hi there! Yes this is normal as docker-compose automatically creates a new network for the groupet services. Please use [our forums](http://forum.sentry.io/) for questions like these in the future as the issue board is only for the Sentry on-premise code-related issues.
