### ISSUE TITLE
How to remove GitHub Enterprise integration?

### ISSUE THREAD

**Issue by chatoo2412** [getsentry/onpremise#235]
I installed GitHub Enterprise integration to an on-premise Sentry instance.
It worked well.
And then, I deleted the app from GitHub Enterprise before uninstalling it.
Now, I can’t remove the integration from Sentry because it requires uninstallation even the app is deleted.

![image](https://user-images.githubusercontent.com/3435149/62591772-af663280-b90b-11e9-92d2-346e27b2b069.png)

Is there any way to remove or disable GitHub Enterprise integration from on-premise Sentry manually?
Thanks.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the Sentry on-premise code-related issues.
