### ISSUE TITLE
On-Prem mount issue Openshift 3.11 Enterprise

### ISSUE THREAD

**Issue by Lukiido** [getsentry/onpremise#236]
Getting the below after installing sentry on off prem postgres, and spinning up a deployment of web/worker/cron. Getting this in web only:

chown: changing ownership of '/var/lib/sentry/files': Operation not permitted

Have validated that the proper policy is set in openshift, and files can be made on the share.

**Comment by BYK** [comment]
I don't know anything about OpenShift but I can easily tell that where you hold your docker containers or volumes does not have enough permissions for sentry container to take ownership of this directory mounted as a volume. I'll be closing this issue as it is configuration specific and the best place to seek answers to these are [our forums](http://forum.sentry.io/).
