### ISSUE TITLE
"chown -R sentry /var/lib/sentry/files" from entrypoint.sh takes a long time

### ISSUE THREAD

**Issue by stumbaumr** [getsentry/onpremise#239]
Hi,

if there are some more files in /var/lib/sentry/files it really takes a long time to start up.

Maybe better to only change the permissions if necessary instead of just writing hard to the filesystem:

```
# Set permissions if necessary
find /var/lib/sentry/files ! -user sentry -exec chown -R sentry {} \;
```

**Comment by BYK** [comment]
Sounds like a good suggestion, what do you think @mattrobenolt? Also, would you be willing to submit a PR for this @stumbaumr?

**Comment by mattrobenolt** [comment]
Alternative is to just drop the `-R` and only make sure the top level directory is sufficient. Lemme see what other images do.

**Comment by mattrobenolt** [comment]
Ok, so kinda my source of truth for this stuff is Postgres. Postgres manages a ton of files in its data directory and it does exactly this as well. https://github.com/docker-library/postgres/blob/master/12/docker-entrypoint.sh#L34

**Comment by mattrobenolt** [comment]
MySQL as well. https://github.com/docker-library/mysql/blob/master/8.0/docker-entrypoint.sh#L90

So I’d be curious why this is more problematic for us than a database who most likely has more files than we do.

**Comment by stumbaumr** [comment]
Use case: We operate data filesystems on NFS mounts on a SSD based appliance. Throughput/Availabilty/Snapshotting is great, but latency is in some cases a problem.

And chowning on a filesystem with many files like this takes time - and since the owner is already sentry it is not necessary. And we are talking currently about 15 Minutes....

**Comment by BYK** [comment]
Eh, mounting a volume from an NFS mount is not a great idea I guess. I mean if your suggestion makes this better, I'm not opposed to it as long as @mattrobenolt is also okay.

**Comment by mattrobenolt** [comment]
Ok, so checking through the docker community, it does seem like they are trending towards making this change, it can be seen in here for Postgres rolled up with other changes: https://github.com/docker-library/postgres/pull/496

They're changing to using `find "$PGDATA" \! -user postgres -exec chown postgres '{}'` which yeah, is exactly what you're proposing.

So I'm ok with this.

I do think NFS is not good, but I don't think it wouldn't work. It's probably fine for most use cases.

**Comment by BYK** [comment]
@stumbaumr so, open to PR's over at https://github.com/getsentry/docker-sentry :)

**Comment by stumbaumr** [comment]
Please do not tell NetApp that operating Systems on NFS is a bad idea. I think a major portion of their business model relies on that...

**Comment by BYK** [comment]
@stumbaumr sorry, didn't want to invalidate or judge anything. NFS itself tends to be slower on some I/O operations, that's why we kind of frowned upon it. Great if it works for you :)

**Comment by BYK** [comment]
Already fixed in https://github.com/getsentry/docker-sentry/pull/200

**Comment by BYK** [comment]
Thanks @stumbaumr!

**Comment by azhurbilo** [comment]
I have 26712 under NFS storage

```
find /mnt/nfs/sentry/data/ -type f | wc -l
26712
```

and it's still take ~3 min to start sentry container :(

**Comment by BYK** [comment]
@azhurbilo sorry to hear that. Which tag are you on for the docker image?

**Comment by azhurbilo** [comment]
9.1.2 image

but I override entrypoint to this one https://github.com/getsentry/docker-sentry/blob/master/9.1/docker-entrypoint.sh

**Comment by BYK** [comment]
@azhurbilo and how do you do that override?

**Comment by azhurbilo** [comment]
```
FROM sentry:9.1.2
...
COPY docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
```

**Comment by azhurbilo** [comment]
just for workaround start using **-maxdepth 1**

> find "$SENTRY_FILESTORE_DIR" -maxdepth 1 ! -user sentry -exec chown sentry {} \;

hope, it doesn't broke smth :)

**Comment by BYK** [comment]
Pretty sure this directory should only have direct descendants so not sure why adding `-maxdepth 1` would speed up anything. @mattrobenolt - any theories?

**Comment by stumbaumr** [comment]
So, for me the startup currently takes about 4 Minutes and I am fine with that.
```
root@sentry01(dc1.prd):~# find /var/lib/docker/volumes/sentry-data/ -type f | wc -l
1091597
root@sentry01(dc1.prd):~#
```
This is a SSD-only NetApp attached with 10GBit.
