### ISSUE TITLE
how to setup multiple environments for an Docker installation of Sentry ?

### ISSUE THREAD

**Issue by hvsop** [getsentry/onpremise#242]

**Comment by hvsop** [comment]
I am very new to sentry, can anyone please advise how to setup "production, staging, dev" environments while run sentry in docker ?  Thanks in advance.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the Sentry on-premise code-related issues.
