### ISSUE TITLE
SENTRY_EMAIL_HOST is not working and can't send email

### ISSUE THREAD

**Issue by zerda** [getsentry/onpremise#244]
# Description
`SENTRY_EMAIL_HOST` is always `smtp`, even specified in `.env`. 

Same as [sentry#10765](https://github.com/getsentry/sentry/issues/10765), but should be fixed in this repo.

# Steps to reproduce
1. Clone this repo to local.
1. Set `SENTRY_EMAIL_HOST=example.com` in `.env` file.
1. Run `./install.sh` and `docker-compose up -d` to start sentry 9.1.2.
1. Run `docker-compose exec web printenv | grep EMAIL`

# Expected
`SENTRY_EMAIL_HOST` should be `example.com`

# Actual
`SENTRY_EMAIL_HOST` is `smtp`, and sending email is not working in Sentry.

In http://localhost:9000/manage/status/mail/, Host value is `smtp:25`.

# Debugging
In [`docker-compose.yml`](https://github.com/getsentry/onpremise/blob/master/docker-compose.yml#L27), `SENTRY_EMAIL_HOST` is always setting with `smtp`. 
In [`sentry.conf.py`](https://github.com/getsentry/onpremise/blob/master/sentry.conf.py#L285), this environment variable is mapping to `mail.host` setting in Sentry.

I'm wondering what is the purpose of `SENTRY_EMAIL_HOST` in `docker-compose.yml`.

**Comment by BYK** [comment]
The purpose is to use the bundled SMTP server, Exim here: https://github.com/getsentry/onpremise/blob/2018fb50d083fbbbd0faafb78d40fe0bca6a2cb7/docker-compose.yml#L31-L33

If you don't want/need that feel free to remove those parts and you should be good to go.

**Comment by BYK** [comment]
I closed the issue but I guess we can remove the hard-coding in `docker-compose.yml` and allow the override from config or env. Is that what you propose? The downside of that is, it would allow scenarios where we spin up an `smtp` service that is not being used so forcing people to modify the `docker-compose` file sounds better to me.

You can do this by simply creating a `docker-compose.overrides.yml` and overriding certain parts btw. Not sure how easy it is to _remove_ sections from the file via an override tho.

**Comment by zerda** [comment]
Unfortunately removing section in `docker-compose.override.yml` is not supported right now. See https://github.com/docker/compose/issues/3729

From real world perspective, most on-premises deployment would use a third-party email provider, because it's cheap and more consistent.

I prefer to remove this bundled SMTP server from `docker-compose.yml`. It should be easier for users to override.

**Comment by BYK** [comment]
>From real world perspective, most on-premises deployment would use a third-party email provider, because it's cheap and more consistent.

Depends on the type of user. Our aim is to provide fully-contained example setup for people to try it out. Anything more serious would already need some more changes and customization.

>I prefer to remove this bundled SMTP server from docker-compose.yml. It should be easier for users to override.

You are free to do so in your local copy and deploy that way. Would that not work for you?

**Comment by zerda** [comment]
This is exactly what I'm doing right now, and I'm totally agree with you about fully-contained example.

Also it would be great helpful to have a doc, which describe how to use 3rd mail provider to send email.

**Comment by BYK** [comment]
@zerda there are these docs: https://docs.sentry.io/server/config/#mail

Are they not helpful?
