### ISSUE TITLE
install.sh invalid number

### ISSUE THREAD

**Issue by tholu** [getsentry/onpremise#246]
```
➜  sentry git:(master) ✗ ./install.sh
Checking minimum requirements...
./install.sh: line 30: printf: 19.03.1: invalid number
./install.sh: line 30: printf: 17.05.0: invalid number
./install.sh: line 30: printf: 1.24.1: invalid number
./install.sh: line 30: printf: 1.17.0: invalid number
```

Fixed it with replacing line 30 `function ver () { echo "$@" | awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'; }`.

Before I create a Pull Request - did anyone else run into this problem?

**Comment by dmitryrn** [comment]
Have this problem too, on macos. I don't really know how it works

**Comment by rjhilgefort** [comment]
I'm hitting this too on a fresh clone today. @tholu That definitely squelches the error, but it's not clear to me what that line is trying to do. Also, it's line `28` now for current Googlers.

**Comment by tholu** [comment]
The line is trying to make versions comparable, I'll create a pull request now.
