### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by GutterBeats** [getsentry/onpremise#249]
Hello,

When trying to install the Slack Integration on the On Premise Sentry server, all it does is open a pop-up window with the text "OAuth Error: Please specify `client_id`". We are running Sentry 9.1.2 via Docker behind an Nginx proxy on a Debian Linux server. Here is a screenshot...

<img width="600" alt="Screen Shot 2019-09-06 at 8 44 41 AM" src="https://user-images.githubusercontent.com/23031998/64441377-a095ab80-d082-11e9-98ab-28832cc9c11c.png">

**Comment by stanl33y** [comment]
+1 
I tried to use environment variables (SENTRY_SLACK_CLIENT_ID,
SENTRY_SLACK_CLIENT_SECRET, SENTRY_SLACK_VERIFICATION_TOKEN)
but I was unsuccessful with slack integration

**Comment by BYK** [comment]
Have you followed this guide: https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463

**Comment by BYK** [comment]
Closing due to lack of response.
