### ISSUE TITLE
Not able to install ldap plugin through requirements.txt

### ISSUE THREAD

**Issue by gumtreeautesting** [getsentry/onpremise#253]
When I add `sentry-ldap-auth` to requirements.txt and run `install.sh`, It fails with `fatal error: lber.h: No such file or directory` during web build process. 
Reason is the os dependencies of `python-ldap`: `python-dev libldap2-dev libsasl2-dev libssl-dev`.
Having `python-dev libldap2-dev libsasl2-dev libssl-dev` in docker image should resolve this.

**Comment by mpibpc-mroose** [comment]
I came up with the same issue and solved it by this Dockerfile:

```
FROM sentry:9-onbuild

RUN mkdir -p /tmp/ && mkdir -p /var/lib/sentry/data
RUN apt-get update && apt-get install -y libsasl2-dev python-dev libldap2-dev libssl-dev
RUN pip install sentry-ldap-auth

COPY sentry.conf.py /etc/sentry/
```

**Comment by gumtreeautesting** [comment]
Thanks. Sure. Still I think it would be good to have those dependencies in official sentry docker image.

**Comment by omidraha** [comment]
Hi,
I would like to add new [sentry-telegram](https://github.com/getsentry/sentry-plugins) plugin.
I follow these Instructions:
```
$ vim requirements.txt
   # Add plugins here
   sentry-telegram
$ docker-compose stop
$ docker-compose run --rm web upgrade
$ docker-compose up -d
```
But on the `Configure plugin` page, there is no plugin for sentry-telegram.
Can you please tell me, how to install this plugin correctly?
Thanks.

**Comment by BYK** [comment]
Maybe you'd be interested in porting https://github.com/getsentry/docker-sentry/pull/131 to here in #220?

**Comment by BYK** [comment]
Closing due to lack of response. Will reopen if needed.
