### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by itmuckel** [getsentry/onpremise#254]
Hello and thank you for this awesome software!

I wanted to note that the redis and postgres containers are pretty outdated.
redis is 3.2 in the docker-compose file, but the current stable release is 5.
postgres is 9.5 in the docker-compose file, but the current stable release is 11.

I'm currently kubernetizing sentry, so it can run in our cluster. Is it safe to bump those numbers? :thinking:

**Comment by mattrobenolt** [comment]
Redis is fine to bump to 5.x, but I wouldn’t bump Postgres beyond 9.6.x. We don’t officially support it, and with Sentry 10, it’s very likely we’ll require an image of Postgres that we produce.
