### ISSUE TITLE
TypeError when sending email from sentry

### ISSUE THREAD

**Issue by sandrotanner** [getsentry/onpremise#255]
When sending a mail (e.g. inviting users or using the 'test mail' functionality in the settings) I recieve a TypeError.

## Expected Behavior
The mail is sent.

## Current Behavior
The mail is not sent, the TypeError appears under issues for the internal project (see stack trace below).

## Possible Solution
To me the issue appears to be that the hmac function is called with a unicode password. According to https://bugs.python.org/issue5285 this was only possible before python 2.6 ([sentry 9.1.2 seems to use python 2.7.16](https://github.com/getsentry/docker-sentry/blob/master/9.1/Dockerfile)). But it could also be something else... 

## Steps to Reproduce
1. Download the latest version of sentry from this repo.
2. Extend the `docker-compose.yml` with the lines:

```
    SENTRY_EMAIL_HOST: mail.example.com
    SENTRY_EMAIL_PORT: 587
    SENTRY_EMAIL_HOST_USER: foo@example.com
    SENTRY_EMAIL_HOST_PASSWORD: password
```

3. `./install.sh`
4. Log into the freshly installed sentry and navigate to the SMTP settings: `/manage/status/mail/`
5. Click 'send a test mail to bar@example.com'

### Stack Trace
```
TypeError: character mapping must return integer, None or unicode
  File "sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "sentry/tasks/email.py", line 76, in send_email
    send_messages([message])
  File "sentry/utils/email.py", line 436, in send_messages
    sent = connection.send_messages(messages)
  File "django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "django/core/mail/backends/smtp.py", line 54, in open
    self.connection.login(self.username, self.password)
  File "smtplib.py", line 608, in login
    (code, resp) = self.docmd(encode_cram_md5(resp, user, password))
  File "smtplib.py", line 572, in encode_cram_md5
    response = user + " " + hmac.HMAC(password, challenge).hexdigest()
  File "hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
```
### Versions
Python 2.7.16 (default, Sep 12 2019, 17:44:15) [GCC 6.3.0 20170516]
sentry 9.1.2
sentry-sdk 0.11.2
six 1.10.0

## Detailed Description
The sentry settings are all defined in the `docker-compose.yml`
Use-TLS: no
Every email before actually being sent produces 'TypeError: character mapping must return integer, None or unicode'

**Comment by sandrotanner** [comment]
I was unsure where to put this issue, hope this is okay here.

**Comment by BYK** [comment]
Looks like your password has weird characters in it and you have not used utf-8 to encode them when putting them into the `docker-compose.yml` file?

**Comment by BYK** [comment]
Closing due to lack of response. Will reopen if needed.
