### ISSUE TITLE
Sentry cannot send Test Email which show Error "[Errno -2] Name or service not known"

### ISSUE THREAD

**Issue by niceMatthew** [getsentry/onpremise#256]
my config is here
`
 mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
 mail.host: 'smtp.yeah.net'
 mail.port: 25
 mail.username: 'xxxx@yeah.net'
 mail.password: 'password'
 mail.use-tls: true
# The email address to send on behalf of
 mail.from: 'xxx@yeah.net'
`

**Comment by mattrobenolt** [comment]
This just means that whatever you have for mail.host isn’t able to be resolved by DNS.
