### ISSUE TITLE
No internet from inside container. Makes impossible to use webhooks

### ISSUE THREAD

**Issue by idchlife** [getsentry/onpremise#257]
After installing with ./install.sh script and starting server, was not able to configure webhooks. Check logs of web service and discovered numerous errors about "connection timeout" etc.

exec bashed inside web container, tried to do apt-get update and got connection timeout errors.

Inside /etc/resolv.conf 127.0.0.11 but on host system /etc/resolv.conf contains other lines.

Did not have docker prior to sentry installation.
System information below:

![image](https://user-images.githubusercontent.com/4563032/65782901-58384d80-e157-11e9-87f9-b5e80502a676.png)

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
