### ISSUE TITLE
Running sentry onpremise in docker swarm using docker stack deploy

### ISSUE THREAD

**Issue by stumbaumr** [getsentry/onpremise#264]
Hi,

I am trying to distribute sentry over more than one server using docker swarm.

So I created three docker swarm workers and tried to docker stack deploy sentry onto them.

```
root@docker-dev1-003(dc1.dev):~/getsentry/onpremise (git:master)# docker stack deploy --compose-file docker-compose.yml sentry-dev
Ignoring unsupported options: build, restart

Creating network sentry-dev_default
Creating service sentry-dev_redis
Creating service sentry-dev_postgres
Creating service sentry-dev_web
failed to create service sentry-dev_web: Error response from daemon: rpc error: code = InvalidArgument desc = ContainerSpec: image reference must be provided
root@docker-dev1-003(dc1.dev):~/getsentry/onpremise (git:master)#
```

So since the built web container is not available in a docker registry the stack deploy fails.

**Comment by BYK** [comment]
I guess you need to manually build it and push to a private registry that you have access to? I've added an image name to this as I need it to build the cron images over at the v10 branch. That may also help?

**Comment by BYK** [comment]
Closing due to lack of response.
