### ISSUE TITLE
Error when running ./install.sh on a new installation on master branch

### ISSUE THREAD

**Issue by majksner** [getsentry/onpremise#269]
Hi,

When running new installation from the master branch there is an error. See below.

```
ERROR: Service 'sentry-cleanup' failed to build: pull access denied for sentry-onpremise-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by BYK** [comment]
Can you try running `docker-compose build --force-rm web` manually and trying again? This already happens in the script but it may have failed for some reason.

**Comment by majksner** [comment]
That fixed the issue. Thanks!
