### ISSUE TITLE
error: API request failed   caused by: sentry reported an error: unknown error (http status: 413)

### ISSUE THREAD

**Issue by seadog0331** [getsentry/onpremise#272]
I ran upload-sourcemaps with 'yarn realease'  formerly. This usually works, but for my newest release, I am seeing:
`error: API request failed   
caused by: sentry reported an error: unknown error (http status: 413)
`
I'm sure 16.8M is not very big and I have added

`client_max_body_size 40M; 
`
to our nginx.conf file and reload!

**Comment by BYK** [comment]
Hi, can you provide more details as this is not enough to even make guesses. Which version of Sentry are you using and what is your installation method? How does your setup look like etc.

**Comment by seadog0331** [comment]
version：Sentry 9.1.2
installation method： docker-compose
When I just upload file.js ,it works;but with file.js.map,it fails.

Here is the debug log
`
...$ yarn release
yarn run v1.17.3
$ yarn && yarn run flow && yarn run lint
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
$ flow check
Found 0 errors
$ eslint src/**/*.{js,vue}
$ node build/scripts.js release
clean-webpack-plugin: /Users/dingchaorong/code/abc-fe-classroom/packages/classroom/dist has been removed.
(node:5339) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
> Analyzing 16 sources
> Rewriting sources
> Adding source map references
> Uploading source maps for release 3e168302435c98ac8bd500451773e7c845e37e24
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.`

**Comment by BYK** [comment]
Can you share the logs from the `web` service? `docker-compose logs web` should do it.

**Comment by seadog0331** [comment]
`web_1        | 192.168.31.71 - - [15/Nov/2019:07:20:51 +0000] "POST /api/4/store/?sentry_version=7&sentry_client=raven-js%2F3.25.2&sentry_key=b032fa94efd24801b0ae555cf688fca7 HTTP/1.1" 200 650 "https://class.dadaabc.com/" "Mozilla/5.0 (iPad; CPU OS 12_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 /sa-sdk-ios DaDaEnglish/iOS/12.4.1/pad_iPad_mini_4/Safari/605.1.15/2.12.2"
web_1        | 192.168.31.71 - - [15/Nov/2019:07:20:58 +0000] "POST /api/0/projects/sentry/classroom-frontend/releases/ HTTP/1.1" 201 666 "-" "sentry-cli/1.49.0"
web_1        | 192.168.31.71 - - [15/Nov/2019:07:20:59 +0000] "POST /api/0/projects/sentry/classroom-frontend/releases/ HTTP/1.1" 208 675 "-" "sentry-cli/1.49.0"
web_1        | 192.168.31.71 - - [15/Nov/2019:07:20:59 +0000] "GET /api/0/organizations/sentry/chunk-upload/ HTTP/1.1" 200 496 "-" "sentry-cli/1.49.0"
web_1        | 192.168.31.71 - - [15/Nov/2019:07:20:59 +0000] "GET /api/0/projects/sentry/classroom-frontend/releases/3e168302435c98ac8bd500451773e7c845e37e24/files/?cursor= HTTP/1.1" 200 645 "-" "sentry-cli/1.49.0"
web_1        | 192.168.31.71 - - [15/Nov/2019:07:20:59 +0000] "POST /api/0/projects/sentry/classroom-frontend/releases/3e168302435c98ac8bd500451773e7c845e37e24/files/ HTTP/1.1" 201 496 "-" "sentry-cli/1.49.0"
web_1        | 192.168.31.71 - - [15/Nov/2019:07:20:59 +0000] "POST /api/0/projects/sentry/classroom-frontend/releases/3e168302435c98ac8bd500451773e7c845e37e24/files/ HTTP/1.1" 201 534 "-" "sentry-cli/1.49.0"
web_1        | 192.168.31.71 - - [15/Nov/2019:07:20:59 +0000] "POST /api/0/projects/sentry/classroom-frontend/releases/3e168302435c98ac8bd500451773e7c845e37e24/files/ HTTP/1.1" 201 538 "-" "sentry-cli/1.49.0"
web_1        | 192.168.31.71 - - [15/Nov/2019:07:21:01 +0000] "PUT /api/0/projects/sentry/classroom-frontend/releases/3e168302435c98ac8bd500451773e7c845e37e24/ HTTP/1.1" 200 690 "-" "sentry-cli/1.49.0"
web_1        | 172.16.1.18 - - [15/Nov/2019:07:21:34 +0000] "POST /api/4/store/?sentry_version=7&sentry_client=raven-js%2F3.25.2&sentry_key=b032fa94efd24801b0ae555cf688fca7 HTTP/1.0" 200 650 "https://class.dadaabc.com/" "Mozilla/5.0 (iPad; CPU OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 /sa-sdk-ios DaDaEnglish/iOS/13.1.3/pad_iPad_Pro_3(12.9-inch)/Safari/605.1.15/2.12.1"
web_1        | 192.168.31.71 - - [15/Nov/2019:07:22:11 +0000] "POST /api/4/store/?sentry_version=7&sentry_client=raven-js%2F3.25.2&sentry_key=b032fa94efd24801b0ae555cf688fca7 HTTP/1.1" 200 658 "https://staging-class.dadaabc.com/" "Mozilla/5.0 (iPad; CPU OS 11_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15F79 /sa-sdk-ios DaDaEnglish/iOS/11.4.0/pad_iPad_6/Safari/605.1.15/2.12.2"`

**Comment by BYK** [comment]
These logs don't seem to include the error you mention (just search them for `413`) so either they are not complete or the error is coming from your nginx instance which I cannot help with.
