### ISSUE TITLE
Service 'symbolicator-cleanup' failed to build

### ISSUE THREAD

**Issue by lengthmin** [getsentry/onpremise#274]
```
Successfully built 8ebea088fe1c
Successfully tagged snuba-cleanup-onpremise-local:latest
Building symbolicator-cleanup
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
ERROR: Service 'symbolicator-cleanup' failed to build: Get https://us.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Cleaning up...
```

I'm using the Aliyun Server in China...
It's hard to connect to this url: https://us.gcr.io/v2/

any idea I can skip this step? or another workaround?
Thanks!

**Comment by lengthmin** [comment]
seems it is google's container registry, how can i replace it by myself?

**Comment by lengthmin** [comment]
azure provide CN user a proxy:
gcr.azk8s.cn

but I can't pull the image:
![image](https://user-images.githubusercontent.com/13938334/68933722-3f9bf980-07d0-11ea-99b8-72d916dacb52.png)

the proxy is actually worked.
![image](https://user-images.githubusercontent.com/13938334/68933755-54788d00-07d0-11ea-8d36-0f609bb9cbea.png)
![image](https://user-images.githubusercontent.com/13938334/68933935-a3bebd80-07d0-11ea-8ab3-f99dc183dd95.png)

**Comment by lengthmin** [comment]
another mirror registry also can't work 
gcr.mirrors.ustc.edu.cn

**Comment by lpisces** [comment]
> another mirror registry also can't work
> gcr.mirrors.ustc.edu.cn

换成这个可以过去https://hub.docker.com/r/getsentry/symbolserver
不知道效果如何 可以试试

**Comment by lpisces** [comment]
> another mirror registry also can't work
> gcr.mirrors.ustc.edu.cn

换成getsentry/symbolserver这个貌似可以过去 不知道能不能兼容

**Comment by sparkKenzo** [comment]
replace it with ty4z2008/symbolicator:latest

**Comment by lengthmin** [comment]
> replace it with ty4z2008/symbolicator:latest

is works, thank you!
