### ISSUE TITLE
Sentry web ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by fl4p** [getsentry/onpremise#276]
Hi,

I have sentry running for a couple of months.
Suddenly, I can't access the web dashboard anymore, it closes the HTTPS connection unexpectedly.
(Chrome error `ERR_CONNECTION_CLOSED`).
Setting the log-level to DEBUG does not give any information.

Any ideas how to debug this?

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for Sentry on-premise installation issues.
