### ISSUE TITLE
access denied for sentry-onpremise-local

### ISSUE THREAD

**Issue by larsnystrom** [getsentry/onpremise#278]
The README says that in order to update, one should run `docker-compose build --pull`, but when I do that I end up with the following error:

> ERROR: Service 'sentry-cleanup' failed to build: pull access denied for sentry-onpremise-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by BYK** [comment]
Hey, sorry my bad for not updating that part yet. The following should fix it for now:
```
docker-compose build web --pull
docker-compose build --pull
```

Also, may I ask which version you are upgrading from? If you are coming from pre-10 you'll lose all your events, be warned.

**Comment by larsnystrom** [comment]
I was in a "something doesn't work let's see if I'm on the latest version" kind of situation, but it's a fresh install of v10, so there wasn't any update available anyway (and also no worries about data loss).

**Comment by zidex** [comment]
> Hey, sorry my bad for not updating that part yet. The following should fix it for now:
> 
> ```
> docker-compose build web --pull
> docker-compose build --pull
> ```
> 
> Also, may I ask which version you are upgrading from? If you are coming from pre-10 you'll lose all your events, be warned.

It does not work for me

**Comment by BYK** [comment]
@zindex please provide full logs so I can diagnose.

**Comment by Chrissi2812** [comment]
@zidex I had the same issue as I have tried it first without the `docker-compose build web --pull`
So maybe this will fix it for you `docker-compose build --force-rm`

**Comment by garethhallnz** [comment]
I too am getting this error message,

`docker-compose build web --pull ` does not work for me as I get this message "No such service: --pull" however switching the arguments around worker `docker-compose build --pull web`

Then I run `docker-compose build --pull ` which again resulted in 
`Building sentry-cleanup
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
ERROR: Service 'sentry-cleanup' failed to build: pull access denied for sentry-onpremise-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

Then I tried `docker-compose build --pull sentry-cleanup` but resulted in the same error.

I also run `docker-compose build --force-rm` which ran successfully .... but is this right without the pull?

**Comment by BYK** [comment]
You should not run `docker-compose build --pull`, only
```
docker-compose build --pull --force-rm web
docker-compose build --force-rm
```

**Comment by maximal** [comment]
Trying to upgrade 9.1.2 to 10-beta and having the same issue

Though these execute successfully:
```sh
docker-compose build --pull --force-rm web
docker-compose build --force-rm
```

Then I cannot run the remaining:
```sh
docker-compose run --rm web upgrade # Run new migrations
docker-compose up -d # Recreate the services
```

They won’t run yielding:
```
ERROR: Volume sentry-redis declared as external, but could not be found. Please create the volume manually using `docker volume create --name=sentry-redis` and try again.
```
