### ISSUE TITLE
Allow configuring web port as env var

### ISSUE THREAD

**Issue by larsnystrom** [getsentry/onpremise#279]
Most of the stuff I need to change in docker-compose can be done by just adding a `docker-compose.override.yml` file (like adding `http_proxy` env vars and switching smtp image). But it is not possible to override the port specification of the `web` service.

I think the cleanest solution would be to change 

```
ports:
  - "9000:9000/tcp"

```
to

```
ports:
  - "${SENTRY_WEB_PORT}:9000/tcp"
```

in `docker-compose.yml`.

What do you think?

My reason for changing the port is simply to restrict to `127.0.0.1:9000`, so that it can only be accessed from localhost.

**Comment by BYK** [comment]
We are moving away from environment variables to config files and this setting can be changed here: https://github.com/getsentry/onpremise/blob/master/sentry/sentry.conf.example.py#L151

Would that satisfy your need?

**Comment by larsnystrom** [comment]
I don't think that will work, because I'm talking about the binding of host ports to container ports, and I think that setting will just change the port used inside the container? I think environment variables is actually the only way to make this configurable, because `docker-compose up` doesn't even have a command line argument for binding ports.

**Comment by BYK** [comment]
Whoops, right sorry my mind was elsewhere I guess. Sounds like a reasonable suggestion, would you like to send a PR?

That said I think the alternative can be using a `docker-compose.override.yml` file and override it there. What do you think?
