### ISSUE TITLE
Troubleshooting customization

### ISSUE THREAD

**Issue by lpzdvd** [getsentry/onpremise#28]
Hi,

I'm trying to avoid interactive input for

1. SENTRY_SECRET_KEY
2. Change db name, user
3. Init / rebuild the database

I managed first point defining the variable in sentry.conf.py and adding to Dockerfile:
COPY sentry.conf.py /usr/src/sentry/sentry.conf.py

Anyway, I'm in trouble with the second and third one because related to the official doc I thinks it's mixing two set of instructions. How should I be building sentry ? I mean, make build, docker build, etc..

Thanks in advance !

**Comment by mattrobenolt** [comment]
I'm not sure what you're asking or what you're trying to do. Step 2 is configured in sentry.conf.py as well, and step 3 is just calling some commands to destroy and rebuild the database.

**Comment by lpzdvd** [comment]
I'm trying to build my custom image adding 1) predefined secret key 2) DBs vars but I'm confused. It would be great if I could avoid interactive input for creating the database (we would like to set an ansible role later, but first we are just playing around).

Let's say for example I want to only set SENTRY_SECRET_KEY in sentry.conf.py

In that case, default instructions are confusing for me due to the fact that this repository, official default sentry repository and doc in the web page mixes a lot of things (or maybe just me :) )

So:

mkdir -p data/{sentry,postgres}
docker-compose run --rm web config generate-secret-key - Generate a secret key. Add it to docker-compose.yml in base as SENTRY_SECRET_KEY. **Do I have to do this step if it's already declared in sentry.conf.py ??? I guess it's already unnecessary but I need to build**
docker-compose run --rm web upgrade - Build the database. Use the interactive prompts to create a user account. **Same here: what variables do I need to set up?**
docker-compose up -d - Lift all services (detached/background mode).
Access your instance at localhost:9000!

So, I'm missing how to build a custom image and where to set this process in your instructions. Could you provide a detailed example?

Sorry for the inconvenience and thanks for your patience !! Great work here.

**Comment by dcramer** [comment]
@lpzdvd you'll need to take this off the issue tracker and use our support options:

https://sentry.io/support/

The short of it is we want everyone to be using Sentry, but the team isn't really here to help everyone operationalize the software (esp. for free). Our aim is to provide a great solution, primarily focused on SaaS, and let people who need to run it behind the firewall do so (but with their own expertise).
