### ISSUE TITLE
Add a fallback for postgres database

### ISSUE THREAD

**Issue by sunil-jhamnani** [getsentry/onpremise#280]
### Machine 1:
All the sentry related docker containers are running on this machine(web, worker and cron)

### Machine 2:
Postgres and redis containers are running on this machine. Sentry containers are connected via IP and port to this machine.

### Machine 3: 
I am planning to create a master-slave system for Postgres with machine 1 being the master and this as a slave.

### My query:
Is there any way I can provide machine 3(IP:port) for postgres connection to sentry as a fallback if for some reason machine 2 is down or for some reason connection fails.

**Comment by BYK** [comment]
Closing in favor of https://forum.sentry.io/t/add-a-fallback-for-postgres-database/8207

Please avoid double posting like this in the future.
