### ISSUE TITLE
make build only recreates image but doesnt update running docker compose

### ISSUE THREAD

**Issue by Freundschaft** [getsentry/onpremise#3]
Hi there,

I noticed that when I write updates to config.yml or sentry.conf.py, then the changes are not updated to a running machine I started with docker compose after running make build
would it make sense to add a task in the makefile that automatically stops the vm, updates the image and restarts it?

cheers
qiong

**Comment by mattrobenolt** [comment]
The Makefile doesn't touch running or stopping services. It purely facilitates building the images. There are too many ways to manage running containers and services, that this is left as an exercise for the reader.
