### ISSUE TITLE
Postgres and Redis errors while upgrading 9.1.2 to 10-beta

### ISSUE THREAD

**Issue by maximal** [getsentry/onpremise#301]
After fighting with https://github.com/getsentry/onpremise/issues/278#issuecomment-567809679 I faced with Postgres and Redis issues.

Container logs:

```
postgres_1              | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1              | 
postgres_1              | FATAL:  database files are incompatible with server
postgres_1              | DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.16.
... ... ...
sentry-onpremise_postgres_1 exited with code 1
cron_1                  | !! Configuration error: Exception: Error: REDIS_PORT_6379_TCP_ADDR (or SENTRY_REDIS_HOST) is undefined, did you forget to `--link` a redis container?
web_1                   | !! Configuration error: Exception: Error: REDIS_PORT_6379_TCP_ADDR (or SENTRY_REDIS_HOST) is undefined, did you forget to `--link` a redis container?
worker_1                | !! Configuration error: Exception: Error: REDIS_PORT_6379_TCP_ADDR (or SENTRY_REDIS_HOST) is undefined, did you forget to `--link` a redis container?
... ... ...
sentry-onpremise_worker_1 exited with code 1
sentry-onpremise_web_1 exited with code 1
sentry-onpremise_cron_1 exited with code 1
```

So, these containers are always on `restarting` state:

```
sentry-onpremise_cron_1                   /bin/sh -c exec $SENTRY_CO ...   Restarting
sentry-onpremise_postgres_1               docker-entrypoint.sh postgres    Restarting
sentry-onpremise_web_1                    /bin/sh -c exec $SENTRY_CO ...   Restarting
sentry-onpremise_worker_1                 /bin/sh -c exec $SENTRY_CO ...   Restarting
```

**Comment by BYK** [comment]
This should also be fixed with https://github.com/getsentry/onpremise/pull/304. The upgrade instructions were incorrect. Can you try running `./install.sh` and see if it works? If you hit #302, just run the workaround suggested there and you should be good.

**Comment by maximal** [comment]
`./install.sh` fails as well. Last lines are:

```
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/9.6/data -l logfile start


*failure*
Consult the last few lines of "pg_upgrade_server.log" for
the probable cause of the failure.

There seems to be a postmaster servicing the old cluster.
Please shutdown that postmaster and try again.
Failure, exiting
Cleaning up...
```

**Comment by BYK** [comment]
@maximal - that means you tried to upgrade while Sentry, and more specifically your Postgres instance, is running. You need to run `docker-compose down` before proceeding. The newer version of the script does this automatically now but it's always a good idea to do this before even updating the repo.

**Comment by maximal** [comment]
Stopped all, run `./install.sh`, got:

```
  /var/lib/postgresql/9.5/data/base/1/2613
  /var/lib/postgresql/9.5/data/base/1/2683
  /var/lib/postgresql/9.5/data/base/1/2995
  /var/lib/postgresql/9.5/data/base/1/2996
                                                            ok
Setting next OID for new cluster                            ok
Sync data directory to disk                                 ok
Creating script to analyze new cluster                      ok
Creating script to delete old cluster                       ok

Upgrade Complete
----------------
Optimizer statistics are not transferred by pg_upgrade so,
once you start the new server, consider running:
    ./analyze_new_cluster.sh

Running this script will delete the old cluster's data files:
    ./delete_old_cluster.sh
Error response from daemon: remove sentry-postgres: volume is in use - [82db8e42d1cb9acf5693cc3f6a338e0962eaedff24d3b4e11b9be4357e2728f8]
Cleaning up...
```

`sentry_onpremise_postgres_1` is in restarting state constantly, all others are up.

There is the similar error in logs:
```
postgres_1                | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1                | 
postgres_1                | FATAL:  database files are incompatible with server
postgres_1                | DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.16.
```

Tired of struggling with upgrade, made a clean install.

**Comment by BYK** [comment]
The reason is you running `docker-compose stop` instead of running `docker-compose down` so the script got stuck at removing the old volume and renaming the new volume to that.

If you haven't deleted you should have a sentry-postgres-new volume laying around with your old data migrated to Postgres 9.6 and you can run from there, even migrate your old events.

**Comment by maximal** [comment]
@BYK, thank you for detailed explanation, I got it. Will try the next time.

**Comment by uhlhosting** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 30, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 174, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 121, in _upgrade
    _migrate_from_south(verbosity)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 93, in _migrate_from_south
    if not _has_south_history(connection):
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 78, in _has_south_history
    cursor = connection.cursor()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 97, in _cursor
    return super(DatabaseWrapper, self)._cursor()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known

root@sentry:/home/cosmic/sentry/onpremise#

**Comment by uhlhosting** [comment]
By runnig simply ./install.sh i get pg errors

`syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/9.6/data -l logfile start


WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

*failure*
Consult the last few lines of "pg_upgrade_server.log" for
the probable cause of the failure.

There seems to be a postmaster servicing the old cluster.
Please shutdown that postmaster and try again.
Failure, exiting
Cleaning up...
root@sentry:/home/cosmic/sentry/onpremise# 
`

I have tried manually docker-compose

docker-compose build --pull --force-rm web
docker-compose build --force-rm
