### ISSUE TITLE
GEOIP_PATH_MMDB support

### ISSUE THREAD

**Issue by ptman** [getsentry/onpremise#310]
How should one configure GEOIP_PATH_MMDB for the docker image?

**Comment by BYK** [comment]
We were planning to add support for this in the on-premise repo but the very recent account/license requirements may make it harder than we want it to.

Still, https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads may help you get started. What you need to do is download this file, put/copy it into a volume and then mount that volume to Sentry containers.

**Comment by ptman** [comment]
Sure, but can I point to that file with an environment variable?

**Comment by BYK** [comment]
As long as the file is volume that is mounted to the containers, you can set `GEOIP_PATH_MMDB` either through the `.env` file or in `docker-compose.yaml` or by creating a `docker-compose.overrides.yaml` and doing it there.

**Comment by ptman** [comment]
Right, so would you consider adding that as a default so that one doesn't need to customize it?

**Comment by BYK** [comment]
Yes, it can be a part of the automation work we intend to do around this. It won't happen very soon though. If you are interested, I can assist you creating a pull request and getting it merged rather than waiting for us.

**Comment by bellini666** [comment]
@BYK I just tried to create a volume and add it to the installation, but I'm getting this:
```
cron_1                    | 17:07:31 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
worker_1                  | 17:07:31 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
post-process-forwarder_1  | 17:07:31 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
web_1                     | 17:07:31 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
worker_1                  | 17:07:32 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
post-process-forwarder_1  | 17:07:32 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
cron_1                    | 17:07:32 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
web_1                     | 17:07:32 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
```

I'm attaching the volume with `- 'sentry-geoip:/geoip'` in the config and added `GEOIP_PATH_MMDB = '/geoip/GeoLite2-City.mmdb'` to my `sentry.conf.py`

Am I doing something wrong? The permissions seems fine:

```
root@2a1d0fb1749c:/geoip# ls -lah
total 64M
drwx------ 2 root root 4.0K Jan 26 17:01 .
drwxr-xr-x 1 root root 4.0K Jan 26 17:07 ..
-rw-r--r-- 1 root root  60M Jan 26 17:00 GeoLite2-City.mmdb
```

**Comment by urusha** [comment]
You just need to add this to `x-sentry-defaults` `volumes` section in `docker-compose.yml`:
`- '/path/to/geoip/on/host:/path/to/geoip/in/sentry/conf/'`

**Comment by BYK** [comment]
Relevant: https://github.com/sentry-kubernetes/charts/issues/92
