### ISSUE TITLE
Sentry Docker Docs - SENTRY_RABBITMQ_*

### ISSUE THREAD

**Issue by lechup** [getsentry/onpremise#311]
I was looking a way to connect RABBITMQ and I found this PR thanks to Google:
https://github.com/getsentry/docker-sentry/pull/60/files

Is not however included in sentry docker docs. Who is able to merge changes in:
https://github.com/docker-library/docs/tree/master/sentry

Should I prepare a PR to this repo?

PS: There is exisitng getsentry/docker-sentry#110 which is I guess connected...

**Comment by BYK** [comment]
We have removed support for almost all environment variables and don't plan to work on this any time soon so closing.
