### ISSUE TITLE
planned helm chart

### ISSUE THREAD

**Issue by trondhindenes** [getsentry/onpremise#313]
I'm a bit surprised that docker-compose is the method of choice for deploying Sentry 10. Is there a helm-chart or other Kubernetes-focused deploy tooling planned?

imho a Helm chart combined with a lightweight kubernetes cluster such as k3s would by far be the easiest way to get a complex container-based app up and running, and its easy to script it almost without any dependencies at all.

**Comment by BYK** [comment]
Currently we have no plans on working on a Helm chart but there's a community-maintained one if you are interested: https://github.com/helm/charts/tree/master/stable/sentry
