### ISSUE TITLE
Add support for pulling images from a private repository

### ISSUE THREAD

**Issue by Tirzono** [getsentry/onpremise#324]
Add support for an environment variable such as `DOCKER_IMAGE_REPOSITORY` that adds the repository as a prefix to all images if set. This would allow running the install script behind a firewall (that does have access to a private repository which proxies the request to the Docker Hub) without having to manually edit multiple files.

**Comment by BYK** [comment]
Hi @Tirzono, I'm not familiar with this much or your specific use case. Would you mind sending a preliminary PR so we can work from there? I'm happy to make this happen if it doesn't complicate the codebase too much (sounds like it won't).

**Comment by Tirzono** [comment]
I am more than happy to send a PR for this. I think it won't complicate the codebase too much, but we will see that if I prepared the PR.

**Comment by BYK** [comment]
>Good job on the release of version 10 by the way.

Thanks a lot, very much appreciated :)

>I am more than happy to send a PR for this. I think it won't complicate the codebase too much, but we will see that if I prepared the PR.

Eagerly waiting for this. We are using Google Cloud Build at Sentry so maybe I can try testing with that once we get the PR up.

**Comment by BYK** [comment]
@Tirzono still interested?

**Comment by Tirzono** [comment]
I am still interested, but it is less of a priority as I got it working without the private repository too. I'm still planning to send a PR for this though.

**Comment by BYK** [comment]
@Tirzono - _still_ interested? 🙂 Otherwise I'll close this issue as we are not planning to work on it ourselves.

**Comment by Tirzono** [comment]
Close it for now. I am still planning to do it but I haven't found time for it yet. If I will make a PR I will link it to this issue. We can always reopen it if needed. Thanks for your patience.
