### ISSUE TITLE
Sentry 10.1.0.dev0 used after upgrade

### ISSUE THREAD

**Issue by nicolas-brousse** [getsentry/onpremise#326]
I upgraded from latest `9.x` to `10.0` today. Then when I loaded the application, I see `10.1.0.dev0
` in footer.

How could I fix the version to `10.0`?

Also I've got a lot of  warning in migration:
`13:43:53 [WARNING] sentry.eventstream.kafka.backend: Could not publish message (error: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Broker: Message size too large"}): <cimpl.Message object at 0x7fbbd3d2f1d0>`

It is normal?

**Comment by BYK** [comment]
Hi @nicolas-brousse! This is expected as we mentioned in our announcement post:

https://blog.sentry.io/2020/01/07/self-hosted-sentry-10-is-ready-to-serve-get-it-while-its-hot/
>We also enabled continuous releases for our Docker images. This means whenever you install or update Sentry through the install script, the version you will be using wouldn’t be older than a handful of minutes. If that’s not your thing, you can always choose a specific image by setting the SENTRY_IMAGE environment variable before running the script.

You can set `SENTRY_IMAGE=getsentry/sentry:10` if you really want to fix it but I assure you that wouldn't bring you any extra safety and would strip you from getting our continuous improvements (fixes and features).

Regarding the error, that is not expected. Can you share your full logs in a separate issue? Also can you check if you have any missing events?

Closing this issue as the main question is answered. Please file a new one for the error you are seeing.

**Comment by nicolas-brousse** [comment]
Hi @BYK, thank you for your answer.

Sorry I didn't take car enough about the `continuous releases` of your `Docker images` when I read the article, before doing upgrades.  
I'll keep this like this so.

But to inform you, I tried to do `SENTRY_IMAGE="getsentry/sentry:10" ./install.sh` or `export SENTRY_IMAGE="getsentry/sentry:10"` and it stayed the same.  
Not sure how or where I should specify this env var.

For the other problem I'll open an other issue.

**Comment by BYK** [comment]
>But to inform you, I tried to do SENTRY_IMAGE="getsentry/sentry:10" ./install.sh or export SENTRY_IMAGE="getsentry/sentry:10" and it stayed the same.
Not sure how or where I should specify this env var.

```bash
SENTRY_IMAGE="getsentry/sentry:10" ./install.sh
```

Should do the trick, I use it all the time. It may have something to do with yours being an existing install and trying to use an older image than what you currently have. I'll still try this myself and see what happens, thanks for reporting.

Waiting for the other issue!
