### ISSUE TITLE
[bug] OCI runtime create failed: container_linux.go:346

### ISSUE THREAD

**Issue by SimonGolms** [getsentry/onpremise#329]
**Version**
- Windows 10 1809
- Git Bash: 4.4.23(1)-release
- Docker: 19.03.5
- Docker-Compose: 1.24.1

**Current behavior:**
When running `install.sh` an error occurs during the `"Migrating file storage..."` step:
```txt
Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"C:/Program\": stat C:/Program: no such file or directory": unknown
```

**Expected behavior:**
Running `install.sh` without errors.

**Steps to reproduce:**
Running the `install.sh` script on Windows and Git Bash.

**Logfile** 

```txt
Checking minimum requirements...
...
Migrating file storage...
Starting sentry_onpremise_symbolicator_1 ... 
Starting sentry_onpremise_redis_1        ... 
Starting sentry_onpremise_smtp_1         ... 
Starting sentry_onpremise_symbolicator_1 ... done
Starting sentry_onpremise_redis_1        ... done
Starting sentry_onpremise_smtp_1         ... done
Starting sentry_onpremise_postgres_1     ... 
Starting sentry_onpremise_memcached_1    ... 
Starting sentry_onpremise_postgres_1     ... done
Starting sentry_onpremise_clickhouse_1   ... 
Starting sentry_onpremise_memcached_1    ... done
Starting sentry_onpremise_clickhouse_1   ... done
Starting sentry_onpremise_zookeeper_1    ... 
Starting sentry_onpremise_zookeeper_1    ... done
Starting sentry_onpremise_kafka_1        ... 
Starting sentry_onpremise_kafka_1        ... done
Starting sentry_onpremise_snuba-consumer_1 ... 
Starting sentry_onpremise_snuba-api_1      ... 
Starting sentry_onpremise_snuba-consumer_1 ... done
Starting sentry_onpremise_snuba-replacer_1 ... 
Starting sentry_onpremise_snuba-api_1      ... done
Starting sentry_onpremise_snuba-replacer_1 ... done
Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"C:/Program\": stat C:/Program: no such file or directory": unknown
Cleaning up...
```

**Current Workaround**
Change the `--entrypoint` parameter from `/bin/bash` to `//bin//bash` to run the script successfully.

```sh
...
if [ "$SENTRY_DATA_NEEDS_MIGRATION" ]; then
  echo "Migrating file storage..."
  # Use the web (Sentry) image so the file owners are kept as sentry:sentry
  # $dcr --entrypoint /bin/bash web -c \
  $dcr --entrypoint //bin//bash web -c \
    "mkdir -p /tmp/files; mv /data/* /tmp/files/; mv /tmp/files /data/files"
fi
```

I hope this will save some headaches for other developers, as it took me some hours for troubleshooting and to find a current workaround. It would be great if this could be fixed.

**Comment by BYK** [comment]
Hi @SimonGolms and thanks a lot for reporting this issue with a workaround! I've been using WSL instead of Git Bash this whole time and didn't consider that as a potential target, my apologies!

That said I cannot relate the error you got with the workaround that worked for you. It clearly looks like a quoting problem due to a path having spaces in it. I wonder if git bash is doing something weird when it sees `/bin/bash` and replaces that with a local path on your machine? Then the "correct" solution would be quoting that parameter instead of adding extra slashes:

```bash
$dcr --entrypoint "/bin/bash" web -c \
```

what do you think? (and can you test this?)

**Comment by SimonGolms** [comment]
Hi @BYK, thanks for the hint with WSL. Since I'm working on a business device, it was easier to install Git Bash than to get WSL enabled.
However, I already tried your solution yesterday without success, and made the double check some seconds ago. There I just found out that this command also works:
```sh
$dcr --entrypoint \"/bin/bash\" web -c \
```

**Comment by BYK** [comment]
Aha! It looks weird but as long as it also works with "normal bash", I'm okay applying it. Will try this later on but be my guest on submitting a PR so we get your name ingrained for this discovery and fix :)

**Comment by SimonGolms** [comment]
Was able to run the `install.sh` successfully on my private Mac with customized entrypoint parameter.
Submitted PR #335 :)
