### ISSUE TITLE
./install.sh Failed: 'system-key' Must be set.

### ISSUE THREAD

**Issue by luffyZh** [getsentry/onpremise#330]
For beginners, follow the tutorial to install！

environment:
MacOS: 10.15.2
Docker: 19.03.5
Docker-Compose: 1.24.1

Steps:

1 - git clone https://github.com/getsentry/onpremise.git

2 - cd onpremise && ./install.sh

Finally the error like the image:

<img width="940" alt="图片" src="https://user-images.githubusercontent.com/17840558/72064495-f4591f80-3316-11ea-9c11-9523d33f1878.png">

Error info: !! Configuration error: `system.secret-key` MUST be set. Use 'sentry config generate-secret-key' to get one.

Any idea?

**Comment by BYK** [comment]
Can you share the full install logs that are automatically generated?

**Comment by luffyZh** [comment]
@BYK Hi, the complete file is here: [sentry install log](https://github.com/luffyZh/next-sentry-demo/blob/master/sentry_install_log-2020-01-10_10-40-22.txt)

**Comment by luffyZh** [comment]
@BYK And I find a strange thing.Install several times（change some config reinstall）, one of which will succeed and the others will fail

**Comment by BYK** [comment]
It is the automatic secret key generation. Since it is random, a second run simply generates a new secret that is actually valid:

>Generating secret key...
>tr: Illegal byte sequence

I'll investigate this but have never encountered this before on the systems I worked with (WSL, Google Cloud Build and TravisCI) so if you can share your system details, it may help me identify what's going wrong there.

**Comment by luffyZh** [comment]
> It is the automatic secret key generation. Since it is random, a second run simply generates a new secret that is actually valid:
> 
> > Generating secret key...
> > tr: Illegal byte sequence
> 
> I'll investigate this but have never encountered this before on the systems I worked with (WSL, Google Cloud Build and TravisCI) ~so if you can share your system details, it may help me identify what's going wrong there.~ -- just saw it is MacOS, will investigate.

Thanks,./install.sh is very convenient, but in my environment, it is not always successful, it needs to install several times to succeed

**Comment by BYK** [comment]
>Thanks,./install.sh is very convenient, but in my environment, it is not always successful, it needs to install several times to succeed

Yup, submitted a potential fix: #338. Feel free to try that branch for now.

**Comment by luffyZh** [comment]
> > Thanks,./install.sh is very convenient, but in my environment, it is not always successful, it needs to install several times to succeed
> 
> Yup, submitted a potential fix: #338. Feel free to try that branch for now.

Thank you. I'll try and give you feedback

**Comment by luffyZh** [comment]
@BYK Great job~I installed twice,both succeed!
