### ISSUE TITLE
Permission denied to create avatars

### ISSUE THREAD

**Issue by bellini666** [getsentry/onpremise#334]
I just upgraded my previous installation to 10. Now I can't see my organization avatar and when I try to upload one it gives me these errors:

https://sentry.zerosoft.com.br/share/issue/f6cb6b84d43440c7983aa355bfbdf8a0/
https://sentry.zerosoft.com.br/share/issue/14c6aeacfb314c3eb66f084260abb91c/

I'm imagining that the volume needs some permissions fixes? Should it be done in the `install.sh` script? Or is this some corner case I hit where I need to correct by hand? If so, what are the permissions I need to set?

**Comment by BYK** [comment]
This is a failure in our Docker entry file as discussed in #328. I've submitted a fix for that and I think I'll update the install script in the meantime to fix this.

Can you try running the commands in https://github.com/getsentry/onpremise/issues/328#issuecomment-572528163 and see if they help in the meantime?

**Comment by bellini666** [comment]
@BYK yeah, it solved my issue, thanks!
