### ISSUE TITLE
Cannot use Sentry 10 since Clickhouse requires SSE4

### ISSUE THREAD

**Issue by jwdb** [getsentry/onpremise#340]
Since Sentry 10 uses Clickhouse for Snuba, it's not possible to install it normally on an older server that does not have SSE4.

Clickhouse can be compiled without SSE4 required, but are there any other steps I need to take to make Clickhouse work outside of the normal Sentry docker compose or can I run a seperate version of clickhouse and make Sentry/Snuba communicate with that?

**Comment by BYK** [comment]
I think you'd need to adjust some network settings to allow the containers to communicate with a device on the host (or some other place outside of the docker-compose network). That said I'm pretty sure you can get a Docker image with SSE4 disabled by using a fork of this: https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/Dockerfile

Finally, I think forums would be a better discussion place as there may be other people in your situation that you can group with ;)

**Comment by siredmar** [comment]
As stated here (https://github.com/ClickHouse/ClickHouse/issues/1695#issuecomment-414951813) it is not planned to provide builds that are build with disabled SSE4. 
You'd need to build ClickHouse your own with SSE4 instructions disabled. See here for more information about that: https://clickhouse.yandex/docs/en/getting_started/install/#system-requirements

If you really do that step, please inform me that i can use your docker image as well ;)
