### ISSUE TITLE
No such service: web

### ISSUE THREAD

**Issue by AggressivelyMeows** [getsentry/onpremise#342]
Hey, when i go to use the install wizard the script, it exits after installing the docker images with "No such service: web".

The error is something to do with [line 101](https://github.com/getsentry/onpremise/blob/master/install.sh#L101) where it tries to install web. For some reason, Docker never gets the memo that web exists, or that web was never installed. Checking installed images yields this:
```bash
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
getsentry/sentry       latest              081e7bd2d112        16 hours ago        789MB
busybox                latest              6d5fcfe5ff17        2 weeks ago         1.22MB
discourse/base         2.0.20191219-2109   4a99baef7044        3 weeks ago         2.23GB
<none>                 <none>              e64b1e41fdca        3 weeks ago         2.87GB
redash/redash          latest              1b48a51810b5        2 months ago        1.31GB
postgres               9                   afd8110f1813        2 months ago        211MB
redash/redash          7.0.0.b18042        3cc82e753890        9 months ago        1.37GB
predictionio/pio       latest              fc1f2fa4cedd        13 months ago       1.62GB
redis                  3.0-alpine          856249f48b0c        2 years ago         12.6MB
postgres               9.5.6-alpine        cc38b642ca58        2 years ago         36.9MB
redash/nginx           latest              76abf32984e9        3 years ago         134MB
```

I followed the exact instructions from the docs page about installing. Any help with this would be great!

**Comment by BYK** [comment]
Can you share how you are running the script and the generated log file?

**Comment by AggressivelyMeows** [comment]
The script is being run from the latest version of the git. The log file is here: https://termbin.com/5l22

**Comment by BYK** [comment]
Seems like you have a globally set `COMPOSE_PROJECT_NAME` and/or `COMPOSE_FILE` environment variables, clashing with Sentry. You need to unset them. For more information, see https://docs.docker.com/compose/reference/envvars/
