### ISSUE TITLE
3rd party plugins integration support still possible?

### ISSUE THREAD

**Issue by max-wittig** [getsentry/onpremise#347]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 10]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Plugins like [sentry-auth-oidc](https://github.com/siemens/sentry-auth-oidc) don't seem to work anymore with sentry 10. Is it still possible to install 3rd party plugins?

## Steps to Reproduce

1. Install sentry 10
2. Add sentry auth oidc
3. Notice 500, when trying to login

Good items to include here include:

> sh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
web_1                     | Traceback (most recent call last):
web_1                     |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
web_1                     |     response = get_response(request)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
web_1                     |     response = self._get_response(request)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1                     |     response = self.process_exception_by_middleware(e, request)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1                     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
web_1                     |     return self.dispatch(request, *args, **kwargs)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
web_1                     |     return view_func(*args, **kwargs)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 227, in dispatch
web_1                     |     return self.handle(request, *args, **kwargs)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
web_1                     |     response = view_func(request, *args, **kwargs)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
web_1                     |     return func(*args, **kwargs)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_organization_login.py", line 72, in handle
web_1                     |     response = self.handle_sso(request, organization, auth_provider)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_organization_login.py", line 35, in handle_sso
web_1                     |     provider = auth_provider.get_provider()
web_1                     |   File "/usr/local/lib/python2.7/site-packages/sentry/models/authprovider.py", line 51, in get_provider
web_1                     |     return manager.get(self.provider, **self.config)
web_1                     |   File "/usr/local/lib/python2.7/site-packages/sentry/auth/manager.py", line 23, in get
web_1                     |     raise ProviderNotRegistered(key)
web_1                     | ProviderNotRegistered: oidc
web_1                     | 15:24:15 [ERROR] django.request: Internal Server Error: /auth/login/org/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/org/'>)
web_1                     | 172.21.0.21 - - [13/Jan/2020:15:24:13 +0000] "GET /auth/login/org/ HTTP/1.0" 500 5321 "https://someurl/auth/login/org" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"

### What you expected to happen

Login should work

### Possible Solution

Describe how to create plugins for sentry >= 10

**Comment by BYK** [comment]
Yes it is. You should be able to put `https://github.com/siemens/sentry-auth-oidc/archive/master.zip` into `sentry/requirements.txt` file and rebuild your container for this to be installed.

**Comment by max-wittig** [comment]
Thanks for your response. But would that change the behavior here, because the plugin is clearly installed?

**Comment by max-wittig** [comment]
Additionally the data from 9 to 10 doesn't seem to be compatible ☹️ 

> django.db.utils.ProgrammingError: UndefinedColumn('column sentry_organizationmember.inviter_id does not exist\nLINE 1: ... "sentry_organizationmember"."has_global_access", "sentry_or...\n                                                             ^\n',)
web_1                     | SQL: SELECT "sentry_organizationmember"."id", "sentry_organizationmember"."organization_id", "sentry_organizationmember"."user_id", "sentry_organizationmember"."email", "sentry_organizationmember"."role", "sentry_organizationmember"."flags", "sentry_organizationmember"."token", "sentry_organizationmember"."date_added", "sentry_organizationmember"."token_expires_at", "sentry_organizationmember"."has_global_access", "sentry_organizationmember"."inviter_id", "sentry_organizationmember"."invite_status", "sentry_organizationmember"."type" FROM "sentry_organizationmember" INNER JOIN "sentry_organization" ON ("sentry_organizationmember"."organization_id" = "sentry_organization"."id") WHERE ("sentry_organization"."status" = %s AND "sentry_organizationmember"."user_id" IN (%s))
web_1                     | 172.21.0.20 - - [14/Jan/2020:08:01:14 +0000] "GET / HTTP/1.0" 500 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"

**Comment by max-wittig** [comment]
@BYK I've done a clean install, but seems like the way sentry loads plugins has changed:

> /providers/base.py\", line 7, in <module>", "    from social_auth.models import UserSocialAuth", "  File \"/usr/local/lib/python2.7/site-packages/social_auth/models.py\", line 12, in <module>", "    from .fields import JSONField", "  File \"/usr/local/lib/python2.7/site-packages/social_auth/fields.py\", line 10, in <module>", "    from sentry.db.models.utils import Creator", "  File \"/usr/local/lib/python2.7/site-packages/sentry/db/models/__init__.py\", line 3, in <module>", "    from .base import *  # NOQA", "  File \"/usr/local/lib/python2.7/site-packages/sentry/db/models/base.py\", line 37, in <module>", "    class BaseModel(models.Model):", "  File \"/usr/local/lib/python2.7/site-packages/django/db/models/base.py\", line 105, in __new__", "    app_config = apps.get_containing_app_config(module)", "  File \"/usr/local/lib/python2.7/site-packages/django/apps/registry.py\", line 237, in get_containing_app_config", "    self.check_apps_ready()", "  File \"/usr/local/lib/python2.7/site-packages/django/apps/registry.py\", line 124, in check_apps_ready", "    raise AppRegistryNotReady(\"Apps aren't loaded yet.\")", "django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet."]}

**Comment by max-wittig** [comment]
The plugin does need to be changed and I found out how. I will publish the changes on sentry-auth-oidc soon for it to be compatible with sentry-10

**Comment by BYK** [comment]
>But would that change the behavior here, because the plugin is clearly installed?

Ehh, sorry I didn't look at the stack trace and just assumed you were asking how to install things. My bad :(

This looks like a migration-related issue to me. Tagging @scefali and @wedamija who may be able to provide more information on this.

**Comment by max-wittig** [comment]
I figured it out. Seems like you need to configure your plugin to wait until django is ready, by using `AppConfig` and setting up the `ready` method.

**Comment by max-wittig** [comment]
@BYK Here are the changes, I needed to make: https://github.com/siemens/sentry-auth-oidc/commit/fc7856910a8dd4a4edaf0e09af64ab8f6e285d8e

**Comment by BYK** [comment]
@max-wittig thanks a lot for sharing your solution! Do you think we can close the issue now?

**Comment by max-wittig** [comment]
Yes, but I guess it should be documented better in sentry maybe?

**Comment by BYK** [comment]
I thought a major revision indicated things may not be 100% backwards compatible. Do you think we should still say some plugins may stop working? There is also a note on 3rd-party plugins over at our documentation: https://docs.sentry.io/server/plugins/#deprecated-plugins

**Comment by max-wittig** [comment]
@BYK Sure major version means things break. I haven't found a single plugin in the wild that still looks like it would work. Maybe remove this list (or add that it only works with sentry 9) and provide and example for sentry 10 instead?

**Comment by chessracer** [comment]
We're using sentry v9.1.2, together with oidc + google auth via a keycloak provider
Now that google-auth-oidc defaults to v3.0.0 we started running into:

>   File "/usr/local/lib/python2.7/site-packages/oidc/apps.py", line 2, in <module>
    from django.apps import AppConfig
ImportError: No module named apps

Following some prior documentation on that integration, we were running 
`pip install sentry-auth-oidc` in a command: block in docker-compose.
Instead, explicitly installing sentry-auth-oidc v2.1.0 works for us in conjunction with sentry:9.1.2

```
   command:
    - /bin/sh
    - -c
    - |
      sentry upgrade --noinput
      sentry createuser --email admin --password admin --superuser
      pip install --upgrade sentry-auth-oidc==2.1.0
      /entrypoint.sh run web
```

**Comment by omidraha** [comment]
When we add third package to `requirements.txt` file, 
Do we need to run `install.sh` again? 
I tried `docker-compose build` , but I had some error for this.

**Comment by BYK** [comment]
It shows that the plugin is installed and working:

>worker_1                                    | 21:45:25 [INFO] sentry.plugins.sentry_telegram_py3: notification.dispatched (event_id='ffeb6e08d9c9486da80c924f0db89e61' group_id=23 plugin='sentry_telegram_py3' rule_id=3 project_id=2)

I'd look into your configuration or the plugin code itself to debug further.

>When we add third package like this to requirements.txt file,
>Do we need to run install.sh again?

Nope. In the most recent versions of the repo, all you need is a restart which will automatically install any missing plugins upon the first start of the container (and won't install them everytime).

**Comment by omidraha** [comment]
> I'd look into your configuration or the plugin code itself to debug further.

The source code of plugin is [here](https://github.com/vortland/sentry-telegram/blob/105654d1745cf4e41ebcab7a570864dd943fa561/sentry_telegram_py3/plugin.py)

And my configuration of plugin is [here](https://user-images.githubusercontent.com/397672/111989872-f5e3c180-8b2f-11eb-9d4b-66a6c67aa91d.png)

Let me know the settings of any file you want. 

Info:
```
Sentry 21.3.096d5172
```

**Comment by BYK** [comment]
@omidraha when I said "I'd" I was making a recommendation for _you_ to check them. Unfortunately I don't have the time to investigate individual 3rd-party plugins and their specific integrations.

**Comment by BYK** [comment]
Closing this out as it got stale. Right now we do not encourage writing new plugins but investing more into our [integration platform](https://docs.sentry.io/product/integrations/integration-platform/). Existing plugins should keep working.
