### ISSUE TITLE
Provide Sentry 10 on Dockerhub

### ISSUE THREAD

**Issue by max-wittig** [getsentry/onpremise#348]
Seems like we only got the `9` image tagged. Latest is `10.1.0-dev`. Would it be possible to also tag the stable 10 image?

https://hub.docker.com/_/sentry/

**Comment by max-wittig** [comment]
Sorry. My mistake. The correct link is at https://hub.docker.com/r/getsentry/sentry/tags

**Comment by BYK** [comment]
@max-wittig that page you linked uses the "official library" feature of Docker Hub which has a slightly different and slower process than publishing our own images directly. We are in conversations with Docker to see if we can keep using that with frequent updates hence we opted into using our own repository to keep everyone as updated as we can.

**Comment by max-wittig** [comment]
@BYK Thanks for the response! What I also noticed is that docker image version `10.0.0` of `getsentry/sentry` actually has the version hint `Sentry 10.1.0.dev0` in the UI. Any ideas why that is?

**Comment by BYK** [comment]
@max-wittig see #355 please. I've pushed new images that should fix the issue. If not, you can follow the progress over there.
