### ISSUE TITLE
Repetitive error message ConnectionError: SafeHTTPSConnectionPool(host='sentry.io', port=443): Max retries exceeded with url: /remote/beacon/

### ISSUE THREAD

**Issue by Tontonitch** [getsentry/onpremise#350]
Hello,
We have installed Sentry on a DMZ server and can see a repetitive message:
`Jan 15 16:26:34 xxxxxxxxxx journal: ConnectionError: SafeHTTPSConnectionPool(host='sentry.io', port=443): Max retries exceeded with url: /remote/beacon/ (Caused by NewConnectionError('<sentry.net.http.SafeHTTPSConnection object at 0x7f55d63d0050>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))`

This is normal to not be able to reach sentry.io as this server is not able to reach internet resources for security reason and DMZ security policies.

So, from what this error comes from, and how to disable that?

Note: Sentry 9.1.2

BR,
Yannick

**Comment by BYK** [comment]
Please see https://docs.sentry.io/server/beacon/.

**Comment by gamefundas** [comment]
I tried this on Sentry docker image by passing "-e SENTRY_BEACON=False" as the environment variable but still see this appearing in the logs of my worker container.

Anything I am missing.

**Comment by BYK** [comment]
@gamefundas 

>Anything I am missing.

Yup. `SENTRY_BEACON` is a setting you should set in the config file, not an environment variable you can pass. I'll try to clarify this on the docs.
