### ISSUE TITLE
Executing install.sh results in syntax error near unexpected token '>'

### ISSUE THREAD

**Issue by dducrest** [getsentry/onpremise#352]
Affects version: [dffd59723c05eb7a8a13f441a6cbb8b4e85fc437](https://github.com/getsentry/onpremise/blob/dffd59723c05eb7a8a13f441a6cbb8b4e85fc437/install.sh#L9
)

Running CentOS 7, this follow error occurs when running install.sh

```
sudo sh install.sh
install.sh: line 9: syntax error near unexpected token `>'
```

The code snippet references https://unix.stackexchange.com/questions/145651/using-exec-and-tee-to-redirect-logs-to-stdout-and-a-log-file-in-the-same-time/145654#145654

By removing the line, I'm able to install successfully.

**Comment by itpimp** [comment]
exec &> >(tee -a "$log_file")

should read 

exec &>>(tee -a "$log_file")

**Comment by BYK** [comment]
The install script is meant to be run with `/bin/bash` which is also indicated in its shebang: https://github.com/getsentry/onpremise/blob/dffd59723c05eb7a8a13f441a6cbb8b4e85fc437/install.sh#L1

This is not an issue we are going to try to fix as we don't intend to support running with `sh`.
