### ISSUE TITLE
Prevent installation on old AMD servers ?

### ISSUE THREAD

**Issue by Amphaal** [getsentry/onpremise#358]
Hi !

I tried to install Sentry on an small homeserver of mine, a kinda rusty HPE ProLiant MicroServer, runing a Turion II Neo N40L CPU. The issue here is that this CPU does not handle SSE 4.2 instructions, and thus cannot run a classic image of Clickhouse (https://clickhouse.yandex/docs/en/operations/requirements/).

Trying to install Sentry via ./install.sh in this context leads to confusing container errorlogs and timeouts during installation, which let you clueless on why the whole process failed...

As memory capacity is checked at script startup, can we also check if SSE 4.2 is handled ?

**Comment by BYK** [comment]
This is a good suggestion, I'll see if we can check this. Thanks!

**Comment by BYK** [comment]
Btw. if you are willing to give this a shot, be my guest please :)

**Comment by Amphaal** [comment]
There you go !
