### ISSUE TITLE
Sentry 10 support for helm community

### ISSUE THREAD

**Issue by ahmedspiir** [getsentry/onpremise#360]
Since Sentry 10 stable is out, do you plan to add support or push it to the helm chart 
https://github.com/helm/charts/tree/master/stable/sentry .
It's not obvious what the changes will be for the settings and if there is a migration guide that can be used.

Note: I understand that the chart is a community version and not officially supported by Sentry but it will be nice if you can offer some kind of guide or support to push Sentry 10 forward.

**Comment by BYK** [comment]
We are always open to helping the community. Regarding Helm charts, if there are any specific questions, we'd be happy to answer them. We just don't have the resources to drive or support the effort itself.

**Comment by BYK** [comment]
Also, I'll be closing this issue as this is more of an ongoing discussion which our forum is better-suited for: https://forum.sentry.io -- Let's create a topic there and continue the discussion.
