### ISSUE TITLE
[Sentry 9.1.2] cleanup command doesn't seem to clean anything

### ISSUE THREAD

**Issue by Rebolon** [getsentry/onpremise#367]
Hi,
yesterday my sentry was down because of no disk space left. In fact i can see that sentry takes a lot of space:
```
none             50G   42G  6.0G  88% /var/lib/docker/aufs/mnt/f202af0a50b4b767534696be9479365cdd1409f0498549d5832796e1b5eba0f9
none             50G   42G  6.0G  88% /var/lib/docker/aufs/mnt/607d4106a6675ce31eb2b3a39c9b78b9af02fab5e47ee755daa2288327766d0d
none             50G   42G  6.0G  88% /var/lib/docker/aufs/mnt/da318fbc0b51ec9ad2aab9dd359826dca8090248f77cd788ddb45c4e2966db25
none             50G   42G  6.0G  88% /var/lib/docker/aufs/mnt/bfeb1cac3424250f833d9ac24b2fb53bc5d79f5f95474fab584e50c0e24ffceb
none             50G   42G  6.0G  88% /var/lib/docker/aufs/mnt/71d613a0774b460aca590256ea4ae7ce9bce6a1235ceb199cbc814563a37977d
none             50G   42G  6.0G  88% /var/lib/docker/aufs/mnt/b408224e5eb052bedeafeac63d3a87df7a3f44c29b36f9a05a963568eac432b8
```

So i wanted to do a cleanup operation like described here :  https://docs.sentry.io/server/cli/cleanup/

```
docker exec -it onpremise_worker_1 bash
sentry cleanup
```

But the command is so long that i'm kicked by the remote shell. 
Is there a way to check why the command doesn't succeed to cleanup even after hours i launched it ?
Is there any other way to clean the database ?
I wish to keep my project stucture and the keys of them.

Thanks for help

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
