### ISSUE TITLE
set -e causes exit without reporting error

### ISSUE THREAD

**Issue by fvhockney** [getsentry/onpremise#370]
I just tried to install sentry on an (admittedly older) computer which turns out not to support sse4_2.

The code on line 66 of install.sh:
`SUPPORTS_SSE42=$(docker run --rm busybox grep -c sse4_2 /proc/cpuinfo)`
exits with an exit code that is not 0 when `grep -c` fails (that is to say when grep can not match any sse4_2 in /proc/cpuinfo). This means that the script will clean up because of the trap, but it will not output the error specified after the check in line 67 since the script aborts before that.

one possible solution I can suggest is to wrap the checking of sse4_2 support in a function:

```
function test_sse42 {
    SUPPORTS_SSE42=$(docker run --rm busybox grep -c -s sse4_2 /proc/cpuinfo || :)
    if (($SUPPORTS_SSE42 == 0)); then
        echo "FAIL: The CPU your machine is running on does not support the SSE 4.2 instruction set, which is required for one of the services Sentry uses (Clickhouse). See https://git.io/JvLDt for more info."
        return -1
    fi
    return 0
}
test_sse42
```
This will still let the error be displayed while exiting and cleaning up. Note the `|| :` in the subshell which sets the `SUPPORTS_SSE42` to 0 while preventing the subshell from throwing a non-zero exit code which would immediately abort. the function returning -1 then causes the set -e to trigger the trap.

**Comment by BYK** [comment]
@fvhockney, thanks for the detailed report! I like the `|| :` trick but not sure if we need to wrap this in its own function as it is a one-time check. What do you think?

Also, would you be interested in submitting a PR for this as you already proposed a pretty good solution?

**Comment by fvhockney** [comment]
I'm more than willing to submit a pull request. Although I agree we should figureout the best solution.

If we just write `$(... /proc/cpuinfo || :)` the subshell will then exit with an acceptable error code and the `if` statement will run and the program will `exit -1`. however, `cleanup` will not be called, meaning we would need to call it manually.

If we go the function route, we can `return -1` and thereby automatically call the `trap` and `cleanup`.

We could also look at modifying
```sh
cleanup () {
  if [ "$DID_CLEAN_UP" -eq 1 ]; then
    return 0;
  fi
  echo "Cleaning up..."
  $dc stop &> /dev/null
  DID_CLEAN_UP=1
}
trap cleanup ERR INT TERM
```

if we make `trap ... TERM EXIT` we can catch all exits. If you don't want to clean up on every exit then we would have to add an extra check in there to do an early return on specific exit codes. If we go this route it would be best to change all the `exit -1` to something like `exit 1` or something because `exit -1` doesn't do what you think (returns and exit status of 255 because of wrap around)

**Comment by fvhockney** [comment]
Although after looking closer it probably isn't required that the cleanup function run at that point since it just stops any running docker-compose commands, which aren't running yet (the only one ran at that point it is `docker-compose --version` which doesn't live)

**Comment by BYK** [comment]
I think we can remove the final, manual call to `cleanup` and add the `EXIT` to the `trap`. I remember doing that first and resorting back to this version because sometimes the trap was getting triggered twice. I don't remember why, wish I commented this.

Anyway, thanks for the fix, closing the issue! :)
