### ISSUE TITLE
Since upgrade to v10, github sso no longer works

### ISSUE THREAD

**Issue by dotconnor** [getsentry/onpremise#373]
After upgrading Github was complaining about the redirect url, before it was: `/extensions/github/setup/`, now Sentry appears to be using the `/auth/sso` route. After changing the URL in Github, I now get the following error:
```
Authentication error: You do not have access to the required GitHub organization.
```

Is there something I'm missing here?
I have all the `github-app.*` settings set in my `config.yml`

**Comment by BYK** [comment]
Sorry our docs are not in great shape regarding this.

https://github.com/getsentry/sentry-auth-github
>Afterwards, you will need to install the GitHub app on your organization.

Can you install the app for your org and try again?

We'll also get the docs fixed up very soon.

**Comment by dotconnor** [comment]
@BYK I had to add the permissions on that repo to the app, and then it worked.

**Comment by dotconnor** [comment]
@BYK Running into a new problem, not sure if it's related. All of my repos say disabled, both under the `Repositories` page and under the `Github Integration` page.

![Screen Shot 2020-02-03 at 6 42 12 PM](https://user-images.githubusercontent.com/14323370/73700620-024f5580-46b5-11ea-9b06-771ab3858b19.png)
![Screen Shot 2020-02-03 at 6 43 12 PM](https://user-images.githubusercontent.com/14323370/73700632-0bd8bd80-46b5-11ea-852e-cbd1f1adc6f3.png)

**Comment by BYK** [comment]
You may need to reinstall your GitHub App and refresh the permissions/

**Comment by dotconnor** [comment]
I uninstalled it from Github, and then reenabled but didn't remove from Sentry and that fixed things.

**Comment by fabiopedrosa** [comment]
@BYK You forgot to update the new redirect URL `/auth/sso`
