### ISSUE TITLE
Error while installing GeoIP

### ISSUE THREAD

**Issue by 4R9UN** [getsentry/onpremise#374]
C:\Windows\system32>pip install GeoIP==1.3.2
Collecting GeoIP==1.3.2
  Using cached https://files.pythonhosted.org/packages/f2/7b/a463b7c3df8ef4b9c92906da29ddc9e464d4045f00c475ad31cdb9a97aae/GeoIP-1.3.2.tar.gz
Building wheels for collected packages: GeoIP
  Building wheel for GeoIP (setup.py) ... error
  ERROR: Complete output from command 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\<USER_NAME>\\AppData\\Local\\Temp\\pip-install-cxgeimpc\\GeoIP\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\<USER_NAME>\AppData\Local\Temp\pip-wheel-yv8aewo1' --python-tag cp37:
  ERROR: C:\ProgramData\Anaconda3\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  Warning: 'classifiers' should be a list, got type 'tuple'
  running bdist_wheel
  running build
  running build_ext
  building 'GeoIP' extension
  creating build
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tcpy_GeoIP.c /Fobuild\temp.win-amd64-3.7\Release\py_GeoIP.obj
  py_GeoIP.c
  c:\programdata\anaconda3\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for GeoIP
  Running setup.py clean for GeoIP
Failed to build GeoIP
Installing collected packages: GeoIP
  Running setup.py install for GeoIP ... error
    ERROR: Complete output from command 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\<USER_NAME>\\AppData\\Local\\Temp\\pip-install-cxgeimpc\\GeoIP\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\<USER_NAME>\AppData\Local\Temp\pip-record-rt501z88\install-record.txt' --single-version-externally-managed --compile:
    ERROR: C:\ProgramData\Anaconda3\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Warning: 'classifiers' should be a list, got type 'tuple'
    running install
    running build
    running build_ext
    building 'GeoIP' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tcpy_GeoIP.c /Fobuild\temp.win-amd64-3.7\Release\py_GeoIP.obj
    py_GeoIP.c
    c:\programdata\anaconda3\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command "'C:\ProgramData\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\<USER_NAME>\\AppData\\Local\\Temp\\pip-install-cxgeimpc\\GeoIP\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\<USER_NAME>\AppData\Local\Temp\pip-record-rt501z88\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\<USER_NAME>\AppData\Local\Temp\pip-install-cxgeimpc\GeoIP\

**Comment by BYK** [comment]
This is not related to Sentry, please file the issue in the relevant repository.
