### ISSUE TITLE
Error with query

### ISSUE THREAD

**Issue by bellini666** [getsentry/onpremise#377]
I just upgraded my onpremise to the latest version and got this error:

https://sentry.zerosoft.com.br/share/issue/b1e4ece23b7147bfba157c23af9380f9/

Looking at the code I imagine this other one is related:

https://sentry.zerosoft.com.br/share/issue/c33acc3c0889498685b9fa9c53f93db1/

**Comment by BYK** [comment]
@bellini666 I'll be closing the issue if we cannot get more information as in its current state, this issue is not actionable.

**Comment by bellini666** [comment]
@BYK np, I didn't see the issue happen anymore so probably it is fixed atm?

**Comment by BYK** [comment]
@bellini666 glad to hear it seems to be resolved. I'm gonna close this issue then but please to file a new one if you have it again.
