### ISSUE TITLE
sentry.runner.importer.ConfigurationError: TypeError: unsupported operand type(s) for -: 'module' and 'str'

### ISSUE THREAD

**Issue by Lipathor** [getsentry/onpremise#38]
When i'm trying to run
`sudo docker-compose run --rm web upgrade`

I'm getting

> Traceback (most recent call last):
>   File "/usr/local/bin/sentry", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 158, in main
>     cli(prog_name=get_prog(), obj={}, max_content_width=100)
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
>     configure()
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 121, in configure
>     configure(ctx, py, yaml, skip_backend_validation)
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 153, in configure
>     }, skip_backend_validation=skip_backend_validation)
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 241, in initialize_app
>     bootstrap_options(settings, config['options'])
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 116, in bootstrap_options
>     from sentry.options import load_defaults
>   File "/usr/local/lib/python2.7/site-packages/sentry/options/__init__.py", line 10, in <module>
>     from .store import OptionsStore
>   File "/usr/local/lib/python2.7/site-packages/sentry/options/store.py", line 19, in <module>
>     from sentry.db.models.query import create_or_update
>   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/__init__.py", line 11, in <module>
>     from .base import *  # NOQA
>   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/base.py", line 14, in <module>
>     from django.db import models
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/__init__.py", line 5, in <module>
>     from django.db.models.query import Q
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 17, in <module>
>     from django.db.models.deletion import Collector
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 4, in <module>
>     from django.db.models import signals, sql
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/__init__.py", line 4, in <module>
>     from django.db.models.sql.subqueries import *
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 12, in <module>
>     from django.db.models.sql.query import Query
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 22, in <module>
>     from django.db.models.sql import aggregates as base_aggregates_module
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/aggregates.py", line 9, in <module>
>     ordinal_aggregate_field = IntegerField()
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 116, in __init__
>     self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
>   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
>     self._setup(name)
>   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
>     __import__(name)
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 52, in load_module
>     reraise_as(ConfigurationError(msg))
>   File "/usr/local/lib/python2.7/site-packages/sentry/utils/settings.py", line 48, in reraise_as
>     six.reraise(new_type, new_exception, e_traceback)
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 44, in load_module
>     mod = self._load_module(fullname)
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 76, in _load_module
>     load_settings(self.config_path, settings=settings_mod, silent=True)
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 90, in load_settings
>     six.exec_(source_file.read(), conf.__dict__)
>   File "/usr/local/lib/python2.7/site-packages/six.py", line 699, in exec_
>     exec("""exec _code_ in _globs_, _locs_""")
>   File "<string>", line 1, in <module>
>   File "<string>", line 65, in <module>
> sentry.runner.importer.ConfigurationError: TypeError: unsupported operand type(s) for -: 'module' and 'str'
>

**Comment by mattrobenolt** [comment]
This is definitely something wrong in your config. Mind sharing that? This would be for sure, coming out of your sentry.conf.py file.

**Comment by Lipathor** [comment]
@mattrobenolt  you are right, sorry for trouble.
