### ISSUE TITLE
Github Integration

### ISSUE THREAD

**Issue by DustinChaloupka** [getsentry/onpremise#385]
Using Sentry 10

Trying to set up `Github Integration` through the settings:
![image](https://user-images.githubusercontent.com/1587451/74272938-26beb980-4cd5-11ea-8bd2-456c6c943caf.png)
Clicking on the `Add Installation` button sends me to `https://github.com/apps/<name-of-github-app>` and then does nothing. Clicking on `Configure` sends me to the `Installed Github Apps` tab for the organization it is installed on.

Before trying to set this up, we did have the Github Auth configured, but we only had part of the configuration options set to get that to work (afterwards made sure all of the options were covered according to [the docs](https://docs.sentry.io/server/integrations/github/)). The `User authorization callback URL` was also set to `${urlPrefix}/auth/sso` instead of `${urlPrefix}/extensions/github/setup`. We have tried disabling the Github Auth and fixing the callback url, but that changed nothing except break trying to reconfigure the Github Auth because it was still sending the `redirect_uri` as `${urlPrefix}/auth/sso` instead of the new `${urlPrefix}/extensions/github/setup`. This was after setting up all of the configuration and restarting Sentry.

**Comment by BYK** [comment]
This should be fixed by getsentry/sentry#16332. If not, I'll reopen and investigate.
