### ISSUE TITLE
Error on cleanup images

### ISSUE THREAD

**Issue by meriturva** [getsentry/onpremise#386]
On a clean install on ubuntu I always get:

```
ERROR: for symbolicator-cleanup  Cannot start service symbolicator-cleanup: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown

ERROR: for snuba-cleanup  Cannot start service snuba-cleanup: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown

ERROR: for sentry-cleanup  Cannot start service sentry-cleanup: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown
```
could you please help us with how to solve the issue?

**Comment by meriturva** [comment]
Just to know...am I the only one with that issue? is it a problem of my configuration?

**Comment by BYK** [comment]
This seems to be an issue with your Docker setup so closing the issue. If you want to seek more help I recommend using StackOverflow for Docker or our [community forum](https://forum.sentry.io).

**Comment by meriturva** [comment]
I will give a try and comment here results.....thanks @BYK !

**Comment by meriturva** [comment]
Really simple just run:
`chmod +x entrypoint.sh` on cron directory

**Comment by BYK** [comment]
@meriturva that should not be necessary as the file is already marked as executable in git?

**Comment by meriturva** [comment]
That's correct but not on our internal mirroring process to the internal git server.
Our fault!
