### ISSUE TITLE
docker-compose run --rm web upgrade报错如下是什么原因

### ISSUE THREAD

**Issue by jianping888** [getsentry/onpremise#388]
Error: REDIS_PORT_6379_TCP_ADDR (or SENTRY_REDIS_HOST) is undefined, did you forget to `--link` a redis container?

**Comment by rhazdon** [comment]
Same issue here.

**Comment by rhazdon** [comment]
@jianping888 I solved the problem for me. Make sure that the config files config files are in the sentry dir **_before_** building the images. :)

**Comment by changtingQ** [comment]
i have same problem. have you sloved it ?

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for code-related issues.
