### ISSUE TITLE
Is git missing in the container? Error migrating with a plugin

### ISSUE THREAD

**Issue by viktorsmari** [getsentry/onpremise#389]
We have this plugin in `requirements.txt`
`git+https://github.com/getsentry/sentry-auth-github.git@master#egg=sentry-auth-github`

And upgrading from 9.1.2 to latest gives this error:

`./install.sh`

```bash
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting sentry-auth-github
  Cloning https://github.com/getsentry/sentry-auth-github.git (to revision master) to /tmp/pip-install-6z8Ze8/sentry-auth-github
  Running command git clone -q https://github.com/getsentry/sentry-auth-github.git /tmp/pip-install-6z8Ze8/sentry-auth-github
  ERROR: Error [Errno 2] No such file or directory while executing command git clone -q https://github.com/getsentry/sentry-auth-github.git /tmp/pip-install-6z8Ze8/sentry-auth-github
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Removing intermediate container 07d9c88ebe10
Service 'web' failed to build: The command '/bin/sh -c if [ -s requirements.txt ]; then pip install -r requirements.txt; fi' returned a non-zero code: 1
Cleaning up...
```
Is `git` missing in the container?

It can be fixed by adding
```
RUN apt update -y
RUN apt install -y git
```
in line 11 in the `sentry/Dockerfile`

But is that the right way?

**EDIT**
Just found out that https://github.com/getsentry/sentry-auth-github is deprecated.
I switched to using the [new way](https://docs.sentry.io/server/integrations/github/) by editing the `sentry/sentry.yml` file.

However, that is not working correctly for me atm, currently the `client_id` param that is sent to
`https://github.com/login/oauth/authorize?` is  empty.

**Comment by BYK** [comment]
Hi!

Yes, `git` does not exist in the image. You can use `https://github.com/getsentry/sentry-auth-github/archive/master.tar.gz#egg=sentry-auth-github` in the future if you need this again (you shouldn't but you can adapt this URL to other things).

Regarding your configuration question, please use the [community forum](https://forum.sentry.io).
