### ISSUE TITLE
sentry_onpremise_web_1 exited with code 1

### ISSUE THREAD

**Issue by rostyslavnikitin** [getsentry/onpremise#392]
**docker-compose ps**
sentry_onpremise_web_1                      /bin/sh -c exec $SENTRY_CO ...   **Restarting** 

web_1                     | 10:47:55 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
web_1                     | 10:47:59 [INFO] sentry.plugins.github: apps-not-configured
web_1                     | *** Starting uWSGI 2.0.18 (64bit) on [Tue Feb 25 10:47:59 2020] ***
web_1                     | compiled with version: 8.3.0 on 25 February 2020 10:20:12
web_1                     | os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
web_1                     | nodename: efc3da5720ca
web_1                     | machine: x86_64
web_1                     | clock source: unix
web_1                     | detected number of CPU cores: 4
web_1                     | current working directory: /usr/src/sentry
web_1                     | detected binary path: /usr/local/bin/uwsgi
web_1                     | !!! no internal routing support, rebuild with pcre support !!!
web_1                     | your memory page size is 4096 bytes
web_1                     | detected max file descriptor number: 1048576
web_1                     | lock engine: pthread robust mutexes
web_1                     | thunder lock: enabled
web_1                     | Python version: 2.7.16 (default, Oct 17 2019, 07:39:30)  [GCC 8.3.0]
web_1                     | Set PythonHome to /usr/local
web_1                     | Python main interpreter initialized at 0x55e5ca617050
web_1                     | python threads support enabled
web_1                     | The -s/--socket option is missing and stdin is not a socket.

**sentry_onpremise_web_1 exited with code 1**

**Comment by franckchateau** [comment]
Hello 
What was the problem? I have this problem on a EC2 instance

**Comment by rostyslavnikitin** [comment]
check the config files, cause in misconfiguration

**Comment by franckchateau** [comment]
ok thank you what was the reason in your case ?
I am using a config that was already working

**Comment by rostyslavnikitin** [comment]
I thought so too
