### ISSUE TITLE
Changing port after running install.sh

### ISSUE THREAD

**Issue by maximiliankaske** [getsentry/onpremise#395]
Hi there, I tried to install sentry on my web server with default port `9000`.  I then realised, that the port was already in use.. Thus, I changed the port in the config file `sentry/sentry.config.py` to ` 9001` as described in the docs and wanted to actually update the settings via:

`docker-compose down`
`docker-compose build`
`docker-compose up -d`

I still get the error
`Creating sentry_onpermise_web_1 ... error`
`Error starting user land proxy: listen tcp 0.0.0.0:9000: bind: address already in use`

Where is my mistake?

**Comment by anusoft** [comment]
check docker-compose.yml you'll need to change docker mapping port near this line

```
  web:
    << : *sentry_defaults
    ports:
      **- '9000:9000/tcp'**
```

**Comment by BYK** [comment]
Answered here: https://forum.sentry.io/t/changing-port-after-running-install-sh/8988/2
