### ISSUE TITLE
Upgrade 9.1.2 -> 10 fails (Kafka error) 

### ISSUE THREAD

**Issue by fbhdk** [getsentry/onpremise#402]
## Important Details

How are you running Sentry?

* [X] On-Premise docker [Version 10]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Ran into this bug: https://github.com/getsentry/sentry/issues/17422 
Now that it has been fixed thi shappens: 

  Applying sentry.0024_auto_20191230_2052...Events to process: 22961

```
06:54:05 [WARNING] sentry.eventstream.kafka.backend: Could not publish message (error: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Broker: Message size too large"}): <cimpl.Message object at 0x7fd6a4ab35d0>
06:54:05 [WARNING] sentry.eventstream.kafka.backend: Could not publish message (error: KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Broker: Message size too large"}): <cimpl.Message object at 0x7fd6a4ab35d0>
```

The same Kafka-error shows up many times and after quite a while it will continue: 
Event migration done. Migrated 22961 of 22961 events.

 - and then eventually finish migrations. 

## Steps to Reproduce

1. git checkout master --force
2. git pull
3. mv sentry/config.example.yml sentry/config.yml  (insert security key)
4. ./install.sh
5. Wait

There are no special configurations. Dataset is in an existing postgres 9.6 container. 

### What you expected to happen
No errors

### Possible Solution

Maybe some limits in terms of message size limit should be altered somewhere?

**Comment by BYK** [comment]
I'll increase this limit in the default configuration as @buffcode suggested over at https://github.com/getsentry/onpremise/issues/356#issuecomment-594203773

**Comment by BYK** [comment]
@buffcode - would you like to submit the PR yourself to get the credit for it? :)

**Comment by tm1000** [comment]
@BYK if we run into this issue (Message size too large) but just wait it out. Is everything ok? or should we re-run the migrations on a backup?

**Comment by fbhdk** [comment]
> @BYK if we run into this issue (Message size too large) but just wait it out. Is everything ok? or should we re-run the migrations on a backup?

If you wait it out the elements that are too large will not be migrated as far as I could tell.  I fixed the errors by modifying docker-compose.yml under the kafka service by adding the `KAFKA_MESSAGE_MAX_BYTES` environment variable.

**Comment by BYK** [comment]
Seems like we use 50MB for this in a few places, I wonder if we should apply it here:

```
KAFKA_MESSAGE_MAX_BYTES=50000000 #50MB or bust
KAFKA_MAX_REQUEST_SIZE=50000000 #50MB on requests apparently too
```

cc @mattrobenolt @JTCunning

**Comment by mattrobenolt** [comment]
Correct. I would.

**Comment by AkshayNarayan777** [comment]
Hi 
Can someone help me out on this sentry.eventstream.kafka.backend: Could not publish message (error: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out".
This error is shown in kafka container
Thanks
