### ISSUE TITLE
Sentry can not change the email config

### ISSUE THREAD

**Issue by nature1995** [getsentry/onpremise#404]
![image](https://user-images.githubusercontent.com/25950998/76041272-a2500700-5f1f-11ea-8bf7-ca896c6809a6.png)

I try different way which including the `docker-compose.yml` and `config.yml`. I can not change the config until now. How should I do for this situation.

sentry version 10

**Comment by cleathley** [comment]
you will have to do a;

```
docker-compose down
docker-compose build
docker-compose up -d
```

to rebuild the containers with the new settings in config.yml

(might need to also put a sudo in front of those commands)

You need to do this if you modify any of the settings (outside of the sentry admin) as these files are baked into the relevant container.

**Comment by nature1995** [comment]
Due to my problem, I don't add right mail backend. Some email provider (Tencent exmail) need to use SSL instead of TLS. So I need to add `mail.backend: 'django_smtp_ssl.SSLEmailBackend'` and  `mail.use-tls: false` in `config.yml`.

```
mail.backend: 'django_smtp_ssl.SSLEmailBackend'  # Use dummy if you want to disable email entirely
mail.host: 'hwsmtp.exmail.qq.com'
mail.port: 465
mail.username: 'example@email.com'
mail.password: 'password'
mail.use-tls: false
# The email address to send on behalf of
mail.from: 'example@email.com'
```

After that use the following command same as you:
```
docker-compose down
docker-compose build
docker-compose up -d
```

**Comment by zffocussss** [comment]
what is "mail.backend"?the default vaule is 'smtp'.

**Comment by nature1995** [comment]
> what is "mail.backend"?the default vaule is 'smtp'.

`mail.backend` is the backend which you use in your web application. e.g. smtp_ssl or smtp_tls.
