### ISSUE TITLE
 Service error 500

### ISSUE THREAD

**Issue by lizwxup** [getsentry/onpremise#406]
According to the instructions,I can view localhost:9000,but the Service error 500 

Unable to fetch all project stats

[
![1583899173(1)](https://user-images.githubusercontent.com/29390455/76381308-02b3ce00-6390-11ea-9704-14352083ff6f.png)
](url)

how to solve it?

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
