### ISSUE TITLE
Sentry web bind to localhost with docker

### ISSUE THREAD

**Issue by fayak** [getsentry/onpremise#410]
Hi !

I believe the `SENTRY_WEB_HOST` in `sentry.conf.py` does not behave exactly like I thought it would.
As I want to have sentry accessible only through my nginx, I chose to bind on `127.1`. However, as it runs in a docker container, it makes the web interface not accessible even on localhost.

What I had to do is to bind to `0.0.0.0` and edit the `docker-compose.yml:140` to tell docker to only bind the port 9000 to `127.0.0.1`, making sentry web accessible only on localhost.

It is a desirable behavior ? Am I missing something ?

Thanks

**Comment by BYK** [comment]
Yup, the docs here are a bit confusing and outdated. I'll update them to align with the on-premise setup while keeping the old meaning for stand-alone installs.

**Comment by windware-ono** [comment]
As of version 20.9.0, I had to change,

```
    nginx:
      << : *restart_policy
      ports:
        - '$SENTRY_BIND:80/tcp'
```
into
```
    nginx:
      << : *restart_policy
      ports:
        - '127.0.0.1:$SENTRY_BIND:80/tcp'
```

so, I can reverse proxy from an existing nginx while not exposing port 9000 publicly.

**Comment by KevinLeigh** [comment]
> As of version 20.9.0, I had to change,
> 
> ```
>     nginx:
>       << : *restart_policy
>       ports:
>         - '$SENTRY_BIND:80/tcp'
> ```
> 
> into
> 
> ```
>     nginx:
>       << : *restart_policy
>       ports:
>         - '127.0.0.1:$SENTRY_BIND:80/tcp'
> ```
> 
> so, I can reverse proxy from an existing nginx while not exposing port 9000 publicly.

Hey @windware-ono! Please could you provide the updates you made to your `ngnix.conf` to reverse proxy and not expose port 9000 publicly, that worked with the update you made in your above comment?

**Comment by BYK** [comment]
@KevinLeigh @windware-ono please keep this discussion over at [the forum](https://forum.sentry.io)
