### ISSUE TITLE
QueryExecutionError: [60] DB::Exception: Table default.sentry_local doesn't exist..

### ISSUE THREAD

**Issue by john1810** [getsentry/onpremise#413]
09:31:17 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/teams/sentry/sentry/members/' method=u'GET' ip_address=u'172.18.0.1')
172.18.0.1 - - [17/Mar/2020:09:31:17 +0000] "GET /api/0/teams/sentry/sentry/members/ HTTP/1.1" 200 2094 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
09:31:17 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://localhost:9000/api/0/organizations/sentry/projects/?statsPeriod=24h&query=id%3A1+id%3A2' method=u'GET' ip_address=u'172.18.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 89, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 196, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/organization_projects.py", line 126, in get
    paginator_cls=OffsetPaginator,
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 263, in paginate
    results = on_results(cursor_result.results)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/organization_projects.py", line 123, in <lambda>
    stats_period=stats_period,
  File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 35, in serialize
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/models/project.py", line 269, in get_attrs
    attrs = super(ProjectSummarySerializer, self).get_attrs(item_list, user)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/models/project.py", line 233, in get_attrs
    attrs = super(ProjectWithTeamSerializer, self).get_attrs(item_list, user)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/serializers/models/project.py", line 132, in get_attrs
    environment_ids=self.environment_id and [self.environment_id],
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 105, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/redissnuba.py", line 85, in method
    return getattr(self.backends[backend], key)(*a, **kw)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/snuba.py", line 354, in get_range
    group_on_time=True,
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/snuba.py", line 282, in get_data
    is_grouprelease=(model == TSDBModel.frequent_releases_by_group),
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 627, in query
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 532, in raw_query
    return bulk_raw_query([snuba_params], referrer=referrer)[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/snuba.py", line 584, in bulk_raw_query
    error["message"]
QueryExecutionError: [60] DB::Exception: Table default.sentry_local doesn't exist.. Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x30) [0x7dd0490]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x25) [0x3bf8a05]
2. /usr/bin/clickhouse-server(DB::Context::getTableImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Exception*) const+0x3fd) [0x6c6622d]
3. /usr/bin/clickhouse-server(DB::Context::getTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x81) [0x6c66421]
4. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x11d4) [0x6ccb5c4]
5. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x37) [0x6ccb757]
6. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x7e8) [0x6cdc9a8]
7. /usr/bin/clickhouse-server(DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum)+0x1b8) [0x6cac458]
8. /usr/bin/clickhouse-server() [0x6ddff55]
9. /usr/bin/clickhouse-server(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool)+0x74) [0x6de00e4]
10. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x8bd) [0x3c02dfd]
11. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x3c034cb]
12. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0x10) [0x77ab320]
13. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xed) [0x77aba3d]
14. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x7ecf1e1]
15. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x3c) [0x7eccf8c]
16. /usr/bin/clickhouse-server() [0xb8a2700]
17. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7efc36d0f6db]
18. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7efc3649688f]

172.18.0.1 - - [17/Mar/2020:09:31:17 +0000] "GET /api/0/organizations/sentry/projects/?statsPeriod=24h&query=id%3A1+id%3A2 HTTP/1.1" 500 702 "http://localhost:9000/organizations/sentry/projects/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

**Comment by lynnagara** [comment]
Did the install script run and exit successfully? It seems like the snuba bootstrap has not been successful

**Comment by john1810** [comment]
Thank you 













在 2020-03-19 02:48:23，"Lyn Nagara" <notifications@github.com> 写道：

Did the install script run and exit successfully? It seems like the snuba bootstrap has not been done
