### ISSUE TITLE
Install specific version (v8.13.0)

### ISSUE THREAD

**Issue by KaKi87** [getsentry/onpremise#415]
Hello,

My company currently runs Sentry through a tool called Rancher, which doesn't allows me to access the containers host, so I can't perform the upgrade procedure detailed in https://github.com/getsentry/docker-sentry/issues/83#issuecomment-233709532.

The only alternative I found is to install the same Docker image on a host that I can control, then copy the Postgres database from Rancher (I can do that with a "shell into container" feature, which is basically an UI implementation of `docker exec -it <containerId> bash` and finally perform the upgrade procedure.

Unfortunately, the [install.sh](https://github.com/getsentry/onpremise/blob/master/install.sh) script will forcibly install the latest version of Sentry.

How can I make it install Sentry using the specific 8.13.0 version ?

Thanks

PS : I already tried the export/import feature but [it didn't worked](https://forum.sentry.io/t/cannot-migrate-from-8-x-to-10-x-using-export-import/9183).

**Comment by BYK** [comment]
[On the README](https://github.com/getsentry/onpremise#versioning) we document the `SENTRY_IMAGE` environment variable that you can use when running `./install.sh` but I don't think the current setup would work with a very old version like `8.13.0`. I'd first try going to 9.1.2 (check out this tag https://github.com/getsentry/onpremise/tree/9.1.2), upgrading to that, and then using the latest from this repo.

Does that help?

**Comment by BYK** [comment]
Closing due to lack of response.
