### ISSUE TITLE
v9.1.2 has a problem related to PostgreSQL

### ISSUE THREAD

**Issue by tamonmon0417** [getsentry/onpremise#417]
Installing v9.1.2 shows error; `django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known`
which is related to docker image of PostgreSQL.
The reason is PostgreSQL had an update.

**Comment by PhillWide** [comment]
I might have encountered the same issue. Using the latest master solved it for me.

**Comment by otsuka-kentaro** [comment]
@tamonmon0417 
I have solved this issue.
`postgres:9.5` has been version up `9.5.21`. This version needs environment variable for security reason (I think). [docker hub](https://hub.docker.com/_/postgres)

Here is my solution. Just fix postgres version, `postgres:9.5.19`

```bash
$ vi docker-compose.yml # fix postgres version 9.5.19 at line 45

$ git diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 18cee6a..cf05a59 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -42,7 +42,7 @@ services:

   postgres:
     restart: unless-stopped
-    image: postgres:9.5
+    image: postgres:9.5.19
     volumes:
       - sentry-postgres:/var/lib/postgresql/data
```

**Comment by tamonmon0417** [comment]
Thanks @otsuka-kentaro 
I'm still investigating about it in terms of rollback.
When rolling back to v9.1.2, image: postgres:9.5.19 doesn't work.
Same error as this topic is caused.

**Comment by BYK** [comment]
This should be a networking issue with your setup. Can you provide more logs from your `docker-compose`?

**Comment by BYK** [comment]
Closing due to lack of response.
