### ISSUE TITLE
Config permissions: !! Configuration error: `system.secret-key` MUST be set.

### ISSUE THREAD

**Issue by PhillWide** [getsentry/onpremise#418]
## Important Details
UPDATED after I figured out the actual issue

I'm running the Docker on-premise commit a7c5a32e36282f513e6dd5f9461f50114cb0597d

## Description

I get the error in issue name if I rewrite the config file with permissions 640 instead of 644.

## Steps to Reproduce

1. ./install.sh
2. change permissions for the config
3. ./install.sh

### What you expected to happen

I'm not really sure why it requires the permissions but at least it would be nice to get correct error.
Additionally it would be nice if the install added the secret key when system.secret-key is not specified at all instead of only with !!changeme!!.

**Comment by stayallive** [comment]
You need to do it the other way around, it looks like you ran `./install.sh` before modifying the `config.yml`, the install script builds docker images and copies the configuration into them. So to update the config you need to re-run `install.sh` to activate those changes.

**Comment by PhillWide** [comment]
Thanks! I must have been the combination of handling the installation as before with the new script.

**Comment by PhillWide** [comment]
Ah, the issue returns if I use CI=yes which I need for my ansible.

**Comment by PhillWide** [comment]
I had to remove the configs and cleanup docker cache to fix the issue

**Comment by PhillWide** [comment]
Ok, so it ended up being a permissions issue: for some reason, I need 644 permissions for the configuration file
