### ISSUE TITLE
Source installation

### ISSUE THREAD

**Issue by azmeuk** [getsentry/onpremise#431]
I can remember a time where installing sentry from sources was supported. But today I cannot find any documentation to achieve this. There are some case where avoiding docker is interesting (old distributions, FreeBSD or unpowerful machines).

If the support is really dropped, maybe it worth mentioning it somewhere (in a README or a FAQ) ?

What do you think?

[related comment](https://aur.archlinux.org/packages/sentry/?setlang=hr&O=60&PP=10#pinned-725205) on archlinux sentry AUR package

**Comment by BYK** [comment]
Closing due to lack of response.
