### ISSUE TITLE
upgrade clickhouse to fix high iowait issue

### ISSUE THREAD

**Issue by link89** [getsentry/onpremise#433]
Hi, we have deployed sentry 10 with clickhouse 19.11 in a single node and find that the iowait would be very high from time to time. 
After an investigation we find out it is problem of clickhouse.
According to this https://github.com/ClickHouse/ClickHouse/issues/6372 that upgrade clickhouse may have great help.
Do you know which version of clickhouse should we use now?

**Comment by BYK** [comment]
Seems like this is what we are using: `19.17.4.11`. Would you like to submit a PR to this repo and update the version to that?
