### ISSUE TITLE
Problem when uploading dsym files

### ISSUE THREAD

**Issue by kh0r** [getsentry/onpremise#44]
I get an error when I upload the generated dsym files of an iOS project with cli tool:
`sentry-cli upload-dsym -o __team__ -p __project__ ./__Project__.app.dSYM.zip`
The output is
```
Batch 1
[1/3] Found 28 debug symbol files. Checking for missing symbols on server
[2/3] Compressing 28 missing debug symbol files
[3/3] Uploading debug symbol files
error: http error: generic error (502)
```

The server side log output with `docker-compose logs -f web` is:
```
web_1        | Invalid (too big) CONTENT_LENGTH. skip.
web_1        | 172.18.0.1 - - [19/Jun/2017:16:20:54 +0000] "POST /api/0/projects/__team__/__project__/files/dsyms/ HTTP/1.0" 500 0 "-" "-"
```

Any idea whats happening here?

**Comment by mattrobenolt** [comment]
How large is the zip file you're trying to upload?

**Comment by kh0r** [comment]
The zip file is 31.6 MB

**Comment by raphaelm** [comment]
The following fixed the issue for us:
```
--- a/sentry.conf.py
+++ b/sentry.conf.py
@@ -247,6 +247,7 @@ SENTRY_WEB_HOST = '0.0.0.0'
 SENTRY_WEB_PORT = 9000
 SENTRY_WEB_OPTIONS = {
     # 'workers': 3,  # the number of web workers
+    'limit-post': 1024 * 1024 * 1024 * 2
 }
```

**Comment by BYK** [comment]
Closing per the comment above (that said 2 GB file uploads are quite huge, unlikely, and probably not very safe).

**Comment by TimoDJatomika** [comment]
Would be nice to set thous value via ENV
