### ISSUE TITLE
Outgoing connection

### ISSUE THREAD

**Issue by xpoinsard** [getsentry/onpremise#441]
I am using Sentry 10.1.0.dev028e739b.
Every hour there is an outgoing connection attempt to IP 35.188.42.15 on port 443 that is failing because of our firewall/proxy.
Is there a way to configure Sentry to use a proxy for this outgoing connection ?

**Comment by BYK** [comment]
This is our beacon: https://docs.sentry.io/server/beacon/

I think you can use the standard `HTTP_PROXY` and `HTTPS_PROXY` environment variables for this. If that doesn't work for you, you can also disable the beacon as explained on the docs.

**Comment by xpoinsard** [comment]
I tried setting HTTP_PROXY and HTTPS_PROXY but without success. Maybe it doesn't reach sentry inside the docker.

**Comment by BYK** [comment]
Yup, you'd need to pass these to the containers. You should be able to use the `.env` file in the repo.
