### ISSUE TITLE
Snuba fails silently

### ISSUE THREAD

**Issue by max-wittig** [getsentry/onpremise#444]
Sentry still seems to work, but snuba doesn't since 
* getsenty/snuba: 6f20e6e195dfe40664e4e5a1628d2c82a2936a37

```
snuba-consumer_1           | 2020-04-24 12:38:33,070 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 7198}
snuba-consumer_1           | Traceback (most recent call last):
snuba-consumer_1           |   File "/usr/local/bin/snuba", line 11, in <module>
snuba-consumer_1           |     load_entry_point('snuba', 'console_scripts', 'snuba')()
snuba-consumer_1           |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
snuba-consumer_1           |     return self.main(*args, **kwargs)
snuba-consumer_1           |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
snuba-consumer_1           |     rv = self.invoke(ctx)
snuba-consumer_1           |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
snuba-consumer_1           |     return _process_result(sub_ctx.command.invoke(sub_ctx))
snuba-consumer_1           |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
snuba-consumer_1           |     return ctx.invoke(self.callback, **ctx.params)
snuba-consumer_1           |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
snuba-consumer_1           |     return callback(*args, **kwargs)
snuba-consumer_1           |   File "/usr/src/snuba/snuba/cli/consumer.py", line 156, in consumer
snuba-consumer_1           |     consumer.run()
snuba-consumer_1           |   File "/usr/src/snuba/snuba/utils/streams/batching.py", line 137, in run
snuba-consumer_1           |     self._run_once()
snuba-consumer_1           |   File "/usr/src/snuba/snuba/utils/streams/batching.py", line 145, in _run_once
snuba-consumer_1           |     msg = self.consumer.poll(timeout=1.0)
snuba-consumer_1           |   File "/usr/src/snuba/snuba/utils/streams/kafka.py", line 688, in poll
snuba-consumer_1           |     return super().poll(timeout)
snuba-consumer_1           |   File "/usr/src/snuba/snuba/utils/streams/kafka.py", line 402, in poll
snuba-consumer_1           |     raise ConsumerError(str(error))
snuba.utils.streams.consumer.ConsumerError: KafkaError{code=OFFSET_OUT_OF_RANGE,val=1,str="Broker: Offset out of range"}
```

Any ideas?

**Comment by BYK** [comment]
That commit seems quite old, can you try pulling a newer version of this repo and Snuba image and see if it fixes this?

**Comment by saubi1993** [comment]
Same happening or me too, I had set up sentry on-premise last month only with the latest images.
`05/05/2020 04:59:59+ '[' r = - ']'
05/05/2020 04:59:59+ snuba replacer --help
05/05/2020 05:00:01+ set -- snuba replacer --auto-offset-reset=latest --max-batch-size 3
05/05/2020 05:00:01+ set gosu snuba snuba replacer --auto-offset-reset=latest --max-batch-size 3
05/05/2020 05:00:01+ exec gosu snuba snuba replacer --auto-offset-reset=latest --max-batch-size 3
05/05/2020 05:00:092020-05-05 03:00:09,237 New partitions assigned: {Partition(topic=Topic(name='event-replacements'), index=0): 1}
05/05/2020 05:00:09Traceback (most recent call last):
05/05/2020 05:00:09  File "/usr/local/bin/snuba", line 11, in <module>
05/05/2020 05:00:09    load_entry_point('snuba', 'console_scripts', 'snuba')()
05/05/2020 05:00:09  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
05/05/2020 05:00:09    return self.main(*args, **kwargs)
05/05/2020 05:00:09  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
05/05/2020 05:00:09    rv = self.invoke(ctx)
05/05/2020 05:00:09  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
05/05/2020 05:00:09    return _process_result(sub_ctx.command.invoke(sub_ctx))
05/05/2020 05:00:09  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
05/05/2020 05:00:09    return ctx.invoke(self.callback, **ctx.params)
05/05/2020 05:00:09  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
05/05/2020 05:00:09    return callback(*args, **kwargs)
05/05/2020 05:00:09  File "/usr/src/snuba/snuba/cli/replacer.py", line 170, in replacer
05/05/2020 05:00:09    replacer.run()
05/05/2020 05:00:09  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 137, in run
05/05/2020 05:00:09    self._run_once()
05/05/2020 05:00:09  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 145, in _run_once
05/05/2020 05:00:09    msg = self.consumer.poll(timeout=1.0)
05/05/2020 05:00:09  File "/usr/src/snuba/snuba/utils/streams/kafka.py", line 402, in poll
05/05/2020 05:00:09    raise ConsumerError(str(error))
05/05/2020 05:00:09snuba.utils.streams.consumer.ConsumerError: KafkaError{code=OFFSET_OUT_OF_RANGE,val=1,str="Broker: Offset out of range"}
`

**Comment by BYK** [comment]
Could this be Kafka running out of space and deleting some old messages? How is your load and resources?

**Comment by max-wittig** [comment]
I solved it by deleting all kafka and zookeeper data.

**Comment by BYK** [comment]
@max-wittig sounds like less-than ideal solution but glad you were able to move forward.

Closing as the issue seems to be resolved, albeit in a not in a great way.
