### ISSUE TITLE
CSRF failures after Nginx introduction

### ISSUE THREAD

**Issue by giggsey** [getsentry/onpremise#447]
Recently updated my install, and I've had CSRF failures.

I believe the problem is the nginx relay in https://github.com/getsentry/onpremise/blob/master/nginx/nginx.conf#L44 (introduced in #421) is not passing the original Host header (at least that fixed it locally for me).

Log line from web:

> 16:46:05 [WARNING] django.security.csrf: Forbidden (Referer checking failed - https://sentry.example.com/auth/login/org/ does not match any trusted origins.): /auth/login/org/ (status_code=403 request=<WSGIRequest: POST u'/auth/login/org/'>)

**Comment by giggsey** [comment]
It's missing the proxy_set_header from https://github.com/getsentry/sentry/pull/18433/files#diff-3194b88002aeabc2a7b45a1640d0869bR50

**Comment by mlaradji** [comment]
Thanks @giggsey. I confirm that after adding the `proxy_set_header`  [line](https://github.com/getsentry/sentry/blob/36e9585c366d2e13e8f6c0210c5b8cbec9207a33/config/reverse_proxy/nginx.conf#L50) from sentry, the CSRF failure disappeared for me.

**Comment by sdwerwed** [comment]
`proxy_set_header $http_host ` worked for me
