### ISSUE TITLE
can`t logged in always redirect to /auth/login/sentry/

### ISSUE THREAD

**Issue by smilemakc** [getsentry/onpremise#451]
can`t logged in, always redirect to /auth/login/sentry/

new clean installation from repo

existing superuser 

```
web_1                      | 172.18.0.38 - - [27/Apr/2020:15:23:39 +0000] "GET / HTTP/1.0" 302 446 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
nginx_1                    | 172.18.0.2 - - [27/Apr/2020:15:23:39 +0000] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
nginx_1                    | 172.18.0.2 - - [27/Apr/2020:15:23:39 +0000] "GET /auth/login/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
web_1                      | 172.18.0.38 - - [27/Apr/2020:15:23:39 +0000] "GET /auth/login/ HTTP/1.0" 302 564 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
nginx_1                    | 172.18.0.2 - - [27/Apr/2020:15:23:39 +0000] "GET /auth/login/sentry/ HTTP/1.1" 200 4033 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
web_1                      | 172.18.0.38 - - [27/Apr/2020:15:23:39 +0000] "GET /auth/login/sentry/ HTTP/1.0" 200 10864 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"

web_1                      | 15:23:45 [INFO] sentry.superuser: superuser.logged-in (user_id=1 ip_address=u'172.18.0.2')
web_1                      | 15:23:45 [INFO] sentry.auth: user.auth.success (username=u'user@gmail.com' organization_id=1L ip_address=u'172.18.0.2')

web_1                      | 172.18.0.38 - - [27/Apr/2020:15:23:45 +0000] "POST /auth/login/sentry/ HTTP/1.0" 302 1188 "https://sentry.hub.some.ru/auth/login/sentry/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
nginx_1                    | 172.18.0.2 - - [27/Apr/2020:15:23:45 +0000] "POST /auth/login/sentry/ HTTP/1.1" 302 0 "https://sentry.hub.some.ru/auth/login/sentry/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
nginx_1                    | 172.18.0.2 - - [27/Apr/2020:15:23:45 +0000] "GET / HTTP/1.1" 302 0 "https://sentry.hub.some.ru/auth/login/sentry/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
web_1                      | 172.18.0.38 - - [27/Apr/2020:15:23:45 +0000] "GET / HTTP/1.0" 302 522 "https://sentry.hub.some.ru/auth/login/sentry/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
nginx_1                    | 172.18.0.2 - - [27/Apr/2020:15:23:45 +0000] "GET /auth/login/ HTTP/1.1" 302 0 "https://sentry.hub.some.ru/auth/login/sentry/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
web_1                      | 172.18.0.38 - - [27/Apr/2020:15:23:45 +0000] "GET /auth/login/ HTTP/1.0" 302 564 "https://sentry.hub.some.ru/auth/login/sentry/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
nginx_1                    | 172.18.0.2 - - [27/Apr/2020:15:23:45 +0000] "GET /auth/login/sentry/ HTTP/1.1" 200 4032 "https://sentry.hub.some.ru/auth/login/sentry/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
web_1                      | 172.18.0.38 - - [27/Apr/2020:15:23:45 +0000] "GET /auth/login/sentry/ HTTP/1.0" 200 10864 "https://sentry.hub.some.ru/auth/login/sentry/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
```

sometimes has warning message

`Your session has expired.`

**Comment by gencer** [comment]
Interestingly, I had the same problem today. Even, `createuser` command also failed. (even forcefully)

But I was able to login in the end. Just click "Forgot my password" then send yourself a reset link. Resetting your password will make you auto-login.

Not a good solution but hopefully a workaround for now.

**Comment by BYK** [comment]
It says auth successful so I suspect some cookie setting issue. I see that you are using Safari. Does this happen with all browsers? (then I'll look into Nginx)

**Comment by BYK** [comment]
I think this will be fixed by #463 too.

**Comment by gencer** [comment]
@BYK. On my case, I suspect neither from nginx nor browser. I already used my own nginx config file since years (I think its from Sentry 8) and i also disabled `nginx` from `docker-compose.yml` as im using a custom environment and directly connected to docker service. What I am suspecting is that at first initial user creation either:

 **a.** password does contains an invalid character and console is unable to transform and hash it. So login failed there.
 **b.** password is hashed wrongly for other reasons or completely skipped...

Because, When I reset my password with same config and same environment, this time i gave alpha-numeric, I am able to login or logout & login back. It is indeed neither nginx nor cookie problem. Otherwise, When i logged out, i couldn't login back.

Just my thoughts. Could be completely a different thing. In both cases, same error occured on my end and am able to login via password reset mechanism.

**Comment by BYK** [comment]
@gencer I'd blame the terminal entry as the hashing cannot be different (they use the same code path).

Regarding having your own Nginx instance, it's fine as long as you do the necessary redirections to the Relay service now as otherwise event ingestion will stop soon and you'll have a bad time.

**Comment by gencer** [comment]
You're right on that. Because, in the past, I have faced similar issues with docker being emit some special characters on my terminal. This could be local or based on server configuration.

Ah, yes! I already did those changes of course. With every new version of Sentry, I follow templates and adapt my code to it. No problem so far. Thanks for the tip!

**Comment by BYK** [comment]
This should be fixed by #463 so closing.

**Comment by smilemakc** [comment]
tried today with a clean install, the problem is not solved

**Comment by BYK** [comment]
@smilemakc please file a new issue with all the details requested (log outputs specifically). Locking this issue as the original issue is resolved.
