### ISSUE TITLE
 ERROR: relay has no credentials, which are required in managed mode. Generate some with "relay credentials generate" first

### ISSUE THREAD

**Issue by yuanzhian** [getsentry/onpremise#453]
ERROR: relay has no credentials, which are required in managed mode. Generate some with "relay credentials generate" first

**Comment by yuanzhian** [comment]
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                      PORTS                          NAMES
08471b560aa4        sentry-cleanup-onpremise-local         "/entrypoint.sh '0 0…"   14 seconds ago      Up 13 seconds               9000/tcp                       sentry_onpremise_sentry-cleanup_1
7c35b134fe11        sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   20 seconds ago      Up 19 seconds               9000/tcp                       sentry_onpremise_worker_1
75a93e5c13dd        sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   21 seconds ago      Up 20 seconds               9000/tcp                       sentry_onpremise_ingest-consumer_1
4d04bca9fb85        sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   22 seconds ago      Up 21 seconds               9000/tcp                       sentry_onpremise_cron_1
3dd3c3be866e        nginx:1.16                             "nginx -g 'daemon of…"   22 seconds ago      Exited (1) 21 seconds ago                                  sentry_onpremise_nginx_1
dbeb245d0099        sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   23 seconds ago      Up 22 seconds               9000/tcp                       sentry_onpremise_web_1
8416236ed6a4        sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   24 seconds ago      Up 23 seconds               9000/tcp                       sentry_onpremise_post-process-forwarder_1
394c84659bc4        getsentry/relay:latest                 "/bin/bash /docker-e…"   24 seconds ago      Exited (1) 23 seconds ago                                  sentry_onpremise_relay_1
73cc2bf52c9d        snuba-cleanup-onpremise-local          "/entrypoint.sh '*/5…"   16 minutes ago      Up 16 minutes               1218/tcp                       sentry_onpremise_snuba-cleanup_1
c8185e13180a        symbolicator-cleanup-onpremise-local   "/entrypoint.sh '55 …"   16 minutes ago      Up 16 minutes               3021/tcp                       sentry_onpremise_symbolicator-cleanup_1
61104d755e5c        getsentry/snuba:latest                 "./docker_entrypoint…"   17 minutes ago      Up 17 minutes               1218/tcp                       sentry_onpremise_snuba-outcomes-consumer_1
616d1faba552        getsentry/snuba:latest                 "./docker_entrypoint…"   17 minutes ago      Up 17 minutes               1218/tcp                       sentry_onpremise_snuba-consumer_1
235691dfacd1        getsentry/snuba:latest                 "./docker_entrypoint…"   17 minutes ago      Up 17 minutes               1218/tcp                       sentry_onpremise_snuba-api_1
a748f80e6db3        getsentry/snuba:latest                 "./docker_entrypoint…"   17 minutes ago      Up 17 minutes               1218/tcp                       sentry_onpremise_snuba-replacer_1
c2181de5957e        confluentinc/cp-kafka:5.1.2            "/etc/confluent/dock…"   17 minutes ago      Up 17 minutes               9092/tcp                       sentry_onpremise_kafka_1
8036fc905201        confluentinc/cp-zookeeper:5.1.2        "/etc/confluent/dock…"   17 minutes ago      Up 17 minutes               2181/tcp, 2888/tcp, 3888/tcp   sentry_onpremise_zookeeper_1
923a7cb478dc        memcached:1.5-alpine                   "docker-entrypoint.s…"   17 minutes ago      Up 17 minutes               11211/tcp                      sentry_onpremise_memcached_1
5f9519ea2c5e        getsentry/symbolicator:latest          "/bin/bash /docker-e…"   17 minutes ago      Up 17 minutes               3021/tcp                       sentry_onpremise_symbolicator_1
f4790d7deaf8        redis:5.0-alpine                       "docker-entrypoint.s…"   17 minutes ago      Up 17 minutes               6379/tcp                       sentry_onpremise_redis_1
cfdeff650927        postgres:9.6                           "docker-entrypoint.s…"   17 minutes ago      Up 17 minutes               5432/tcp                       sentry_onpremise_postgres_1
7493503ce104        yandex/clickhouse-server:19.11         "/entrypoint.sh"         17 minutes ago      Up 17 minutes               8123/tcp, 9000/tcp, 9009/tcp   sentry_onpremise_clickhouse_1
c3e865716761        tianon/exim4                           "docker-entrypoint.s…"   17 minutes ago      Up 17 minutes               25/tcp                         sentry_onpremise_smtp_1
yuanzhian@yuanzhiandeMacBook-Pro onpremise % docker logs 394c84659bc4 
2020-04-28T02:45:52Z [relay::setup] INFO: launching relay from config folder /etc/relay
2020-04-28T02:45:52Z [relay::setup] INFO:   relay mode: managed
2020-04-28T02:45:52Z [relay::setup] INFO:   relay id: -
2020-04-28T02:45:52Z [relay::setup] INFO:   public key: -
2020-04-28T02:45:52Z [relay::setup] INFO:   log level: INFO
2020-04-28T02:45:52Z [relay::cli] ERROR: relay has no credentials, which are required in managed mode. Generate some with "relay credentials generate" first.

**Comment by BYK** [comment]
Fixed by #450.
