### ISSUE TITLE
lost  overview  data

### ISSUE THREAD

**Issue by jiazhonglin** [getsentry/onpremise#454]
HELP!
I`m upgrading  sentry  9.0-->9.1.2
I run those command:
```
docker-compose down
docker-compose build --pull
docker-compose run --rm web upgrade
docker-compose up -d
```
then,  I lost my   data.
![image](https://user-images.githubusercontent.com/15116568/80445966-1d460480-8948-11ea-9577-3344a348481b.png)
this  is   my config :
![image](https://user-images.githubusercontent.com/15116568/80446161-ac531c80-8948-11ea-8570-5f703f9dabbd.png)

**Comment by BYK** [comment]
I think you just lost statistics which I suspect is due to `redis` not persisting its data. This is fixed in newer versions of this repo but for that data, I don't think you can bring it back.

Closing as this is related to a very old version and won't get any updates.
