### ISSUE TITLE
not receiving events from client after crash and restart

### ISSUE THREAD

**Issue by jeffguorg** [getsentry/onpremise#458]
hi,

we started a sentry instance but it crashed under high load days ago. and after i restart the services, sentry no longer receive events. i tried to clear the queue or even flush redis db but none of these actions works.

i can see http api is receiving requests, and the worker is preprocessing events, but i cannot see any events in project issue lists.

```
$ docker-compose logs -f --tail=100 worker web
......
web_1                     | 06:26:02 [DEBUG] sentry.api: New event received (ec9aab05de3f4505ac33ea7a80068979)
worker_1                  | 06:26:02 [DEBUG] celery.worker.job: Task accepted: sentry.tasks.store.preprocess_event[63fcac03-4502-49d9-a358-6271d21eff4f] pid:20
web_1                     | 58.215.175.57 - - [30/Apr/2020:06:26:02 +0000] "POST /api/5/store/ HTTP/1.1" 200 708 "-" "sentry-java/1.7.16-9b60b"
worker_1                  | 06:26:02 [INFO] celery.worker.job: Task sentry.tasks.store.preprocess_event[63fcac03-4502-49d9-a358-6271d21eff4f] succeeded in 0.0153253870085s: None
```
there is more log output here:
- sentry worker: https://www.jianguoyun.com/p/DRdfZUUQ8MzNBhjEpJQD
- sentry web: https://www.jianguoyun.com/p/DbS5x84Q8MzNBhjYpJQD

where should we start to diagnose?

**Comment by jeffguorg** [comment]
ok.... i found that snuba consumer is not responding. nor does it exit after receiving interrupt signal. i have to kill -9.

maybe docker has also crashed or it was just snuba that has crashed. 

but my new problem is why a search module failure may lead to whole system failure?

**Comment by BYK** [comment]
Snuba and Clickhouse are the datastore powering all the event data so it makes sense that when they go down, you cannot receive (or at least process) new events.

Can you see the Snuba logs for diagnosis?

**Comment by jeffguorg** [comment]
@BYK Hi

thanks. but i didn't realize that snuba went down and i was furious for i could not find the problem. thus i just recreated the whole docker-compose cluster and the logs were lost.

and i tried to reproduce the situation but failed. i think it is docker's bug. not sentry's. maybe i could provide more information next time.

**Comment by BYK** [comment]
>thanks. but i didn't realize that snuba went down and i was furious for i could not find the problem. thus i just recreated the whole docker-compose cluster and the logs were lost.

Heh, that's a strong rage quit/rebuild 😀 Snuba may have bugs itself so next time if you can share some logs via `docker-compose logs`, we may be able to diagnose the issue.

If you need monitoring, Snuba and Sentry comes with a built-in Dogstatsd plugin for uWSGI: https://github.com/DataDog/uwsgi-dogstatsd

You may also customize the images a bit or implement some monitoring around Docker/Compose.
