### ISSUE TITLE
* Unknown config option found: 'transaction-events.force-disable-internal-project' * Unknown config option found: 'releasefile.cache-path' !! Configuration error: sentry.search service failed to call validate() 'module' object has no attribute 'EventsDatasetSnubaSearchBackend'

### ISSUE THREAD

**Issue by yuanzhian** [getsentry/onpremise#460]
* Unknown config option found: 'transaction-events.force-disable-internal-project'
* Unknown config option found: 'releasefile.cache-path'
!! Configuration error: sentry.search service failed to call validate()
'module' object has no attribute 'EventsDatasetSnubaSearchBackend'

**Comment by BYK** [comment]
Which version of Sentry are you trying to use?

**Comment by yuanzhian** [comment]
> Which version of Sentry are you trying to use?

newest

**Comment by yuanzhian** [comment]
05:41:05 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
05:41:11 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'transaction-events.force-disable-internal-project'
* Unknown config option found: 'releasefile.cache-path'
!! Configuration error: sentry.search service failed to call validate()
'module' object has no attribute 'EventsDatasetSnubaSearchBackend'

**Comment by BYK** [comment]
Unfortunately "newest" is not a version number. You need to provide more details around how you are trying to install and also share the full install logs for us to be able to help you.

**Comment by yuanzhian** [comment]
> Unfortunately "newest" is not a version number. You need to provide more details around how you are trying to install and also share the full install logs for us to be able to help you.

How can I check the version number？

**Comment by BYK** [comment]
@yuanzhian you can just share the install logs that are automatically saved when you run `./install.sh`. Also sharing the value of `SENTRY_IMAGE` env variable if you have set it would be very helpful.

**Comment by yuanzhian** [comment]
> @yuanzhian you can just share the install logs that are automatically saved when you run `./install.sh`. Also sharing the value of `SENTRY_IMAGE` env variable if you have set it would be very helpful.

sentry:10

**Comment by BYK** [comment]
Okay, can you try removing the `SENTRY_IMAGE` variable to get the latest Sentry image and then try with that? You'd need to run `./install.sh` again once you remove it.

**Comment by BYK** [comment]
Closing due to lack of response.

**Comment by idchlife** [comment]
@BYK 

centos 7

Steps ro reproduce:

- git clone this repo
- ./install.sh

```bash
Setting up database...
Creating sentry_onpremise_smtp_1 ...
Starting sentry_onpremise_zookeeper_1 ...
Starting sentry_onpremise_zookeeper_1 ... done
Starting sentry_onpremise_clickhouse_1 ...
Creating sentry_onpremise_postgres_1   ...
Starting sentry_onpremise_clickhouse_1 ... done
Starting sentry_onpremise_redis_1      ...
Starting sentry_onpremise_kafka_1      ...
Creating sentry_onpremise_symbolicator_1 ...
Creating sentry_onpremise_memcached_1    ...
Starting sentry_onpremise_redis_1        ... done
Starting sentry_onpremise_kafka_1        ... done
Creating sentry_onpremise_snuba-consumer_1 ...
Creating sentry_onpremise_snuba-replacer_1 ...
Creating sentry_onpremise_snuba-outcomes-consumer_1 ...
Creating sentry_onpremise_snuba-transactions-consumer_1 ...
Creating sentry_onpremise_snuba-api_1                   ...
Creating sentry_onpremise_snuba-sessions-consumer_1     ...
Creating sentry_onpremise_smtp_1                        ... done
Creating sentry_onpremise_postgres_1                    ... done
Creating sentry_onpremise_symbolicator_1                ... done
Creating sentry_onpremise_memcached_1                   ... done
Creating sentry_onpremise_snuba-transactions-consumer_1 ... done
Creating sentry_onpremise_snuba-outcomes-consumer_1     ... done
Creating sentry_onpremise_snuba-replacer_1              ... done
Creating sentry_onpremise_snuba-sessions-consumer_1     ... done
Creating sentry_onpremise_snuba-api_1                   ... done
Creating sentry_onpremise_snuba-consumer_1              ... done
08:22:37 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
08:22:40 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'transaction-events.force-disable-internal-project'
* Unknown config option found: 'releasefile.cache-path'
* Unknown config option found: 'slack.legacy-app'
!! Configuration error: sentry.search service failed to call validate()
'module' object has no attribute 'EventsDatasetSnubaSearchBackend'
An error occurred, caught SIGERR on line 264
Cleaning up...
```

**Comment by BYK** [comment]
@idchlife please file a new issue with the full install logs.
