### ISSUE TITLE
2020/05/07 03:15:12 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.19:9000/", host: "0.0.0.0:9000" 172.21.0.1 - - [07/May/2020:03:15:12 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"

### ISSUE THREAD

**Issue by yuanzhian** [getsentry/onpremise#477]
2020/05/07 03:15:12 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.19:9000/", host: "0.0.0.0:9000"
172.21.0.1 - - [07/May/2020:03:15:12 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"

**Comment by BYK** [comment]
@yuanzhian please provide proper titles and summaries for the issues you report. These are not helpful.
