### ISSUE TITLE
Statistic error

### ISSUE THREAD

**Issue by adityosnrost** [getsentry/onpremise#48]
Hi,

I would like to know that happened with my Sentry statistics. Here is what I did:

1. Stop cron, web, worker container and delete them.
2. Dumpall PostgreSQL database from sentry-postgre container.
3. Update Sentry docker image with cloning and build from GitHub
4. Run upgrade command
5. Run new cron, web, worker container from new build.

And, this is the error that I got when I opened statistic page:
![image](https://user-images.githubusercontent.com/8223156/28055568-b6e75664-6643-11e7-8ce4-9c2ddf0a5f77.png)

Thank You

Best Regards,

Adityo Setyonugroho

**Comment by dcramer** [comment]
You will need to look at your servers logs as something is misconfigured and this is not a support channel.
