### ISSUE TITLE
Error while removing network, network has active endpoints

### ISSUE THREAD

**Issue by CaptainHypertext** [getsentry/onpremise#480]
Events have stopped coming into my onpremise Sentry server.  The application servers all seem to be configured fine, and can reach it via curl.
I just tried running `docker-compose down` to restart Sentry, and got this error message at the end:
```
ERROR: error while removing network: network sentry_onpremise_default id XXX has active endpoints 
```
I put things back up and it's running, but still not getting events.  Any help would be appreciated.

**Comment by CaptainHypertext** [comment]
Looks like this could be related to #400, an issue with Kafka, which was closed with no fix.

**Comment by BYK** [comment]
I think [you've created a new thread over at the forums](https://forum.sentry.io/t/sentry-is-totally-dead/9738) regarding this so let's continue over there until we determine that this is a bug with the repo.
