### ISSUE TITLE
Service 'web' failed to build: Get https://registry-1.docker.io/v2/getsentry/sentry/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Agetsentry%2Fsentry%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by yuanzhian** [getsentry/onpremise#483]
Service 'web' failed to build: Get https://registry-1.docker.io/v2/getsentry/sentry/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Agetsentry%2Fsentry%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by BYK** [comment]
Dear @yuanzhian, please stop spamming our issues with random error messages.
