### ISSUE TITLE
ProgrammingError('column "is_sentry_app" of relation "auth_user" does not exist

### ISSUE THREAD

**Issue by destiny0210** [getsentry/onpremise#487]
django.db.utils.ProgrammingError: ProgrammingError('column "is_sentry_app" of relation "auth_user" does not exist\nLINE 1: ...taff", "is_active", "is_superuser", "is_managed", "is_sentry...\n                                           
this log is in “onpremise912_worker” ，I don't login IP:9000 to visit it
please,How to solve it，tks~

**Comment by BYK** [comment]
We are not supporting on-premise 9.1.2, sorry.

You may want to re run your migrations though.
