### ISSUE TITLE
How to upgrade from 9.1.2 -> 10 with gitlab authentication

### ISSUE THREAD

**Issue by marcelloceschia** [getsentry/onpremise#489]
Hi,

we tried to migrate from 9.1.2 to 10.

1) we had to disable `sentry-auth-gitlab` during migration, otherwise we get the `django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.` exception
2) when we start without this plugin, we can not login anymore, cos we get `ProviderNotRegistered: gitlab`

How to login again?

**Comment by Ilya-Kuchaev** [comment]
I have the same issue. How can I resolve it?

**Comment by sakharovaan** [comment]
if you're facing this issue after migrating, changing gitlab -> auth_gitlab in sentry_authprovider db table and installing `sentry-auth-gitlab-v2` package may help
