### ISSUE TITLE
Graphs are delayed

### ISSUE THREAD

**Issue by ThYpHo0n** [getsentry/onpremise#501]
Hi,

since we upgraded from Sentry 9.1.2 to 10 the graphs shown in Sentry are delayed:
![image](https://user-images.githubusercontent.com/1675399/82339548-70aeee00-99ee-11ea-84cb-1fe36ed2c113.png)
They are ~8hrs behind even though if you look at the Exception you see "5 minutes ago".
We installed Sentry via a helm chart (https://github.com/sentry-kubernetes/charts/tree/develop/sentry) in GKE but I guess this shouldn't be the issue here.
A hint into which direction to debug would be helpful, how/where are the graphs calculated?

Thanks for all the work, Sentry is really great!

**Comment by BYK** [comment]
Hi!

Looks like that helm chart is a bit old and doesn't have some of the recent fixes we have made around this:

 - https://github.com/getsentry/onpremise/pull/426
 - https://github.com/getsentry/onpremise/pull/430

I'll close this as we don't maintain the helm chart but if you have any further questions, I'm happy to help here or over at the [forums](https://forum.sentry.io/c/on-premise/helm/11)
