### ISSUE TITLE
CSRF Verification Failure when enabling Okta Auth

### ISSUE THREAD

**Issue by davjr96** [getsentry/onpremise#503]
I'm attempting to enable okta auth on our sentry on premise instance "Sentry 10.1.0.dev0a59045a" 
If I go to settings and select okta and copy the Metadata URL from the okta admin panel I get a CSRF verification error page 

Django prints out
`web_1                      | 16:26:18 [WARNING] django.security.csrf: Forbidden (Referer checking failed OKTA_URL does not match any trusted origins.): / (status_code=403 request=<WSGIRequest: POST u'/'>)`

Any ideas? Sentry is running in sentry.COMPANYNAME.local and okta is coming from COMPANYNAME.oktapreview.com

Thanks!

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
