### ISSUE TITLE
Sentry10: Sporadic missing events

### ISSUE THREAD

**Issue by sagor999** [getsentry/onpremise#504]
Hi,
wondering if anyone encountered similar issue and might know what might be causing this.
Sentry receives event, sends email about event being created. But, if you follow the link to sentry, it says:
`Sorry, the events for this issue could not be found.`
Even though it shows:
`Events: 1`
but if you click on Events tab, it is also empty.
If you go to project's dashboard, that event will be missing from there too. 

It happens to some events only. At some point something changes, and then events are coming through and showing up just fine.

Nothing in logs shows any errors or anything that would explain this.
snuba consumer is working fine and no errors.
workers are working fine and not backlogged.
Queue is completely empty.

Any help or ideas would be greatly appreciated.

Sentry 10.1.0.dev06e6ed91

**Comment by BYK** [comment]
I'd check the `post-process-forwarder` service logs first: `docker-compose logs post-process-forwarder`.

**Comment by sagor999** [comment]
@BYK hm. it doesn't have anything in logs at all. Only two entries since start up:
```
13:50:17 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured. 
13:50:21 [INFO] sentry.plugins.github: apps-not-configured
```
Is that normal?

**Comment by BYK** [comment]
If it is running, that should be fine actually. Is it running?

**Comment by sagor999** [comment]
@BYK it is running. just double checked.

**Comment by sagor999** [comment]
@BYK only thing that I see that maybe is related, is message like this from worker:
```
%3|1589941698.811|ERROR|rdkafka#producer-2| [thrd:sentry-kafka:9092/bootstrap]: sentry-kafka:9092/bootstrap: Disconnected
```
Is that normal?

**Comment by sagor999** [comment]
Resolved. Issue was with not correctly configured clickhouse and snuba. 
Here are details if someone else will encounter similar issue (running sentry from helm chart in kubernetes):
https://github.com/sentry-kubernetes/charts/issues/68

**Comment by BYK** [comment]
@sagor999, happy that your issue is resolved but I wish you mentioned you were not using this repo as we have now spent considerable time trying to figure this out internally (and failed).

**Comment by sagor999** [comment]
@BYK my apologies. I did not realize that helm chart is completely separate from this repo, and not using it. :( 
P.S. You should consider maybe adopting that helm chart as official helm chart for deploying sentry 10 into kubernetes.

**Comment by BYK** [comment]
>@BYK my apologies. I did not realize that helm chart is completely separate from this repo, and not using it. :(

No worries 🙂 

>P.S. You should consider maybe adopting that helm chart as official helm chart for deploying sentry 10 into kubernetes.

We don't have any plans around this right now but thanks for the suggestion!
