### ISSUE TITLE
Missing snuba sessions consumer

### ISSUE THREAD

**Issue by ainopara** [getsentry/onpremise#513]
Release Adoption not showing any data with onpremise deployment because `ingest-sessions` topic in kafka do not have a consumer.
I tried to fix this issue by adding a snuba container with command
```
consumer --storage sessions_raw --auto-offset-reset=latest --max-batch-time-ms 750
```

**Comment by BYK** [comment]
I think we have not released this yet. @mitsuhiko and I were planning on adding this soon.

**Comment by ainopara** [comment]
Resoloved by #524
