### ISSUE TITLE
Nginx config necessary?

### ISSUE THREAD

**Issue by ChibangLW** [getsentry/onpremise#516]
The nginx config for relay defines two separate locations but from reading the relay documentation I am curious if `location ~ ^/api/[1-9]\d*/ {
	proxy_pass http://relay;
}` is enough (`/api/<project_id>/store`). Is the other entry (`location /api/store/`) used by any SDK or CLI?

Furthermore `[1-9]` and `\d*` are more or less equivalent, right?

**Comment by BYK** [comment]
>Furthermore [1-9] and \d* are more or less equivalent, right?

The exception is `0` being excluded as that is routed to Sentry. We wouldn't have added nginx if it wasn't necessary. Why do you ask? 🙂

**Comment by ChibangLW** [comment]
Thanks for the clarification. We have a haproxy instead of nginx and I want to convert the config and was not sure because in the relay documentation only `/api/X/store` is mentioned as endpoint ([relay](https://getsentry.github.io/relay/architecture/ingest-event-path/)).
