### ISSUE TITLE
Indentation error while lifting services

### ISSUE THREAD

**Issue by Amar-Myana** [getsentry/onpremise#52]
Getting same error while running below commands:

`$ sudo docker-compose run --rm web upgrade`
`$ sudo docker-compose up --force-recreate --abort-on-container-exit`

base_1       | Traceback (most recent call last):
base_1       |   File "/usr/local/bin/sentry", line 11, in <module>
base_1       |     sys.exit(main())
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 158, in main
base_1       |     cli(prog_name=get_prog(), obj={}, max_content_width=100)
base_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
base_1       |     return self.main(*args, **kwargs)
base_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
base_1       |     rv = self.invoke(ctx)
base_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
base_1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
base_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
base_1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
base_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
base_1       |     return ctx.invoke(self.callback, **ctx.params)
base_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
base_1       |     return callback(*args, **kwargs)
base_1       |   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
base_1       |     return f(get_current_context(), *args, **kwargs)
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 65, in inner
base_1       |     return ctx.invoke(f, *args, **kwargs)
base_1       |   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
base_1       |     return callback(*args, **kwargs)
base_1       |   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
base_1       |     return f(get_current_context(), *args, **kwargs)
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
base_1       |     configure()
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 121, in configure
base_1       |     configure(ctx, py, yaml, skip_backend_validation)
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 159, in configure
base_1       |     }, skip_backend_validation=skip_backend_validation)
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 241, in initialize_app
base_1       |     bootstrap_options(settings, config['options'])
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 116, in bootstrap_options
base_1       |     from sentry.options import load_defaults
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/options/__init__.py", line 10, in <module>
base_1       |     from .store import OptionsStore
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/options/store.py", line 19, in <module>
base_1       |     from sentry.db.models.query import create_or_update
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/__init__.py", line 11, in <module>
base_1       |     from .base import *  # NOQA
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/db/models/base.py", line 14, in <module>
base_1       |     from django.db import models
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/__init__.py", line 5, in <module>
base_1       |     from django.db.models.query import Q
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 17, in <module>
base_1       |     from django.db.models.deletion import Collector
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 4, in <module>
base_1       |     from django.db.models import signals, sql
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/__init__.py", line 4, in <module>
base_1       |     from django.db.models.sql.subqueries import *
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 12, in <module>
base_1       |     from django.db.models.sql.query import Query
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 22, in <module>
base_1       |     from django.db.models.sql import aggregates as base_aggregates_module
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/aggregates.py", line 9, in <module>
base_1       |     ordinal_aggregate_field = IntegerField()
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 116, in __init__
base_1       |     self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
base_1       |     self._setup(name)
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
base_1       |     self._wrapped = Settings(settings_module)
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
base_1       |     mod = importlib.import_module(self.SETTINGS_MODULE)
base_1       |   File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
base_1       |     __import__(name)
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 52, in load_module
base_1       |     reraise_as(ConfigurationError(msg))
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/utils/settings.py", line 48, in reraise_as
base_1       |     six.reraise(new_type, new_exception, e_traceback)
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 44, in load_module
base_1       |     mod = self._load_module(fullname)
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 76, in _load_module
base_1       |     load_settings(self.config_path, settings=settings_mod, silent=True)
base_1       |   File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 90, in load_settings
base_1       |     six.exec_(source_file.read(), conf.__dict__)
base_1       |   File "/usr/local/lib/python2.7/site-packages/six.py", line 699, in exec_
base_1       |     exec("""exec _code_ in _globs_, _locs_""")
base_1       |   File "<string>", line 1, in <module>
base_1       | sentry.runner.importer.ConfigurationError: IndentationError: unexpected indent (<string>, line 258)

Any help would be appreciated.

**Comment by mattrobenolt** [comment]
This is purely an issue with your config. Python is white space sensitive. This error is saying the indentation somewhere is wrong.
