### ISSUE TITLE
Service 'web' failed to build: failed to copy files

### ISSUE THREAD

**Issue by zhangkuiworld** [getsentry/onpremise#528]
**Run ./install.sh,  here is the log info:**

Checking minimum requirements...
./install.sh: line 62: [: : integer expression expected
docker: Error response from daemon: open /var/lib/docker/overlay/c9678ed031f0c3556f40bc0438ae86291e66fa63066ee6c7722a53b94d215cad-init/merged/.dockerenv: no such device or address.
See 'docker run --help'.
./install.sh: line 70: ((: == 0: syntax error: operand expected (error token is "== 0")
Removing network onpremise_default
Network onpremise_default not found.
Removing network sentry_onpremise_default
Network sentry_onpremise_default not found.

Creating volumes for persistent storage...
Created sentry-data.
Created sentry-postgres.
Created sentry-redis.
Created sentry-zookeeper.
Created sentry-kafka.
Created sentry-clickhouse.
Created sentry-symbolicator.

sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
sentry/requirements.txt already exists, skipped creation.

Fetching and updating Docker images...

Some service image(s) must be built from source by running:
    docker-compose build worker cron web snuba-cleanup symbolicator-cleanup ingest-consumer sentry-cleanup post-process-forwarder
latest: Pulling from getsentry/sentry
Digest: sha256:8ed2500ddb60a215f0de341996833941f3e97f6b90be98841242ebbf5981de40
Status: Image is up to date for getsentry/sentry:latest
docker.io/getsentry/sentry:latest

Building and tagging Docker images...

Building web
Step 1/5 : ARG SENTRY_VERSION=latest
Step 2/5 : ARG SENTRY_IMAGE
Step 3/5 : FROM ${SENTRY_IMAGE:-getsentry/sentry:$SENTRY_VERSION}
 ---> 124562c8150b
Step 4/5 : COPY . /usr/src/sentry
Service 'web' failed to build: failed to copy files: failed to copy directory: Error processing tar file(exit status 1): open /requirements.txt: no such device or address
Cleaning up...
[root@M7-10-6-12-27-13-33 onpremise]# ./install.sh
Checking minimum requirements...
./install.sh: line 62: [: : integer expression expected
docker: Error response from daemon: open /var/lib/docker/overlay/9be762ee0d9d3508913bfd28ea00dce2079acad7f1f8f5487569aa8d8e0d325f-init/merged/etc/hosts: no such device or address.
See 'docker run --help'.
./install.sh: line 70: ((: == 0: syntax error: operand expected (error token is "== 0")
Removing network onpremise_default
Network onpremise_default not found.
Removing network sentry_onpremise_default
Network sentry_onpremise_default not found.

Creating volumes for persistent storage...
Created sentry-data.
Created sentry-postgres.
Created sentry-redis.
Created sentry-zookeeper.
Created sentry-kafka.
Created sentry-clickhouse.
Created sentry-symbolicator.

sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
sentry/requirements.txt already exists, skipped creation.

Fetching and updating Docker images...

Some service image(s) must be built from source by running:
    docker-compose build worker cron web snuba-cleanup symbolicator-cleanup ingest-consumer sentry-cleanup post-process-forwarder
latest: Pulling from getsentry/sentry
Digest: sha256:8ed2500ddb60a215f0de341996833941f3e97f6b90be98841242ebbf5981de40
Status: Image is up to date for getsentry/sentry:latest
docker.io/getsentry/sentry:latest

Building and tagging Docker images...

Building web
Step 1/5 : ARG SENTRY_VERSION=latest
Step 2/5 : ARG SENTRY_IMAGE
Step 3/5 : FROM ${SENTRY_IMAGE:-getsentry/sentry:$SENTRY_VERSION}
 ---> 124562c8150b
Step 4/5 : COPY . /usr/src/sentry
Service 'web' failed to build: failed to copy files: failed to copy directory: Error processing tar file(exit status 1): open /requirements.txt: no such device or address

**What's the problem?**

**Comment by BYK** [comment]
Seems like `sentry/requirements.txt` is not being included in the build context for the Sentry image. Can you check its permissions?

**Comment by zhangkuiworld** [comment]
> Seems like `sentry/requirements.txt` is not being included in the build context for the Sentry image. Can you check its permissions?

How ？run some shell command ？QAQ

**Comment by zhangkuiworld** [comment]
> Seems like `sentry/requirements.txt` is not being included in the build context for the Sentry image. Can you check its permissions?

`sentry/requirements.txt` is exist.
‘Can you check its permissions?‘, what do you mean, what should I do, T_T

**Comment by BYK** [comment]
>‘Can you check its permissions?‘, what do you mean, what should I do, T_T

`chmod 0777 sentry/requirements.txt`

**Comment by zhangkuiworld** [comment]
> > ‘Can you check its permissions?‘, what do you mean, what should I do, T_T
> 
> `chmod 0777 sentry/requirements.txt`

still can't work, same log message ..

**Comment by BYK** [comment]
Can you try running `chmod -r 0777 .` while inside the `onpremise` directory?

**Comment by zhangkuiworld** [comment]
> chmod -r 0777

Thx, I have just tried, here is the message: `chmod: cannot access ‘0777’: No such file or directory`

**Comment by BYK** [comment]
You need the ` .` part at the end.

**Comment by zhangkuiworld** [comment]
> You need the ` .` part at the end.

It's a typo, I have run `chmod -r 0777 .` same log message here: `chmod: cannot access ‘0777’: No such file or directory`

BTW, Thank you for your patience...

**Comment by zhangkuiworld** [comment]
still can't work ..

**Comment by BYK** [comment]
@zhangkuiworld I think you need to run `chmod -R 0777 .` then (note the capital `-R`).

**Comment by BYK** [comment]
Closing due to lack of response.

**Comment by zhangkuiworld** [comment]
run `chmod -R 0777 .` , no message here.

**Comment by BYK** [comment]
>run chmod -R 0777 . , no message here.

That means the command succeeded.

**Comment by zhangkuiworld** [comment]
> > run chmod -R 0777 . , no message here.
> 
> That means the command succeeded.

but still does't work, and same message.

**Comment by BYK** [comment]
@zhangkuiworld then I don't know how else to help you unfortunately. There's clearly something wrong with your local filesystem permissions or your docker client. You may try asking this on StackOverflow. A similar issue to yours: https://stackoverflow.com/questions/58327096/unable-to-copy-file-during-docker-build

**Comment by zhangkuiworld** [comment]
> https://stackoverflow.com/questions/58327096/unable-to-copy-file-during-docker-build

thanks a lot！
