### ISSUE TITLE
Base service in docker-compose

### ISSUE THREAD

**Issue by pgrzesik** [getsentry/onpremise#53]
I'm toying around with this repo (awesome work by the way!) and I'm wondering - is it necessary to run base service to run the whole application (I'm pretty sure that I know the answer and the answer is 'no') ?

What I'm refering to is Up and Running, 4. point:
`docker-compose up -d` - it will spin up unnecessary(I think) base service which is essentialy the same as `web` service that doesn't map ports. 

Regards
Piotr

**Comment by mattrobenolt** [comment]
No, `base` isn't used. I was just using it as inheritance. If you have an improvement, I'd be open to a suggestion. I don't use docker-compose, so it's mostly fumbling around.

**Comment by exp0nge** [comment]
Using `build` also prevents `ecs compose` AWS ECS deployment.

**Comment by mattrobenolt** [comment]
I don't know how to fix this, so feel free to submit a PR. I don't use docker compose or ECS, unfortunately.

**Comment by exp0nge** [comment]
@mattrobenolt ECS is a pain in the ass at the moment. They don't have their CLI tool available on windows yet, also. once I figure it out, I'll see what I can do.

**Comment by revolunet** [comment]
should be fixed here : https://github.com/getsentry/onpremise/pull/105

**Comment by BYK** [comment]
Closing per the comment above.
