### ISSUE TITLE
Release health on Sentry 10

### ISSUE THREAD

**Issue by PaulWoitaschek** [getsentry/onpremise#533]
With sentry 10 and the "Eearly adopter" setting enabled, according to the documentation:
https://docs.sentry.io/workflow/releases/health/
We should see stats on release meterics. However there is no "Releases v2" tab available.

Is this a bug or am I missing something?

**Comment by carlosrivin** [comment]
Hello. 
I actually see this tab since the update I did on the sentry server. But no stats show up in the releases besides the old ones. I have everything enabled in the app and we have a iOS demo app and an Android demo app. Both releases show nothing about health information.
I found this error in the android logs
[SentryAsyncConnection-0] throwable = [java.io.FileNotFoundException: https://www.MYSENTRYSERVER.com/api/2/envelope/], message = [Error while closing the connection.], args = [ 
Can you check if you have the same? Not sure if I'm missing some configuration or what is wrong.
By the way, I was able to see the new releases tab without the "Early adopter" option activated.

**Comment by PaulWoitaschek** [comment]
What is the url?
Maybe its possible to access it that way?
I.e the v1 release path is:
https://domain.com/organizations/org/releases/

**Comment by carlosrivin** [comment]
It's the same url. A bunch of banners showed up after I updated the onpremisse server. Maybe that's all you need to do. Have you tried to run the ./install.sh script?

**Comment by PaulWoitaschek** [comment]
And you are running version 10?

**Comment by carlosrivin** [comment]
Yes. I ran the update script like 2 days ago or something.

**Comment by BYK** [comment]
@PaulWoitaschek the early adopter setting is for sentry.io only (this repo is for on-premise). You may need to compare your `sentry.conf.py` file with [our default config file](https://github.com/getsentry/onpremise/blob/master/sentry/sentry.conf.example.py) to make sure there are no mismatches (especially around feature flags).

@carlosrivin - did you get the latest updates to this repo which includes nginx, relay, and a new kafka consumer?

**Comment by PaulWoitaschek** [comment]
So this is something that will be available in the future? Or can this be enabled in the config file right now?
Maybe you should add a note here: https://docs.sentry.io/workflow/releases/health/ that it's not available with the onpremise version. This has caused a lot of confusion and manual investigation on our side.

**Comment by BYK** [comment]
@PaulWoitaschek this was added recently: https://github.com/getsentry/onpremise/pull/524

**Comment by PaulWoitaschek** [comment]
Thanks! So is it possible to activate with the 10.0.0 release or do I have to wait for a new release?

**Comment by BYK** [comment]
v10 is ~6 months old at this point so if you are explicitly using that, you cannot use release health. You can install the latest from this repo or wait for a new tagged release (which is soon but will be compatible with the latest version of this repo).

**Comment by carlosrivin** [comment]
I updated the onpremise server today again and it is still not working. I have all the feature flags from the example and more.

```
SENTRY_FEATURES["projects:sample-events"] = False
SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            "organizations:discover",
            "organizations:events",
            "organizations:global-views",
            "organizations:integrations-issue-basic",
            "organizations:integrations-issue-sync",
            "organizations:invite-members",
            "organizations:new-issue-ui",
            "organizations:repos",
            "organizations:require-2fa",
            "organizations:sentry10",
            "organizations:sso-basic",
            "organizations:sso-rippling",
            "organizations:sso-saml2",
            "organizations:suggested-commits",
            "projects:custom-inbound-filters",
            "projects:data-forwarding",
            "projects:discard-groups",
            "projects:plugins",
            "projects:rate-limits",
            "projects:servicehooks",
        )
    }
)
```

**Comment by BYK** [comment]
@carlosrivin do you have the [snuba-sessions-consumer](https://github.com/getsentry/onpremise/blob/c2120aafc94e34ee33420d0afb7f3c1641fbe514/docker-compose.yml#L119-L122) service running?

**Comment by carlosrivin** [comment]
Yes @BYK 
` getsentry/snuba:latest                 "./docker_entrypoint…"   10 minutes ago      Up 9 minutes        1218/tcp                       sentry_onpremise_snuba-consumer_1`

**Comment by marandaneto** [comment]
@BYK I believe they also need to set:

`SENTRY_USE_RELAY = True` (server.conf.py)

Can you confirm that this is enabled by default? otherwise, they'd need to do that in order to consume the `/envelope` endpoint.

**Comment by BYK** [comment]
@marandaneto yup: https://github.com/getsentry/sentry/blob/12f4ee73c414ef8472d390f017285868c8e97bc0/src/sentry/conf/server.py#L1395-L1401

**Comment by BYK** [comment]
@carlosrivin on top of the feature flags, do you have the relay related configuration such as the PK definition etc?

**Comment by carlosrivin** [comment]
@BYK  So, we are running the onpremise via the docker. And I see no configuration for relay in the `sentry.conf.py`. Because I couldn't find the `server.py`. I guess it's imported via the `sentry.conf.py`. I couldn't find this files even inside the docker images. Maybe I'm doing something wrong. I'm know only the basics in docker. So my question is:
Do I need to manually install and configure https://getsentry.github.io/relay/ ? Or is there an easier way?
Thanks for the support!

**Comment by carlosrivin** [comment]
@BYK I have some development. I saw this on the sentry web logs. 
```web_1                     | 09:04:24 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /api/3/envelope/ (status_code=403 request=<WSGIRequest: POST u'/api/3/envelope/'>)
web_1                     | 172.27.0.1 - - [16/Jun/2020:09:04:24 +0000] "POST /api/3/envelope/ HTTP/1.1" 403 5182 "-" "sentry-cocoa"```
I guess we have the same issue with the android.
I tried to force this `CSRF_COOKIE_SECURE = False` in the `sentry.conf.py`. What else can I try?

**Comment by carlosrivin** [comment]
@BYK can you please take a look at my recent comments and help me out?

**Comment by BYK** [comment]
@carlosrivin are you using a recent version of this repo as the envelope endpoint needs Relay as far as I need so that request should never reach Sentry. /cc @jan-auer in case I'm mistaken.

**Comment by jan-auer** [comment]
> the envelope endpoint needs Relay

That is correct. Release Health requires Sentry `v20.6.0`, specifically the Relay service which is included in the default setup.

> Do I need to manually install and configure https://getsentry.github.io/relay/

Outside of the latest Sentry docker compose setup, you won't have to run Relay.

**Comment by carlosrivin** [comment]
We found out what the issue was. Just for the record I'm going to write here.
So, even thought the install script was updating most of the code. The docker container was not getting updates. So we were probably running an old version of the setup with the new code. As soon as we updated the container and the configuration we got it to work again.
Thanks for the help.

**Comment by BYK** [comment]
Thanks for reporting back @carlosrivin. We do try to update the images in this block: https://github.com/getsentry/onpremise/blob/e75e6f1deeb8dd534700f783fe6c10a4418f42d4/install.sh#L149-L162

I wonder what's going wrong there. Any ideas or logs you can share?

**Comment by BYK** [comment]
@carlosrivin closing the issue since you managed to fix it but I'd love to hear your thoughts on what might be going wrong with our auto pull mechanism.

**Comment by carlosrivin** [comment]
Hello. Sorry I forgot to reply. I did investigate a little bit but we are not sure what happened and we lost the logs. I'll monitor this specifically next time we do an update.
