### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'connection_pool'

### ISSUE THREAD

**Issue by zoidberg77** [getsentry/onpremise#54]
Is there a way to resolve this bug for the docker or docker-compose version? 
i tried to run pip install redis==2.10.5 before the init migration via docker-compose run --rm web upgrade but it still failed

**Comment by mattrobenolt** [comment]
I would just upgrade to 8.20 which won't have the issue.

**Comment by mattrobenolt** [comment]
Bumped here: https://github.com/getsentry/onpremise/commit/855f9cade9d1fb618307e6d9e62176d8f6249cb9

**Comment by zoidberg77** [comment]
thanks! now it works
