### ISSUE TITLE
Disk space usage

### ISSUE THREAD

**Issue by rps-v** [getsentry/onpremise#540]
We updated from 9.1.2 o 10 and after a few days of running, our server's disk space was used up. The server has 40GB of storage and was running fine on Sentry 9.1.2.
We get about ~150,000 events per day.

The culprit seems to be `sentry-kafka`.

```bash
root@sentry:~# docker system df -v
Local Volumes space usage:

VOLUME NAME                                                        LINKS               SIZE
sentry-kafka                                                       1                   18.55GB
```

How can we reduce the space usage ?
Did we miss some configuration ?

**Comment by rps-v** [comment]
Found possible solution [on the forum](https://forum.sentry.io/t/restrict-kafka-disk-usage/9838).

```docker-compose.yml
...
  kafka:
    environment:
      KAFKA_LOG_RETENTION_HOURS: '24'
      KAFKA_LOG_RETENTION_BYTES: '1073741824'
      KAFKA_LOG_SEGMENT_BYTES: '107374182'
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: '60000'
      KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: '1000'
...
```

**Comment by ahmadalli** [comment]
I think it's related to #502

**Comment by BYK** [comment]
Closing this in favor of #502 as @ahmadalli suggested.
