### ISSUE TITLE
Migration from 10.0.0 to 20.6.0

### ISSUE THREAD

**Issue by TheRatG** [getsentry/onpremise#546]
Hello,

Trying to install new version of onpremise, but got fatal error. Please help.

```
DuplicateTable('relation "sentry_exporteddata" already exists\n',)
```

[install.log](https://github.com/getsentry/onpremise/files/4796522/install.log)

**Comment by BYK** [comment]
Sounds like you have run this migration eariler but it was not marked as run. Did you have a failed install?

**Comment by TheRatG** [comment]
> Sounds like you have run this migration eariler but it was not marked as run. Did you have a failed install?

Maybe. 
Is it possible to dump project setting data especially SDK client keys and make a fresh installation?

**Comment by BYK** [comment]
>Is it possible to dump project setting data especially SDK client keys and make a fresh installation?

We have the `export` command but AFAIK that and `import` is broken and not very easy to fix right now.

We can tell Django to skip this migration which should resolve the issue:
```shell
docker-compose run --rm web django migrate --fake sentry 0028_user_reports
```
After that step, try running the install script again. If it fails, with another migration, the process is finding the migration right after the failing one from here: https://github.com/getsentry/sentry/tree/master/src/sentry/migrations

And then running the above command with that.

LMK how it goes. Also, while you're at it I'd go with version 20.9.0 at this point.

**Comment by TheRatG** [comment]
`docker-compose run --rm web django migrate --fake sentry 0028_user_reports`

Thanks a lot @BYK. Now we have 20.9.0 version.
