### ISSUE TITLE
Sentry migrate from 10 to 20.6.0 - Zookeeper cp: cannot create regular file

### ISSUE THREAD

**Issue by strange-developer** [getsentry/onpremise#547]
On migrating to v20.6.0 from Sentry 10, I encountered an error during the install process which had the following description:

```
cp: cannot create regular file ‘/var/lib/zookeeper/data/version-2/snapshot.0’: No such file or directory
```

After some debugging and investigation I noticed that the issue lies in the line of code at:
https://github.com/getsentry/onpremise/blob/master/install.sh#L178

What I've found is that the copy target folder doesn't exist within the container, more specifically, this copy target location:
`/var/lib/zookeeper/data/version-2`

I've rectified the issue by updating the erroring line of code to include creating the copy target location:

```
$dcr -v $(pwd)/zookeeper:/temp zookeeper bash -c 'mkdir -pv /var/lib/zookeeper/data/version-2 && cp /temp/snapshot.0 /var/lib/zookeeper/data/version-2/snapshot.0'
```

I haven't been able to find any articles relating to this issue so I thought I'd post it here with the solution, however, I can create a PR with that change if it is to your satisfaction. Would this be an ideal fix for the issue?

Docker version: `Docker version 17.05.0-ce, build 89658be`
Compose version: `docker-compose version 1.24.1, build 4667896b`

**Comment by BYK** [comment]
Hi @strange-developer and thanks a lot for the report! If that directory doesn't exist, I think we don't even need to copy this file in. Would you be willing to submit a patch that does this?

**Comment by strange-developer** [comment]
Sure! I'll submit a PR a bit later :)
