### ISSUE TITLE
the uWSGI progresses consume too much CPU

### ISSUE THREAD

**Issue by nju-Nicko** [getsentry/onpremise#549]
We are using on-premise Sentry 9.1.1  without docker. And recently i find that the sentry uWSGI wokers often consume too much CPU time(100% or more). The server is 8C16G. The web server is confiured as default, which starts one master uWSGI woker and 3 sub uWSGI workers. When all the uWSGI workers consume 100% CPU, operation on Sentry frontend webpage will be blocked.
Thanks a lot for anybody who can help !

**Comment by nju-Nicko** [comment]
![image](https://user-images.githubusercontent.com/7032962/85386981-da369500-b576-11ea-8a8d-7bd93cd5fcc7.png)

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
