### ISSUE TITLE
The Sentry uWSGI progress consumes too much CPU

### ISSUE THREAD

**Issue by nju-Nicko** [getsentry/onpremise#551]
## Important Details

How are you running Sentry?

On-Premise Sentry without Docker
version 9.1.1
## Description
We are using on-premise Sentry 9.1.1 without docker. And recently i find that the sentry uWSGI wokers often consume too much CPU time(100% or more). The server is 8C16G. The web server is configured as default, which starts one master uWSGI woker and 3 sub uWSGI workers. When all the uWSGI workers consume 100% CPU, operation on Sentry frontend webpage will be blocked.

As below, the Sentry uWSGI progress keeps consuming 100% CPU for very long time. And i checked the log of `sentry run web`, there are very few http request logs. So it's not caused by too many concurrent requests. And i also checked the events queues, all the queues are empty. So it's not caused by too many backlog events. So i wonder what causes the uWSGI's high usage of CPU.
![image](https://user-images.githubusercontent.com/7032962/85505825-c1cf8480-b621-11ea-8a61-1c26d0ca3c56.png)

### What you expected to happen
The progresses consume low `%CPU`.
### Possible Solution
As i have mentioned above, i have checked the log of  `sentry run web`, there are few logs of http requests. So it's not caused by too many concurrent requests. And all the event queues are empty, which means it is not caused by too many backlog events.

**Comment by nju-Nicko** [comment]
Emmmm... about an hour passed, the `%CPU` eventually turned down to 0%....

**Comment by nju-Nicko** [comment]
It seems that it costs much CPU time on regular-expression matching.
![image](https://user-images.githubusercontent.com/7032962/85544489-a5494180-b64d-11ea-88c2-c02664a5da2e.png)

**Comment by BYK** [comment]
Since this is about 9.1.1 which is both old and unsupported, we won't be able to assist you here. You may find some help from the community over at the [forum](https://forum.sentry.io).

I strongly recommend upgrading to a more recent version as we improve performance all the time.
