### ISSUE TITLE
qps too high

### ISSUE THREAD

**Issue by jiazhonglin** [getsentry/onpremise#555]
there is  one  project in my sentry,  it's error report  ver frequently,  qps is too high,
I find that  i can config params like "sample_rate" in my code.  but project is too many.
how can i config it  at  Background management platform?

![image](https://user-images.githubusercontent.com/15116568/86096660-24bf9080-bae6-11ea-8fb8-b205bd68b87f.png)
![image](https://user-images.githubusercontent.com/15116568/86096705-399c2400-bae6-11ea-90aa-ba8c9575c738.png)

          Background management platform

**Comment by BYK** [comment]
I think you are looking for this: https://develop.sentry.dev/services/quotas/#system-wide-rate-limiting
