### ISSUE TITLE
Sentry accessible remotely on port 9000

### ISSUE THREAD

**Issue by ragesoss** [getsentry/onpremise#56]
I've set up a new onpremise instance using this docker system, and it's now all working with nginx for the correct domain with SSL. However, it is still accessible remotely via IP address on port 9000 (without https), even when nginx is not running.

In poking around iptables, I infer that this is because of this policy:

```
Chain DOCKER (2 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.18.0.8           tcp dpt:9000
```

That's useful (but maybe not strictly necessary) for getting set up initially to confirm that you got sentry installed correctly, but I don't know how to disable that for production use.

**Comment by qari** [comment]
It's normal, how can you use sentry without opening port?

**Comment by mattrobenolt** [comment]
Just don't expose port 9000 over public interface. I'm not sure anything about your setup, but this would be in how you're using docker. You can just bind 9000 to 127.0.0.1 and have nginx running on localhost as well, for example. Then 9000 is never exposed. Or at least bind to a private only interface.

**Comment by ragesoss** [comment]
Thanks. I was just running it by following the setup instructions in this repo.

That exposing of port 9000 publicly was coming from the docker-compose.yml file.

I fixed it by change the `web:ports` lines to:

```
    ports:
      - '127.0.0.1:9000:9000'
```

**Comment by caugner** [comment]
> 
> 
> Thanks. I was just running it by following the setup instructions in this repo.
> 
> That exposing of port 9000 publicly was coming from the docker-compose.yml file.
> 
> I fixed it by change the `web:ports` lines to:
> 
> ```
>     ports:
>       - '127.0.0.1:9000:9000'
> ```

Here's another solution without changing the `docker-compose.yml` file:

```terminal
$ echo "{
\"iptables\": false
}" > /etc/docker/daemon.json
$ systemctl reload docker
```
(Source: https://www.mkubaczyk.com/2017/09/05/force-docker-not-bypass-ufw-rules-ubuntu-16-04/)
