### ISSUE TITLE
Unable to add Slack Alert rules. The slack resource "<channel>" does not exist or has not been granted access in the loop Slack workspace.

### ISSUE THREAD

**Issue by harshulj** [getsentry/onpremise#562]
I am trying to add slack alert rules to On Premise Sentry.
But I am receiving the following error
```The slack resource "<channel-name>" does not exist or has not been granted access in the loop Slack workspace.```
The channel does exist. I have followed the instructions mentioned on this page.
https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463

**Comment by phyzical** [comment]
hey @harshulj 

its due to a new change in config land apply whats in this pr and itll just start working 👍 

https://github.com/getsentry/onpremise/pull/563

**Comment by harshulj** [comment]
This worked, thanks!

**Comment by BYK** [comment]
Closed by #563.
