### ISSUE TITLE
Why does mail.host default to `smtp`?

### ISSUE THREAD

**Issue by caugner** [getsentry/onpremise#565]
I just configured my second Sentry onpremise server. While most things went more smoothly than last time, the email setup still doesn't seem to be intuitive to me.

During the install dialog, I typed in the email credentials, but for some reason it did *not* ask for the hostname (and so emails did not send, like the first time I setup Sentry onpremise).

In fact the hostname seems to be hardcoded as `smtp` in the default config:
https://github.com/getsentry/onpremise/blob/a549ab1300f94149bf347df9277cf7bc50f0e5d7/sentry/config.example.yml#L11

Could it be that this is the reason that Sentry doesn't ask for `mail.host` during setup?

PS: Where are the mail credentials from the installation dialog stored?

**Comment by caugner** [comment]
(After commenting out that line in the `config.yml`, Sentry did indeed ask for the hostname.)

**Comment by caugner** [comment]
The other UX issue here is that the user interface says "TLS", but means "STARTTLS" (usually port 25).

Since the UI seemingly only offered TLS, I provided the TLS port (465), so it couldn't work, as some folks pointed out in #4252.

**Comment by BYK** [comment]
Hi @caugner! I agree that we can do better job explaining how to set up email and SMTP and also how the configuration system works so I tagged the issue as a docs request. We'll be working on improving on-premise docs in the coming months.

Now, to answer your question about the hard-coded `smtp` value:

Because on-premise actually ships with `exim4` and the service name for it is `smtp`. So emails should actually work out of the box. Was that not your experience?

**Comment by caugner** [comment]
@BYRK Oh, that makes sense.

To be honest, since Sentry was asking for mail credentials (except host, see above) in the setup dialog, I assumed that Sentry's emails does *not* work out of the box. Since I provided those credentials (except host), I assumed it would automagically figure out the host, but of course it didn't work.

Does onpremise also support messaging integration out of the box with that `exim4` service?

**Comment by ankit-arora-369** [comment]
Even I am facing the same issue, how can we configure the mail service in sentry/onpremise?
Even after making changes to sentry/config.yml, install.sh script is fetching the default setting which has port 25 being used and in most of the cloud provider port 25 is block by default.
Config I am using is:

mail.host: 'IP'
mail.port: 587
mail.from: 'sentry@domain.com'

How to setup mails properly?
Can you please help?

**Comment by caugner** [comment]
@ankit-arora-369 That would be a separate issue. Would you mind creating a new issue for that?

**Comment by ankit-arora-369** [comment]
Sure, I will do that.

**Comment by BYK** [comment]
@caugner 

>Does onpremise also support messaging integration out of the box with that exim4 service?

Not sure what you are referring to "messaging integration" so I need clarification before answering.

For the rest, I think we can make the initial setup page a bit better but not sure how, any more recommendations (other than exposing the `host` field there)?

**Comment by caugner** [comment]
@BYK 

> Not sure what you are referring to "messaging integration" so I need clarification before answering.

Sorry, I meant "messaging capabilities", as [mentioned in the Sentry Additional Data docs](https://docs.sentry.io/enriching-error-data/additional-data/#capturing-the-user):
![grafik](https://user-images.githubusercontent.com/495429/87418500-11c2bb00-c5d2-11ea-91d0-93aba2d79859.png)

> any more recommendations

What would help *a lot*:
1. Verify the entered SMTP credentials directly and rejecting them if invalid,
2. Allow to change the SMTP credentials via the UI or,
3. Mention where the SMTP credentials (entered into the initial setup page) can be changed.

**Comment by BYK** [comment]
>Sorry, I meant "messaging capabilities", as mentioned in the Sentry Additional Data docs:

Oh, this has nothing to do with sending e-mails or smtp. This is about capturing user information when a crash happens and I think the messaging capabilities is about being able to message the user who experienced the crash.

Thanks a lot for the improvement suggestions! I cannot promise to get them all in or by a certain date but will definitely keep these in mind when we are improving the install wizard experience.
