### ISSUE TITLE
How to update settings without doing  `./install.sh` ?

### ISSUE THREAD

**Issue by littlehome-eugene** [getsentry/onpremise#567]
Can I just use `docker-compose up -d --build` after changing some setting?

**Comment by BYK** [comment]
You can run `docker-compose restart web worker cron`

**Comment by ankit-arora-369** [comment]
@BYK How to update only SMTP settings?
I don't want to resetup all the services using ./install.sh.

I have updated the settings in config.yml.

**Comment by BYK** [comment]
@ankit-arora-369, same as https://github.com/getsentry/onpremise/issues/567#issuecomment-656893817
