### ISSUE TITLE
HTTPS reverse proxy giving a non-secure warning due to assets 

### ISSUE THREAD

**Issue by thomasmoors** [getsentry/onpremise#57]
Only 2 assets are loaded over HTTP by default:

_static/1507896046/sentry/images/favicon.ico
_static/1507896046/sentry/images/icons/apple-touch-icon.png

![image](https://user-images.githubusercontent.com/486765/31551893-3f8736f6-b036-11e7-8194-0b1ba7d9442a.png)
Can those be set to https, without having to alter the source?

**Comment by thomasmoors** [comment]
I have "fixed" it now by configuring Nginx to replace all http:// strings to https:// with sub_filter"

`
proxy_set_header Accept-Encoding ""; # no compression allowed or next won't work
sub_filter 'http://'  'https://';
sub_filter_once off;
`

**Comment by RDLeiria** [comment]
@thomasmoors, thanks a lot man!

**Comment by CaptainHypertext** [comment]
This is a problem for me right now.  This really should be fixed, unless it's something I set up wrong.

**Comment by BYK** [comment]
@CaptainHypertext it is very likely that your `system.url-prefix` setting has the `http` in it. Replacing that with an `https` version should resolve your issue.

**Comment by thomasmoors** [comment]
@BYK is right, I forgot to update this topic, but it's just setting I missed an created a way to complex solution

**Comment by CaptainHypertext** [comment]
@BYK Yes, it looks like you would be correct, but oddly enough, my url prefix was set to the https url.  However the Root URL setting in my admin settings was set to http, and changing that fixed it.  Are these the same settings?  Does setting it in the app override the configuration?
Thanks

**Comment by BYK** [comment]
@CaptainHypertext - yes they are the same setting. Normally, when you set this via the config files, it should override the settings in the UI and disable that setting. Not sure what happened in your case.

**Comment by CaptainHypertext** [comment]
Probably just me bumbling around with this setup.  Thanks again!
