### ISSUE TITLE
some traceback cann't find in issues

### ISSUE THREAD

**Issue by yejiang125** [getsentry/onpremise#570]
I upgrade sentry from 9.2 to 10, and there are about 1200 process send traceback to sentry server, but i find that many issues send by some process cann't be found in sentry server web page。Through tcpdump, i find the nginx server received  these messages,  is there any other logs to help me solve this problem? Thanks very much

**Comment by BYK** [comment]
You may check `relay` and `web` logs: `docker-compose logs -f web relay`.

Closing as this is a somewhat bleak question and not an issue. Please use the [forums](https://forum.sentry.io) if you need more help.
