### ISSUE TITLE
Cannot access admin menu

### ISSUE THREAD

**Issue by NullIsNot0** [getsentry/onpremise#577]
On 9th of July I set up Sentry without changing anything in setup - just copying files to server and running `./install.sh`. Everything was working fine - I could access Admin menu http://mydomain.com:9000/manage/ and click through submenu items. Today I updated to latest version of this project, and I can't access admin menu (with first user created in system which has admin rights) - I get password prompt popup which does not go away if I enter password. If I enter incorrect password, it shows that password is incorrect, but when I enter correct password, it just pops up again.

![admin0](https://user-images.githubusercontent.com/12268397/87228716-b1eacb00-c3ab-11ea-8cb9-22010fb00118.png)

After reverting files back to commit [9d44b99](https://github.com/getsentry/onpremise/tree/9d44b99c5521239971a4be397fe68c9c3f0ac4f3) and running `./install.sh` and `docker-compose up -d`, admin menu started to work again.

![admin1](https://user-images.githubusercontent.com/12268397/87228752-dcd51f00-c3ab-11ea-8fd0-212bfe4b09f3.png)

I found out that something is broken in 10th of July commit [73213bc](https://github.com/getsentry/onpremise/tree/73213bc51f57e665df0077a2c323f9d9ee8d948d).

![commit](https://user-images.githubusercontent.com/12268397/87228993-5de0e600-c3ad-11ea-837f-07e8fc190ac2.png)

I even installed clean system on test Linux. Latest project version did not allow admin menu access, but when I reverted it back to [9d44b99](https://github.com/getsentry/onpremise/tree/9d44b99c5521239971a4be397fe68c9c3f0ac4f3), menu was accessible again.
Tried both on CentOS 7 (with latest available packages) and Ubuntu 20.04. Docker version 19.03.12, Docker Compose 1.26.2.
Both times (when working and not working) Sentry build version was `Sentry 20.7.0.dev0 92b1577` - so it's not the problem in Sentry's Docker image as both times it was `getsentry/sentry:92b1577`.

Logs in Docker output when working:
```
web_1 | 16:36:54 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://mydomain.com/api/0/internal/stats/?since=1593880614.914&resolution=1h&key=client-api.all-versions.responses.5xx' method=u'GET' ip_address=u'192.168.1.10')
web_1 | 16:36:55 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://mydomain.com/api/0/internal/stats/?since=1593880614.914&resolution=1h&key=events.total' method=u'GET' ip_address=u'192.168.1.10')
web_1 | 16:36:55 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://mydomain.com/api/0/internal/stats/?since=1593880614.914&resolution=1h&key=client-api.all-versions.responses.2xx' method=u'GET' ip_address=u'192.168.1.10')
web_1 | 16:36:55 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://mydomain.com/api/0/internal/stats/?since=1593880614.914&resolution=1h&key=events.dropped' method=u'GET' ip_address=u'192.168.1.10')
web_1 | 16:36:55 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://mydomain.com/api/0/internal/stats/?since=1593880614.914&resolution=1h&key=client-api.all-versions.responses.4xx' method=u'GET' ip_address=u'192.168.1.10')
```

Logs in Docker output when not working:
```
web_1 | 16:18:49 [INFO] sentry.superuser: superuser.logged-in (user_id=1 ip_address=u'192.168.1.10')
web_1 | 16:18:49 [INFO] sentry.auth: user.auth.success (username=u'hxxxxxxx@example.com' ip_address=u'192.168.1.10')
web_1 | 16:18:49 [WARNING] sentry.superuser: superuser.missing-cookie-token (user_id=1 ip_address=u'192.168.1.10')
```

**Comment by daxpedda** [comment]
I can confirm this, encountered the exact same problem just now after updating.

**Comment by BYK** [comment]
Thanks a lot for the very clear and detailed bug report @NullIsNot0 and apologies for the inconvenience!

I know exactly what is causing this and will submit a fix now.

**Comment by BYK** [comment]
Keep in mind that you'll need to apply the fix manually to your already existing `sentry.conf.py` file for this to work.
