### ISSUE TITLE
Can't run install.sh with content trust enabled.

### ISSUE THREAD

**Issue by willskates-cyberhawk** [getsentry/onpremise#580]
Heyah, we're having trouble installing sentry with docker's content trust enabled. I'm not sure how best to solve this with hub.docker.com.

**Summary**:
We have to turn off image verification to get the installer to run.

**Date**
13-07-2020

**Input**
*Note* These are run as the root user.
```bash
export DOCKER_CONTENT_TRUST=1
cd /var
git clone https://github.com/getsentry/onpremise.git sentry
cd sentry
./install.sh
```

**Expected**
Installer to move on to starting up containers.

**Result**
Installer fails with "does not have trust data" error.

**Result (output)**
Some service image(s) must be built from source by running:
    docker-compose build symbolicator-cleanup post-process-forwarder worker cron sentry-cleanup snuba-cleanup web ingest-consumer
Error: remote trust data does not exist for docker.io/getsentry/sentry: notary.docker.io does not have trust data for docker.io/getsentry/sentry

**Solution**
Use [```docker trust.....```](https://docs.docker.com/engine/security/trust/content_trust/) commands to sign docker image builds. However I'm not really sure how this works with hub.docker.com.

**Comment by BYK** [comment]
Hi @willskates-cyberhawk,

We currently don't sign our images so if your environment requires this, the error/warning you face is expected. We do not have any immediate plans to start signing our images but I'll leave the issue open in case anyone else stumbles on it or we decide to pull this into our roadmap.

**Comment by willskates-cyberhawk** [comment]
Hi @BYK,

Thanks very much for your reply and thank you for keeping the issue open. If possible I'd really appreciate

**Comment by BYK** [comment]
I'm going to close this issue as we don't have any plans to sign our images or enroll into the content trust system in the near future.
