### ISSUE TITLE
I could see no issues on the website, which is successfully posted to my server

### ISSUE THREAD

**Issue by yh27tc** [getsentry/onpremise#601]
for the first time, my vue project submited errors to the sentry server successfully, and i could see all issues on the website.
but after the upgrage of new release, i restarted my nginx server,then  i could not see any issues on the website, which is submited successfully and got reponse 200. 

eventtime i register a new account , it worked well again,
then i upgrade a new release, issues could not be seen again.

**Comment by BYK** [comment]
Is this sentry.io or are you using on-premise? If you are using on-premise please provide your install and service logs, otherwise it is impossible for us to help you with only this much information.

**Comment by BYK** [comment]
Closing due to lack of response.
