### ISSUE TITLE
CSRF Protection on API call

### ISSUE THREAD

**Issue by HCrane** [getsentry/onpremise#605]
## Important Details

How are you running Sentry?

Other, version x.y.z, [briefly describe your environment]
Running Sentry docker image from https://hub.docker.com/r/getsentry/sentry with this hash `42c170c4a61352db969b8ef811b0802016a076e7` on openshift (pods for memchaed redis and postgres are here and work together)

## Description

Setup the project and wanted to track a C project and did the example how to connect to sentry and tried the everything works event.

## Steps to Reproduce

1. Setup with docker image 
2. use example project to connect to sentry but it dos not work.
Logs:

``` bash
12:27:02 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /api/2/envelope/ (status_code=403 request=<WSGIRequest: POST u'/api/2/envelope/'>) --| 10.125.0.1 - - [21/Jul/2020:12:27:01 +0000] "POST /api/2/envelope/ HTTP/1.1" 403 5200 "-" "sentry.native/0.3.4"
```

DSN is set correctly without a trailing `/`. I am a bit at my wits end what could be the case of this.

**Comment by BYK** [comment]
@HCrane this is the answer: https://github.com/getsentry/onpremise/issues/605#issuecomment-661844101 (thanks @temoto!)

You can see how we do this over at https://github.com/getsentry/onpremise/blob/master/nginx/nginx.conf#L44

**Comment by simonfrey** [comment]
When using this via the relay I get another cors problem, as the cors request fails with a `400`.

Web container throws: `django.security.csrf: Forbidden (CSRF cookie not set.)` 
And relay container `WARN: Error occurred during request handling: One or more headers requested are not alloweẁ`

Nginx is is configured as in https://github.com/getsentry/onpremise/blob/master/nginx/nginx.conf with the exeception of using ssl and having the no-ssl redirect with 301. 

relay config:
```yaml
relay:
  upstream: "http://web:9000/"
  host: 0.0.0.0
  mode: proxy
  port: 3000
logging:
 level: WARN
```
