### ISSUE TITLE
Reducing in-place upgrade downtime

### ISSUE THREAD

**Issue by ktosiek** [getsentry/onpremise#607]
Currently `install.sh` stops the whole installation before pulling and building containers. Would it make sense to move that step later in the script, or even replacing it with restarting each container in turn?

**Comment by ktosiek** [comment]
This is especially useful for people with more involved builds, for example when using sentry-ldap-auth: https://github.com/getsentry/onpremise/issues/253. Moving the `$dc down` step to just after ` echo "Docker images built."` reduced downtime on upgrade from ~3 minutes to ~1:30.

**Comment by untitaker** [comment]
What is the most important component/endpoint that you want to keep available? Historically we did not want to commit to writing code that works for any rolling restart outside of our own production systems (e.g. can deal with data coming from old processes).

**Comment by ktosiek** [comment]
I'm mostly worried about events ingestion, I think that's `relay` + `nginx`? `web` would be nice to have too.

**Comment by BYK** [comment]
@ktosiek I think this makes sense as getting new images should not touch any of the already-running containers until a full down/up cycle.

Would you be willing to submit a PR for your idea & improvement?

**Comment by ktosiek** [comment]
I've made a PR for the late stop of the whole cluster. To get additional seconds of availability I'd need a way to stop "everything but nginx and relay", which doesn't seem to be provided by `docker-compose`. (I'm assuming relay can queue events for a minute without Kafka and Redis - but is that true?).

**Comment by BYK** [comment]
>To get additional seconds of availability I'd need a way to stop "everything but nginx and relay", which doesn't seem to be provided by docker-compose. (I'm assuming relay can queue events for a minute without Kafka and Redis - but is that true?).

I think you can use `docker-compose rm -s` as documented here: https://docs.docker.com/compose/reference/rm/
Combined with `docker-compose config --services` and a clever `grep`, it should get you the list of all services but `nginx` and `relay`. And, yes, relay can buffer things for a while so this would work as long as you don't forget to upgrade `nginx` and `relay` themselves afterwards.

This may become tricky if there are any cross-dependencies between `relay` and `sentry` though. Any thoughts @mattrobenolt, @jan-auer, @untitaker?

**Comment by mattrobenolt** [comment]
> This may become tricky if there are any cross-dependencies between relay and sentry though.

This is rarely the case if ever. You should be safe 99% of the time with the assumption that they can operate independently.

**Comment by untitaker** [comment]
I think for relay to stay operational while sentry is down, nginx, redis and kafka need to be up.
