### ISSUE TITLE
Get DSN programatically

### ISSUE THREAD

**Issue by Klaitos** [getsentry/onpremise#610]
Hello,

I did not found a way to get a project DSN programatically as a step in CD deployment. 
I am currently building and deploying with Terraform and Docker with one click a full internal environnement for my team (a backend with a frontend. I would like to deploy a Sentry stack but i'm stuck at retrieving and saving project DSN in a .env for my backend.

I did research with the sentry api and sentry-cli without solution.

Please advice.

**Comment by BYK** [comment]
Hi,

To be able to get the project DSN through the API, you need to jump a few hoops. We do this in our test script so take a look at there:

https://github.com/getsentry/onpremise/blob/4dbfcbcebe9d7ea54bd009bb85a331dc6ef51295/test.sh#L71

**Comment by BYK** [comment]
(closed as this is not an issue but a question, please use [the forum](https://forum.sentry.io) next time 😉 )
