### ISSUE TITLE
Pass Flag to install script for User creation prompt

### ISSUE THREAD

**Issue by cwillhelm** [getsentry/onpremise#611]
Why isn't it possible to simply pass `-n` or another flag to the install script to _not_ create a user? I'm installing through Puppet and it keeps breaking at this step (because of the interactivity I'm assuming). I see that the script does check for an interactive prompt, but it would be nice to have this alternative approach for more flexibility in the install process. If I missed something please point me in the right direction!

**Comment by BYK** [comment]
> If I missed something please point me in the right direction!

You can submit a PR that does what you ask? 🙂 

I wonder why the interactivity check fails though so I'd rather make it more robust instead of adding a new option.

I guess we can replace the blunt `CI` env var check with something like this: https://unix.stackexchange.com/a/26782/108960?

**Comment by bonzobavaria** [comment]
Has there been any more consideration on this? I'm trying to install onpremise in an AWS EC2 instance using Pulumi, and it's a no-go. If I connect with the instance and view the install log, it shows the user prompt, followed by:

`Aborted! An error occurred, caught SIGERR on line 269`

Solutions such as `yes n | ./install.sh` are also not viable. I'd be happy with any viable solution, and would be happy to help. My work life will be happier if I can accomplish this deployment somehow.

**Comment by BYK** [comment]
See my previous comment please:

1. You can simply set `CI=1` before running the script like `CI=1 ./install.sh`
2. You can submit a pull request to both improve the non-interactive terminal detection _and_ add a flag

**Comment by kwaddledxs** [comment]
Thanks for your response. It wasn't exactly clear to me from your response that I should override the `CI` environment variable to prevent the user prompt, and unfortunately for some reason I'm struggling to debug, that solution isn't working for me. The create user prompt is still happening. I have to modify `install.sh` to get the installation to happen without the prompt, but unfortunately adding and maintaining a modified install script creates numerous extra difficulties.

I'll be happy to work on creating a PR to add a `--no-user-prompt` flag or similar, but unfortunately I'm not an accomplished bash developer, and I'll need to brush up on best practices for parsing flags in bash.

**Comment by bonzobavaria** [comment]
Pull Request #646
