### ISSUE TITLE
Used storage increasing daily

### ISSUE THREAD

**Issue by mschickervxob** [getsentry/onpremise#619]
We have cleanup in cron but still used space is increasing. But Cleanup only deletes old issues? 

I deleted some debug info files manually - quite large some gigs - but still the used storage did not decrease at all.

How to purge debug-symbols/old releases or non public releases regularly?

Thanks.

**Comment by BYK** [comment]
Hi @mschickervxob, I think [the forum](https://forum.sentry.io) is a better place to discuss this. There's already a similar topic: https://forum.sentry.io/t/manual-clean-up/10631/4

I'd say check which service/volume is consuming the most space first and then we can help you go in the right direction.

**Comment by BYK** [comment]
Closing in favor of a forum discussion. Will reopen if we find a bug in the existing implementation.
