### ISSUE TITLE
not able to add user from host:9000/admin , throwing error  seems postgres connection is not established

### ISSUE THREAD

**Issue by vishnu123sai** [getsentry/onpremise#621]
not able to add user from host:9000/admin , throwing error  seems postgres connection is not established. 

even the dump i have added is not reflecting in sentry in sentry 10.0.0

**Comment by BYK** [comment]
Hi @vishnu123sai, without more details like installation and service logs, it is not possible to figure out what may be going wrong.

**Comment by BYK** [comment]
Closing due to lack of response.
