### ISSUE TITLE
Once I installed a fresh Sentry v20, how to upgrade to newer versions later?

### ISSUE THREAD

**Issue by pedrofurtado** [getsentry/onpremise#623]
Once I installed a fresh Sentry v20, how to upgrade to newer versions later?

**Comment by NullIsNot0** [comment]
Upgrading info here: Info here: https://github.com/getsentry/onpremise#updating-sentry

In short:
1) Make full backup of your system
2) Copy new files over existing ones
3) Run ./install.sh

**Comment by BYK** [comment]
Even more at here now: https://develop.sentry.dev/self-hosted/#upgrading
