### ISSUE TITLE
IndentationError on fresh master branch pull

### ISSUE THREAD

**Issue by multinerd** [getsentry/onpremise#624]
This is a fresh pull of master branch, didnt touch the config files as yet. Simply running `install.sh` produces the following: 

https://gist.github.com/multinerd/dea70020e340e9c3707b45890f619d82

**Comment by BYK** [comment]
Looks like your `sentry.conf.py` file has a bug in it. Mind sharing that as we are sure the latest master works with the default file (just released 20.8.0 with CI tests passing from master).

**Comment by multinerd** [comment]
https://gist.github.com/multinerd/dea70020e340e9c3707b45890f619d82#file-sentry-py

Thats the current `sentry.conf.py` file that was created. 

Ill try again in a bit with the latest changes and report back.

**Comment by BYK** [comment]
There the error is, shining: https://gist.github.com/multinerd/dea70020e340e9c3707b45890f619d82#file-sentry-py-L165-L166

I think this is an issue with our `./install.sh`, checking...

**Comment by BYK** [comment]
@multinerd found the issue, submitted a fix. Thanks a lot for the report & follow-up and apologies for the inconvenience.

**Comment by multinerd** [comment]
Fresh pull, 20.8, all good now. Thanks for the quick turn around time.
