### ISSUE TITLE
Connect to ipv4#172.19.0.10:9092 failed: Connection refused

### ISSUE THREAD

**Issue by adrielliu** [getsentry/onpremise#633]
%3|1597742901.053|FAIL|rdkafka#consumer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: 
%3|1597742901.053|ERROR|rdkafka#consumer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.19.0.10:9092 failed: Connection refused
%3|1597742901.053|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.19.0.10:9092 failed: Connection refused
%3|1597742901.053|ERROR|rdkafka#consumer-2| [thrd:kafka:9092/bootstrap]: 1/1 brokers are down
%3|1597742901.053|ERROR|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.19.0.10:9092 failed: Connection refused
%3|1597742901.053|ERROR|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: 1/1 brokers are down
%3|1597743224.187|FAIL|rdkafka#consumer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/1001: Disconnected
%3|1597743224.187|ERROR|rdkafka#consumer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/1001: Disconnected
%3|1597743224.187|ERROR|rdkafka#consumer-2| [thrd:kafka:9092/bootstrap]: 1/1 brokers are down
%3|1597743224.190|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1001: Disconnected
%3|1597743224.190|ERROR|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1001: Disconnected
%3|1597743224.190|ERROR|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: 1/1 brokers are down
%3|1597743224.288|FAIL|rdkafka#consumer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/1001: Connect to ipv4#172.19.0.10:9092 failed: Connection refused
%3|1597743224.288|ERROR|rdkafka#consumer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/1001: Connect to ipv4#172.19.0.10:9092 failed: Connection refused
%3|1597743224.290|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1001: Connect to ipv4#172.19.0.10:9092 failed: Connection refused
%3|1597743224.290|ERROR|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/1001: Connect to ipv4#172.19.0.10:9092 failed: Connection refused

**Comment by ansonhorse** [comment]
Have you solved this problem？

**Comment by Przeblysk** [comment]
same Issues

**Comment by yocaning** [comment]
i got this,have you solved ? i cannot find the solution
