### ISSUE TITLE
Hyperlinks have ports in their url

### ISSUE THREAD

**Issue by norbertpy** [getsentry/onpremise#64]
I'm trying to put an `nginx` on top of the `web` container and not expose it directly to outside. Everything is working as expected but some of the links on the UI are pointing to `9000` port and fail.

For instance, if I'm not the dashboard page, the `History` is correctly pointing to `http://whatever/organizations/sentry/auth/`. But if I go to `auth` page then the same `History` link is pointing to `http://whatever:9000/organizations/sentry/issues/history/`.

How can I fix this?

![dash](https://user-images.githubusercontent.com/10294525/32626166-6b36a260-c543-11e7-8796-66f3da0d76f8.png)
![auth](https://user-images.githubusercontent.com/10294525/32626176-700346d6-c543-11e7-996e-358f85680a9c.png)

**Comment by dcramer** [comment]
You need to configure the Sentry installation to have the correct URL prefix. That said, the issue tracker is not a support forum, and I'm closing this to keep noise at a minimum.

**Comment by norbertpy** [comment]
I filed that because I though it's an `issue`. Why? Because some of the links work some of them not. Would have been great if you could point to some docs regarding that instead of passive-aggresive comment.

**Comment by dcramer** [comment]
@norbertpy its not passive aggressive, its simply direct:

https://docs.sentry.io/support/

The docs should cover all configuration within Sentry, and this almost certainly isn't an issue in Sentry's core as we'd have seen this in numerous other forms.

(we love that people use Sentry, but if we let everyone use our issue tracker as free support we wouldn't be able to get anything done)

**Comment by norbertpy** [comment]
Awesome. I found this on github and had no idea the support forum exist. Sorry for the inconvenience and thanks.

**Comment by dcramer** [comment]
I guess we dont have the ISSUE_TEMPLATE that we have on sentry which tries to help people understand better where docs/support can go. Something we should certainly follow up with.

You'll find everything you need here though: https://docs.sentry.io/server/config/
