### ISSUE TITLE
Documentation: This a help request on how to configure SSO with google on sentry

### ISSUE THREAD

**Issue by thapakazi** [getsentry/onpremise#640]
**Motivation** Need help finding docs (or writing one if missing) regard to SSO with google on sentry

As of now, I found very few resources on "how to do login with google" on sentry which are not easily digestible :cry: 
Resource I have found so far more related are:
- https://docs.sentry.io/accounts/sso/#google-business-app
- https://support.google.com/a/answer/7674800?hl=en 

Please guide me to the documentation if I am searching blind :see_no_evil: 
Thanks

**Comment by thapakazi** [comment]
Thanks BYK

**Comment by thapakazi** [comment]
Finally able to configure it. :green_heart: 
![screenshot-20200828-15:37:13](https://user-images.githubusercontent.com/1695906/91550591-7cdd0c80-e948-11ea-8b23-fd7583987a4c.png)

**Learnings**:
1. sso with google is built in on latest sentry release (I am at 20.7.2 46de988)
2. we need to create google project and configure credentials and get client id and client secret
like explained here: https://github.com/getsentry/sentry-auth-google#setup

3. then update the sentry.conf.py (I used helm, its under configmap sentry-sentry and restart pod)

**Comment by BYK** [comment]
Thanks for sharing this @thapakazi! I'll keep the issue open until we have some official documentation in place for this 😄

**Comment by thapakazi** [comment]
Hehe, okay.
btw, who is doing the docs ?

**Comment by BYK** [comment]
@thapakazi me? 🙂
