### ISSUE TITLE
Cannot switch between organizations via UI

### ISSUE THREAD

**Issue by ingria** [getsentry/onpremise#641]
Also there's no way to _create_ a new organization (only by manually navigating to /organizations/new in browser).

I’ve migrated from Sentry 9 to Sentry 20.9 (20.9.0.dev 0295d95b). Since everything works fine on `sentry.io`, I assume that's something wrong with `onpremise`.
 
This is how user menu looked like in Sentry 9 (and looks on `sentry.io` at the moment):

![image](https://user-images.githubusercontent.com/2178368/90967692-b8607c80-e4eb-11ea-93fc-1f2c7c57dbb6.png)

And the same menu in Sentry 20 on-premise:

![image](https://user-images.githubusercontent.com/2178368/90967702-cf9f6a00-e4eb-11ea-8932-3a92c87d900f.png)

**Comment by BYK** [comment]
You may need to set `SENTRY_SINGLE_ORGANIZATION=False` in your `sentry.conf.py` file.

**Comment by ingria** [comment]
Yes, this was it. Somehow this setting was lost during upgrade.

Thanks!

**Comment by marbon87** [comment]
Are multiple organizations supported for sentry on premise?

**Comment by BYK** [comment]
@marbon87 for sure. It is just not turned on by default. On-premise uses the same code that runs on production. Only differences are around billing code.
