### ISSUE TITLE
ERROR: Service 'sentry-cleanup' failed to build

### ISSUE THREAD

**Issue by uhlhosting** [getsentry/onpremise#643]
Tried to run:

`docker-compose build --pull && docker-compose run --rm web upgrade && docker-compose up -d`

```
Successfully built 78a78f51f233
Successfully tagged sentry-onpremise-local:latest
Building sentry-cleanup
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
ERROR: Service 'sentry-cleanup' failed to build: pull access denied for sentry-onpremise-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

How can I fix this?

**Comment by BYK** [comment]
Please use the bundled `install.sh` script which handles this case.

**Comment by uhlhosting** [comment]
@BYK I did so, that leaded to break my whole setup, I had to go and restore my VPS entirely.

**Comment by BYK** [comment]
>@BYK I did so, that leaded to break my whole setup, I had to go and restore my VPS entirely.

If you can file an issue about how it broke, we'd love to fix it if we can.

**Comment by uhlhosting** [comment]
@BYK I have continued this on the community thread. https://forum.sentry.io/t/unable-to-upgrade-stuck-on-version-9-1-2/10846/8
