### ISSUE TITLE
AWS EC2 server crashes after some time

### ISSUE THREAD

**Issue by mintwzy** [getsentry/onpremise#644]
I successfully installed the Sentry on AWS EC2 sever, and I can receive error event from my project. But the EC2 server will crash after about 1 day. I cannot ssh into the server, and I cannot access the Sentry web page. But all work well if I stop and start the server from the AWS console.

Anyone encountered this problem before? Thanks!

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
