### ISSUE TITLE
服务器买的小了,有办法安装吗

### ISSUE THREAD

**Issue by hhcol620** [getsentry/onpremise#647]
## Version Information

Version: *VERSION HERE*

## Description

[What happened]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

## Logs

Please share any applicable logs:

- ./install.sh logs
- `docker-compose logs` output

**Comment by BYK** [comment]
Closing due to incomplete report. Based on Google Translate, the title says "The server is too small, is there a way to install it", which implies this is more of a question for the forum anyway: https://forum.sentry.io
