### ISSUE TITLE
Installation with install.sh error 220

### ISSUE THREAD

**Issue by bdbais** [getsentry/onpremise#652]
## Version Information

Version: lastest from repository  

## Description

I follow instruction to install:   cloned repository and start install.sh

git clone https://github.com/getsentry/onpremise.git
Cloning into 'onpremise'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 1014 (delta 7), reused 15 (delta 3), pack-reused 985
Receiving objects: 100% (1014/1014), 303.57 KiB | 1.29 MiB/s, done.
Resolving deltas: 100% (544/544), done.
root@linux:/usr/local/sentry# ls
onpremise
root@linux:/usr/local/sentry# cd onpremise/
**root@linux:/usr/local/sentry/onpremise# ls -la
total 108
drwxr-xr-x 11 root root  4096 Sep  1 12:39 .
drwxr-xr-x  3 root root  4096 Sep  1 12:39 ..
-rw-r--r--  1 root root   245 Sep  1 12:39 .craft.yml
drwxr-xr-x  2 root root  4096 Sep  1 12:39 cron
-rw-r--r--  1 root root  6611 Sep  1 12:39 docker-compose.yml
**
[...]

Digest: sha256:89c0b3f2be29c68394ec1b9d6d61a7b3c5e110c16d959db9ec3ebdbc7ae61359
Status: Downloaded newer image for getsentry/sentry:latest
docker.io/getsentry/sentry:latest

Building and tagging Docker images...

        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

An error occurred, caught SIGERR on line 220
Cleaning up...

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

## Logs

Please share any applicable logs:

- ./install.sh logs

root@rei-linux:/usr/local/sentry/onpremise# ./install.sh logs
root@rei-linux:/usr/local/sentry/onpremise# Unexpected argument: 'logs'. Use --help for usage information.

- `docker-compose logs` output

root@rei-linux:/usr/local/sentry/onpremise# docker-compose logs
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by BYK** [comment]
`./install.sh logs` is not a command, the install script automatically generates some log files with the timestamp 😀  - anyway, I'll clarify the issue template for this.

My guess would be the missing `+x` permission on your `docker-compose.yml` file as it is clearly there.

**Comment by BYK** [comment]
Closing due to lack of response.
