### ISSUE TITLE
README Improvement

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [getsentry/onpremise#653]
## Summary

It was fairly difficult self hosting sentry on my own with little missing pieces of information
- Which port does the dashboard come up on
- How do I configure sentry with nginx
- After I update the configuration for mail service, how do I make my installation reflect it

## Motivation

This will make it easier for more people to get sentry installed on their first go

## Additional Context

I was installing sentry on an AWS ubuntu instance. This blog has a great set of steps that finally helped me do this in a single attempt but it's fairly difficult to find it via search
[Steps to install sentry](https://cleody.com/install-sentry-on-ubuntu-18-04-using-nginx-and-letsencrypt-certificates/
)

P.S: I'd be happy to raise a PR to do this

**Comment by BYK** [comment]
Hi @Nikhil-Nandagopal and thanks a lot for raising this! We are aware and _just_ released https://develop.sentry.dev/self-hosted/. We are also adding more resources day by day to cover [all issues labeled by docs](https://github.com/getsentry/onpremise/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22category%3A+docs%22).

Would you mind taking a look at that and provide some feedback?

**Comment by Nikhil-Nandagopal** [comment]
Hi @BYK glad to see these docs shaping up! My one feedback is that the part we really struggled with was SSL. This was because the on-premise Github page directed us to add nginx to docker-compose.yml while it was already present there and that lead to a host of other problems. Ultimately installing nginx separately and updating the default conf was what worked for us. Additionally you could also automate this like we do in appsmith
[Install Gist](https://github.com/appsmithorg/appsmith/blob/350ea64ab604d8c238ea74a735149b25344871fb/deploy/install.sh#L446
)
We also went ahead and automatically downloaded docker and docker-compose to make it dead easy to install 😃

**Comment by BYK** [comment]
>This was because the on-premise Github page directed us to add nginx to docker-compose.yml while it was already present there and that lead to a host of other problems. 

Ah, great catch! This was put there before we introduced Nginx into the mix. I'll go ahead and fix that now.

>Additionally you could also automate this like we do in appsmith
>We also went ahead and automatically downloaded docker and docker-compose to make it dead easy to install 😃

Thanks for the suggestion. Since we expect this script to run on various different operating systems, I'm not sure if we can assume a single way to install Docker and Docker Compose.
