### ISSUE TITLE
generate-secret-key returns error: <error: exec: "tini": executable file not found in $PATH>

### ISSUE THREAD

**Issue by xaionaro** [getsentry/onpremise#66]
Hello. I've tried to follow `README.md` and got an error on the second step:

```
$ docker-compose run --rm web config generate-secret-key
error: exec: "tini": executable file not found in $PATH
```

**Comment by mattrobenolt** [comment]
I'm not sure what you're doing to get this, but `tini` should be baked in. If it wasn't, there'd be significantly more widespread issues.
