### ISSUE TITLE
self-hosted sentry report error occur cors error

### ISSUE THREAD

**Issue by llisonly** [getsentry/onpremise#666]
## Version Information

Version: 20.8.0

## Description
when i report an error to sentry web manage platform i find an error，the screen is bellow
![image](https://user-images.githubusercontent.com/4126495/92570329-58702100-f2b4-11ea-946d-bc3fca3026a7.png)

![image](https://user-images.githubusercontent.com/4126495/92570509-94a38180-f2b4-11ea-837b-caa5df1dcc86.png)
![image](https://user-images.githubusercontent.com/4126495/92570586-aa18ab80-f2b4-11ea-96bb-e8391b573a96.png)
![image](https://user-images.githubusercontent.com/4126495/92580564-1bf6f200-f2c1-11ea-85e8-f41b98d143fa.png)

how can i fix it

**Comment by BYK** [comment]
Looks like you are not using the built-in `nginx` service which would direct these requests to `relay`.

**Comment by llisonly** [comment]
@BYK i use onpremise nginx ，i have a question bellow
![image](https://user-images.githubusercontent.com/4126495/92699385-1ad8ca00-f380-11ea-8dc1-d88f4fe780ee.png)
nginx config file
![image](https://user-images.githubusercontent.com/4126495/92699538-49ef3b80-f380-11ea-840c-cd14e9bfcd7e.png)
docker-compose.yml
![image](https://user-images.githubusercontent.com/4126495/92699636-6e4b1800-f380-11ea-8b29-03f9280d6a6e.png)
![image](https://user-images.githubusercontent.com/4126495/92699687-7c993400-f380-11ea-9f6b-4fbd52011e61.png)

**Comment by BYK** [comment]
Hi @llisonly - it is very hard to work with screenshots so can you please provide logs as text.

It seems like Relay having some issues connecting to Sentry and potentially other networking/dns issues but very hard to tell as I can't read the logs much.

**Comment by llisonly** [comment]
thank you , there is no problem now
