### ISSUE TITLE
host not found in upstream "relay:3000" in /etc/nginx/nginx.conf:55

### ISSUE THREAD

**Issue by phobos-dthorga** [getsentry/onpremise#675]
Hello!

We're currently using Sentry onpremise, v`20.8.0`, and have been experiencing issues with the `nginx` portion crashing sometime (within hours) after executing `docker-compose up -d` with the following error below:

```2020/09/14 20:34:19 [emerg] 1#1: host not found in upstream "relay:3000" in /etc/nginx/nginx.conf:55 
root@sentry:~# docker logs 7eabf4234c7e
nginx: [emerg] host not found in upstream "relay:3000" in /etc/nginx/nginx.conf:55 
root@sentry:~#
```

We are running Sentry onpremise under a KVM machine on a self-hosted dedicated server using Ubuntu 18.04 LTS, although I can't remember which version of Python we are using. But everything used to be alright up and until a few weeks ago.

So yeah, this has been ongoing for some weeks now and I'm not sure what to do, hence why I'm reaching out via an Issue ticket here. Any and all help would be appreciated, thank you.

**Comment by BYK** [comment]
Looks like a DNS issue in docker-compose. Have you made any changes to your host configuration?

**Comment by BYK** [comment]
Closing due to lack of response.

**Comment by Fleuri** [comment]
I'd wish to reopen this. I have the same issue: Nginx cannot be restarted because nginx: [emerg] host not found in upstream "relay:3000" in /etc/nginx/nginx.conf:55.

Relay is running though. I have pulled the latest sentry-onpremise from master branch, done a reinstall etc. The only modifiation I've done is that I'm using GCP Cloudsql as the database backend.

**Comment by BYK** [comment]
@Fleuri please use the forums first as a support channel. Our CI works without issues with the current default config and setup so this is very likely to be an issue with your configuration rather than being a bug.
