### ISSUE TITLE
metric alert never trigger

### ISSUE THREAD

**Issue by GaoYuJian** [getsentry/onpremise#677]
## Version Information

Version: *Sentry 20.9.0.dev00d0cb1f*

## Description
metric alert never trigger

## Steps to Reproduce

1. open `organizations:incidents` in sentry.conf.py
2. create a metric alert rule
3. alert never trigger

**Comment by lynnagara** [comment]
I assume this is because the subscriptions consumer is not running in onpremise. @BYK - is this feature supposed to be already released to onpremise?

**Comment by BYK** [comment]
Hi @GaoYuJian - We don't support metric alerts on self-hosted Sentry yet. As @lynnagara pointed out, there's a new consumer that needs to run (and potentially some other infra that needs to be put in place).

We are planning to add support for metric alerts in the near future though.
