### ISSUE TITLE
where is the data stored and how to connect to database

### ISSUE THREAD

**Issue by lzz2017** [getsentry/onpremise#678]
We use the install.sh,  then is success. now  we want to how to store the data, and where is it stored?

**Comment by VentyCZ** [comment]
The data is stored in Postgres database (see [docker-compose.yml section](https://github.com/getsentry/onpremise/blob/master/docker-compose.yml#L59))

If you'd like to connect to the database, I used this technique:
1 - Update docker-compose.yml to expose the Postgres server to host.
```
postgres:
    ports:
      - '127.0.0.1:5432:5432/tcp'
```
2 - Use something like [Adminer](https://www.adminer.org/en/) to connect to the database remotely (username: postgres, no password) - ensure, that the interface is not accessible to other parties as they can trash the db

**Comment by lzz2017** [comment]
After connecting to the database, I didn't see the table or the data

> 
![image](https://user-images.githubusercontent.com/28996304/93864105-fde4b500-fcf6-11ea-87a8-cc87c1b3e621.png)

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.

PS: Thanks for the help @VentyCZ!
