### ISSUE TITLE
web works well, but can't capture exception via code

### ISSUE THREAD

**Issue by fflskh** [getsentry/onpremise#68]
Hi, 
I installed sentry, and the web works well, but I can't capture exception via nodejs code, I've checked the DSN, and it correct. Here's my code,
```
var Raven = require('raven');
Raven.config('http://2c485cf04ad2454a8d34015701f674d8:1451ffec89e54ae9aaf98c4bb0117a52@localhost:9000/1').install();

try {
    throw new Error('some error');
} catch (e) {
    Raven.captureException(e);
}

setTimeout(function(){}, 3000);
```

I ran the code, and got this error, I don't know why
```
/usr/local/bin/node index.js
raven@2.2.1 alert: failed to send exception to sentry: socket hang up
{ Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 'ECONNRESET' }
```

Could someone help me and give some suggestions?

**Comment by riyajk** [comment]
any luck on this?

**Comment by pbvarga1** [comment]
If you are on dockertoolbox then the ``localhost`` in your DSN should be replaced by ``192.168.99.100`` as that is the IP address for the VM (run ``docker-machine ip`` and see the output). That worked for me. The other thing you can do is make sure the sentry worker, web, and cron are running before the application that throws the error

**Comment by BYK** [comment]
Closing as the issue is quite old and stale and I think @pbvarga1's answer provides enough hints to remedy. Please open a new issue if you think there's still something that needs to be fixed/addressed.
