### ISSUE TITLE
Docker minimum version

### ISSUE THREAD

**Issue by christopherowen** [getsentry/onpremise#680]
## Version Information

Version: 2.9.0

## Description

The minimum docker version was updated to 19.03.12 in install.sh

## Request

the current version of docker in Amazon Linux 2, with Amazon Linux extras is 19.03.6

```
# yum info docker
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
202 packages excluded due to repository priority protections
Installed Packages
Name        : docker
Arch        : x86_64
Version     : 19.03.6ce
Release     : 4.amzn2
Size        : 161 M
Repo        : installed
From repo   : amzn2extra-docker
```
  
I see we reduced the docker version requirement for GCP, could it be reduced further to the AML version?

**Comment by BYK** [comment]
Thanks for raising this! Yeah, I think we can flex this a bit for now.
