### ISSUE TITLE
InvalidConfiguration: Error -2 connecting to redis:6379. Name or service not known.

### ISSUE THREAD

**Issue by robov** [getsentry/onpremise#69]
I downloaded your repo
added the secret key
but now on the web upgrade I get : InvalidConfiguration: Error -2 connecting to redis:6379. Name or service not known.

**Comment by robov** [comment]
The only error I could see is
 WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value ... THAN 128

**Comment by dcramer** [comment]
@robov I would go over the instructions again, but the error is saying 'cannot find the redis service'. Note this issue tracker is for just that, issues in the project. If you need support/advice you can use our community forum:

https://forum.sentry.io
