### ISSUE TITLE
After Upgrading from 10.0.1-dev0 to 20.7.0 there are no new Events in Frontend

### ISSUE THREAD

**Issue by CyberLine** [getsentry/onpremise#691]
## Version Information

Version: 20.7.0

## Description

[What happened]

After upgrading from 10.0.1-dev0 to 20.7.0 i can see in the logs, that new Events are POSTed, but i can not see any new event in the Frontend.

## Logs

`10.111.121.11 - - [01/Oct/2020:07:27:47 +0000] "POST /api/3/store/ HTTP/1.1" 200 41 "-" "sentry.php/2.4.2"`

**Comment by mjmucha** [comment]
I have exactly the same problem with a fresh install of Sentry from the master branch (Sentry 20.10.0.dev 0f0a54df).
During installation i also get these error messages:
```
|1601560476.220|FAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.29.0.6:9092 failed: Connection refused (after 4ms in state CONNECT)
|1601560477.218|FAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.29.0.6:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2020-10-01 13:54:37,220 Connection to Kafka failed (attempt 0)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 58, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
|1601560478.224|FAIL|rdkafka#producer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.29.0.6:9092 failed: Connection refused (after 1ms in state CONNECT)
|1601560479.228|FAIL|rdkafka#producer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.29.0.6:9092 failed: Connection refused (after 1ms in state CONNECT, 1 identical error(s) suppressed)
2020-10-01 13:54:39,228 Connection to Kafka failed (attempt 1)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 58, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
|1601560480.232|FAIL|rdkafka#producer-3| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.29.0.6:9092 failed: Connection refused (after 1ms in state CONNECT)
|1601560481.231|FAIL|rdkafka#producer-3| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.29.0.6:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2020-10-01 13:54:41,232 Connection to Kafka failed (attempt 2)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 58, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
```

**Comment by CyberLine** [comment]
@mjmucha i had those errors too during install but now there are no errors in any docker containers ...

**Comment by BYK** [comment]
Looks like your Kafka instance is having connectivity issues. I recommend restarting all services to see if this resolves the issue.

**Comment by mjmucha** [comment]
Sadly it doesn't.

**Comment by BYK** [comment]
@mjmucha you may be running out of memory and getting your instances killed by the OOM killer. Could that be the case

**Comment by mjmucha** [comment]
Without Sentry running our server has over 10GB of memory left. So i doubt that there isn't enough memory for a clean instance.
By the way. I'm running CenotOS 8 with SELinux. The compose file is already modified to work with SELinux.

**Comment by CyberLine** [comment]
> Looks like your Kafka instance is having connectivity issues. I recommend restarting all services to see if this resolves the issue.

nope. already tryd that. no errors in kafka container but still no new issues in the frontend.

**Comment by BYK** [comment]
>Without Sentry running, our server has over 10GB of memory left. So i doubt that there isn't enough memory for a clean instance.

Never underestimate the memory hunger of Clickhouse and Kafka :D

@cyberline @mjmucha - I don't think I can provide anything more without more detailed logs. There were some more people having similar issues over at the forum and since this doesn't seem to be a bug in this repo that we can fix, I'll go ahead and close the issue in favor of pursuing the conversation at [the forum](https://forum.sentry.io).
