### ISSUE TITLE
Install the last stable version by default

### ISSUE THREAD

**Issue by soullivaneuh** [getsentry/onpremise#696]
## Summary

After a fresh install, I have a dev version setup:

![image](https://user-images.githubusercontent.com/1698357/95223404-d236f400-07f9-11eb-8eee-f4b6f5e4d5ae.png)

The current stable as I'm writing the issue is [`v20.9.0`](https://github.com/getsentry/sentry/releases/tag/20.9.0).

It would be great to install the default stable instead of the dev version and/or propose version related docker image tag instead of commits. (e.g. `20`, `20.9`, `20.9.0`...)

## Motivation

When we setup a new product, we generally expect to use a stable version of this one, especially for production.

Also, the only current way to setup a fixed version is too provide the git hash which is not very user friendly.

**Comment by soullivaneuh** [comment]
My bad, docker tag with release currently exists.

Still, having a default update to the latest stable instead of master would be better. :+1:

**Comment by BYK** [comment]
I think this is mostly a documentation issue as we clearly say "Nightly" at the top header and direct people to the latest release from https://develop.sentry.dev/self-hosted.

I guess we can add a banner telling people to go to the latest release tag with a link in it, what do you think?

Also, would you mind sharing how you landed on the repo main page to track the source that you brought you here? (for instance if it is Google, then my suggestion above would be useful, if some of our docs point you here, they should be updated).

**Comment by itsnotvalid** [comment]
I use both on-prem and cloud-based version, while cloud-based has no indication of versioning (for obvious reasons), however, the latest release do yield `Sentry Acceptance Test`: `test` as version.

**Comment by BYK** [comment]
>however, the latest release do yield Sentry Acceptance Test: test as version.

Can you explain what you mean by this?

**Comment by BYK** [comment]
@itsnotvalid please follow getsentry/sentry#21409 for future updates. We'll release `20.10.1` with a fix soon. That said this is purely a cosmetical issue and I can assure you that you are running Sentry `20.10.0`.

**Comment by itsnotvalid** [comment]
@BYK thanks for your prompt reply. Just to also note that on `20.10.0`, pages that display some secrets (e.g. DSN) would show something like `__DSN__` which likely to be also related to turning `CI=1`. I double-checked by making a fresh nightly build install, found to be of the same case.

**Comment by BYK** [comment]
@itsnotvalid yup, very likely to be related and I just merged a fix. Let's continue over at getsentry/sentry#21409 as this is not relevant to the current issue here.

**Comment by soullivaneuh** [comment]
> I guess we can add a banner telling people to go to the latest release tag with a link in it, what do you think?

In my opinion, it would be better to have `latest` releasing a stable version or have a special tag.

Something like this (.env example):

```
SENTRY_IMAGE=getsentry/sentry:stable
SNUBA_IMAGE=getsentry/snuba:stable
RELAY_IMAGE=getsentry/relay:stable
SYMBOLICATOR_IMAGE=getsentry/symbolicator:stable
```

Thanks to that, we can simply run `./install.sh` without having to worry about the image env providing.

Many users like myself will just fo `./install.sh` without asking as its provided on the documentation: https://github.com/getsentry/onpremise#setup

Side note: Having a `.env.local` and something like that would help to have a local configuration without getting a diff with git.

**Comment by soullivaneuh** [comment]
Oh it looks like you did a change on https://github.com/getsentry/onpremise/pull/703.

But now I don't understand:

```
❯ docker run getsentry/sentry:nightly sentry --version
sentry, version 20.10.1 (d76c13dcbc6d)

~
❯ docker run getsentry/sentry:latest sentry --version
sentry, version 20.10.1 (78833d943440)
```

According to the commit version, `latest` looks to be the [real stable release](https://github.com/getsentry/sentry/releases/tag/20.10.1).

So in that case, we should keep on latest. Am I right?

**Comment by BYK** [comment]
@soullivaneuh - yeah, we decided to make `:latest` to point to the _latest stable_ release to align better with Docker conventions and renamed the nightly builds to, well `:nightly`.

Since we want the latest master of this repo to be nightly releases, it defaults to the new `:nightly` tags, which doesn't address this issue.

**Comment by BYK** [comment]
@soullivaneuh I think we have addressed your request/concern so closing this issue.

Let us know if that's not the case please.
