### ISSUE TITLE
Clickhouse server failed to come up in 5 tries

### ISSUE THREAD

**Issue by llisonly** [getsentry/onpremise#699]
Version: 20.8

System: Centos 7.5

when i run ./install.sh, i have this problem, the logs is bellow

Docker images built.
Removing network onpremise_default
Network onpremise_default not found.
Removing ltierrorreporting_clickhouse_1 ... 
Removing ltierrorreporting_clickhouse_1 ... done
Removing network ltierrorreporting_default
Creating network "ltierrorreporting_default" with the default driver
Creating ltierrorreporting_clickhouse_1 ... 
Creating ltierrorreporting_clickhouse_1 ... done
Trying again. Remaining tries #4
Trying again. Remaining tries #3
Trying again. Remaining tries #2
Trying again. Remaining tries #1
Clickhouse server failed to come up in 5 tries.

when i run docker-compose logs clickhouse, the logs is bellow

clickhouse_1 | Include not found: clickhouse_remote_servers
clickhouse_1 | Include not found: clickhouse_compression
clickhouse_1 | Logging trace to /var/log/clickhouse-server/clickhouse-server.log
clickhouse_1 | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
clickhouse_1 | Include not found: networks
clickhouse_1 | Include not found: clickhouse_remote_servers
clickhouse_1 | Include not found: clickhouse_compression

when i run docker-compose up -d clickhouse, is ok

when i run docker-compose run clickhouse clickhouse-client --host clickhouse -q "SELECT 1";  i find an error, the logs is bellow

Code: 210. DB::NetException: Net Exception: Host not found: clickhouse (clickhouse:9000)

when i modify docker-compose.yml, add hostname: clickhouse, i find another error connection refused

when i run ifconfig -a , my network name is bond0 and no eth0.

i hope to help me find the reason, thanks

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
