### ISSUE TITLE
How to set the name of the single organisation when SENTRY_SINGLE_ORGANIZATION = True

### ISSUE THREAD

**Issue by hasancansaral** [getsentry/onpremise#7]
Hi, I am installing a self-hosted Sentry server. Everything's fine, but the name for the single organisation is `Sentry`. I could not come across how could one change this -or the related setting for that matter- when using Docker for an on-premise installation with `SENTRY_SINGLE_ORGANIZATION = True`. Any help appreciated. Thanks.

**Comment by dcramer** [comment]
Please use our community forum for questions and general advice:

https://forum.sentry.io/

(That said, this is all handled via various settings panes, in this case, the one in the sidebar from the root app page)

**Comment by hasancansaral** [comment]
Thanks! I was not aware that this can be done via UI and expecting a setting via environment variable or in `config.yml` or `sentry.conf.py`.
