### ISSUE TITLE
Clickhouse has a too high log level for production

### ISSUE THREAD

**Issue by soullivaneuh** [getsentry/onpremise#701]
I took a look at the generated `/var/lib/docker/volumes/sentry_onpremise_sentry-clickhouse-log/_data/clickhouse-server.log` file and I found a lot of `Debug` and `Trace` lines:

```
2020.10.13 15:13:10.712743 [ 55 ] {} <Debug> system.metric_log: Removing part from filesystem 202010_71214_71214_0
2020.10.13 15:13:18.152269 [ 56 ] {} <Trace> SystemLog (system.metric_log): Flushing system log
2020.10.13 15:13:18.156817 [ 56 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 3.62 GiB.
2020.10.13 15:13:18.183674 [ 56 ] {} <Trace> system.metric_log: Renaming temporary part tmp_insert_202010_243_243_0 to 202010_71279_71279_0.
2020.10.13 15:13:25.684530 [ 56 ] {} <Trace> SystemLog (system.metric_log): Flushing system log
2020.10.13 15:13:25.689540 [ 56 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 3.68 GiB.
```

I would like to change the log level, but the `clickhouse/config.xml` is versioned, so I suppose I should not touch it, and nothing is configurable with environment variables.

The log level should be lowed down by default with and an option to change it may be added.

What do you think?

**Comment by BYK** [comment]
Agreed, good catch. Awaiting your PR 😀  (along with the other great issues you have filed)

**Comment by soullivaneuh** [comment]
This one is an easy to do, will do it.
