### ISSUE TITLE
Unable to recieve issues

### ISSUE THREAD

**Issue by multinerd** [getsentry/onpremise#705]
## Version Information

Version: Sentry 20.11.0.dev0a355bde

## Description

using a demo .net project with the following code i am unable to receive issues. Replacing the URL with a sentry.io dns works without problems. 

## Steps to Reproduce

1. Clone repo and run `./install.sh`
2. Create project and get a dns
3. Use the dns in the code below in a console app

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            using (SentrySdk.Init("https://MY_DNS@MY_ROOT_URL.com:44310/2"))
            {
                var i = 0;
                Console.WriteLine(1 / i);
            }
        }
    }
```

## Logs

Please share any applicable logs:

When i run my .net program, the following lines are shown in docker logs console

```
nginx_1 | 2020/10/16 17:48:03 [error] 6#6: *41 connect() failed (113: No route to host) while connecting to upstream, client: 172.27.0.1, server: , request: "POST /api/2/store/ HTTP/1.1", upstream: "http://172.27.0.22:3000/api/2/store/", host: "MY_ROOT_URL.com:44310"
nginx_1 | 172.27.0.1 - - [16/Oct/2020:17:48:03 +0000] "POST /api/2/store/ HTTP/1.1" 502 175 "-" "-" "10.200.5.18:60227"
sentry_onpremise_relay_1 exited with code 1
```

**Comment by BYK** [comment]
Can you share your relay logs as it seems to be crashing?

**Comment by multinerd** [comment]
It shows the following over and over

```
error: could not parse json config file (file /work/.relay/credentials.json)

caused by: EOF while parsing a value at line 1 column 0
```

Ive deleted the file in the `relay` folder and ran `install.sh` but it looks like its always creating/copying a blank `credentials.json` file.

**Comment by BYK** [comment]
>Am i supposed to do something with that credentials.json file?

I don't know why it is empty but it should not be empty. I recommend running this step manually: https://github.com/getsentry/onpremise/blob/e9cff2e28867eda078b3d3b103aae68252e19d91/install.sh#L314

If it is still generating an empty file, try dumping things to your console and manually copy paste. If it is still failing, I'd first try to understand what is going wrong. If you just want to get unblocked, you can download the relevant Relay binary from relay releases page and run it manually `relay config init` and use the generated credentials file manually.

**Comment by multinerd** [comment]
I ended up downloading the binary and generating the config file manually.

**Comment by BYK** [comment]
@multinerd if you ever figure out why the install script cannot do this automatically, feel free to come back and report and we'd happily try to fix if this is a general issue.

**Comment by SDohle** [comment]
I have the same issue on windows 10 machine (Docker for windows 19.03.13).
During install i get this erorr message:
```
Generating Relay credentials...
Creating sentry_onpremise_relay_run ...
Creating sentry_onpremise_relay_run ... done
error: could not open config file (file /work/C:/Users/CurrentUser/AppData/Local/Temp/config.yml)
  caused by: No such file or directory (os error 2)
An error occurred, caught SIGERR on line 319
Cleaning up...
```
And that results in the empty credentials file.

**Comment by BYK** [comment]
@SDohle are you using git-bash? This path seems problematic: `/work/C:/Users/CurrentUser/AppData/Local/Temp/config.yml` (the `C:` part in particular)

I'm using WSL2 on Windows and have no problems setting sentry up.

**Comment by SDohle** [comment]
> @SDohle are you using git-bash?

Yes, git bash. I downloaded the relay binary and generated the credentials manually to solve my issue. 
Everything else works as expected.

**Comment by BYK** [comment]
Docker for Windows and Git-Bash don't play well together. It would be nice if the script could detect Git-Bash and stop actually. I'll see if this is possible.

Btw you can also use the Relay docker image next time, which is already downloaded :)
