### ISSUE TITLE
Install script is failing for Python3

### ISSUE THREAD

**Issue by ChillarAnand** [getsentry/onpremise#706]
## Version Information

Version: latest master

## Description

Looks like there is some byte/str conversion issue while upgrading. 

## Steps to Reproduce

```

    $ git pull origin master
    
    $ docker-compose build snuba-cleanup cron web symbolicator-cleanup ingest-consumer worker post-process-forwarder sentry-cleanup

    $ SENTRY_LOG_LEVEL=DEBUG SENTRY_PYTHON3=1 ./install.sh

```

## Logs

```

    Creating sentry_onpremise_snuba-consumer_1              ... done
    Creating sentry_onpremise_snuba-transactions-consumer_1 ... done
    Creating sentry_onpremise_snuba-replacer_1              ... done
    Creating sentry_onpremise_web_run                       ... 
    Creating sentry_onpremise_web_run                       ... done
    !! Configuration error: error: argument for 's' must be a bytes object
    An error occurred, caught SIGERR on line 293
    Cleaning up...
```

**Comment by BYK** [comment]
Ooh, thanks for the report! Do you have an old config as a fresh install definitely works (CI tests this for each commit now).

If so can you share the config?

**Comment by ChillarAnand** [comment]
This is related to https://github.com/getsentry/onpremise/pull/692/files

I had an old config file which has strings instead of bytes. Updating the config file resolved the issue.

**Comment by BYK** [comment]
Closing then as this is a configuration issue.
