### ISSUE TITLE
删除了/var/lib/docker/volumes/sentry-kafka/_data/events-0/*.log重启后收不到新的上报

### ISSUE THREAD

**Issue by tiancityycf** [getsentry/onpremise#707]
## Version Information

Version: *VERSION HERE*

## Description

因为占用磁盘过大，所以我删除了以下文件

删除了/var/lib/docker/volumes/sentry-kafka/_data/events-0/*.log

重启后收不到新的上报

现在咋办呢。。

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
