### ISSUE TITLE
CSRF issue with mostly fresh install

### ISSUE THREAD

**Issue by scnerd** [getsentry/onpremise#708]
## Version Information

Version: *version 20.10.1*

## Description

Get the following page:

    CSRF Verification Failed
    A required security token was not found or was invalid.

The docker logs show the following:

    [WARNING] django.security.csrf: Forbidden (Referer checking failed - https://my-hostname:9001/auth/login/sentry/ does not match any trusted origins.): /auth/login/sentry/ (status_code=403 request=<WSGIRequest: POST u'/auth/login/sentry/'>)

## Steps to Reproduce

Starting from mostly-fresh install. Docker volumes are left over from previous installation, but pulled entirely new codebase, adjusted .env and nginx configuration (for port and SSL). Ran install.sh script. Went to login page. Submitted previous credentials.

*I did not see any configuration option for setting the server hostname,* only the port in the .env file. I did not see any instructions in the README about setting the server hostname explicitly, and I didn't see any instances of my hostname in the previous, working Sentry installation.

I get the same behavior whether or not I use the experimental Python 3 installation.

## Logs

Web container logs:

```
...
web_1                          | *** Operational MODE: preforking+threaded ***
web_1                          | spawned uWSGI master process (pid: 18)
web_1                          | spawned uWSGI worker 1 (pid: 23, cores: 4)
web_1                          | spawned uWSGI worker 2 (pid: 24, cores: 4)
web_1                          | spawned uWSGI worker 3 (pid: 25, cores: 4)
web_1                          | spawned uWSGI http 1 (pid: 26)
web_1                          | 17:30:04 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
web_1                          | 17:30:04 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
web_1                          | 17:30:04 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
web_1                          | /usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
web_1                          |   from cryptography import x509
web_1                          | /usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
web_1                          |   from cryptography import x509
web_1                          | /usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
web_1                          |   from cryptography import x509
web_1                          | 17:30:07 [INFO] sentry.plugins.github: apps-not-configured
web_1                          | 17:30:07 [INFO] sentry.plugins.github: apps-not-configured
web_1                          | 17:30:07 [INFO] sentry.plugins.github: apps-not-configured
web_1                          | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x56195e06ffd0 pid: 25 (default app)
web_1                          | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x56195e06ffd0 pid: 24 (default app)
web_1                          | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x56195e06ffd0 pid: 23 (default app)
web_1                          | 17:30:09 [WARNING] django.request: Not Found: /_static/1603128604/sentry/images/logos/default-organization-logo.png (status_code=404 request=<WSGIRequest: GET u'/_static/1603128604/sentry/images/logos/default-organization-logo.png'>)
web_1                          | 17:30:09 [WARNING] django.request: Not Found: /_static/1603128604/sentry/js/ads.js (status_code=404 request=<WSGIRequest: GET u'/_static/1603128604/sentry/js/ads.js'>)
web_1                          | 17:30:10 [WARNING] django.request: Not Found: /_static/1603128604/sentry/js/ads.js (status_code=404 request=<WSGIRequest: GET u'/_static/1603128604/sentry/js/ads.js'>)
web_1                          | 17:30:11 [WARNING] django.request: Not Found: /_static/1603128604/sentry/images/logos/default-organization-logo.png (status_code=404 request=<WSGIRequest: GET u'/_static/1603128604/sentry/images/logos/default-organization-logo.png'>)
web_1                          | 17:30:12 [WARNING] django.security.csrf: Forbidden (Referer checking failed - https://my-hostname:9001/auth/login/sentry/ does not match any trusted origins.): /auth/login/sentry/ (status_code=403 request=<WSGIRequest: POST u'/auth/login/sentry/'>)
web_1                          | 17:30:13 [WARNING] django.request: Not Found: /_static/1603128604/sentry/js/ads.js (status_code=404 request=<WSGIRequest: GET u'/_static/1603128604/sentry/js/ads.js'>)
web_1                          | 17:30:13 [WARNING] django.request: Not Found: /_static/1603128604/sentry/js/ads.js (status_code=404 request=<WSGIRequest: GET u'/_static/1603128604/sentry/js/ads.js'>)
```

**Comment by BYK** [comment]
We have `system.url-prefix` mentioned here: https://develop.sentry.dev/config/#general

That said this is normally asked on the setup wizard that pops up with fresh installs (or upgrades too). I wonder why it didn't show up.

Anyway, can you try setting this in your `config.yml` file and see if it fixes before we look elsewhere?

**Comment by scnerd** [comment]
Unfortunately, this doesn't seem to have resolved it.
- I added ``system.url-prefix: 'https://my-hostname:port'`` to config.yml
  - I did double check that this field was **not** set in my previously working run of Sentry (from which the database and various volumes are being inherited, hence probably the lack of a first-time setup for this installation).
  - ``docker-compose restart`` - same CSRF error.
  - Re-ran install script - same CSRF error.
- Followed all instructions on the CSRF error page again. Cleared cookies, re-typed credentials, also tried logging in from private window to prevent auto-complete from filling the form. All resulted in the same CSRF error.

If this might be related to the fact that this installation is inheriting docker volumes from the previous installation (I've done ``docker-compose down -v``, so it's only inheriting the ``external`` volumes), I'd be willing to purge the whole thing if I could do a backup, purge volumes, fresh install, and restore. I have been getting emails from errors being sent to the Sentry server, so besides the CSRF login issue it seems to be running properly and I should be able to run commands within the container.

**Comment by BYK** [comment]
Could it be possible that you have tried the PY3 version at some point?

**Comment by scnerd** [comment]
I did try the Py3 version (sorry, I intended to mention that in my last comment). I'd gone back and forth a bit, though at this point the error arises with either Py2 or Py3. Did I cause some permanent damage by trying the Py3 version?

**Comment by scnerd** [comment]
And just to clarify, I first tried Py3 when I got this error, I tried going back to Py2 after that.

**Comment by BYK** [comment]
@scnerd we did have an issue around pickle usage in our PY3 builds which is fixed now but I think it requires manual intervention in the database (and I don't know what exactly). I can try to dig it out but I think it would be easier for you to start over if possible (that means data loss).

If your data is important, we'll dig out a solution :)

**Comment by scnerd** [comment]
@BYK I really appreciate that. The data is not very valuable, it was an individual setup that will only take a few hours to get back up and running. If I can be a guinea pig for anything for the Py3 transition (for which I'm very excited), please let me know, else I'll just burn my database volume and start over.

**Comment by scnerd** [comment]
I am continuing to get the same error with completely fresh installs (wiped out all docker volumes with ``docker-compose down -v`` and ``docker volume rm ...`` for the external volumes).

- Same issue with both Py3 and Py2.
- I've tried simple container restarts as well as re-running the full install script.
- I haven't configured this with SSL before, but I did uncomment the lines in sentry.conf.py and checked that the appropriate header forwarding was set in the nginx file. There's no reverse proxy in front of this (since apparently that can matter), I'm hitting the nginx container directly.

I've attached my config.yml, sentry.conf.py, and nginx config (since I added HTTPS).
[sentry_error.zip](https://github.com/getsentry/onpremise/files/5432966/sentry_error.zip)

**Comment by scnerd** [comment]
I should add, I switched back to port :9000 instead of the :9001 in the original report, just in case that was affecting anything.

**Comment by BYK** [comment]
@scnerd heya, sorry for not getting back to you earlier. We have added automatic cache invalidation when going across Python versions in necessary places and fixed a bunch more issues around this. I think you can just directly pull the latest nightly and move along without issues.

I'll be closing this issue as it should be resolved but please do comment back if you still have problems.

Thanks again for helping us test Python 3 and for your patience.
