### ISSUE TITLE
Favicon disappeared after latest upgrade

### ISSUE THREAD

**Issue by bellini666** [getsentry/onpremise#709]
Just upgraded sentry about an hour ago and the favicon is empty (it gives the browser 404).

Don't know if this is something related to the `sentry` project itself, but since I'm using onpremise I thought it was better to post it here.

**Comment by BYK** [comment]
Thanks for the report! This is due to a recent optimization I made which chopped off a bit too much.

Fix submitted and will publish 20.10.2 soon with the fix applied.

**Comment by bellini666** [comment]
Hi @BYK ,

Awesome, thanks for letting me know! Will upgrade again soon and close the issue here if it is resolved!
