### ISSUE TITLE
Report error when Run install.sh

### ISSUE THREAD

**Issue by yydzxz** [getsentry/onpremise#711]
## Version Information

Version:  the newest master branch
Docker version: 2.4.0.0

## Description

can't startup

## Steps to Reproduce

run ./install.sh

## Logs

Building web
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : ARG SENTRY_PYTHON3
Step 3/5 : FROM ${SENTRY_IMAGE}${SENTRY_PYTHON3:+-py3}
nightly: Pulling from getsentry/sentry
Service 'web' failed to build : unexpected EOF
An error occurred, caught SIGERR on line 216

**Comment by BYK** [comment]
I don't know how you were able to get that far with Docker 2.4 but that's not a version we support. We support Docker 19.03.6 or higher as we mention on our README.

**Comment by yydzxz** [comment]
> I don't know how you were able to get that far with Docker 2.4 but that's not a version we support. We support Docker 19.03.6 or higher as we mention on our README.

Sorry，it is a typo. Docker version is 24.0.0.0, the latest version

**Comment by BYK** [comment]
There is no Docker version 24: https://docs.docker.com/engine/release-notes/

I'm guessing you are using one of these:

 - https://docs.docker.com/docker-for-windows/release-notes/
 - https://docs.docker.com/docker-for-mac/release-notes/

Even than, `unexpected EOF` looks like an issue with your system rather than something we an fix in this repo.

**Comment by yydzxz** [comment]
> There is no Docker version 24: https://docs.docker.com/engine/release-notes/
> 
> I'm guessing you are using one of these:
> 
> * https://docs.docker.com/docker-for-windows/release-notes/
> * https://docs.docker.com/docker-for-mac/release-notes/
> 
> Even then, `unexpected EOF` looks like an issue with your system rather than something we an fix in this repo.

Thanks for your help.I use Docker Desktop on Mac, so maybe there is something about docker version I misunderstand, and I’ll check it tomorrow morning. Thanks a lot 😄

**Comment by BYK** [comment]
@yydzxz no worries. If you are using that version for Docker for Mac, it does satisfy the minimum requirements as it is the latest version as you mentioned.

What I'm saying is, regardless of that, something is weird on your system blocking the build process. I've googled the error and seems like it is either a bug in docker or something in your network chain: https://github.com/docker/for-win/issues/6192

**Comment by yydzxz** [comment]
It's a network problem, now build process is ok
