### ISSUE TITLE
release health unavailable on latest version

### ISSUE THREAD

**Issue by voltcode** [getsentry/onpremise#717]
## Version Information

Version: Sentry 20.10.17877af3 (upgraded from v10

## Description

I am trying to access functionality described under https://docs.sentry.io/product/releases/health/
but my releases page is much different that the screenshot there. I upgraded from v10 and the releases functionality was much richer there too! I was able to see releases list, check each releases artifacts, etc.

**Comment by markstory** [comment]
Are you using an [SDK that provides release health data](https://docs.sentry.io/product/releases/health/#getting-started)?

**Comment by voltcode** [comment]
Nope, I missed that. Using .NET at the moment.
