### ISSUE TITLE
docker compose version

### ISSUE THREAD

**Issue by sseypt** [getsentry/onpremise#72]
**issue**

https://github.com/getsentry/onpremise/blob/a514caf906fa22a66eaf6532a721a9393177d2ff/docker-compose.yml#L12

> Value 'unless-stopped' is not expected here

**solution**

'unless-stopped' was added in version 3
https://github.com/getsentry/onpremise/blob/a514caf906fa22a66eaf6532a721a9393177d2ff/docker-compose.yml#L9

**Comment by pedrofurtado** [comment]
@mattrobenolt Any news about this issue?

**Comment by mattrobenolt** [comment]
I'm not sure what the fix is. I don't use docker-compose myself.

So if you'd like to submit a PR, please do, I'd be happy to accept.

**Comment by mattrobenolt** [comment]
As mentioned in #73, it seems just bumping the version number breaks other stuff.

**Comment by revolunet** [comment]
I submitted a PR with version:3.4 here : https://github.com/getsentry/onpremise/pull/105

**Comment by BYK** [comment]
Closing per the comment above.
