### ISSUE TITLE
Sentry onpremise just stops processing events after few hours

### ISSUE THREAD

**Issue by hheexx** [getsentry/onpremise#723]
## Important Details

How are you running Sentry?
On-Premise w/ Docker, version 19.03.6
Default docker-compose.yml, only port changed from 9000 to 80.

## Description

After upgrade from 10 to 20.8.0 sentry stopped processing events few hours after upgrade.
I had same issue on version 10 few times but restart of a system helped.
Now only thing that helps is deleting all zookeeper kafka and clickhouse data. When I delete those volumes and run install.sh again it works for few hours and then stops again. 

I first asked on forums and it looks like lot of people have same or similiar problem:
https://forum.sentry.io/t/sentry-stops-processing-events-after-upgrade-10-0-20-8-0-dev0ba2aa70/10702/24

### Possible Solution

I'm willing to give access to my system to Sentry engineers to debug.
There are no documentation for Sentry event pipeline so debugging for me is very hard.
I did not find anything in logs that could give me direction...

**Comment by peppe77** [comment]
same problem here k8s/1.18 and sentry 20.8. will try @max-wittig  hack as a work-around though would be good to have official fix for it. thanks

**Comment by BYK** [comment]
@max-wittig pinging Davind won't make things faster, something to keep in mind for the future 😉 

This seems to be due to getsentry/sentry#21133 so closing in favor of that. We'll be looking into this but no promises as it is mostly dependent on upstream code.
