### ISSUE TITLE
Clickhouse crashes after upgrade from 19.X to 20.X

### ISSUE THREAD

**Issue by max-wittig** [getsentry/onpremise#726]
## Version Information

Version: 20-09

## Description

> From clickhouse
2020.10.26 21:09:46.660924 [ 1 ] {} <Error> Application: DB::Exception: Table contains parts with adaptive and non adaptive marks, but `setting enable_mixed_granularity_parts` is disabled: Cannot attach table `default`.`sentry_local` from metadata file /var/lib/clickhouse/metadata/default/sentry_local.sql from query ATTACH TABLE sentry_local

## Steps to Reproduce

1. Install 19.X
2. Have some events
3. Upgrade to 20.X

**Comment by BYK** [comment]
There's a fix for this in Clickhouse already: https://github.com/ClickHouse/ClickHouse/issues/6394

Are you using a custom configuration somewhere?

**Comment by max-wittig** [comment]
Nevermind, my fault. I had to use the new way to run clickhouse bootstrapping. You guys change a lot of stuff around 😄

**Comment by BYK** [comment]
> I had to use the new way to run clickhouse bootstrapping. You guys change a lot of stuff around 😄

Ah, you mean the new snuba commands 😄 Yeah but it is due to breaking new ground. Things will get more stable probably in 6-12 months.

**Comment by max-wittig** [comment]
Just noticed this again after clickhouse restore. This config was missing:

```xml
<yandex>
    <max_server_memory_usage_to_ram_ratio from_env="MAX_MEMORY_USAGE_RATIO" />
    <merge_tree>
      <enable_mixed_granularity_parts>1</enable_mixed_granularity_parts>
    </merge_tree>
</yandex>
```

**Comment by BYK** [comment]
@max-wittig I thought this was enabled by default in the never versions?

**Comment by max-wittig** [comment]
I also though that, because this was mentioned on their issue tracker and I'm kind of confused. But this seems to work. We use `yandex/clickhouse-server:20.3.9.70` with sentry 20.09 currently.

**Comment by BYK** [comment]
@max-wittig maybe we should just add this to our custom config. Would you like to do the honors to take the credit? :)

**Comment by max-wittig** [comment]
I could do that, but I'm not sure that others are also affected. I haven't read about anybody else with this problem, so maybe it's just our setup? I'm not sure.

**Comment by BYK** [comment]
My reasoning is: does it hurt to have this setting in? No. So let's have it and avoid any other issues :)

**Comment by max-wittig** [comment]
Makes sense 👍
