### ISSUE TITLE
Upgrade Sentry 20.8.0 to 20.9.0 with custom configuration - docker-compose error

### ISSUE THREAD

**Issue by JeSappelleRoot** [getsentry/onpremise#729]
## Version Information

Version: *20.8.0*
Targeted version : *20.9.0*

## Description

We are facing following bugs with self-hosted Sentry on docker, some threads mentioned that upgrade to 20.9.0 could help to fix
You can find related threads : 
-[here](https://github.com/getsentry/onpremise/issues/723)
-[here](https://forum.sentry.io/t/sentry-stops-processing-events-after-upgrade-10-0-20-8-0-dev0ba2aa70/10702/48)

`/opt/sentry-20.8.0` -> root folder for version 20.8.0 (clone of original 20.8.0 branch)
`/opt/sentry-20.9.0` -> root folder for version 20.9.0 (clone of original 20.9.0 branch)

I clone Sentry 20.9.0 branch on my self-hosted Sentry
I moved the following files/folders to sentry-20.9.0 folder : 
```
sentry/config.yml
sentry/Dockerfile
sentry/requirements.txt
sentry/sentry.conf.py
nginx/nginx.conf
nginx/ssl/
```

**We are using LDAP authentication integration and port 443 for HTTPS on nginx.conf (certificates on nginx/ssl/ folder)**

Extra line on Sentry Dockerfile : 
`RUN apt-get update && apt-get install gcc openssl libsasl2-dev python-dev libldap2-dev libssl-dev -y` 

Sentry requirements.txt content : `sentry-ldap-auth`

## Steps to Reproduce

1. `./install.sh` -> no error, everything is running smooth
2. `docker-compose up` give me many errors and Sentry is unreachable

I perform a successful upgrade to 20.9.0 with keeping my original sentry-20.8.0 folder and with replacing .env file from 20.9.0 version, and running a new ./install.sh command
**But I think this is not a graceful upgrade and could give us many issues later**

## Logs

Please share any applicable logs:

Some help or any advice will be appreciated
Thanks

**Comment by BYK** [comment]
I think you just need to give Kafka some time to get up and restore its state?

Btw I recommend you delete these logs as they leak information about where you are running this (your employer 😉 ). I think you may also need a DNS adjustment as it seems to be looking for docker-compose names on your local network.

**Comment by JeSappelleRoot** [comment]
Thanks @BYK for your reply
Well, if you mentionned the relay error message about name resolution for `web.google.internal`, I'm not working at Google 😄 
But maybe I missed a leaked info on the log (I checked before uploading...), anyway I removed this file
I'll check tomorrow to give more time to Kafka

**Comment by JeSappelleRoot** [comment]
@BYK 
After quick check...I missed to replicate Nginx change on docker-compose, container wasn't expose on port 443
I can reach Web UI from my browser now, I'm going to test entire upgrade path with some test events

Anyway, I appreciated your help and your support on this false positive
Best

JeSappelleRoot
