### ISSUE TITLE
SAML2: Authentication error: SAML SSO failed, There is no AttributeStatement on the Response

### ISSUE THREAD

**Issue by olevole** [getsentry/onpremise#743]
## Version Information

Version: *20.10.17 8833d9*

## Description

After activating SAML2 (configuring  relying party in ADFS, Map identity provider  attributes, etc..), an attempt to authorize results in the following error: `Authentication error: SAML SSO failed, There is no AttributeStatement on the Response`

## Steps to Reproduce

1. Configure SAML2
2. Login with SAML2

## Logs

Please share any applicable logs:

nothing in `docker logs <web>`

**Comment by BYK** [comment]
@olevole sorry but there's no way anyone can investigate this with the information you have provided.

You'll need to share _some_ logs, whether you are using the Python 3 version or not, how do you configure your SAML2 etc.

**Comment by olevole** [comment]
**upd**: same behavior with **20.11.1** ( using the usual installation method: 

```
wget https://github.com/getsentry/onpremise/archive/20.11.1.tar.gz
tar xfz ..
cd onpremise-20.11.1
env SENTRY_PYTHON3=1 ./install.sh
docker-compose up -d
```

Сomplete steps for setup:

1) Sentry SAML2 settings ( SAML Configure ):

**Register Identity Provider**:

Metadata URL → https://<adfs>/FederationMetadata/2007-06/FederationMetadata.xml

**Map identity provider attributes**:

IdP User ID→ http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname
User Email →  http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
First Name → http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
Last Name → http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
Save Attributes

2) Configure ADFS (Windows 2016 server) by Metadata from https://<sentry FQDN>/saml/metadata/sentry/

After these steps, AD/FS returns to the sentry back after successful authorization.


Unfortunately, the web container does not write anything related to SAML2/SSO when I try to use SAML2 login, 
I just see any other messages:
```
09:55:12 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/settings/sentry/auth/' method=u'GET' ip_address=u'172.18.0.1')
09:55:13 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/organizations/sentry/?detailed=1' method=u'GET' ip_address=u'172.18.0.1')
09:55:13 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/organizations/?member=1' method=u'GET' ip_address=u'172.18.0.1')
09:55:13 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/internal/health/' method=u'GET' ip_address=u'172.18.0.1')
09:55:13 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/assistant/?v2' method=u'GET' ip_address=u'172.18.0.1')
09:55:13 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/organizations/sentry/broadcasts/' method=u'GET' ip_address=u'172.18.0.1')
09:55:13 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/organizations/sentry/auth-providers/' method=u'GET' ip_address=u'172.18.0.1')
09:55:13 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/organizations/sentry/auth-provider/' method=u'GET' ip_address=u'172.18.0.1')
```

Some resources found on the Internet for this error recommend turning off AttributeStatement (when they are not sent in claim). However, I have not found how to do this with Sentry

**Comment by BYK** [comment]
@olevole thanks a lot for sharing all this information. I suspect this might be a Python 3 issue (with string manipulation). Are you able to try this with our Python 2 images (without setting the `SENTRY_PYTHON3` env var?).

Once we confirm this is a Python 3 issue, we'll start digging in relevant places in the code to figure out what is going wrong.

**Comment by olevole** [comment]
@BYK  Unfortunately no changes. I see this check in the code:

**/usr/local/lib/python2.7/site-packages/onelogin/saml2**
```
if security.get('wantAttributeStatement', True) ...
```

But I can't figure out where to adjust this parameter.
Sentry distribution is too complicated (docker ;-) to try to make a code change

**Comment by BYK** [comment]
@EvanPurkhiser so I looked at https://github.com/getsentry/sentry/blob/b8bf85948d4c4832c60ab31e9f1a5a3c39fd53cf/src/sentry/auth/providers/saml2/provider.py#L340 and then https://github.com/onelogin/python3-saml

From there what I understand is:

1. First of all, we need to explicitly allow setting `wantAttributeStatement` in our `provider.py` file
2. Then @olevole should set `SAML_FOLDER` in their `sentry.conf.py` file like in https://github.com/onelogin/python3-saml/blob/589425d1fbd2161ce2a566dfcb92835a221a3541/demo-django/demo/settings.py#L76
3. Finally, they should put an `advanced_settings.json` file with this setting into this folder.

Is that correct?

**Comment by olevole** [comment]
found a local problem with an incorrect ADFS setting. For the sentry, we must additionally specify the attributes in response:
```
| LDAP Attrubyte            | Outgoing Claim Type     |
| SAM-Account-Name    | Windows account name |
| E-Mail-Addresses        | E-Mail Address               |   
| Surname                      | Surname                        |
| Given-Name                | Name                             |
```
