### ISSUE TITLE
Sentry high availability deploy

### ISSUE THREAD

**Issue by jiankunking** [getsentry/onpremise#747]
There is almost no information on the high availability of Sentry deployment on the Internet. I have recorded my process of deploying Sentry to Kubernetes for your reference:

[https://jiankunking.com/sentry-high-availability-deploy.html](https://jiankunking.com/sentry-high-availability-deploy.html)

**Comment by BYK** [comment]
Thanks for sharing this @jiankunking. I think you already shared this on the forum so closing the issue in favor of the forum topic: https://forum.sentry.io/t/sentry-high-availability-deploy/11838/2

Please refrain from double posting in the future.
