### ISSUE TITLE
install.sh don't ask for user

### ISSUE THREAD

**Issue by sysmat** [getsentry/onpremise#752]
## Version Information

Version: * onpremise-20.11.1*
echo $TERM -> xterm

## Description

no prompt for creating user

## Steps to Reproduce

1.  ./install.sh

## Logs

Please share any applicable logs:

- `ls -1 sentry_install_log-*.txt | tail -1 | xargs cat` # latest instal logs
```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  No migrations to apply.
Creating missing DSNs
Correcting Group.num_comments counter

----------------
You're all done! Run the following command to get Sentry running:

```
  docker-compose up -d
- `docker-compose logs` output

**Comment by BYK** [comment]
This is expected when doing upgrades and seems like that's what you did here?

**Comment by BYK** [comment]
Also, please don't clip the logs next time when you are reporting something. Share the full output of both commands.

**Comment by sysmat** [comment]
* it was a fresh install
* bash script is not promoting even in xterm-256color terminal

**Comment by BYK** [comment]
@sysmat, 

> No migrations to apply.

This implies that you've run all the migrations already, which is not possible for a fresh install. Please double check.

>bash script is not promoting even in xterm-256color terminal

This is intentional as it is hard to strip color code escapes from the automatic log files.

**Comment by JoostSaanen** [comment]
I think I have the same problem. Although this was not my first run on my machine, but I tried to prune all my docker images and run install from a clean HEAD of master, it still doesn't prompt for an user.

**Comment by sysmat** [comment]
@BYK so in which terminal is then working?

**Comment by BYK** [comment]
@JoostSaanen removing the images wouldn't do anything for the persisted data. You need to remove the volumes if you want a clean install.

@sysmat we deliberately suppress color output from Docker & docker-compose. Changing terminals wouldn't change that.

Closing this issue as it is turning into a generic discussion and the reported issue is the expected/desired outcome when you keep the volumes.

**Comment by sysmat** [comment]
@BYK who is talking about a color scheme, 

> ./install.sh --no-user-prompt

so without that switch, you should expect some prompt to create admin user or what or not, if so update REDME.md

**Comment by BYK** [comment]
>@BYK who is talking about a color scheme,

>bash script is not promoting even in xterm-256color terminal

I thought you were asking about color output when you said "promote" here (to a higher terminal support etc.). Now I realized that was a typo and you meant "prompt".

>so without that switch, you should expect some prompt to create admin user or what or not, if so update REDME.md

See my answer above please:

>@JoostSaanen removing the images wouldn't do anything for the persisted data. You need to remove the volumes if you want a clean install.

You seem to have your old volumes around hence Sentry does not run any migrations and it doesn't prompt for user creation because there is already a user from your earlier install.

**Comment by sysmat** [comment]
@BYK thx for the explanation it is confusing based on README, but even from a fresh install there was no promt

**Comment by BYK** [comment]
> but even from a fresh install there was no prompt

Your logs suggest this was not a fresh install. If there are no migrations needed to be run, it means you are using an already migrated `sentry-postgres` volume.

**Comment by sysmat** [comment]
yes, because I try it for a few  times, but from scratch was no prompt

**Comment by BYK** [comment]
@sysmat this is my final response as we seem to be going in circles. As much as you say "from scratch" it is clear from the logs you have shared that this was not a clean install.

If you really want to see it working you can just `docker volume rm sentry-postgres` and start over and you'll see that it will start doing many migrations and after that will prompt you for a new user creation.
