### ISSUE TITLE
install.sh fails to contact deb.debian.org

### ISSUE THREAD

**Issue by hopoffbaby** [getsentry/onpremise#756]
## Version Information

Version: 20.11.1 (

## Description

Docker images fail to build. Looks like it is referencing incorrect upstream URLs

## Steps to Reproduce

1. Remove all containers `docker rm $(docker ps -aq)`
2. Remove all images `docker rmi $(docker images -q)`
3. remove all volumes `docker volume rm $(docker volume ls -q)`
4. pull a fresh copy of repo. check out tag 20.11.1
5. Run ./install.sh

## Logs

Successfully tagged sentry-onpremise-local:latest
Building cron                               ... done
Err:1 http://security.debian.org/debian-security stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:2 http://deb.debian.org/debian stretch InRelease
  Temporary failure resolving 'deb.debian.org'
Err:1 http://security.debian.org/debian-security buster/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:2 http://deb.debian.org/debian buster InRelease
  Temporary failure resolving 'deb.debian.org'
Err:1 http://deb.debian.org/debian buster InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security buster/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian stretch-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package cron
Removing intermediate container f6baebc7475d

**Comment by BYK** [comment]
These are all valid domains and URLs, why do you think there's something wrong with the install script?

Seems like you have a DNS issue on your system.
