### ISSUE TITLE
problem with links

### ISSUE THREAD

**Issue by atefehzaker** [getsentry/onpremise#76]
Hello,
I installed onpremise sentry  and I have a problem with links. when I go different places in my sidebar, at some point the link would be something like this:
http://mywebsite.com/organizations/sentry/members/mywebsite.com/organizations/sentry/issues/bookmarks/
I wonder what the problem is and how it can be solved.
regards,
atefeh zaker

**Comment by pquerner** [comment]
I have the same issue. I installed this version just 2 days ago, so I'm not sure whats going on.

**Comment by sseypt** [comment]
@atefehzaker Did you set `system.url-prefix: 'http://mywebsite.com'` in `config.yml`?

**Comment by atefehzaker** [comment]
@sseypt I didn't have any "system.url-prefix" to set in my config.yml file. should I declare one in config.yml?

**Comment by sseypt** [comment]
@atefehzaker That should solve your problem. I just remembered, that the "Welcome to Sentry" view should also prompt you to set an url. I guess `http://` is missing? Have a look at http://mywebsite.com/manage/settings/ `Root URL`

**Comment by atefehzaker** [comment]
@sseypt thanks a lot! that did the job ;)

**Comment by pquerner** [comment]
Protocol was missing for me, too. Wierd. Does that field need a check for that perhaps? (ie. it HAS to start with either http or https ?)
