### ISSUE TITLE
Install shell script can not complete, throw exception:  failed: Connection refused  & so on...

### ISSUE THREAD

**Issue by yujiaao** [getsentry/onpremise#762]
## Version Information

Version: onpremise-20.11.1.tar.gz

$ docker --version
Docker version 18.03.1-ce, build 9ee9f40

$ docker-compose --version
docker-compose version 1.27.4, build 40524192

uname -a
Linux dockerhost 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

CentOS 7

## Description

Can not install.

## Steps to Reproduce

in user home dir:
1.  tar xvf onpremise-20.11.1.tar.gz
2.  cd onpremise
3.  install.sh

## Logs

Checking minimum requirements...
Removing network onpremise_default
Network onpremise_default not found.
Removing sentry_onpremise_kafka_1      ... 
Removing sentry_onpremise_clickhouse_1 ... 
Removing sentry_onpremise_zookeeper_1  ... 
Removing sentry_onpremise_redis_1      ... 
Removing sentry_onpremise_zookeeper_1  ... done
Removing sentry_onpremise_clickhouse_1 ... done
Removing sentry_onpremise_kafka_1      ... done
Removing sentry_onpremise_redis_1      ... done
Removing network sentry_onpremise_default

Creating volumes for persistent storage...
Created sentry-data.
Created sentry-postgres.
Created sentry-redis.
Created sentry-zookeeper.
Created sentry-kafka.
Created sentry-clickhouse.
Created sentry-symbolicator.

sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
sentry/requirements.txt already exists, skipped creation.

Building and tagging Docker images...

Pulling smtp                    ... 
Pulling memcached               ... 
Pulling redis                   ... 
Pulling postgres                ... 
Pulling zookeeper               ... 
Pulling kafka                   ... 
Pulling clickhouse              ... 
Pulling snuba-api               ... 
Pulling snuba-consumer          ... 
Pulling snuba-outcomes-consumer ... 
Pulling snuba-replacer          ... 
Pulling snuba-cleanup           ... 
Pulling symbolicator            ... 
Pulling symbolicator-cleanup    ... 
Pulling web                     ... 
Pulling cron                    ... 
Pulling worker                  ... 
Pulling post-process-forwarder  ... 
Pulling sentry-cleanup          ... 
Pulling smtp                    ... pulling from tianon/exim4
Pulling smtp                    ... digest: sha256:a841a4501a526a7866...
Pulling smtp                    ... status: image is up to date for t...
Pulling smtp                    ... done
Pulling postgres                ... pulling from library/postgres
Pulling memcached               ... pulling from library/memcached
Pulling symbolicator            ... pulling from getsentry/symbolicator
Pulling symbolicator            ... digest: sha256:fb7b74d7343bc665c2...
Pulling symbolicator            ... status: image is up to date for g...
Pulling symbolicator            ... done
Pulling snuba-consumer          ... pulling from getsentry/snuba
Pulling snuba-consumer          ... digest: sha256:539bfac10e05d55a88...
Pulling snuba-consumer          ... status: image is up to date for g...
Pulling snuba-consumer          ... done
Pulling postgres                ... digest: sha256:cd9fe2d45072804673...
Pulling postgres                ... status: image is up to date for p...
Pulling postgres                ... done
Pulling memcached               ... digest: sha256:6627e971255440a1bd...
Pulling memcached               ... status: image is up to date for m...
Pulling memcached               ... done
Pulling redis                   ... pulling from library/redis
Pulling cron                    ... done
Pulling snuba-outcomes-consumer ... pulling from getsentry/snuba
Pulling snuba-outcomes-consumer ... digest: sha256:539bfac10e05d55a88...
Pulling snuba-outcomes-consumer ... status: image is up to date for g...
Pulling snuba-outcomes-consumer ... done
Pulling redis                   ... digest: sha256:e0256846c84d070957...
Pulling redis                   ... status: image is up to date for r...
Pulling redis                   ... done
Pulling zookeeper               ... pulling from confluentinc/cp-zook...
Pulling zookeeper               ... digest: sha256:c63871c17b038e1685...
Pulling zookeeper               ... status: image is up to date for c...
Pulling zookeeper               ... done
Pulling kafka                   ... pulling from confluentinc/cp-kafka
Pulling kafka                   ... digest: sha256:c5ff41b494329e9dea...
Pulling kafka                   ... status: image is up to date for c...
Pulling kafka                   ... done
Pulling symbolicator-cleanup    ... done
Pulling snuba-cleanup           ... done
Pulling web                     ... done
Pulling worker                  ... done
Pulling snuba-replacer          ... pulling from getsentry/snuba
Pulling snuba-replacer          ... digest: sha256:539bfac10e05d55a88...
Pulling snuba-replacer          ... status: image is up to date for g...
Pulling snuba-replacer          ... done
Pulling clickhouse              ... pulling from yandex/clickhouse-se...
Pulling clickhouse              ... digest: sha256:9cda4acf02b112f7c1...
Pulling clickhouse              ... status: image is up to date for y...
Pulling clickhouse              ... done
Pulling sentry-cleanup          ... done
Pulling snuba-api               ... pulling from getsentry/snuba
Pulling snuba-api               ... digest: sha256:539bfac10e05d55a88...
Pulling snuba-api               ... status: image is up to date for g...
Pulling snuba-api               ... done
Pulling post-process-forwarder  ... done
Some service image(s) must be built from source by running:
    docker-compose build cron symbolicator-cleanup snuba-cleanup web worker sentry-cleanup post-process-forwarder
latest: Pulling from getsentry/sentry
Digest: sha256:c44619851c548bbac43c7ac716e0b0404679344de36792d84717745d8e23517b
Status: Image is up to date for getsentry/sentry:latest
Building web
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> 71ac5bcb4aaa
Step 3/4 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 8e80a6cff799
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 411f5d2879e2

Successfully built 411f5d2879e2
Successfully tagged sentry-onpremise-local:latest
smtp uses an image, skipping
memcached uses an image, skipping
redis uses an image, skipping
postgres uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
clickhouse uses an image, skipping
snuba-api uses an image, skipping
snuba-consumer uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-replacer uses an image, skipping
symbolicator uses an image, skipping
Building snuba-cleanup          ... 
Building symbolicator-cleanup   ... 
Building web                    ... 
Building cron                   ... 
Building worker                 ... 
Building post-process-forwarder ... 
Building sentry-cleanup         ... 
Building worker
Building cron
Building web
Building sentry-cleanup
Building post-process-forwarder
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> 71ac5bcb4aaa
Step 3/4 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 8e80a6cff799
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 411f5d2879e2

Successfully built 411f5d2879e2
Successfully tagged sentry-onpremise-local:latest
Building cron                   ... done
Building symbolicator-cleanup
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> 71ac5bcb4aaa
Step 3/4 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 8e80a6cff799
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 411f5d2879e2

Successfully built 411f5d2879e2
Successfully tagged sentry-onpremise-local:latest
Building post-process-forwarder ... done
Building snuba-cleanup
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> 71ac5bcb4aaa
Step 3/4 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 8e80a6cff799
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 411f5d2879e2

Successfully built 411f5d2879e2
Successfully tagged sentry-onpremise-local:latest
Building worker                 ... done
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 411f5d2879e2
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> a67362d855cd
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> 71ac5bcb4aaa
Step 3/4 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 8e80a6cff799
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 411f5d2879e2

Successfully built 411f5d2879e2
 ---> Using cache
 ---> 7f103ceeaba8
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 1d380faa3e82

Successfully built 1d380faa3e82
Successfully tagged sentry-onpremise-local:latest
Building web                    ... done
Successfully tagged sentry-cleanup-onpremise-local:latest
Building sentry-cleanup         ... done
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 7f0af34f3f78
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 907e6b07b551
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> db5d4c33dc93
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> f0a6004006fa

Successfully built f0a6004006fa
Successfully tagged symbolicator-cleanup-onpremise-local:latest
Building symbolicator-cleanup   ... done
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 7cf07ea0a0a6
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 21e95a29b2c2
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> a2b24f45ee72
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> ed48603c1a53

Successfully built ed48603c1a53
Successfully tagged snuba-cleanup-onpremise-local:latest
Building snuba-cleanup          ... done

Docker images built.
Bootstrapping Snuba...
Creating network "sentry_onpremise_default" with the default driver
Creating sentry_onpremise_zookeeper_1 ... 
Creating sentry_onpremise_clickhouse_1 ... 
Creating sentry_onpremise_redis_1      ... 
Creating sentry_onpremise_zookeeper_1  ... done
Creating sentry_onpremise_kafka_1      ... 
Creating sentry_onpremise_redis_1      ... done
Creating sentry_onpremise_clickhouse_1 ... done
Creating sentry_onpremise_kafka_1      ... done
Creating sentry_onpremise_snuba-api_run ... 
Creating sentry_onpremise_snuba-api_run ... done
+ '[' b = - ']'
+ snuba bootstrap --help
+ set -- snuba bootstrap --force
+ set gosu snuba snuba bootstrap --force
+ exec gosu snuba snuba bootstrap --force
%3|1606992780.072|FAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.5:9092 failed: Connection refused (after 4ms in state CONNECT)
2020-12-03 10:53:01,068 Connection to Kafka failed (attempt 0)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
%3|1606992781.069|FAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.5:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
%3|1606992782.078|FAIL|rdkafka#producer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.5:9092 failed: Connection refused (after 2ms in state CONNECT)
%3|1606992783.076|FAIL|rdkafka#producer-2| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.5:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2020-12-03 10:53:03,080 Connection to Kafka failed (attempt 1)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
%3|1606992784.087|FAIL|rdkafka#producer-3| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.5:9092 failed: Connection refused (after 2ms in state CONNECT)
%3|1606992785.086|FAIL|rdkafka#producer-3| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.5:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2020-12-03 10:53:05,089 Connection to Kafka failed (attempt 2)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
%3|1606992786.091|FAIL|rdkafka#producer-4| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.5:9092 failed: Connection refused (after 1ms in state CONNECT)
%3|1606992787.091|FAIL|rdkafka#producer-4| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.5:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2020-12-03 10:53:07,094 Connection to Kafka failed (attempt 3)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
%3|1606992788.098|FAIL|rdkafka#producer-5| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.5:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1606992789.098|FAIL|rdkafka#producer-5| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.5:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2020-12-03 10:53:09,103 Connection to Kafka failed (attempt 4)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
2020-12-03 10:53:10,865 Failed to create topic events
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'events' already exists."}
2020-12-03 10:53:10,866 Failed to create topic errors-replacements
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'errors-replacements' already exists."}
2020-12-03 10:53:10,867 Failed to create topic cdc
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'cdc' already exists."}
2020-12-03 10:53:10,867 Failed to create topic ingest-sessions
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'ingest-sessions' already exists."}
2020-12-03 10:53:10,867 Failed to create topic outcomes
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'outcomes' already exists."}
2020-12-03 10:53:10,867 Failed to create topic event-replacements
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'event-replacements' already exists."}
2020-12-03 10:53:10,867 Failed to create topic snuba-commit-log
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 91, in bootstrap
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'snuba-commit-log' already exists."}
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 98, in bootstrap
    Runner().run_all(force=True)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 132, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 257, in _get_pending_migrations
    raise MigrationInProgress(migration_key)
snuba.migrations.errors.MigrationInProgress: transactions: 0008_transactions_add_timestamp_index
Cleaning up...

**Comment by boyrest** [comment]
@yujiaao 
I had this error too. Have you solved it?
