### ISSUE TITLE
Server Requirements

### ISSUE THREAD

**Issue by codehimanshu** [getsentry/onpremise#77]
What are the minimum requirements for setting up a Sentry Server?
RAM requirement and Disk Requirement.

**Comment by mimischi** [comment]
There are some informations here: https://docs.sentry.io/server/installation/#hardware

**Comment by codehimanshu** [comment]
This link has information for a particular use case (handling 4 million events).
But for a basic website in production, will an AWS EC2 t2.micro (1GB RAM, 30GB SSD) be sufficient?

**Comment by codehimanshu** [comment]
I was able to install sentry but ot an error on /auth/login page. But seems that 1GB RAM is sufficient.

**Comment by AlexWayfer** [comment]
> There are some informations here: https://docs.sentry.io/server/installation/#hardware

No there is nothing about hardware.
