### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by navneetgarggate6** [getsentry/onpremise#782]
## Version Information

Version: Self-Hosted Sentry 20.12.1

## Description

trying to run on windows 10 

## Logs

[sentry_install_log-2020-12-22_11-10-31.txt](https://github.com/getsentry/onpremise/files/5728060/sentry_install_log-2020-12-22_11-10-31.txt)

**Comment by BYK** [comment]
Seems like you have connection issues to Docker Hub. Nothing we can fix here.

Please try to troubleshoot the errors yourself first before filing an issue without any information in it.
