### ISSUE TITLE
internal project undefined column exception

### ISSUE THREAD

**Issue by omaraltayyan** [getsentry/onpremise#786]
## Version Information

Version: 20.12.1 bade073

we installed sentry on an EC2 instance

## Description

an error gets raised randomly in sentry's internal project

## Steps to Reproduce

1. updated sentry to version  20.12.1
2. error gets raised randomly and frequently 

## Logs

this is the JSON representation of the event

https://pastebin.com/YPKC535n

**Comment by BYK** [comment]
Seems like you haven't run `sentry upgrade`. This field is added in the latest version: https://github.com/getsentry/sentry/commit/d10a62d5965c4841c7fe99e22bef2802d55e1a6a
