### ISSUE TITLE
Document how to troubleshoot queue problems

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/onpremise#788]
We have some basic [troubleshooting docs](https://develop.sentry.dev/self-hosted/#troubleshooting). Let's expand them to talk about [`sentry queues`](https://github.com/getsentry/sentry/blob/20.12.1/src/sentry/runner/commands/queues.py).

@kanadaj:

> basic troubleshooting (to find which worker is actually broken, we have like 7 different consumers/replacers/workers)

@lucas-zimerman:

> ah yeah, when sentry breaks nobody knows how to fix it xD
> I think our biggest issue is the workers that often times die
> and they won't come back

**Comment by lucas-zimerman** [comment]
This might be too complex but it would be nice if there was troubleshooting about migrating Sentry from one computer/server to another.

**Comment by kanadaj** [comment]
> This might be too complex but it would be nice if there was troubleshooting about migrating Sentry from one computer/server to another.

I think you just need to SQL dump CH and postgres, then restore on the new server. You can also just shut down the containers and copy the mounted data folders as they are, that should work as well.

**Comment by lucas-zimerman** [comment]
one thing to point out for troubleshooting is to check the number of active connections:
![image](https://user-images.githubusercontent.com/8229322/103656717-b43b7580-4f47-11eb-9ca1-dba7af5eb75b.png)
I just noticed from redis container that the maximum number of connections is not allowing the internal services to communicate.
