### ISSUE TITLE
What I'm doing wrong and sentry server doesn't work?

### ISSUE THREAD

**Issue by johncodeos** [getsentry/onpremise#79]
Hi,
I'm trying to setup sentry server on my digital ocean server. These are the steps I'm doing and it's not working.

0) Clone this git
1) Install Compose and Docker using this [.sh file](https://gist.github.com/masiuchi/a3046a7dc4971a96f8d8b04150089af8)
2) Create a linux user, dbuser, dbpassword and a database
3) execute `mkdir -p data/{sentry,postgres}`
4) run `docker-compose run --rm web config generate-secret-key`
5) take the secret key and paste it in `docker-compose.yml` and uncomment the SENTRY_SECRET_KEY
6) save and exit the `docker-compose.yml` file
7) open, edit and save the `sentry.conf.py` with my new db details (db, dbuser, dbpassword, port)
8) run `docker-compose run --rm web upgrade`
9) run `docker-compose up -d`
10) Check `http://my-host-ip:9000` , and nothing happening, page keeps loading and at the end It's like website doesn't exist.

Can you help me please?

Is there any video-tutorial who explain how to setup a sentry server? I searched a lot and I didn't find anything. Even it's very hard to find a noob-friendly tutorial on a website.

**Comment by pokidovea** [comment]
I join the issue. I've done step by step and localhost:9000 is unavailable - endless loading.

**Comment by JEKos** [comment]
@pokidovea I tested on my mac, and it's working. But on my Ubuntu 14.04 server has this endless loading

**Comment by JEKos** [comment]
@mattrobenolt Can you help us please?

**Comment by pokidovea** [comment]
I use Ubuntu 16.04

**Comment by JEKos** [comment]
@pokidovea  Try this tutorial [here](https://blog.driftingruby.com/configuring-a-sentry-server-on-ubuntu-16-04-lts/). It might help

**Comment by feizhaojun** [comment]
CentOS 7，occurred

**Comment by tenling** [comment]
make sure that you are not in vm share folder....

ubuntu16.04 success

**Comment by iiDestiny** [comment]
Okay, I'm a mail server configuration error, and now It's already working.

**Comment by revolunet** [comment]
if fixed, can you close the issue please ?

**Comment by JEKos** [comment]
Done

**Comment by wupeng1351** [comment]
I also encountered this problem. How do you solve it?

**Comment by wupeng1351** [comment]
> 发生了CentOS 7

I also encountered this problem. How do you solve it?

**Comment by BYK** [comment]
Closing as this doesn't seem to be an issue with the repo. Feel free to start a thread in our forum if you'd like to leverage the knowledge of the community: https://forum.sentry.io/c/on-premise

**Comment by aliBordbar1992** [comment]
Same problem here on windows 8.1. localhost:9000 gives me ERR_CONNECTION_REFUSED

**Comment by aliBordbar1992** [comment]
> Same problem here on windows 8.1. localhost:9000 gives me ERR_CONNECTION_REFUSED

turned out that sentry is up on localhost related to docker vm, not windows. it was available on 192.168.99.100:9000
