### ISSUE TITLE
trying to follow documentation: unknown flag --port

### ISSUE THREAD

**Issue by lucidlemon** [getsentry/onpremise#8]
So I'm trying to follow the installation guide mentioned [here](https://docs.sentry.io/on-premise/server/installation/docker/#starting-the-web-service), but when I run this command:

```
docker run \
  --detach \
  --rm \
  --name sentry-web-01 \
  --port 9000:9000 \
  sentry-onpremise \
  run web
```

I get this:

```
unknown flag: --port
See 'docker run --help'.
```

**Comment by mattrobenolt** [comment]
Oh, I guess there is no long version. It's just `-p`. I'll fix the docs. Thanks for pointing this out.

**Comment by marc1404** [comment]
Thanks @mattrobenolt 
I am receiving this error message now:
```
λ docker run --detach --rm -p 9000:9000 --name sentry-web-01 sentry-onpremise run web
Conflicting options: --rm and -d
```

**Comment by mattrobenolt** [comment]
@marc1404 I updated docs to reflect both of these issues. Thanks! :cookie:
