### ISSUE TITLE
How to switching MySQL from PostgreSQL

### ISSUE THREAD

**Issue by insoz** [getsentry/onpremise#80]
Hi, I want to use mysql, how to switch it ?  Thank you !

**Comment by mattrobenolt** [comment]
We don't support this, and MySQL support as a whole for us is going away in the nearish future.

**Comment by mattrobenolt** [comment]
@insoz To follow up, I got some clarification and I slightly misspoke. We're not explicitly removing support for MySQL, but we just haven't supported it in a long time. Since this comes up, we've added an FAQ to address this: https://github.com/getsentry/sentry/pull/7666
