### ISSUE TITLE
"There is 1 issue with your system configuration." is not actionable

### ISSUE THREAD

**Issue by WoLpH** [getsentry/onpremise#804]
## Version Information

Version: Sentry 21.1.0.dev0f96907d

## Description

![image](https://user-images.githubusercontent.com/270571/104040620-29bd7500-51d8-11eb-9e81-d0d4080dafc2.png)

I upgraded Sentry, now I get this message.
It's good to know that there's an issue, but it's quite useless as it is.
- The message is not clickable
- The interface doesn't show the actual error anywhere
- It doesn't offer any suggestion where to look for the cause

## Steps to Reproduce

1. Upgrade sentry to get this error
2. That's what I would like to know :) I'll probably have to dig in the logs or something so I'll solve it.

## Logs

Not relevant. My issue isn't the problem that's causing the error, only the useless error message.

**Comment by BYK** [comment]
Thanks for reporting! This is an ongoing headache that we strive to fix 👍🏻

**Comment by WoLpH** [comment]
Yes... I believe it. These issues are really annoying and could be anything. 

In my case it was due to an old Github integration setting that I wasn't using anyhow.

**Comment by jasonk** [comment]
There actually is a URL where you can see what warnings caused the banner now.  It wasn't easy to find though, so it would be nice if the banner was just linked to it:

https://sentry.example.com/manage/status/warnings/
