### ISSUE TITLE
Upgrading from 9.1.2 -> 20.11.1 failing due to "database files are incompatible with server"

### ISSUE THREAD

**Issue by wtangofoxtrot** [getsentry/onpremise#808]
## Version Information

Version: 9.1.2

## Description

my setup:
- everything runs in docker including the pgsql db
- the docker volumes are all local bind mounted folders, I am re-using them as this is a migration (reusing the postgres and sentry bind mounted volumes)
- upgrading from 9.1.2 to 20.11.1 using `./install.sh`

## Steps to Reproduce

1. clean checkout `git fetch; git reset --hard 14d20c0b632166188800a91f06c46499c7314faf`
2. updated `sentry/config.yml` to use existing secret, no other change
3. updated `docker-compose.yml` to bind mount existing local folders: `- '/sentry/data/postgres:/var/lib/postgresql/data'`
3. `./install.sh`

## Logs

Please share any applicable logs:

- install logs: 
[sentry_install_log-2021-01-12_12-01-40.txt](https://github.com/getsentry/onpremise/files/5804631/sentry_install_log-2021-01-12_12-01-40.txt)

- `docker-compose logs` output: 
[docker-compose-logs.txt](https://github.com/getsentry/onpremise/files/5804630/docker-compose-logs.txt)

Do we need to manually update the db or is this something that `web upgrade` does ?

**Comment by BYK** [comment]
We bumped the postgres version we are using so you need to upgrade your DB first. The following lines try to check and automatically do this but since you removed anything around volumes, I'm guessing it was skipped.
