### ISSUE TITLE
Update automatically

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/onpremise#821]
### Summary

Update Sentry automatically, to further reduce the delta between SaaS and self-hosted.

### Motivation

Sentry exists in several deployment environments:

1. **SaaS** - primary target, sentry.io cloud
2. **single-tenant** - FSI†-managed, isolated from (1)
3. **self-hosted** - single-node, docker-compose-based ... this repo! 😁
4. **custom** - anything else (unsupported by FSI†)

† Functional Software, Inc.

(1) is a continuous deployment (CD) environment (using [freight](https://github.com/getsentry/freight)).
(3) is a non-CD environment.
(2) is somewhere in between(?).

With the [move to CalVer](https://blog.sentry.io/2020/06/22/self-hosted-sentry-switching-to-calver) we brought self-hosted Sentry installations within reach of a CD implementation, if the self-hoster so chooses to set it up that way. The proposal here is to teach Self-Hosted Sentry (SHS) to automatically update itself by default out of the box, so that it stays close to current with SaaS. This ensures that SHS users are getting a comparable experience to SaaS users.

### Additional Context

n/a

**Comment by BYK** [comment]
This sounds pretty neat but I have concerns around the safety and feasibility of it. Can you be more specific about your proposal @chadwhitacre?
