### ISSUE TITLE
Problem with url

### ISSUE THREAD

**Issue by freaghill** [getsentry/onpremise#83]
I have installed a Sentry at my workplace with docker-compose.
The problem that I'm encountering is the following:
If I'm clicking on various links on the Sentry home page on the left, after a few times I get an error that says Page not Found.
After that I can see that the URL is wrong.
The URL is like this:
http://sentry.[my-company]/organizations/sentry/auth/sentry.[my-company].com/organizations/sentry/rate-limits/
As you can see it does not point to the right destination. At the first part there is the URL from where I'm coming, and it just pastes the new URL where I'm going at the end.
I've tried it with just the ip and the original port, and it messes it up also, so Nginx is not the fault.
Please help.

**Comment by zWingz** [comment]
I also have this problem

**Comment by BYK** [comment]
Very likely that you have your `system.url-prefix` set incorrectly (or not set at all). You can also set this on the `/manage` page of your Sentry installation.

Closing as this looks like a very old and stale issue and is not an issue with this repo.
