### ISSUE TITLE
Reqwest Upstream error to web:9000

### ISSUE THREAD

**Issue by MazzMazz** [getsentry/onpremise#831]
### Version Information

Sentry: 21.2.0.dev0371f4f4
Docker version 19.03.14, build 5eb3275d40
docker-compose version 1.26.0, build d4451659
OS: Ubuntu 20.04.1 LTS

### Steps to Reproduce

Since suddenly 2 days ago Sentry stopped displaying errors (UI is working) i found that in issue https://github.com/getsentry/onpremise/issues/771 the same problem with the relay docker is described. 

I tried to Downgrade to Docker 19.03.x Neither with Docker 20.10.x nor 19.03.x the relay docker is working.
I enabled https://github.com/getsentry/onpremise/pull/810/commits/5239b12d558269db6070584c9136012b1a7429c8 in the relay config which resulted in a different error (see Logs).

I tried a fresh install on the same server - cloned the repo and installed again - with same results - the same authentication errors. Installed the nightly version in the end which is not working either.

Also double-checked that the  pubKey of `relay/credentials.json` is the same as in `sentry/sentry.conf.py`

Nothing is modified in the sentry installation except enabling Email with AWS and having a nginx reverse Proxy to enable the web UI via https (listen 443 -> proxy pass localhost:9000).

### Expected Result

The relay docker can communicate with the web docker again after i downgrade to Docker 19.03 and enable reqwest (https://github.com/getsentry/onpremise/pull/810/commits/5239b12d558269db6070584c9136012b1a7429c8) which solves this Error. 

```
2020-12-14T19:37:01Z [relay_server::actors::upstream] INFO: registering with upstream (http://web:9000/)
2020-12-14T19:37:01Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: Failed to connect to host: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
```

### Actual Result

The failed resolving hostname is no more - however reqwest is not working either. This happens with Docker 19.03 and Docker 20.10

### Logs

```
relay_1                                     | 2021-01-20T08:27:04Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
relay_1                                     |   caused by: could not send request using reqwest
relay_1                                     |   caused by: error sending request for url (http://web:9000/api/0/relays/register/response/): connection error: Connection reset by peer (os error 104)
relay_1                                     | 2021-01-20T08:28:04Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
relay_1                                     |   caused by: could not send request using reqwest
relay_1                                     |   caused by: error sending request for url (http://web:9000/api/0/relays/register/response/): connection error: Connection reset by peer (os error 104)
relay_1                                     | 2021-01-20T08:36:10Z [relay_server::actors::events] ERROR: error processing event: event exceeded its configured lifetime
relay_1                                     | 2021-01-20T08:36:10Z [relay_server::actors::events] ERROR: error processing event: event exceeded its configured lifetime
relay_1                                     | 2021-01-20T08:29:04Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
relay_1                                     |   caused by: could not send request using reqwest
relay_1                                     |   caused by: error sending request for url (http://web:9000/api/0/relays/register/response/): connection error: Connection reset by peer (os error 104)
relay_1                                     | 2021-01-20T08:30:05Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
relay_1                                     |   caused by: could not send request using reqwest
relay_1                                     |   caused by: error sending request for url (http://web:9000/api/0/relays/register/response/): connection error: Connection reset by peer (os error 104)

```

**Comment by MazzMazz** [comment]
For whatever reason our Sentry started working again...

Haven't changed anything since the creation of this ticket.
Closed for me.

**Comment by BYK** [comment]
This is probably because `relay` starts up much faster than `web` (Sentry backend).
