### ISSUE TITLE
Maybe lower MIN_RAM_HARD from 4000 to 3800?

### ISSUE THREAD

**Issue by arusa** [getsentry/onpremise#839]
How much memory does sentry really need?
With a hard limit of 4000 I can't even install it on a machine with 4gb memory because the machine in my case shows just 3888. The next step at most providers would be 8gb, but I think that is not what you intended with 4000?

https://github.com/getsentry/onpremise/blob/54a20969a62675cb3e5b8a976c573f86806a081b/install.sh#L28

**Comment by BYK** [comment]
I think that makes sense, @chadwhitacre?

@arusa would you be willing to submit a PR?

**Comment by chadwhitacre** [comment]
What's the proposal here? Drop the hard limit to `MIN_RAM_HARD=3888`? Maybe 3000 or 3500 to account for slight variations?

**Comment by lucas-zimerman** [comment]
Or not block the installation but force the user to type Y/y That he's aware the current ram is below the minimum required and he agrees errors or slowdowns might happen.

usually, you have 4096MB of RAM where a percent of it is dedicated to the hardware (I/O, GPU,...). 
I'd drop the Min req to 3800 and add the warning instead of blocking the installation.

**Comment by chadwhitacre** [comment]
sgtm

*/me whispers * PR * ...* 😁

**Comment by arusa** [comment]
I created the PR.

Because the variable is called MIN_RAM_HARD, it sounds like a hard limit. For me that means it is not possible to run sentry with less memory and it wold not be necessary to let someone skip it by typing [Yy].

If it is possible to run sentry with less memory, then I would suggest just displaying a warning instead of blocking the install.

In my case I run this install script automated and would again need to work around if the script forces me to type [Yy].

I am happy for now with just reducing the hard limit to 3800.

**Comment by chadwhitacre** [comment]
Yay, awesome! Thanks @arusa! 💃 😁

**Comment by chadwhitacre** [comment]
> I would suggest just displaying a warning instead of blocking the install.

We do also have a soft limit of 8GB, and we display a warning for that. 4GB is really tiny these days. Do you have a need to run Sentry with less RAM than that?

**Comment by BYK** [comment]
We used to say `2400` for the min hard requirement but that was barely enough to get a few events through. Realistically, under any non-trivial load you'd need ~4G
