### ISSUE TITLE
Sentry ingesting events even if wrong key is used

### ISSUE THREAD

**Issue by nodomain** [getsentry/onpremise#846]
### Version Information

Version: 21.1.0

### Steps to Reproduce

I completely re-setup the stack from scratch due to some DB issues. I then found that events are ingested and shown in the newly created project even if the key part of the DSN is different. I happened to set up the projects in the same order, so the events are assigned correctly.

Old DSN: `https://8407e5bbce8547518946d4939de9ae16@o1.ingest.DOMAIN/2`
New DSN: `https://53bc39e8f48d44eebbf23f654683c7a3@o1.ingest.DOMAIN/2`

### Expected Result

Events/issues are denied.

### Actual Result

Events/issues are ingested and shown.

### Logs

n/a

**Comment by BYK** [comment]
Sorry about the misbehaving bot (again 😀). We have a fix up: https://github.com/getsentry/.github/pull/36
