### ISSUE TITLE
Sentry ingesting events even if wrong key is used

### ISSUE THREAD

**Issue by nodomain** [getsentry/onpremise#847]
### Version Information

Version: *21.1.0*

### Steps to Reproduce

1. I completely re-setup the stack from scratch due to some DB issues. I used the same secret system key.
2. I then found that events are ingested and shown in the newly created project even if the *key* part of the DSN is different. 
3. I happened to set up the projects in the same order, so the events are assigned correctly.

### Expected Result

Events/issues are denied.

### Actual Result

Events/issues are ingested and shown.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/104389/106582926-d3c4be80-6544-11eb-82f3-7365e88bebcd.png">

### Logs

Old DSN: `https://8407e5bbce8547518946d4939de9ae16@o1.ingest.DOMAIN/2`
New DSN: `https://53bc39e8f48d44eebbf23f654683c7a3@o1.ingest.DOMAIN/2`

**Comment by BYK** [comment]
Whoops, that bot looks very broken, sorry @nodomain.

**Comment by BYK** [comment]
@jan-auer @untitaker this is the second report claiming DSN keys are not respected. Can you take a look.

**Comment by nodomain** [comment]
Thank you!

**Comment by untitaker** [comment]
This is the same issue as https://github.com/getsentry/sentry/issues/22789. That one has more users on it so I am inclined to close this one. I have left a reply there, tldr I am not actually able to reproduce this issue on onpremise.

>I then found that events are ingested and shown in the newly created project even if the key part of the DSN is different.

Different how? Changed to a completely random value or using a value from the previous install?

**Comment by BYK** [comment]
This issue should have been closed long ago as it got stale.
