### ISSUE TITLE
Any way to avoid initial database upgrade and key-generation?

### ISSUE THREAD

**Issue by drozzy** [getsentry/onpremise#85]
I would like to configure everything inside docker-compose file or via ENV variables.

Having a separate "initialization" step is a problem when I ship the system to the client. Usually I just say run:

docker-compose up -d

This would require additional instructions. Is there any way to pre-configure the key? Perhaps hardcode it? Similarly for database `upgrade` command.

Thanks.

**Comment by BYK** [comment]
I don't think there is a way to avoid the `upgrade` command other than running it once and then shipping the data container along with others. I think same goes with the secret key.

Feel free to dive into the main Sentry code base to create a custom version for yourself that does this if you're interested: https://github.com/getsentry/sentry
