### ISSUE TITLE
`You have no environments` when going to an individual transaction in Performance section

### ISSUE THREAD

**Issue by kmulka-medigo** [getsentry/onpremise#850]
### Version Information

Version: 20.12.0.dev0 d0ae462

### Steps to Reproduce

1. Click `Performance` on the left
2. Click an individual transaction
3. Click refresh in browser
4. Click on `All Environments`
5. Notice the message `You have no environments`

### Expected Result

I do have several environments configured for this project, so was expecting them to show up there so I could filter by environment.

https://sentry.example.com/organizations/sentry/performance/summary/?project=1&query=&statsPeriod=7d&transaction=example.get_foo&unselectedSeries=p100%28%29

### Actual Result

The message `You have no environments` shows up.

**Comment by BYK** [comment]
Do you have any logs you can share from the Sentry Web instance?

**Comment by kmulka-medigo** [comment]
Here's some logs around the time, but since they didn't show up right when I was clicking around I think they might not be related:

web_1                          | /usr/local/lib/python2.7/site-packages/sentry/models/project.py:184: DeprecationWarning: Project.callsign is deprecated. Use Group.get_short_id() instead.
web_1                          |   "Project.callsign is deprecated. Use Group.get_short_id() instead.", DeprecationWarning

**Comment by BYK** [comment]
@kmulka-medigo just curious, are you able to test with a more recent version of Sentry?

**Comment by mulka** [comment]
I would have, but I don't like the fact that there are no release notes for more recent versions

**Comment by BYK** [comment]
@mulka - seems like you are already on a nightly from December so not sure what you are worried about?

**Comment by kmulka-medigo** [comment]
Yea, I think that was a mistake. Should have used a stable version. Fear of the unknown I guess.

**Comment by BYK** [comment]
>Yea, I think that was a mistake. Should have used a stable version. Fear of the unknown I guess.

Most of the time our master is safe to deploy. The main reason we have labeled releases is to give people time and established points for breaking changes (such as dropping Python 2 support).

**Comment by kmulka-medigo** [comment]
Are there any breaking changes between what I'm on and the latest version?

**Comment by BYK** [comment]
@kmulka-medigo nope.
