### ISSUE TITLE
Make it possible for an administrator of the Sentry instance to delete performance transactions

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [getsentry/onpremise#856]
### Summary

It would be great to be able for an administrator of the Sentry instance to delete performance transactions that are available under http://machine:port/organizations/orgname/performance/. Currently it is already possible to delete issues http://machine:port/organizations/orgname/issues/, but not recorded transactions.

### Motivation

I believe it can be common to set up an instance running and then use it for some testing making sure the performance transactions are recorded and are valid. After the initial testing, one would want to use this instance for production, however the test performance transactions are no longer of interest and clutter the dashboards and skew statistics.

### Additional Context

It would be useful to be able to delete all performance transactions in one operation from the Settings UI or at least via a safe command-line command, if applicable. In addition, it would be very useful to be able to delete performance transactions by date (e.g. "delete last 30 days transactions").

**Comment by BYK** [comment]
@getsentry/sns is this something we can implement?

@alexey-tereshenkov-oxb - if your main use case is testing, why not just use different projects?

**Comment by alexey-tereshenkov-oxb** [comment]
@BYK thanks for the tip about using different projects. That's what I do, indeed. However, there is some overhead of switching between the projects as all clients would need get a new DSN (`/number`) and one would need to set up the alerts among other things. This is just a feature request -- please do decided whether this is something reasonable and useful to implement or not. :)

I think it's useful to be able to delete transactions that may have sneaked into the repository for some reason, whatever it can be -- let's say someone messed up the CI settings and running tests have submitted transactions and whatnot. It feels natural to be able to delete objects stored in a repository based on some criteria (coming from a certain host or within a given time range, for instance).

Cheers,

**Comment by alexey-tereshenkov-oxb** [comment]
Up

**Comment by untitaker** [comment]
@alexey-tereshenkov-oxb We currently try to avoid building the same type of featureset for transactions as we do for errors, as in the errors case we already have to deal with performance implications of [making issues deletable even if the database does not really support deletion](https://blog.sentry.io/2019/10/25/how-to-mutate-data-in-a-system-designed-for-immutable-data).

I think you need to clarify which usecase *you* actually *need* solved, as your two comments are talking about two different usecases that potentially have different solutions.

* For your OP: The way to separate staging/test from production is via environments. This holds true for both transactions and errors.
* For the case of deleting accidental trash data, we have no obvious solution yet except to exclude from queries until retention deletes the data.

**Comment by alexey-tereshenkov-oxb** [comment]
@untitaker thanks a lot for extra context, that's very helpful.

Let's focus on a use case where there are accidental registration of metrics that is not coming from a valid user -- this could be anything, but, say, from CI or some stress testing environment which for some reason didn't disable telemetry collection. Does this sound like a plausible use case for you?

**Comment by untitaker** [comment]
Either one does, but I'm trying to understand what your specific situation
is :)
