### ISSUE TITLE
Sentry Cloud/Self Hosted issue with 2FA

### ISSUE THREAD

**Issue by hasore** [getsentry/onpremise#858]
### Version Information

Version: 21.1.0

### Steps to Reproduce

1. Register an account on either Sentry Cloud or Sentry Self Hosted and set-up 2FA.
2. Register an account (using same email address) on either Sentry Cloud or another instance of Sentry Self Hosted and set-up 2FA using the same app and device used on step 1.
3. Try to log in on account created on first step.

### Expected Result

- A new 2FA Sentry Instance should be created on 2FA application.

### Actual Result

- Previous 2FA Sentry Instance is replaced with new 2FA Sentry Instance.

### Observation
- This was tested using Microsoft Authenticator, didn't try on Google Authenticator, Authy or other apps.

**Comment by BYK** [comment]
Duplicate of getsentry/sentry#23824
