### ISSUE TITLE
kafka error

### ISSUE THREAD

**Issue by rajkumarks7** [getsentry/onpremise#868]
### Version Information
20.11.1
Version: *VERSION HERE*

### Steps to Reproduce
just install in ec2 and leave it
1. What 
2. you
3. did.
i did not thign but getting this error  KafkaError{code=_TIMED_OUT,val=-185,str="FindCoordinator resp
### Expected Result
no error 
What you thought would happen.

### Actual Result
KafkaError{code=_TIMED_OUT,val=-185,str="FindCoordinator resp
What actually happened. Maybe a screenshot/recording?

### Logs

What you saw along the way, e.g.:

- latest install logs: `ls -1 sentry_install_log-*.txt | tail -1 | xargs cat`
- `docker-compose logs` output

**Comment by chadwhitacre** [comment]
Sorry for the trouble @rajkumarks7. Is there a reason you're using `20.11.1` instead of the latest version? Can you paste more of the error? `FindCoordinator` sounds to me like a network issue in your setup. Can you be more specific about the steps you are following to install Sentry?

**Comment by rajkumarks7** [comment]
1) hey thank you for your response i followed the below link to get sentry on to certain domain available.  

https://datayuge.com/install-sentry-with-docker-on-ubuntu-self-hosted/

2)i just cloned the latest master branch from the getsentry/onpremise and followed the below link for the installation.

https://develop.sentry.dev/self-hosted/

please let me know if you need more information and one more thing do we need a ssl can we use it on the 'http:' rather than 'https:'

**Comment by chadwhitacre** [comment]
I need a lot more detail to be able to help you. (1) and (2) describe different installation methods. Skimming (1) I see a custom `installer.sh` script, for example. So what exactly did you do to install Sentry?

I also asked you to paste more of the error. Can you do that?

> one more thing do we need a ssl can we use it on the 'http:' rather than 'https:'

You can use it on http, you don't need ssl if you don't want it.

**Comment by rajkumarks7** [comment]
yes it is a network error presently i am not getting any error thank you for your support.
