### ISSUE TITLE
Update deletes issue tracking and performance metrics data

### ISSUE THREAD

**Issue by pharindoko** [getsentry/onpremise#876]
### Version Information

Version: 20.12.1

### Steps to Reproduce

1. Update sentry from 20.11.1 to 20.12.1

### Expected Result

Issue tracking and performance data is still available.

### Actual Result

Data is lost.

### Logs

We use AWS EC2 with autoscaling. This might be the reason. I guess that I deleted the Instance and the root volume was deleted.
**My Question:**
Where does sentry onpremise persist the performance and issue data ? On the VM the docker-compose is running ?
Or in redis container itself ?

The masterdata is still available. This is kept in an external postgre Rds database.

**Comment by BYK** [comment]
Hi @pharindoko: does this answer your question: https://develop.sentry.dev/self-hosted/backup/#full-backup

**Comment by pharindoko** [comment]
@BYK 
Thanks a lot - yes that answers the question
