### ISSUE TITLE
Can't deliver erros to sentry

### ISSUE THREAD

**Issue by nuget1991** [getsentry/onpremise#879]
### Version Information

Version: 20.11.0

### Steps to Reproduce

So I can't receive any errors into sentry. I dumped traffic and apps are delivering their messages to sentry server. So I tried to look into docker logs and I saw "***sentry kafka:9092/bootstrap: Connect to ipv4 **" into containers. But kafka container was up and running. Into kafka logs I saw that kafka " Failed to elect leader for partition outcomes-0" and the same messages with other partitions. After it I removed data from from kafka - /bin/rm -rf /var/lib/docker/volumes/sentry-kafka/_data/ and start containers again. It didn't help(. Changed in compose file sentry-kafka:/var/lib/kafka/data to sentry-kafka:/var/lib/kafka. No luck again. Also kafka container is restarting all the time. After it I tried upgrade sentry to the latest version using install.sh script in other directory with my sentry.conf.py Dockerfile and config.yml. During install script it reported that my install can't connect to kafka and aborted. So I have a several questions: 1) Corect way of updating sentry from 20.11.0 to latest stable release where we will have no problems with delivery errors in high load and save current sentry configuration; 2) May be we can fix current version, what can you suggest? In repository I can see only 20.11.1 version. So currentry after recreating volumes of kafka and zookeper kafka is not restaring but now restaring zoookeper container all the time. In logs:

[2021-03-03 17:34:33,420] WARN Either no config or no quorum defined in config, running in standalone mode (org.apache.zookeeper.server.quorum.QuorumPeerMain)
[2021-03-03 17:34:33,551] WARN o.e.j.s.ServletContextHandler@4d95d2a2{/,null,UNAVAILABLE} contextPath ends with /* (org.eclipse.jetty.server.handler.ContextHandler)
[2021-03-03 17:34:33,551] WARN Empty contextPath (org.eclipse.jetty.server.handler.ContextHandler)
[2021-03-03 17:34:33,680] ERROR Unexpected exception, exiting abnormally (org.apache.zookeeper.server.ZooKeeperServerMain)
java.io.IOException: No snapshot found, but there are log entries. Something is broken!

### Expected Result

Deliver message to sentry or upgrade and deliver message to sentry)

### Actual Result

No screenshot recording but have logs.

### Logs

What you saw along the way, e.g.:

- Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
%3|1605784978.335|FAIL|rdkafka#producer-3| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.18.0.5:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1605784979.335|FAIL|rdkafka#producer-3| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.18.0.5:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)

- docker-compose didn't show any errors during all steps

**Comment by chadwhitacre** [comment]
Sounds like a networking issue. Are all components running on the same node? I.e., are you running stock install with `docker-compose up` or something custom?

**Comment by nuget1991** [comment]
Yes, all components running on the same node, I just add custom static net on all containers of sentry and started them using docker-compose up. Checked availability and hadn't any problem with docker net.

**Comment by nuget1991** [comment]
Currently I have the following logs into zookeeper container (and it is restarting all the time):
[2021-03-04 04:22:05,927] ERROR Unexpected exception, exiting abnormally (org.apache.zookeeper.server.ZooKeeperServerMain)
java.io.IOException: No snapshot found, but there are log entries. Something is broken!

**Comment by BYK** [comment]
> I just add custom static net on all containers of sentry and started them using docker-compose up

Not sure if this is a good idea as we rely on `docker-compose`'s internal DNS system to route things to the correct service container. If that works tho, this should be fine.

>Currently I have the following logs into zookeeper container (and it is restarting all the time):

This seems to be the main issue then (I noticed this was in your original report but logs were not formatted so they weren't easy to read or parse and we missed this). We have a built-in workaround for this issue here: https://github.com/getsentry/onpremise/blob/7365a034575b3beeb6fc70103f13916b52b7f29a/install.sh#L269-L278

Are you running our install script for upgrades?

**Comment by nuget1991** [comment]
I didn't clone repo and install sentry first time, it means that I wget https://github.com/getsentry/onpremise/archive/releases/20.11.0.zip and perform install script - I haven't git there. After it I have made static net into sentry. So what is correct way of upgrade sentry to the latest version now? 1) Perform git clone from sentry repo on separate directory 2) Change install script in 20.11.0 directory by creating install script from master and perform it?

**Comment by BYK** [comment]
> So what is correct way of upgrade sentry to the latest version now? 1) Perform git clone from sentry repo on separate directory 2) Change install script in 20.11.0 directory by creating install script from master and perform it?

See the 3rd paragraph on https://develop.sentry.dev/self-hosted/#upgrading

>To upgrade, all you need to do is download or check out the version of onpremise repository you want, replace your existing folder's contents with that, and then run ./install.sh. **We may have some updated configuration, especially for new features, so always check the example config files under the sentry directory and see if you need to update your existing configuration.** We do our best to automate critical configuration updates, but you should always check your configs during upgrades.

You don't really need git, you should be able to just unzip the latest release onto your existing folder and allow rewrites. It will keep any customizable configs but beware that it will overwrite anything tracked in the repo.
