### ISSUE TITLE
ubuntu20 docker20 can not run onpremise-21.2.0

### ISSUE THREAD

**Issue by 6qiongtao** [getsentry/onpremise#880]
### Version Information

Version: 
*
Host system: Ubuntu 20.04.1 LTS amd64,
Docker version: 20.10.1, build 831ebea,
onpremise-21.2.0
*

### Steps to Reproduce

I built Sentry in Ubuntu 20, Everything looks pretty normal when I look at the UI,But when I use the code to send a message, I can't get it,I can't see it in the UI.

### Expected Result

Errors should be ingested.

### Logs

```
nginx_1 | 192.168.31.47 - - [03/Mar/2021:13:56:28 +0000] "GET /api/0/projects/sentry/go/rules/configuration/ HTTP/1.1" 200 5789 "http://192.168.31.244:9000/organizations/sentry/alerts/go/new/?referrer=alert_stream" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15" "-"
relay_1  | 2021-03-03T13:56:52Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 57.665039062s
relay_1  | 2021-03-03T13:57:08Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
relay_1  |   caused by: could not send request using actix-web client
relay_1  |   caused by: Failed to connect to host: Failed resolving hostname: no record found for name: web type: AAAA class: IN
relay_1  |   caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
relay_1  |   caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
web_1   | 13:57:11 [INFO] sentry.superuser: superuser.request (url='http://192.168.31.244/api/0/organizations/sentry/members/?query=' method='GET' ip_address='192.168.31.47' user_id=1)
```

### Actual Result

```
ERROR: authentication encountered error: could not send request to upstream relay_1
```

### Notes

I downgrading docker version fixed the problem.

```
apt-get remove -y docker-ce docker-ce-cli
apt-get install -y --allow-downgrades docker-ce=5:19.03.14~3-0~ubuntu-bionic docker-ce-cli=5:19.03.14~3-0~ubuntu-bionic
```

**Comment by BYK** [comment]
Can you try using the latest relay image (`RELAY_IMAGE=getsentry/relay:nightly ./install.sh`) and try again as it should have a fix for this.

**Comment by 6qiongtao** [comment]
sorry,sir. I thinks Problems remain.

As you mentioned, I using the latest relay image (RELAY_IMAGE=getsentry/relay:nightly ./install.sh) and try again as it, Can't  fix it.

### Log

`nginx_1                                     | 172.25.0.1 - - [04/Mar/2021:14:57:28 +0000] "GET /api/0/organizations/sentry/issues/?collapse=stats&limit=25&project=2&query=is%3Aunresolved&shortIdLookup=1&statsPeriod=24h HTTP/1.1" 200 2 "http://localhost:9000/organizations/sentry/issues/?project=2&statsPeriod=24h" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36" "-"
nginx_1                                     | 172.25.0.1 - - [04/Mar/2021:14:57:28 +0000] "GET /api/0/organizations/sentry/sent-first-event/?project=2 HTTP/1.1" 200 23 "http://localhost:9000/organizations/sentry/issues/?project=2&statsPeriod=24h" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36" "-"
nginx_1                                     | 172.25.0.1 - - [04/Mar/2021:14:57:28 +0000] "GET /api/0/organizations/sentry/projects/?per_page=1&query=id%3A2 HTTP/1.1" 200 562 "http://localhost:9000/organizations/sentry/issues/?project=2&statsPeriod=24h" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36" "-"
relay_1                                     | 2021-03-04T14:57:30Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
relay_1                                     |   caused by: could not send request using actix-web client
relay_1                                     |   caused by: Failed to connect to host: Failed resolving hostname: no record found for name: web type: AAAA class: IN
relay_1                                     |   caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
relay_1                                     |   caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
^CGracefully stopping... (press Ctrl+C again to force)
Stopping sentry_onpremise_nginx_1                                    ... done
Stopping sentry_onpremise_subscription-consumer-transactions_1       ... done
Stopping sentry_onpremise_sentry-cleanup_1                           ... done
Stopping sentry_onpremise_cron_1                                     ... done
Stopping sentry_onpremise_post-process-forwarder_1                   ... done
Stopping sentry_onpremise_subscription-consumer-events_1             ... done
Stopping sentry_onpremise_worker_1                                   ... done
Stopping sentry_onpremise_web_1                                      ... done
Stopping sentry_onpremise_ingest-consumer_1                          ... done
Stopping sentry_onpremise_snuba-cleanup_1                            ... done
Stopping sentry_onpremise_relay_1                                    ... done
Stopping sentry_onpremise_symbolicator-cleanup_1                     ... done
Stopping sentry_onpremise_snuba-api_1                                ... done
Stopping sentry_onpremise_snuba-subscription-consumer-events_1       ... done
Stopping sentry_onpremise_snuba-sessions-consumer_1                  ... done
Stopping sentry_onpremise_snuba-transactions-consumer_1              ... done
Stopping sentry_onpremise_snuba-consumer_1                           ... done
Stopping sentry_onpremise_snuba-replacer_1                           ... done
Stopping sentry_onpremise_snuba-outcomes-consumer_1                  ... done
Stopping sentry_onpremise_snuba-subscription-consumer-transactions_1 ... done
Stopping sentry_onpremise_memcached_1                                ... done
Stopping sentry_onpremise_symbolicator_1                             ... done
Stopping sentry_onpremise_smtp_1                                     ... done
Stopping sentry_onpremise_postgres_1                                 ... done
Stopping sentry_onpremise_kafka_1                                    ... done
Stopping sentry_onpremise_redis_1                                    ... done
Stopping sentry_onpremise_zookeeper_1                                ... done
Stopping sentry_onpremise_clickhouse_1                               ... done
barry@ubuntu:~/go/middleware/sentry/onpremise$ printenv |grep RELAY_IMAGE
RELAY_IMAGE=getsentry/relay:nightly
barry@ubuntu:~/go/middleware/sentry/onpremise$ docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

`

my go code
sentry.go
`
package main

import (
	"errors"
	"log"
	"time"

	"github.com/getsentry/sentry-go"
)

func main() {
	err := sentry.Init(sentry.ClientOptions{
		Dsn: "http://88d47609601a4d15b880a2096249e4ea@127.0.0.1:9000/2",
		Debug : true,
	})
	if err != nil {
		log.Fatalf("sentry.Init: %s", err)
	}
	// Flush buffered events before the program terminates.
	defer sentry.Flush(5 * time.Second)
	sentry.CaptureException(errors.New("wo cao,shou bu dao"))
	sentry.CaptureMessage("test one first")
}
`
go run sentry.go

**Comment by BYK** [comment]
Oh wait, you also need to set `RELAY_IMAGE=getsentry/relay:nightly` when running `docker-compose up` like `RELAY_IMAGE=getsentry/relay:nightly docker-compose up` (or just change it in your `.env` file in the repo).

Sorry for the missing info earlier.
