### ISSUE TITLE
docker-compose base service, should it run?

### ISSUE THREAD

**Issue by fredvd** [getsentry/onpremise#9]
From reading the docker-compose.yml I get the impression that the base service is an abstract definition of config and the other services extend on it. 

But docker-compose is happily starting 'base' and it runs the default command from the sentry:8.8-onbuild image.  Or is it necessary to have this double django service running, once exposed and once running without being able to accept any connections?

There's a discussion on compose abstract services here. 
https://github.com/docker/compose/issues/1988

**Comment by mattrobenolt** [comment]
Yeah, it should work. If there are any specific issues with it, let me know. I'm not particularly a docker-compose user, so this doesn't see much love. I'm happy for someone to contribute to it.

**Comment by mattrobenolt** [comment]
This was meant to be closed with https://github.com/getsentry/onpremise/commit/177ed0efa8df77a7e76ba557708127eddfd0d8ef
