### ISSUE TITLE
Configure IP range on .env file

### ISSUE THREAD

**Issue by ErMaqui** [getsentry/onpremise#915]
### Summary

Allow to configure network range to be used by docker-compose on .env file or another method

### Motivation

Each time I execute install.sh, composer creates a new ip configuration, and delete old one. Thats is, creating new network range, and breaking some configurations (for example, allow rules on my own postgresql server).

### Additional Context

Probably the same problem are present if try to upgrade sentry.

**Comment by BYK** [comment]
Feel like it is better to mark this as a duplicate of #770 and move in that direction, what do you think @ErMaqui?

**Comment by ErMaqui** [comment]
I think that can be correct.
