### ISSUE TITLE
Support docker-compose installed as a container

### ISSUE THREAD

**Issue by PMExtra** [getsentry/onpremise#931]
### Version Information

Version: 21.4.1

### Steps to Reproduce

1. `./install.sh`
2. Got error:
```text
...
▶ Fetching and updating Docker images ...


        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
        
21.4.1: Pulling from getsentry/sentry
Digest: sha256:3a213d32539701290f8eb244d0c6e849fae16ebba846a24e413f185987d6d2b5
Status: Image is up to date for getsentry/sentry:21.4.1
docker.io/getsentry/sentry:21.4.1

▶ Building and tagging Docker images ...


        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
        
An error occurred, caught SIGERR on line 4
Cleaning up...
```

I've tried to analyse for the first error. It's from
https://github.com/getsentry/onpremise/blob/e7a11016838a1a8ea85db2f8869f6f1eafb90368/install/update-docker-images.sh#L8

I inserted a `pwd` command before this line, it print `/root/onpremise/install` !
But  `docker-compose.yml` is in the `/root/onpremise` .

Then I found the `_lib.sh` has been refactor recently: https://github.com/getsentry/onpremise/commit/a0a86e400f886cb65471bb6f79600872e0db7ba0#diff-1b8181453221651d519090bfd43b23252b324c5fc3756c6f61de3c6aeed9a5c1R9-R13

**Comment by PMExtra** [comment]
I temporary add `cd ..` and `cd install` around each `$dc ...` commands, the problem was solved.

**Comment by BYK** [comment]
Hi @PMExtra! This has been working as expected on our CI and local builds. Can you share some more information so we can find what edge case we missed during this refactor and in our tests?

**Comment by BYK** [comment]
Also, in the error message it says (emphasis mine)

>Can't find a suitable configuration file in this directory **or any parent**.

So even if we are in the `install` directory, this should be fine.

**Comment by PMExtra** [comment]
I got it. It because I installed `docker-compose` as a container (https://docs.docker.com/compose/install/#install-as-a-container).
It will mount only current work directory. So it can't access the parent directory.

Would you make a patch to adapt this case? Or make a hint in document to prevent people to use containerized docker-compose.

**Comment by BYK** [comment]
>It will mount only current work directory in the temporary container. So it can't access the parent directory.

If you mount the root of this repo, it should still work though, right?

**Comment by PMExtra** [comment]
@BYK I think it's right. But it mounted by docker official script, I can't change this behavior easily.

In the https://docs.docker.com/compose/install/#install-as-a-container document:
> ```
> sudo curl -L --fail https://github.com/docker/compose/releases/download/1.29.1/run.sh -o /usr/local/bin/docker-compose
> sudo chmod +x /usr/local/bin/docker-compose
> ```

The `run.sh` will create a temporary container to execute docker-compose, and mount only the current work directory.

**Comment by PMExtra** [comment]
For simply, it's like `alias docker-compose='docker run -v $(pwd):$(pwd) -w $(pwd) ... docker/comose:1.29.1'`

**Comment by BYK** [comment]
Ah, now I got it. When this is invoked from the script inside, it cannot see the outer directory. I'll see what we can do about this.

/cc @chadwhitacre

**Comment by chadwhitacre** [comment]
Thanks for the report @PMExtra.

If/when we get to this, I'd love to see this tested in CI somehow so we don't regress in the future.

**Comment by PMExtra** [comment]
I found the new project: https://github.com/docker/compose-cli
It's already integrated with Docker Desktop (Windows / macOS).
I think it will come to the Linux platform soon (for now, we can install it in Linux manually)

So I think install docker-compose as a container will be an obsoleted solution, we can give up to support it. Just take a hint in documentation is enough.
