### ISSUE TITLE
Stronger queries with Discover

### ISSUE THREAD

**Issue by mikkylok** [getsentry/onpremise#935]
### Summary

I am using a self-hosted sentry service (latest release 21.4.1). However my Discover interface is different from the one described in this [release blog](https://blog.sentry.io/2019/03/06/new-features-greater-visibility/) - Discover:

### Motivation

I need to aggregate results by day or week, and do more customized result filtering. 

### Additional Context

Does anybody know which on-premise release include [this discover interface](https://images.ctfassets.net/em6l9zw4tzag/ErHrw5F89sQmYQ2pb8OsD/7a074acec24d51cc8bcfe4e88154ea71/dashboards-discover.png?w=2402)?

Any guidance is appreciated!

**Comment by BYK** [comment]
Hi @mikkylok - that blog post is quite dated and that interface is actually the _old_ Discover UI :)

You may find information for daily grouping over at: https://docs.sentry.io/product/sentry-basics/guides/discover/#errors-by-hour-or-day
