### ISSUE TITLE
Add .env to .gitignore

### ISSUE THREAD

**Issue by dimi-github** [getsentry/onpremise#936]
### Summary

The file .env is every time changed according to documentation, but needs to be stashed and restored on each update.

### Motivation

Adding .env file to .gitignore (as already done on sentry repo) will simplify updates. Best practice would be to deal with this file as already done with other configuration files.

**Comment by BYK** [comment]
Hi @dimi-github,

This is intentional as that's how we set the versions of the Docker images with releases. We do not recommend using this file for customization.

**Comment by dimi-github** [comment]
Got it. Would it probably be better to create another file for docker image version variables and don't touch .env? Because only in this file is possible to change some important variables and we need to stash and restore it on each update.

**Comment by BYK** [comment]
@dimi-github You should be able to use `docker-compose.override.yml`. Does it not work for you?

**Comment by dimi-github** [comment]
Need to test. Anything from .gitignore would work for me. But docker-compose.override.yml is normally used for environment definitions. We have only one environment. It makes only things probably little wired because mostly we use .env for customizing :)

**Comment by BYK** [comment]
@dimi-github you may use this then: https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file

This is also something we may look into @chadwhitacre

**Comment by dimi-github** [comment]
Sure, thanks. I know all the possibilities. I only saw .env already in .gitignore in other sentry repo and thought it may be a bug here. But never mind, we can manage it. Thanks for fast responding and also ideas and explanation!
