### ISSUE TITLE
Failed to run install.sh on Ubuntu

### ISSUE THREAD

**Issue by graferowy** [getsentry/onpremise#942]
### Version Information

Version: 21.4.1
Docker: 20.10.6
Ubuntu 20.04 (WSL)

### Steps to Reproduce

1. Clone the repository to local user folder
2. Run install.sh script without any options

### Expected Result

Script runs smoothly

### Actual Result

Script fails to succeed

### Logs

After running `sh ./install.sh`

`./install.sh: 2: set: Illegal option -`

After running `./install.sh`

`/usr/bin/env: ‘bash\r’: No such file or directory`

After converting file to DOS type using dos2unix and running `sh ./install.sh`

`./install.unix.sh: 3: [[: not found
./install.unix.sh: 8: source: not found`

After converting file to DOS type using dos2unix and running `./install.sh`

`: invalid option namene 1: set: pipefail`

**Comment by BYK** [comment]
I think your local `git` installation converts line endings to `CRLF` automatically. I'd try dowloading the repo as a zip archive and try that way.

I just double checked our line endings and all are `LF`. We also have CI tests that run on Ubuntu so this is 100% an issue with your system.

**Comment by graferowy** [comment]
Just to confirm, It was probably git. I downloaded a zip repository and uzipped it and the script finished successfuly.
