### ISSUE TITLE
Unable to update config.yml (or create one with custom settings) to use SMTP server

### ISSUE THREAD

**Issue by subrato30** [getsentry/onpremise#953]
### Version Information

Version: *21.4.1*

### Steps to Reproduce

1. Clone the repo on the Ubuntu EC2 instance
2. Run ./install.sh 
3. Open sentry/config.yml
4. Add smtp  (Need to use office 365) settings in the mail section
5. Run docker-compose up -d 

### Expected Result
The containers should run without any error

What you thought would happen.
Open the browser and continue with sentry setup

### Actual Result
!! Configuration error: ConfigurationError('Malformed config.yml file: did not find expected <document start>\n  in "/etc/sentry/config.yml", line 38, column 1',)

![Sentry-Capture](https://user-images.githubusercontent.com/41803529/118197797-a4fc9500-b41d-11eb-8e1c-027be247ff09.PNG)

Line 38 is where system.secret_key is stored. 

What actually happened. Maybe a screenshot/recording?

### Logs

Docker-compose logs output

Attaching to sentry_onpremise_snuba-outcomes-consumer_1, sentry_onpremise_snuba-consumer_1, sentry_onpremise_snuba-subscription-consumer-events_1, sentry_onpremise_snuba-sessions-consumer_1, sentry_onpremise_snuba-transactions-consumer_1, sentry_onpremise_snuba-subscription-consumer-transactions_1, sentry_onpremise_snuba-replacer_1, sentry_onpremise_smtp_1, sentry_onpremise_snuba-api_1, sentry_onpremise_memcached_1, sentry_onpremise_postgres_1, sentry_onpremise_symbolicator_1, sentry_onpremise_kafka_1, sentry_onpremise_clickhouse_1, sentry_onpremise_redis_1, sentry_onpremise_zookeeper_1
memcached_1                                 | Signal handled: Terminated.
clickhouse_1                                | Processing configuration file '/etc/clickhouse-server/config.xml'.
clickhouse_1                                | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
clickhouse_1                                | Merging configuration file '/etc/clickhouse-server/config.d/sentry.xml'.
clickhouse_1                                | Include not found: clickhouse_remote_servers
clickhouse_1                                | Include not found: clickhouse_compression
clickhouse_1                                | Logging information to /var/log/clickhouse-server/clickhouse-server.log
clickhouse_1                                | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
clickhouse_1                                | Logging information to console
clickhouse_1                                | 2021.05.13 21:10:50.202315 [ 1 ] {} <Information> : Starting ClickHouse 20.3.9.70 with revision 54433
clickhouse_1                                | 2021.05.13 21:10:50.211129 [ 1 ] {} <Information> Application: starting up
clickhouse_1                                | Include not found: networks
clickhouse_1                                | 2021.05.13 21:10:50.221857 [ 1 ] {} <Information> Application: Uncompressed cache size was lowered to 3.89 GiB because the system has low amount of memory
clickhouse_1                                | 2021.05.13 21:10:50.222171 [ 1 ] {} <Information> Application: Mark cache size was lowered to 3.89 GiB because the system has low amount of memory
clickhouse_1                                | 2021.05.13 21:10:50.222210 [ 1 ] {} <Information> Application: Loading metadata from /var/lib/clickhouse/
clickhouse_1                                | 2021.05.13 21:10:50.223769 [ 1 ] {} <Information> DatabaseOrdinary (system): Total 2 tables and 0 dictionaries.
clickhouse_1                                | 2021.05.13 21:10:50.226564 [ 46 ] {} <Information> BackgroundProcessingPool: Create BackgroundProcessingPool with 16 threads
clickhouse_1                                | 2021.05.13 21:10:50.262804 [ 1 ] {} <Information> DatabaseOrdinary (system): Starting up tables.
clickhouse_1                                | 2021.05.13 21:10:50.276259 [ 1 ] {} <Information> DatabaseOrdinary (default): Total 13 tables and 0 dictionaries.
clickhouse_1                                | 2021.05.13 21:10:50.293816 [ 1 ] {} <Information> DatabaseOrdinary (default): Starting up tables.
clickhouse_1                                | 2021.05.13 21:10:50.295102 [ 1 ] {} <Information> BackgroundSchedulePool: Create BackgroundSchedulePool with 16 threads
clickhouse_1                                | 2021.05.13 21:10:50.302164 [ 1 ] {} <Information> Application: It looks like the process has no CAP_NET_ADMIN capability, 'taskstats' performance statistics will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_net_admin=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems. It also doesn't work if you run clickhouse-server inside network namespace as it happens in some containers.
clickhouse_1                                | 2021.05.13 21:10:50.302314 [ 1 ] {} <Information> Application: It looks like the process has no CAP_SYS_NICE capability, the setting 'os_thread_nice' will have no effect. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_sys_nice=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
clickhouse_1                                | 2021.05.13 21:10:50.303895 [ 1 ] {} <Error> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
clickhouse_1                                | 2021.05.13 21:10:50.304386 [ 1 ] {} <Error> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
clickhouse_1                                | 2021.05.13 21:10:50.304920 [ 1 ] {} <Error> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
clickhouse_1                                | 2021.05.13 21:10:50.305433 [ 1 ] {} <Error> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
clickhouse_1                                | 2021.05.13 21:10:50.305783 [ 1 ] {} <Information> Application: Listening for http://0.0.0.0:8123
clickhouse_1                                | 2021.05.13 21:10:50.306013 [ 1 ] {} <Information> Application: Listening for connections with native protocol (tcp): 0.0.0.0:9000
clickhouse_1                                | 2021.05.13 21:10:50.306218 [ 1 ] {} <Information> Application: Listening for replica communication (interserver): http://0.0.0.0:9009
clickhouse_1                                | 2021.05.13 21:10:50.551811 [ 1 ] {} <Information> Application: Listening for MySQL compatibility protocol: 0.0.0.0:9004
clickhouse_1                                | 2021.05.13 21:10:50.556275 [ 1 ] {} <Information> Application: Available RAM: 7.77 GiB; physical cores: 2; logical cores: 2.
clickhouse_1                                | 2021.05.13 21:10:50.556297 [ 1 ] {} <Information> Application: Ready for connections.
clickhouse_1                                | Include not found: clickhouse_remote_servers
clickhouse_1                                | Include not found: clickhouse_compression
clickhouse_1                                | 2021.05.13 21:11:05.438798 [ 85 ] {f8aa847f-3471-4f3e-9879-cea70a922a2c} <Information> executeQuery: Read 1 rows, 1.00 B in 0.001 sec., 1274 rows/sec., 1.25 KiB/sec.
clickhouse_1                                | 2021.05.13 21:11:05.439111 [ 85 ] {} <Information> TCPHandler: Processed in 0.001 sec.
clickhouse_1                                | 2021.05.13 21:11:05.441144 [ 85 ] {bc819212-6014-4150-b9cc-86fb48aa06a4} <Information> executeQuery: Read 40 rows, 2.51 KiB in 0.001 sec., 33004 rows/sec., 2.03 MiB/sec.
clickhouse_1                                | 2021.05.13 21:11:05.441378 [ 85 ] {} <Information> TCPHandler: Processed in 0.002 sec.
clickhouse_1                                | 2021.05.13 21:11:05.469823 [ 85 ] {} <Information> TCPHandler: Done processing connection.
clickhouse_1                                | 2021.05.13 21:12:22.526927 [ 44 ] {} <Information> Application: Received termination signal (Terminated)
clickhouse_1                                | 2021.05.13 21:12:22.952639 [ 1 ] {} <Information> Application: Closed all listening sockets.
clickhouse_1                                | 2021.05.13 21:12:22.952690 [ 1 ] {} <Information> Application: Closed connections.
clickhouse_1                                | 2021.05.13 21:12:22.953220 [ 1 ] {} <Information> Application: Shutting down storages.
clickhouse_1                                | 2021.05.13 21:12:23.426534 [ 1 ] {} <Information> Application: shutting down
clickhouse_1                                | 2021.05.13 21:12:23.426649 [ 44 ] {} <Information> BaseDaemon: Stop SignalListener thread
postgres_1                                  |
postgres_1                                  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1                                  |
postgres_1                                  | LOG:  database system was shut down at 2021-05-13 21:05:22 UTC
postgres_1                                  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1                                  | LOG:  database system is ready to accept connections
postgres_1                                  | LOG:  autovacuum launcher started
postgres_1                                  | LOG:  received fast shutdown request
postgres_1                                  | LOG:  aborting any active transactions
postgres_1                                  | LOG:  autovacuum launcher shutting down
postgres_1                                  | LOG:  shutting down
postgres_1                                  | LOG:  database system is shut down
redis_1                                     | 1:C 13 May 2021 21:10:49.905 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1                                     | 1:C 13 May 2021 21:10:49.905 # Redis version=5.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1                                     | 1:C 13 May 2021 21:10:49.905 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                                     | 1:M 13 May 2021 21:10:49.907 * Running mode=standalone, port=6379.
redis_1                                     | 1:M 13 May 2021 21:10:49.907 # Server initialized
redis_1                                     | 1:M 13 May 2021 21:10:49.907 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                                     | 1:M 13 May 2021 21:10:49.907 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1                                     | 1:M 13 May 2021 21:10:49.910 * DB loaded from disk: 0.003 seconds
redis_1                                     | 1:M 13 May 2021 21:10:49.910 * Ready to accept connections
redis_1                                     | 1:signal-handler (1620940342) Received SIGTERM scheduling shutdown...
redis_1                                     | 1:M 13 May 2021 21:12:22.600 # User requested shutdown...
redis_1                                     | 1:M 13 May 2021 21:12:22.606 * Saving the final RDB snapshot before exiting.
redis_1                                     | 1:M 13 May 2021 21:12:22.615 * DB saved on disk
redis_1                                     | 1:M 13 May 2021 21:12:22.615 # Redis is now ready to exit, bye bye...
smtp_1                                      | + sed -ri '
smtp_1                                      |   s/^#?(dc_local_interfaces)=.*/\1='\''0.0.0.0 ; ::0'\''/;
smtp_1                                      |   s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
smtp_1                                      |   s/^#?(dc_relay_nets)=.*/\1='\''0.0.0.0\/0'\''/;
smtp_1                                      |   s/^#?(dc_eximconfig_configtype)=.*/\1='\''internet'\''/;
smtp_1                                      | ' /etc/exim4/update-exim4.conf.conf
smtp_1                                      | + update-exim4.conf -v
smtp_1                                      | using non-split configuration scheme from /etc/exim4/exim4.conf.template
smtp_1                                      |   269 LOG: MAIN
smtp_1                                      |   269   exim 4.92 daemon started: pid=269, no queue runs, listening for SMTP on port 25 (IPv6 and IPv4)
kafka_1                                     | ===> ENV Variables ...
kafka_1                                     | ALLOW_UNSIGNED=false
kafka_1                                     | COMPONENT=kafka
kafka_1                                     | CONFLUENT_DEB_VERSION=1
kafka_1                                     | CONFLUENT_PLATFORM_LABEL=
kafka_1                                     | CONFLUENT_SUPPORT_METRICS_ENABLE=false
kafka_1                                     | CONFLUENT_VERSION=5.5.0
kafka_1                                     | CUB_CLASSPATH=/etc/confluent/docker/docker-utils.jar
kafka_1                                     | HOME=/root
kafka_1                                     | HOSTNAME=045c5a62b8e0
kafka_1                                     | KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
kafka_1                                     | KAFKA_LOG4J_LOGGERS=kafka.cluster=WARN,kafka.controller=WARN,kafka.coordinator=WARN,kafka.log=WARN,kafka.server=WARN,kafka.zookeeper=WARN,state.change.logger=WARN
kafka_1                                     | KAFKA_LOG4J_ROOT_LOGLEVEL=WARN
kafka_1                                     | KAFKA_LOG_RETENTION_HOURS=24
kafka_1                                     | KAFKA_MAX_REQUEST_SIZE=50000000
kafka_1                                     | KAFKA_MESSAGE_MAX_BYTES=50000000
kafka_1                                     | KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=1
kafka_1                                     | KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
kafka_1                                     | KAFKA_TOOLS_LOG4J_LOGLEVEL=WARN
kafka_1                                     | KAFKA_VERSION=
kafka_1                                     | KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
kafka_1                                     | LANG=C.UTF-8
kafka_1                                     | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
kafka_1                                     | PWD=/
kafka_1                                     | PYTHON_PIP_VERSION=8.1.2
kafka_1                                     | PYTHON_VERSION=2.7.9-1
kafka_1                                     | SCALA_VERSION=2.12
kafka_1                                     | SHLVL=1
kafka_1                                     | ZULU_OPENJDK_VERSION=8=8.38.0.13
kafka_1                                     | _=/usr/bin/env
kafka_1                                     | ===> User
kafka_1                                     | uid=0(root) gid=0(root) groups=0(root)
kafka_1                                     | ===> Configuring ...
kafka_1                                     | ===> Running preflight checks ...
kafka_1                                     | ===> Check if /var/lib/kafka/data is writable ...
kafka_1                                     | ===> Check if Zookeeper is healthy ...
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.5.7-f0fdd52973d373ffd9c86b81d99842dc2c7f660e, built on 02/10/2020 11:30 GMT
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:host.name=045c5a62b8e0
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.8.0_212
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Azul Systems, Inc.
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.home=/usr/lib/jvm/zulu-8-amd64/jre
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=/etc/confluent/docker/docker-utils.jar
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/tmp
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.version=5.4.0-1048-aws
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.name=root
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.home=/root
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.free=117MB
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.max=1769MB
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.total=121MB
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=zookeeper:2181 sessionTimeout=40000 watcher=io.confluent.admin.utils.ZookeeperConnectionWatcher@cc34f4d
kafka_1                                     | [main] INFO org.apache.zookeeper.common.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
kafka_1                                     | [main] INFO org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 4194304 Bytes
kafka_1                                     | [main] INFO org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=
kafka_1                                     | [main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper/172.26.0.4:2181. Will not attempt to authenticate using SASL (unknown error)
kafka_1                                     | [main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /172.26.0.5:58652, server: zookeeper/172.26.0.4:2181
kafka_1                                     | [main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Session establishment complete on server zookeeper/172.26.0.4:2181, sessionid = 0x10001ea29b70000, negotiated timeout = 40000
kafka_1                                     | [main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x10001ea29b70000 closed
kafka_1                                     | [main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x10001ea29b70000
kafka_1                                     | ===> Launching ...
kafka_1                                     | ===> Launching kafka ...
kafka_1                                     | [2021-05-13 21:10:57,680] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka_1                                     | [2021-05-13 21:10:58,235] WARN The package io.confluent.support.metrics.collectors.FullCollector for collecting the full set of support metrics could not be loaded, so we are reverting to anonymous, basic metric collection. If you are a Confluent customer, please refer to the Confluent Platform documentation, section Proactive Support, on how to activate full metrics collection. (io.confluent.support.metrics.KafkaSupportConfig)
kafka_1                                     | [2021-05-13 21:10:58,235] WARN The support metrics collection feature ("Metrics") of Proactive Support is disabled. (io.confluent.support.metrics.SupportedServerStartable)
kafka_1                                     | [2021-05-13 21:10:59,060] INFO Starting the log cleaner (kafka.log.LogCleaner)
kafka_1                                     | [2021-05-13 21:10:59,144] INFO [kafka-log-cleaner-thread-0]: Starting (kafka.log.LogCleaner)
kafka_1                                     | [2021-05-13 21:10:59,511] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.Acceptor)
kafka_1                                     | [2021-05-13 21:10:59,549] INFO [SocketServer brokerId=1001] Created data-plane acceptor and processors for endpoint : EndPoint(0.0.0.0,9092,ListenerName(PLAINTEXT),PLAINTEXT) (kafka.network.SocketServer)
kafka_1                                     | [2021-05-13 21:10:59,551] INFO [SocketServer brokerId=1001] Started 1 acceptor threads for data-plane (kafka.network.SocketServer)
kafka_1                                     | [2021-05-13 21:10:59,644] INFO Creating /brokers/ids/1001 (is it secure? false) (kafka.zk.KafkaZkClient)
kafka_1                                     | [2021-05-13 21:10:59,667] INFO Stat of the created znode at /brokers/ids/1001 is: 529,529,1620940259658,1620940259658,1,0,0,72059699271761921,180,0,529
kafka_1                                     |  (kafka.zk.KafkaZkClient)
kafka_1                                     | [2021-05-13 21:10:59,669] INFO Registered broker 1001 at path /brokers/ids/1001 with addresses: ArrayBuffer(EndPoint(kafka,9092,ListenerName(PLAINTEXT),PLAINTEXT)), czxid (broker epoch): 529 (kafka.zk.KafkaZkClient)
kafka_1                                     | [2021-05-13 21:10:59,996] INFO [/config/changes-event-process-thread]: Starting (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
kafka_1                                     | [2021-05-13 21:11:00,207] INFO [SocketServer brokerId=1001] Started data-plane processors for 1 acceptors (kafka.network.SocketServer)
kafka_1                                     | [2021-05-13 21:12:22,659] INFO [/config/changes-event-process-thread]: Shutting down (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
kafka_1                                     | [2021-05-13 21:12:22,660] INFO [/config/changes-event-process-thread]: Stopped (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
kafka_1                                     | [2021-05-13 21:12:22,661] INFO [/config/changes-event-process-thread]: Shutdown completed (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
kafka_1                                     | [2021-05-13 21:12:22,662] INFO [SocketServer brokerId=1001] Stopping socket server request processors (kafka.network.SocketServer)
kafka_1                                     | [2021-05-13 21:12:22,672] INFO [SocketServer brokerId=1001] Stopped socket server request processors (kafka.network.SocketServer)
kafka_1                                     | [2021-05-13 21:12:23,665] INFO Shutting down the log cleaner. (kafka.log.LogCleaner)
kafka_1                                     | [2021-05-13 21:12:23,666] INFO [kafka-log-cleaner-thread-0]: Shutting down (kafka.log.LogCleaner)
kafka_1                                     | [2021-05-13 21:12:23,666] INFO [kafka-log-cleaner-thread-0]: Stopped (kafka.log.LogCleaner)
kafka_1                                     | [2021-05-13 21:12:23,669] INFO [kafka-log-cleaner-thread-0]: Shutdown completed (kafka.log.LogCleaner)
kafka_1                                     | [2021-05-13 21:12:26,743] INFO [SocketServer brokerId=1001] Shutting down socket server (kafka.network.SocketServer)
kafka_1                                     | [2021-05-13 21:12:26,766] INFO [SocketServer brokerId=1001] Shutdown completed (kafka.network.SocketServer)
snuba-consumer_1                            | 2021-05-13 21:11:30,476 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 13}
snuba-api_1                                 | *** Starting uWSGI 2.0.18 (64bit) on [Thu May 13 21:11:26 2021] ***
snuba-api_1                                 | compiled with version: 8.3.0 on 13 May 2021 19:41:12
snuba-api_1                                 | os: Linux-5.4.0-1048-aws #50-Ubuntu SMP Mon May 3 21:44:17 UTC 2021
snuba-api_1                                 | nodename: ac969ec528c2
snuba-api_1                                 | machine: x86_64
snuba-api_1                                 | clock source: unix
snuba-api_1                                 | pcre jit disabled
snuba-api_1                                 | detected number of CPU cores: 2
snuba-api_1                                 | current working directory: /usr/src/snuba
snuba-api_1                                 | detected binary path: /usr/local/bin/uwsgi
snuba-api_1                                 | your memory page size is 4096 bytes
snuba-api_1                                 | detected max file descriptor number: 1048576
snuba-api_1                                 | lock engine: pthread robust mutexes
snuba-api_1                                 | thunder lock: enabled
snuba-api_1                                 | uwsgi socket 0 bound to TCP address 0.0.0.0:1218 fd 3
snuba-api_1                                 | Python version: 3.8.10 (default, May 12 2021, 15:56:47)  [GCC 8.3.0]
snuba-api_1                                 | Set PythonHome to /usr/local
snuba-api_1                                 | Python main interpreter initialized at 0x561aebf76c00
snuba-api_1                                 | python threads support enabled
snuba-api_1                                 | your server socket listen backlog is limited to 100 connections
snuba-api_1                                 | your mercy for graceful operations on workers is 60 seconds
snuba-api_1                                 | mapped 145808 bytes (142 KB) for 1 cores
snuba-api_1                                 | *** Operational MODE: single process ***
snuba-api_1                                 | initialized 38 metrics
snuba-api_1                                 | spawned uWSGI master process (pid: 1)
snuba-api_1                                 | spawned uWSGI worker 1 (pid: 15, cores: 1)
snuba-api_1                                 | metrics collector thread started
snuba-api_1                                 | WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x561aebf76c00 pid: 15 (default app)
snuba-outcomes-consumer_1                   | 2021-05-13 21:11:30,472 New partitions assigned: {Partition(topic=Topic(name='outcomes'), index=0): 13}
snuba-replacer_1                            | 2021-05-13 21:11:30,047 New partitions assigned: {Partition(topic=Topic(name='event-replacements'), index=0): 0}
snuba-subscription-consumer-events_1        | 2021-05-13 21:11:33,655 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 12}
snuba-subscription-consumer-transactions_1  | 2021-05-13 21:11:33,413 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 12}
snuba-transactions-consumer_1               | 2021-05-13 21:11:30,543 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 13}
snuba-sessions-consumer_1                   | 2021-05-13 21:11:30,473 New partitions assigned: {Partition(topic=Topic(name='ingest-sessions'), index=0): 170}
zookeeper_1                                 | ===> ENV Variables ...
zookeeper_1                                 | ALLOW_UNSIGNED=false
zookeeper_1                                 | COMPONENT=zookeeper
zookeeper_1                                 | CONFLUENT_DEB_VERSION=1
zookeeper_1                                 | CONFLUENT_PLATFORM_LABEL=
zookeeper_1                                 | CONFLUENT_SUPPORT_METRICS_ENABLE=false
zookeeper_1                                 | CONFLUENT_VERSION=5.5.0
zookeeper_1                                 | CUB_CLASSPATH=/etc/confluent/docker/docker-utils.jar
zookeeper_1                                 | HOME=/root
zookeeper_1                                 | HOSTNAME=0b83e56a4a0b
zookeeper_1                                 | KAFKA_OPTS=-Dzookeeper.4lw.commands.whitelist=ruok
zookeeper_1                                 | KAFKA_VERSION=
zookeeper_1                                 | LANG=C.UTF-8
zookeeper_1                                 | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
zookeeper_1                                 | PWD=/
zookeeper_1                                 | PYTHON_PIP_VERSION=8.1.2
zookeeper_1                                 | PYTHON_VERSION=2.7.9-1
zookeeper_1                                 | SCALA_VERSION=2.12
zookeeper_1                                 | SHLVL=1
zookeeper_1                                 | ZOOKEEPER_CLIENT_PORT=2181
zookeeper_1                                 | ZOOKEEPER_LOG4J_ROOT_LOGLEVEL=WARN
zookeeper_1                                 | ZOOKEEPER_TOOLS_LOG4J_LOGLEVEL=WARN
zookeeper_1                                 | ZULU_OPENJDK_VERSION=8=8.38.0.13
zookeeper_1                                 | _=/usr/bin/env
zookeeper_1                                 | ===> User
zookeeper_1                                 | uid=0(root) gid=0(root) groups=0(root)
zookeeper_1                                 | ===> Configuring ...
zookeeper_1                                 | ===> Running preflight checks ...
zookeeper_1                                 | ===> Check if /var/lib/zookeeper/data is writable ...
zookeeper_1                                 | ===> Check if /var/lib/zookeeper/log is writable ...
zookeeper_1                                 | ===> Launching ...
zookeeper_1                                 | ===> Launching zookeeper ...
zookeeper_1                                 | [2021-05-13 21:10:55,787] WARN Either no config or no quorum defined in config, running  in standalone mode (org.apache.zookeeper.server.quorum.QuorumPeerMain)
zookeeper_1                                 | [2021-05-13 21:10:56,109] WARN o.e.j.s.ServletContextHandler@4d95d2a2{/,null,UNAVAILABLE} contextPath ends with /* (org.eclipse.jetty.server.handler.ContextHandler)
zookeeper_1                                 | [2021-05-13 21:10:56,109] WARN Empty contextPath (org.eclipse.jetty.server.handler.ContextHandler)

I have tried copying config.example.yml to config.yml and updating mail settings but I run into the same problem every single time. The only time I can get sentry to work is when I do not create a config.yml and let docker create everything for me.

**Comment by BYK** [comment]
Please make sure your yaml file is a valid one using a service like https://yaml-online-parser.appspot.com/.

This is not something we can help with.
