### ISSUE TITLE
Very big postgresql database on sentry

### ISSUE THREAD

**Issue by nuget1991** [getsentry/onpremise#954]
### Version Information

Version: 21.3.0

### Steps to Reproduce

Our sentry is working good, but we configured performance monitoring 2 months ago. And during this time we have a very big postgresql database(centos, postgresql12-server-12.5-1PGDG.rhel7.x86_64) - 750Gb. Is it ok? I tried perform "sentry cleanup --days 30" in sentry worker container but no luck, I didn't clear database. Also I tried perform autocacuum full comand into db, but this process ate all memory and I canceled performing it. Have you got any ides why we have so big db and how can we purge old data from db. All sentry containers in stock but database has been installed separately.

### Expected Result

We need to reclaim disk space into db.

### Actual Result

Actually we have no disk space on server and notifications has been stopped.

### Logs

No strange logs has been found.

**Comment by nuget1991** [comment]
The largest table in sentry db is public.nodestore_node       | 729 GB.
How can we safely purge old data on it?

**Comment by max-wittig** [comment]
Same problem as here: https://github.com/getsentry/onpremise/issues/783

**Comment by chadwhitacre** [comment]
Thanks @max-wittig, closing this as a dupe.
