### ISSUE TITLE
stuck in noninteractive mode using aws ec2 and userdata script

### ISSUE THREAD

**Issue by pharindoko** [getsentry/onpremise#959]
### Version Information

Version: 21.5.1 

 Still geth the same issue  #946 using aws ec2 and starting install script in userdata

```

▶ Setting up Zookeeper ...
--no-ansi option is deprecated and will be removed in future versions. Use `--ansi never` instead.
Creating network "sentry_onpremise_default" with the default driver
Creating volume "sentry_onpremise_sentry-secrets" with default driver
Creating volume "sentry_onpremise_sentry-smtp" with default driver
Creating volume "sentry_onpremise_sentry-zookeeper-log" with default driver
Creating volume "sentry_onpremise_sentry-kafka-log" with default driver
Creating volume "sentry_onpremise_sentry-smtp-log" with default driver
Creating volume "sentry_onpremise_sentry-clickhouse-log" with default driver
Creating sentry_onpremise_zookeeper_run ...
Creating sentry_onpremise_zookeeper_run ... done
```

### Steps to Reproduce

1. create an amazon ec2 with linux
2. add step to install to user_data script
3. check logs in cloud-init-output.log

### Expected Result

zookeeper does not hang in this step

### Actual Result

zookeeper hangs

**Comment by BYK** [comment]
Please provide more information (more logs, maybe permissions, etc) as in its current state, this issue is not actionable.

**Comment by pharindoko** [comment]
hmm okay first of all I made a test:
my assumption was that this was working with 20.12.1 but this seems not to be the case:


so to describe my problem:
this script will be executed as root when the ec2 / autoscaling start up happens:



#!/bin/bash
yum update -y
yum install ruby wget git jq -y
# Install amazon-efs-utils
yum install -y amazon-efs-utils
echo "password-path: ${admin_pw}"
# Create /efs folder
mkdir -p /data
efs_dns="${efs_dns}"
mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport $efs_dns:/ data

# Edit fstab so EFS automatically loads on reboot
echo $efs_dns:/ /data efs defaults,_netdev 0 0 >> /etc/fstab
df -kh
cd data
mkdir -p sentry-clickhouse
mkdir -p sentry-data

# Docker
amazon-linux-extras install docker -y
echo '{
  "log-driver": "awslogs",
  "log-opts": {
    "awslogs-region": "eu-central-1",
    "awslogs-group" : "${cloudwatch_log}",
    "tag": "{{.Name}}"
  }
}' >> /etc/docker/daemon.json

service docker start
usermod -a -G docker ec2-user
chkconfig docker on
# docker-compose
curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose
chmod +x /usr/bin/docker-compose


# create docker-volumes attached to efs

docker volume create \
    --driver local \
    --opt type=nfs \
    --opt o=addr=${efs_dns},rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 \
    --opt device=:/sentry-clickhouse sentry-clickhouse
docker volume create \
    --driver local \
    --opt type=nfs \
    --opt o=addr=${efs_dns},rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 \
    --opt device=:/sentry-data sentry-data

# Configure the sentry server
git clone --depth=1 --branch ${sentry_version} https://github.com/getsentry/onpremise /home/ec2-user/onpremise
cd /home/ec2-user/onpremise


# Configure the onpremise sentry
mv sentry/config.example.yml sentry/config.yml
echo "system.url-prefix: 'https://${url_prefix}'" >> sentry/config.yml
echo "system.admin-email: '${admin_user}'" >> sentry/config.yml
secret=$(aws ssm get-parameter --name "${secret_name}" --with-decryption --region eu-central-1 | jq -r .Parameter.Value)
echo "system.secret-key: '$secret'" >> sentry/config.yml


# config smtp
sed -i "s+mail.host: 'smtp'+mail.host: 'email-smtp.eu-west-1.amazonaws.com'+g" sentry/config.yml
echo "mail.port: 587" >> sentry/config.yml
smtp_password=$(aws ssm get-parameter --name "${smtp_password}" --with-decryption --region eu-central-1 | jq -r .Parameter.Value)
echo "mail.username: \"${smtp_user}\"" >> sentry/config.yml
echo "mail.password: \"$smtp_password\"" >> sentry/config.yml
echo "mail.from: 'sentry@mail.apps.vitesco.io'" >> sentry/config.yml
echo "mail.use-ssl: false" >> sentry/config.yml
echo "mail.use-tls: true" >> sentry/config.yml
echo "mail.list-namespace: \"${mail_domain}\"" >> sentry/config.yml
echo "mail.backend: \"smtp\"" >> sentry/config.yml

mv sentry/sentry.conf.example.py sentry/sentry.conf.py
db_passwd=$(aws ssm get-parameter --name "${db_passwd_name}" --with-decryption --region eu-central-1 | jq -r .Parameter.Value)
sed -i "s+\"PASSWORD\": \"\"+\"PASSWORD\": \"$db_passwd\"+g" sentry/sentry.conf.py
sed -i 's+"HOST": "postgres"+"HOST": "${db_endpoint}"+g' sentry/sentry.conf.py
sed -i 's+"PORT": ""+"PORT": "5432"+g' sentry/sentry.conf.py
sed -i '/GEOIP_PATH_MMDB/d' sentry/sentry.conf.py

sudo chown -R ec2-user .

# Install the sentry
su ec2-user -c './install.sh --no-user-prompt &'
passwd=$(aws ssm get-parameter --name ${admin_pw} --with-decryption --region eu-central-1 | jq -r .Parameter.Value)

docker-compose run web createuser --email=${admin_user} --password=$passwd --superuser
docker-compose up -d
RELAY_CONFIG_YML='relay/config.yml'
RELAY_CREDENTIALS_JSON='relay/credentials.json'
sed -i '/geoip_path:/d' $RELAY_CONFIG_YML
docker-compose run --no-deps -v $(pwd)/$RELAY_CONFIG_YML:/tmp/config.yml relay --config /tmp credentials generate --stdout > "$RELAY_CREDENTIALS_JSON"


This was working, now it seems not to work anymore. Have to find out why...but this seems to be tricky ...

**It all works when I execute the install.sh script manually as ec2-user**

**Comment by BYK** [comment]
Pretty sure this is a permissions issue and you need `sudo chown -R ec2-user .` on the whole `on-premise` folder.

**Comment by pharindoko** [comment]
hmm no I tried this but it`s not the point - in the end I have the same issue as in #946  described:

using bash with +x options I get following output:

```bash
+ echo 'Docker images built.'
Docker images built.
+ [[ -n '' ]]
+ docker-compose --no-ansi -p onpremise down -t 60 --rmi local --remove-orphans
--no-ansi option is deprecated and will be removed in future versions. Use `--ansi never` instead.
Removing network onpremise_default
Network onpremise_default not found.
+ docker-compose --no-ansi down -t 60 --rmi local --remove-orphans
--no-ansi option is deprecated and will be removed in future versions. Use `--ansi never` instead.
Removing network sentry_onpremise_default
++ docker-compose --no-ansi run --rm zookeeper bash -c 'ls 2>/dev/null -Ubad1 -- /var/lib/zookeeper/data/version-2 | wc -l | tr -d [:space:]'
--no-ansi option is deprecated and will be removed in future versions. Use `--ansi never` instead.
Creating network "sentry_onpremise_default" with the default driver
Creating volume "sentry_onpremise_sentry-secrets" with default driver
Creating volume "sentry_onpremise_sentry-smtp" with default driver
Creating volume "sentry_onpremise_sentry-zookeeper-log" with default driver
Creating volume "sentry_onpremise_sentry-kafka-log" with default driver
Creating volume "sentry_onpremise_sentry-smtp-log" with default driver
Creating volume "sentry_onpremise_sentry-clickhouse-log" with default driver
Creating sentry_onpremise_zookeeper_run ...
Creating sentry_onpremise_zookeeper_run ... done
```

**ps fax output:**

```
 3000 ?        Ssl    0:01 /usr/bin/containerd
 3051 ?        Ssl    0:55 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --default-ulimit nofile=1024:4096
 3373 ?        S      0:00 bash -x install.sh --no-user-prompt
 3383 ?        S      0:00  \_ bash -x install.sh --no-user-prompt
 3385 ?        S      0:00  |   \_ tee -a sentry_install_log-2021-05-24_22-15-22.txt
 6931 ?        S      0:00  \_ docker-compose --no-ansi run --rm zookeeper bash -c ls 2>/dev/null -Ubad1 -- /var/lib/zookeeper/data/version-2 | wc -l | tr -d
 6932 ?        S      0:00      \_ docker-compose --no-ansi run --rm zookeeper bash -c ls 2>/dev/null -Ubad1 -- /var/lib/zookeeper/data/version-2 | wc -l | t
 6978 ?        Sl     0:00          \_ /usr/bin/docker start --attach --interactive 6e5c71624eb907e0262ac6dcb548b6d253297cc7aeaeff5a16322d21fb93f61a
```

**Comment by BYK** [comment]
@pharindoko can you try the associated PR? I think that should fix the issue.

**Comment by pharindoko** [comment]
@BYK  thanks, will try it out...

**Comment by BYK** [comment]
@pharindoko will hold on from merging until I get news from you that this actually fixes the issue. Thanks a lot for reporting this and trying the solution out!

**Comment by BYK** [comment]
@pharindoko is it possible for you to get some more error logs, maybe historical logs from docker and the zookeeper container as without reproduction locally, it is very hard for us to find a solution?

**Comment by pharindoko** [comment]
@BYK That's fine. Thanks for your support. I understand that this is a kinda strange case. It's hard to debug. I will continue to figure out the root cause. If you have any proposals let me know. Will continue today in the evening ...

Br, 

pharindoko

**Comment by BYK** [comment]
@pharindoko last time it was a `cwd` issue and we couldn't mount the folder we should be mounting. I suspect something similar, that's why I asked about ownership and permissions.

Actually, just to try it out, can you set the permissions on the ZK directory to `555` at least to see what happens?

**Comment by pharindoko** [comment]
created a fork from the last release 21.5.1 and remove ```source set-up-zookeeper.sh``` from install.sh

ok this time it got stuck when trying to start snuba api and start --attach to it.
```
bash -x install.sh --no-user-prompt
 3377 ?        S      0:00  \_ bash -x install.sh --no-user-prompt
 3379 ?        S      0:00  |   \_ tee -a sentry_install_log-2021-05-25_21-52-16.txt
 7300 ?        S      0:00  \_ docker-compose --no-ansi run --rm snuba-api bootstrap --no-migrate --force
 7304 ?        S      0:00      \_ docker-compose --no-ansi run --rm snuba-api bootstrap --no-migrate --force
 7860 ?        Sl     0:00          \_ /usr/bin/docker start --attach --interactive 4ca8682c98509bb02dd1585c79ed422aad991aea35eb805e2eac83b3823151bb
```

**Comment by BYK** [comment]
I noticed that you are running `mv` instead of `cp` to create some config files. The script assumes the example files to exists so maybe try using `cp` instead of `mv` there and see if it helps?

Sorry, I'm clueless at this point.

**Comment by pharindoko** [comment]
I will change this ...
Additionally I tried out to take a larger instance type (t3.xlarge) and set storage to 50 GB to ensure there is no resource blocking. Same issue.

**Comment by pharindoko** [comment]
Hmm I gave up on this now. Did all the steps before install.sh and the rest manually. If anyone has an idea why docker hangs up in this moment it tries to start zookeeper/snuba please let me know.

**Comment by BYK** [comment]
Sorry to hear that @pharindoko 😦 If you ever get down to the root cause, please share it with us so we can fix it for everyone!
