### ISSUE TITLE
Events not being created for issues(but new issues are)

### ISSUE THREAD

**Issue by cjesper** [getsentry/onpremise#963]
Version: 20.11

Hello,
Events are not being (properly) created in my installation of Sentry. Everything else - creating users, projects, issues - works perfectly, but navigating to an issue returns "Sorry, the events for this issue could not be found."
However, strangely i am able to see the correct event count at the top right in the issue ("Events: N" where N is the number of events i've created). I have tried this in multiple environments/projects but the issue remains the same.

Image of the UI in an issue, including the correct event counter to the right but no events displayed:
![image](https://user-images.githubusercontent.com/15783742/119484986-da2ab080-bd56-11eb-8734-730264415ddd.png)

### What i have tried ###

1. Restarting the containers and docker service multiple times
2. Followed the steps described [here](https://github.com/getsentry/onpremise/issues/478#issuecomment-666254392) for debugging problems with Kafka/post_process_forwarder. No dice.
3.  Verified that it wasn't an issue with Clickhouse not using UTC as timezone. Also, getting all events (ie. sending a request to issues/<id>/events rather than issues/14/events/latest/ returns [], indicating that there are no events created)

### Logs

Latest install logs: https://pastebin.com/dZjnPVqQ

Here are the log entries for when i post a new event (tailing all docker logs):
`root@computer:~# docker ps -q | xargs -L 1 -P `docker ps | wc -l` docker logs --since 30s -f
10.10.1.1 - - [25/May/2021:09:53:14 +0000] "POST /api/2/store/ HTTP/1.0" 200 41 "-" "-" "172.20.37.202"
09:53:15 [INFO] batching-kafka-consumer: Flushing 1 items (from {('ingest-events', 0): [249, 249]}): forced:False size:False time:True
09:53:15 [INFO] batching-kafka-consumer: Worker flush took 7ms
2021-05-25 09:53:16,705 Completed processing <Batch: 1 message, open for 1.00 seconds>.
2021.05.25 09:53:16.711404 [ 89 ] {834ec15e-a990-4354-ade7-ccdac7eff938} <Information> executeQuery: Read 1 rows, 71.00 B in 0.004 sec., 229 rows/sec., 15.90 KiB/sec.
2021.05.25 09:53:16.712436 [ 89 ] {} <Information> HTTPHandler: Done processing query
2021-05-25 09:53:16,720 Completed processing <Batch: 1 message, open for 1.02 seconds>.
2021.05.25 09:53:16.721747 [ 90 ] {2c17eaf1-e5c0-49df-ac4e-3fb8a4964135} <Information> executeQuery: Read 1 rows, 1.03 KiB in 0.016 sec., 62 rows/sec., 64.67 KiB/sec.
2021.05.25 09:53:16.722513 [ 90 ] {} <Information> HTTPHandler: Done processing query
2021-05-25 09:53:16,724 Completed processing <Batch: 1 message, open for 1.02 seconds>.
2021-05-25 09:53:20,662 Flushing 1 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=235, hi=236)})
2021-05-25 09:53:20,662 Worker flush took 0ms
2021-05-25 09:53:20,677 Flushing 1 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=235, hi=236)})
2021-05-25 09:53:20,677 Worker flush took 0ms`

As can be seen, there are no errors/warnings. 

When GET-ing the events for an issue the following is logged:
`09:54:00 [WARNING] django.request: Not Found: /api/0/issues/32/events/latest/ (status_code=404 request=<WSGIRequest: GET '/api/0/issues/32/events/latest/'>)
172.21.24.2 - - [25/May/2021:09:54:00 +0000] "GET /api/0/issues/32/events/latest/ HTTP/1.1" 404 38 "http://sentry.recfut.com:9000/organizations/sentry/issues/32/?project=2&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" "-"`

**Comment by BYK** [comment]
What is your event retention period? How/when did this issue start to manifest itself?

**Comment by cjesper** [comment]
Hi, i haven't changed the retention period from the default of 90 days.
This issue "manifested" as soon as started to send issues/events to Sentry ie. event creation has never worked.

**Comment by mcolladoio** [comment]
For me was the same problem. I fixed applying the #478 solution but including the rest of groups:

First listing the groups:
`kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --list`

Then applying the next command to the groups: 
`kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --group <group_name> --topic events --reset-offsets --to-latest --execute`

And now everything is working fine.

**Comment by cjesper** [comment]
> > This issue "manifested" as soon as started to send issues/events to Sentry ie. event creation has never worked.
> 
> That sounds bizarre. Are you using this repo as it is or do you have modifications? Also are you able to upgrade to a more recent version?

The only changes i make are

- Adding the Google SSO key(in sentry.config.yml)
- I also change the address range for the docker service because the default ones conflict with the VPN i use.

I can try upgrading to a more recent version.

**Comment by cjesper** [comment]
> For me was the same problem. I fixed applying the #478 solution but including the rest of groups:
> 
> First listing the groups:
> `kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --list`
> 
> Then applying the next command to the groups:
> `kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --group <group_name> --topic events --reset-offsets --to-latest --execute`
> 
> And now everything is working fine.



I tried doing this, but it didn't help unfortunately. I can create new (unique) issues but no events are created. 
I also did a full wipe (delete all images, containers, volumes, re-create Sentry installation)
So if i do this:
`root@is-1878b:/var/lib/docker# sentry-cli send-event -m "Testing my new event"
710280a9-a190-4cc1-b61c-b9fd4aa878b9
root@is-1878b:/var/lib/docker# sentry-cli send-event -m "Testing my new event"
97dda6b3-cde8-4f1f-834f-a33987a88d5b`

I would expect one issue to be created with 2 events. But what i get is:
![image](https://user-images.githubusercontent.com/15783742/119513099-34863a00-bd74-11eb-91bf-e7800d970560.png)

**Comment by BYK** [comment]
Can you share all your container logs?

**Comment by cjesper** [comment]
Here they are:

./sentry_clickhouse_1.log
http://sprunge.us/b2hQKU
./sentry_cron_1.log
http://sprunge.us/AirJdS
./sentry_ingest-consumer_1.log
http://sprunge.us/WitIdq
./sentry_kafka_1.log
http://sprunge.us/vL7Ihw
./sentry_memcached_1.log
http://sprunge.us/Jzrz8j
./sentry_nginx_1.log
http://sprunge.us/lJ0HRT
./sentry_postgres_1.log
http://sprunge.us/ZoJ8Gt
./sentry_post-process-forwarder_1.log
http://sprunge.us/Dyconc
./sentry_redis_1.log
http://sprunge.us/tqu4XG
./sentry_relay_1.log
http://sprunge.us/s7jWYq
./sentry_sentry-cleanup_1.log
http://sprunge.us/jR9Rh0
./sentry_smtp_1.log
http://sprunge.us/xF4KVq
./sentry_snuba-api_1.log
http://sprunge.us/DFkbpM
./sentry_snuba-cleanup_1.log
http://sprunge.us/GH9ifn
./sentry_snuba-consumer_1.log
http://sprunge.us/xYsuRf
./sentry_snuba-outcomes-consumer_1.log
http://sprunge.us/KjvEJU
./sentry_snuba-replacer_1.log
http://sprunge.us/VTzLFt
./sentry_snuba-sessions-consumer_1.log
http://sprunge.us/nCywxM
./sentry_snuba-subscription-consumer-events_1.log
http://sprunge.us/vMQVgu
./sentry_snuba-subscription-consumer-transactions_1.log
http://sprunge.us/bctH8D
./sentry_snuba-transactions-consumer_1.log
http://sprunge.us/acocvd
./sentry_subscription-consumer-events_1.log
http://sprunge.us/uezv3F
./sentry_subscription-consumer-transactions_1.log
http://sprunge.us/hrX3gX
./sentry_symbolicator_1.log
http://sprunge.us/e3tpcZ
./sentry_symbolicator-cleanup_1.log
http://sprunge.us/5fxZDO
./sentry_web_1.log
http://sprunge.us/fc2YeI
./sentry_worker_1.log
http://sprunge.us/L2F4Qp
./sentry_zookeeper_1.log
http://sprunge.us/Pq4mYz

**Comment by BYK** [comment]
Okay, based on your `relay` logs, it looks like the same issue with getsentry/relay#997 which should be resolved (temporarily) if you just restart relay but keep other services up: `docker-compose restart relay`.

Can you try that?

**Comment by cjesper** [comment]
Hi again, i appreciate all of your help with this issue

docker-compose restart doesn't work:
`root@/var/lib/docker/sentry/onpremise-master# docker-compose restart sentry_relay_1
ERROR: No such service: sentry_relay_1
root@/var/lib/docker/sentry/onpremise-master# docker-compose top
root@/var/lib/docker/sentry/onpremise-master#`
In fact, there doesn't seem to be any docker-compose containers running:
`root@/var/lib/docker/sentry/onpremise-master# docker-compose top
root@/var/lib/docker/sentry/onpremise-master# <no output>`

But according to docker ps:
`root@is-1878b:/var/lib/docker/sentry/onpremise-master# docker ps
CONTAINER ID   IMAGE                                  COMMAND                  CREATED        STATUS              PORTS                          NAMES
64a2d1080073   nginx:1.16                             "nginx -g 'daemon of…"   17 hours ago   Up 3 minutes        0.0.0.0:9000->80/tcp           sentry_nginx_1
8a24d69fb04c   sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   17 hours ago   Up 3 minutes        9000/tcp                       sentry_ingest-consumer_1
7a14e31dd69d   sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   17 hours ago   Up About a minute   9000/tcp                       sentry_subscription-consumer-events_1
ca757594de97   sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   17 hours ago   Up 3 minutes        9000/tcp                       sentry_worker_1
1d883b6a0e80   sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   17 hours ago   Up 3 minutes        9000/tcp                       sentry_web_1
16de4772ff94   sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   17 hours ago   Up About a minute   9000/tcp                       sentry_subscription-consumer-transactions_1
53107e69092c   sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   17 hours ago   Up 3 minutes        9000/tcp                       sentry_post-process-forwarder_1
c1760a90203f   sentry-cleanup-onpremise-local         "/entrypoint.sh '0 0…"   17 hours ago   Up 3 minutes        9000/tcp                       sentry_sentry-cleanup_1
948f700023c1   sentry-onpremise-local                 "/bin/sh -c 'exec /d…"   17 hours ago   Up 3 minutes        9000/tcp                       sentry_cron_1
6cd661963f22   getsentry/snuba:nightly                "./docker_entrypoint…"   17 hours ago   Up 2 minutes        1218/tcp                       sentry_snuba-consumer_1
bad179671b60   getsentry/snuba:nightly                "./docker_entrypoint…"   17 hours ago   Up 3 minutes        1218/tcp                       sentry_snuba-sessions-consumer_1
237e8b5cdeb9   getsentry/snuba:nightly                "./docker_entrypoint…"   17 hours ago   Up 3 minutes        1218/tcp                       sentry_snuba-subscription-consumer-transactions_1
9284f98cc769   getsentry/snuba:nightly                "./docker_entrypoint…"   17 hours ago   Up 3 minutes        1218/tcp                       sentry_snuba-api_1
e7b42ec18e6e   getsentry/snuba:nightly                "./docker_entrypoint…"   17 hours ago   Up 3 minutes        1218/tcp                       sentry_snuba-replacer_1
dd03b8e5e1ab   getsentry/snuba:nightly                "./docker_entrypoint…"   17 hours ago   Up 3 minutes        1218/tcp                       sentry_snuba-transactions-consumer_1
ab1093411423   snuba-cleanup-onpremise-local          "/entrypoint.sh '*/5…"   17 hours ago   Up 3 minutes        1218/tcp                       sentry_snuba-cleanup_1
f0795fedff6e   getsentry/snuba:nightly                "./docker_entrypoint…"   17 hours ago   Up 3 minutes        1218/tcp                       sentry_snuba-outcomes-consumer_1
be497a0ae95e   getsentry/snuba:nightly                "./docker_entrypoint…"   17 hours ago   Up 3 minutes        1218/tcp                       sentry_snuba-subscription-consumer-events_1
04e65909a2bd   getsentry/relay:nightly                "/bin/bash /docker-e…"   17 hours ago   Up 3 minutes        3000/tcp                       sentry_relay_1
057b8734dca4   confluentinc/cp-kafka:5.5.0            "/etc/confluent/dock…"   17 hours ago   Up About a minute   9092/tcp                       sentry_kafka_1
5fac848f6b72   yandex/clickhouse-server:20.3.9.70     "/entrypoint.sh"         17 hours ago   Up 3 minutes        8123/tcp, 9000/tcp, 9009/tcp   sentry_clickhouse_1
15a569f9ef66   memcached:1.5-alpine                   "docker-entrypoint.s…"   17 hours ago   Up 3 minutes        11211/tcp                      sentry_memcached_1
d207df02b9e6   tianon/exim4                           "docker-entrypoint.s…"   17 hours ago   Up 3 minutes        25/tcp                         sentry_smtp_1
90ca3b961205   redis:5.0-alpine                       "docker-entrypoint.s…"   17 hours ago   Up 3 minutes        6379/tcp                       sentry_redis_1
f2a96f1390e2   symbolicator-cleanup-onpremise-local   "/entrypoint.sh '55 …"   17 hours ago   Up 3 minutes        3021/tcp                       sentry_symbolicator-cleanup_1
c9157c9f6c79   getsentry/symbolicator:nightly         "/bin/bash /docker-e…"   17 hours ago   Up 3 minutes        3021/tcp                       sentry_symbolicator_1
8c0fe45a21ad   postgres:9.6                           "docker-entrypoint.s…"   17 hours ago   Up 3 minutes        5432/tcp                       sentry_postgres_1
62a721b2aab3   confluentinc/cp-zookeeper:5.5.0        "/etc/confluent/dock…"   17 hours ago   Up 3 minutes        2181/tcp, 2888/tcp, 3888/tcp   sentry_zookeeper_1`

Not really related to your suggestion but i found this interesting/strange. Anyway - docker restart sentry_relay_1 (even multiple attempts) do not solve the issue. Same with restarting the docker service as per the issue you linked. The output in the relay log is always the same:
`2021-05-26T07:05:06Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: error sending request for url (http://web:9000/api/0/relays/register/challenge/): error trying to connect: tcp connect error: Connection refused (os error 111)
2021-05-26T07:05:08Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: error sending request for url (http://web:9000/api/0/relays/register/challenge/): error trying to connect: tcp connect error: Connection refused (os error 111)
2021-05-26T07:05:12Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 0ns
2021-05-26T07:05:12Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: error sending request for url (http://web:9000/api/0/relays/register/challenge/): error trying to connect: tcp connect error: Connection refused (os error 111)
2021-05-26T07:05:12Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 1s
2021-05-26T07:05:13Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 1.5s
2021-05-26T07:05:14Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 2.25s
2021-05-26T07:05:16Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 3.375s
2021-05-26T07:05:17Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: error sending request for url (http://web:9000/api/0/relays/register/challenge/): error trying to connect: tcp connect error: Connection refused (os error 111)
2021-05-26T07:05:20Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 5.0625s
2021-05-26T07:05:24Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: error sending request for url (http://web:9000/api/0/relays/register/challenge/): error trying to connect: tcp connect error: Connection refused (os error 111)
2021-05-26T07:05:25Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 7.59375s
2021-05-26T07:05:32Z [rdkafka::client] ERROR: librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#10.10.9.13:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)
2021-05-26T07:05:32Z [rdkafka::client] ERROR: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Connect to ipv4#10.10.9.13:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)
2021-05-26T07:05:35Z [rdkafka::client] ERROR: librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#10.10.9.13:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)
2021-05-26T07:05:35Z [rdkafka::client] ERROR: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Connect to ipv4#10.10.9.13:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)


2021-05-26T07:06:02Z [rdkafka::client] ERROR: librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#10.10.9.13:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)
2021-05-26T07:06:02Z [rdkafka::client] ERROR: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Connect to ipv4#10.10.9.13:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)
2021-05-26T07:06:05Z [rdkafka::client] ERROR: librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#10.10.9.13:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)
2021-05-26T07:06:05Z [rdkafka::client] ERROR: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Connect to ipv4#10.10.9.13:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)`


Maybe this can be related to the fact that i've changed the default address range for Docker? For clarity, this is what my docker/daemon.json file looks like:
`root@is-1878b:~# cat /etc/docker/daemon.json
{
 "default-address-pools":
   [
     {"base":"10.10.0.0/16","size":24}
   ]
 }`

**Comment by cjesper** [comment]
> Okay, based on your `relay` logs, it looks like the same issue with [getsentry/relay#997](https://github.com/getsentry/relay/issues/997) which should be resolved (temporarily) if you just restart relay but keep other services up: `docker-compose restart relay`.
> 
> Can you try that?

I also tried adding 'web' as a dependency for relay based on your suggestion in that issue:
` relay:
    << : *restart_policy
    image: '$RELAY_IMAGE'
    volumes:
      - type: bind
        read_only: true
        source: ./relay
        target: /work/.relay
      - type: bind
        read_only: true
        source: ./geoip
        target: /geoip
    depends_on:
      - kafka
      - redis
      - web`
Unfortunately same problem, even after multiple restarts.

**Comment by cjesper** [comment]
UPDATE: Everything is working now!

I did a full wipe of everything, re-downloaded the latest version of this repo and used the latest version of Sentry (21.6.0.dev0), and it worked on the first try

**Comment by BYK** [comment]
Closing then as I'm guessing this was a local issue with your setup. Thanks a lot for sticking with us and sharing all the steps you've taken to debug and solve the issue! 🚀
