### ISSUE TITLE
Relay is unable to send events because of CSRF cookie not set

### ISSUE THREAD

**Issue by ofzhur** [getsentry/onpremise#970]
### Version Information

Version: 21.5.1

### Steps to Reproduce

1. Run web/relay on premise with nginx
2. Register relay on web
3. Try to send event over relay

### Expected Result

Event sent to web.

### Actual Result

Relay gets 403 error from web

### Logs

Relay:
2021-05-28T08:14:44Z [relay_server::actors::envelopes] TRACE: queueing envelope
2021-05-28T08:14:44Z [relay_server::actors::envelopes] TRACE: processing json transaction
2021-05-28T08:14:44Z [relay_server::actors::envelopes] TRACE: sending envelope to sentry endpoint
2021-05-28T08:14:44Z [relay_server::actors::envelopes] DEBUG: dropped envelope: could not send request to upstream
  caused by: upstream request returned error 403 Forbidden
  caused by: no error details

Web:
08:15:44 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /api/1/envelope/ (status_code=403 request=<WSGIRequest: POST '/api/1/envelope/'>)
127.0.0.1 - - [28/May/2021:08:15:44 +0000] "POST /api/1/envelope/ HTTP/1.1" 403 6425 "-" "sentry.python/1.1.0"

**Comment by BYK** [comment]
This doesn't seem right, Relay should never contact this endpoint as it does not exist on Sentry Web. The user agent for the request is `"sentry.python/1.1.0"` so looks like your setup bypasses Relay and makes the SDK talk to Sentry Web directly instead.

**Comment by BYK** [comment]
Is there a reason why you are not using the configuration from this repo?

**Comment by ofzhur** [comment]
I did have my setup on kubernetes with version 9.1.2 and now trying to make it running similar way with a latest release. btw I can't see any difference on changing relay config, I tried exact config from repo - same issue.

**Comment by ofzhur** [comment]
Okay, just realized that statement about wrong relay config is true: kafka must be present and there is no way to workaround this. (which is logically makes sense).
