### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by bbhu-y** [getsentry/onpremise#971]
Hi,

I m using Sentry for React projects.

### Version Information

Version: *21.4.0*

### Steps to Reproduce

The cause is a CORS issue:

Access to fetch at 'https://36.133.251.125:9000/api/3/store/?sentry_key=d9506f20aa7d425fa6cd79e1929d5282&sentry_version=7' from origin 'https://dev-edt.***.com:9700' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

![image](https://user-images.githubusercontent.com/38289190/120347995-5745bf00-c32f-11eb-9208-019b2475277f.png)

![image](https://user-images.githubusercontent.com/38289190/120348024-5d3ba000-c32f-11eb-8c73-44a75e38d933.png)

Any one has same problem ? how to solved it...

**Comment by BYK** [comment]
Have you [set your `system.url-prefix`](https://develop.sentry.dev/self-hosted/#configuration)? Not sure if CORS works well with IP-based origins btw.

**Comment by bbhu-y** [comment]
> 你[设置了`system.url-prefix`](https://develop.sentry.dev/self-hosted/#configuration)吗？不确定 CORS 是否适用于基于 IP 的起源顺便说一句。
like this?
![image](https://user-images.githubusercontent.com/38289190/120147860-ed87c100-c219-11eb-975c-f06d249d6824.png)
but it still doesn't work

**Comment by bbhu-y** [comment]
@BYK

**Comment by bbhu-y** [comment]
@BYK

**Comment by bbhu-y** [comment]
@BYK 
like this?

![image](https://user-images.githubusercontent.com/38289190/120148053-36d81080-c21a-11eb-8dfb-7a77c0bdcf68.png)


But it still doesn't work

**Comment by bbhu-y** [comment]
@BYK 
but Sentry is used normally on another project that does not use https

**Comment by BYK** [comment]
Interesting. @jan-auer do you know anything about this as the response seems to be coming from Relay?

**Comment by bbhu-y** [comment]
I found my issue and solved it.   It's really because of relay. Thanks.

**Comment by untitaker** [comment]
@bbhu-y could you elaborate what the issue was?

there is also the "Allowed origins" setting in the UI that may influence which header values we emit

**Comment by windole** [comment]
@bbhu-y Can you tell me how you solved it?Thanks.

**Comment by bbhu-y** [comment]
> @bbhu-y Can you tell me how you solved it?Thanks.

I changed the nginx  configuration, 

before:

![image](https://user-images.githubusercontent.com/38289190/124594090-f6f7ef00-de91-11eb-9f72-385429919147.png)


after:

![image](https://user-images.githubusercontent.com/38289190/124594110-fd866680-de91-11eb-987e-639ac31bbc44.png)

And then it works

**Comment by Java-http** [comment]
> @bbhu-y Can you tell me how you solved it?Thanks.
Hello, I also encountered this problem, how did you solve it，Thanks.
