### ISSUE TITLE
Slack integration: "Redirect URI did not match any configured URIs"

### ISSUE THREAD

**Issue by cjesper** [getsentry/onpremise#982]
### Version Information

Version: 21.5.1

### Steps to Reproduce

Sentry version: 21.5.1

Hi,
I am trying to setup a Slack integration for my onpremise Sentry. I have created an app in Slack and added the required client_id/secret in config.yml.
However, when i go to the Slack integration in the UI and click "Add workspace" i am met with

`
redirect_uri did not match any configured URIs. Passed URI: http://sentry.mysite.com/extensions/slack/setup/`
(mysite.com is the DNS pointing to the VPS running my Sentry)

I did some digging and found that this can happen if system.internal-url-prefix is misconfigured. I had the default value set (http://web:9000), so i changed it to http://sentry.mysite.com. I then re-installed Sentry (with the install script), and restarted the docker containers. This did not help unfortunately - the exact same error appears.

### Expected Result

I would successfully add the Slack integration to Sentry.

### Actual Result

`
redirect_uri did not match any configured URIs. Passed URI: http://sentry.mysite.com/extensions/slack/setup/`

### Logs

Logs from docker_web container when clicking "Add workspace":
`12:33:56 [INFO] sentry.superuser: superuser.request (url='http://sentry.mysite.com/organizations/sentry/integrations/slack/setup/' method='GET' ip_address='<redacted>' user_id=1)`

Also maybe worth noting - if i inspect the network while clicking "Add workspace" it doesn't actually send any request anywhere.

**Comment by BYK** [comment]
>I did some digging and found that this can happen if system.internal-url-prefix is misconfigured.

It is the `system.url-prefix` setting not `system.internal-url-prefix` 🙂

>I had the default value set (http://web:9000), so i changed it to http://sentry.mysite.com.

You need to revert this value back to its original or a bunch of internal services will fail.


>I then re-installed Sentry (with the install script), and restarted the docker containers. This did not help unfortunately - the exact same error appears.

You do not need to re-install, just restart: `docker-compose restart`

Can you try the above and see if it helps?

**Comment by cjesper** [comment]
Hi again,
I see - i've reverted the internal-url.

Unfortunately setting system.url-prefix in config.yml to http://sentry.mysite.com didn't help. I also tried specifying the port (http://sentry.mysite.com:9000), and that causes the error message to change to 
`redirect_uri did not match any configured URIs. Passed URI: http://sentry.recfut.com:9000/extensions/slack/setup/`

I also tried removing http://, but then i get an "Internal System Error" when clicking Add Workspace.

**Comment by BYK** [comment]
>redirect_uri did not match any configured URIs

You need to check your Slack APP configuration for this. Looks like setting it to `http://sentry.mysite.com:9000` will fix your issue on the Sentry end.

Closing as this is not something we can fix here, you need to update your Slack configuration.

Pretty sure it won't accept `http` URLs btw so you may want to set up a load balancer in front that does SSL termination: https://develop.sentry.dev/self-hosted/#productionalizing
