### ISSUE TITLE
Update the README.md with more specific updating steps

### ISSUE THREAD

**Issue by hbokh** [getsentry/onpremise#983]
### Summary

The current `README.md` is having a different update strategy than suggested in multiple forum posts.
@BYK has answered multiple questions in the Sentry forum that contradicts this specific part in `README.md`:

 **Updating Sentry**:
...
_We recommend (and sometimes require) you to upgrade Sentry one version at a time. That means if you are running 20.6.0, instead of going directly to 20.8.0, first go through 20.7.0. Skipping versions would work most of the time, but there will be times that we require you to stop at specific versions to ensure essential data migrations along the way._

FYI: I ran an upgrade from Sentry 9.0.0 to 9.1.2 --> 20.12.1 --> 21.5.1.
But it looks like I could have skipped the 20.12.1 in the steps.

### Motivation

It is unclear from the `README.md` in this repo that a Sentry on premise upgrade can be done from 9.1.2 [directly to 21.5.1](https://forum.sentry.io/t/best-way-to-upgrade-to-latest-sentry-version-from-v9-0-0/11418/4).

### Additional Context

Examples from the Sentry forum to illustrate my motivation:

- _I’d try upgrading directly and running migrations at each step. You should be able to do 9.0.0 -> 9.1.2 -> 20.12.1_
  https://forum.sentry.io/t/the-best-way-to-upgrade-to-latest-sentry-version/12275/2
- _Right now it is safe and recommended to go directly to 21.4_
  https://forum.sentry.io/t/upgrade-9-1-2-current-via-export-import/13695/4
- _Yup, right now you can go directly to 21.5.1 which is the latest version._
  https://forum.sentry.io/t/best-way-to-upgrade-to-latest-sentry-version-from-v9-0-0/11418/4

**Comment by BYK** [comment]
Thanks a lot for bringing this up @hbokh and sorry for the confusion! Even the current wording there is a bit confusing.

Do you have any suggestions do make it clearer (can be a PR to get your name on it) or you wanna roll with whatever we come up with? 🙂

**Comment by BYK** [comment]
Even more, we have this: https://develop.sentry.dev/self-hosted/#upgrading

Maybe this is the correct opportunity to close out #790?
