### ISSUE TITLE
Fix  install/bootstrap-snuba.sh

### ISSUE THREAD

**Issue by pikodd** [getsentry/onpremise#990]
### Version Information

Version: *latest*
Os: Debian 10
Docker: 20.10.7, build f0df350
docker-compose: 1.29.2, build 5becea4c
### Steps to Reproduce

1. add own Postgres credentials to sentry/sentry.conf.example.py
2. add ClickHouse and Redis env vars to docker-compose.yaml

```
    CLICKHOUSE_HOST: "some.clickhouse.host"
    CLICKHOUSE_USER: "user"
    CLICKHOUSE_PASSWORD: pass
    CLICKHOUSE_DATABASE: "db"
    REDIS_HOST: "some.redis.host"
```

3.  execute ./install

### Expected Result

Sentry is installed 

### Actual Result

Error 
### Logs
```
▶ Bootstrapping and migrating Snuba ...
--no-ansi option is deprecated and will be removed in future versions. Use `--ansi never` instead.
Creating sentry_onpremise_zookeeper_1 ... 
Creating sentry_onpremise_redis_1     ... 
Creating sentry_onpremise_redis_1     ... done
Creating sentry_onpremise_zookeeper_1 ... done
Creating sentry_onpremise_kafka_1     ... 
Creating sentry_onpremise_kafka_1     ... done
Creating sentry_onpremise_snuba-api_run ... 
Creating sentry_onpremise_snuba-api_run ... done
./docker_entrypoint.sh: line 15: exec: bootstrap: not found
127
An error occurred, caught SIGERR on line 3
Cleaning up...
```

Solution:

in file install/bootstrap-snuba.sh add "snuba" before "bootstrap" like

```
$dcr snuba-api snuba bootstrap --no-migrate --force
$dcr snuba-api snuba migrations migrate --force
```

**Comment by BYK** [comment]
Can you please share which version of Sentry are you using? This is is not necessary for a long time and as you can see from the CI tests, it definitely is not necessary now.
