### ISSUE TITLE
install.sh fails when starting sentry_onpremise_postgres_1

### ISSUE THREAD

**Issue by sschoelzel** [getsentry/onpremise#998]
### Version Information

Version: 21.6.1

### Steps to Reproduce

when I start install.sh I get an error

### Expected Result

sentry is installed

### Actual Result

senty install fails

### Logs

▶ Setting up / migrating database ...
Starting sentry_onpremise_clickhouse_1 ...
Creating sentry_onpremise_symbolicator_1 ...
Starting sentry_onpremise_clickhouse_1   ... done
Starting sentry_onpremise_redis_1        ...
Starting sentry_onpremise_redis_1        ... done
Creating sentry_onpremise_memcached_1    ...
Starting sentry_onpremise_zookeeper_1    ...
Creating sentry_onpremise_postgres_1     ...
Creating sentry_onpremise_smtp_1         ...
Starting sentry_onpremise_zookeeper_1    ... done
Starting sentry_onpremise_kafka_1        ...
Starting sentry_onpremise_kafka_1        ... done
Creating sentry_onpremise_snuba-subscription-consumer-transactions_1 ...
Creating sentry_onpremise_snuba-consumer_1                           ...
Creating sentry_onpremise_snuba-outcomes-consumer_1                  ...
Creating sentry_onpremise_snuba-api_1                                ...
Creating sentry_onpremise_snuba-transactions-consumer_1              ...
Creating sentry_onpremise_snuba-subscription-consumer-events_1       ...
Creating sentry_onpremise_snuba-sessions-consumer_1                  ...
Creating sentry_onpremise_snuba-replacer_1                           ...
Creating sentry_onpremise_symbolicator_1                             ... done
Creating sentry_onpremise_memcached_1                                ... done
Creating sentry_onpremise_smtp_1                                     ... done
Creating sentry_onpremise_snuba-consumer_1                           ... done
Creating sentry_onpremise_snuba-replacer_1                           ... done
Creating sentry_onpremise_postgres_1                                 ... error

ERROR: for sentry_onpremise_postgres_1  Cannot start service postgres: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/opt/sentry/postgres-entrypoint.sh": permission denied: unknown
Creating sentry_onpremise_snuba-subscription-consumer-transactions_1 ... done
Creating sentry_onpremise_snuba-transactions-consumer_1              ... done
Creating sentry_onpremise_snuba-outcomes-consumer_1                  ... done
Creating sentry_onpremise_snuba-api_1                                ... done
Creating sentry_onpremise_snuba-sessions-consumer_1                  ... done
Creating sentry_onpremise_snuba-subscription-consumer-events_1       ... done

ERROR: for postgres  Cannot start service postgres: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/opt/sentry/postgres-entrypoint.sh": permission denied: unknown
Encountered errors while bringing up the project.
An error occurred, caught SIGERR on line 12

**Comment by BYK** [comment]
You probably need to run `chmod -R 0777 .` in your `onpremise` folder.

**Comment by sschoelzel** [comment]
ok, that worked :) maybe there should be a hint in readme.md ;)

**Comment by BYK** [comment]
@sschoelzel 
>ok, that worked :) maybe there should be a hint in readme.md ;)

Sounds good, why don't you add it? 🙂 Or add it here: https://github.com/getsentry/develop/edit/master/src/docs/self-hosted/troubleshooting.mdx

**Comment by BYK** [comment]
Closing as we have resolved the issue :)
